### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Neuss1987** [evancohen/smart-mirror#1]
Hey Evan,

just an idea... maybe it's possible to include Spotify (which is OpenSource!?) via VoiceRecognation...

**Comment by SaiKrishnaMohan7** [comment]
Dude! Awesome work you have done! Putting it all over here, you are the real MVP!!

**Comment by evancohen** [comment]
I'm looking at having some music integration. I currently use Chromecast for all of the audio/video in my room, but there are certain restrictions for the Chrome extension that make this impossible(?)

Namely there is no way to dynamically pick a Receiver to cast to (the current version of the Chromecast Extension handles this selection, all you can give it is a callback). If anyone knows how to sneak around this please let me know!

**Comment by evancohen** [comment]
In case you are still curious, I'm working on a solution to this issue: [express-cast](https://github.com/evancohen/express-cast)

This will expose Chromecast functionality over HTTP on your local network making it possible for the mirror to give commands to Chromecast (indirectly). It's still a work in progress though and I haven't quite mastered the dark arts of the CASTV2 protocol.
