### ISSUE TITLE
Integrate Rss Feed

### ISSUE THREAD

**Issue by davidgaldon** [evancohen/smart-mirror#102]
I think it would be very cool and useful to integrate a rss feed, to be able to load the news from NYT for example.
I have found this and I think it would be very clean and nice to ingrate it, but unfortunately my knowledge about angular is not so good to figure it out.

https://github.com/siddii/angular-feeds

Here there is an example of it working:
http://siddii.github.io/angular-feeds/app/

We are in touch! ;-)
Thanks a lot for your help!

**Comment by gothmate** [comment]
Michael Teeuw has added feed messages on his mirror.
Maybe it helps to make your own modifications.
http://michaelteeuw.nl/tagged/magicmirror

**Comment by evancohen** [comment]
@gothmate Michael's code in a completely different programming language, so there's nothing to draw from there.

**Comment by missionrulz** [comment]
@gothmate, I am currently porting Michaels code from jQuery into Angularjs. I currently have a working prototype that should be ready for a PR later today or tomorrow.

**Comment by evancohen** [comment]
@missionrulz you should really use https://github.com/siddii/angular-feeds, it's totally awesome :)

**Comment by trenkert** [comment]
I would also love to have this feature.

**Comment by evancohen** [comment]
@trenkert noted. Once in finished with the keyword spotter I'll take a crack at it :)

**Comment by kurtdb** [comment]
I think this one was already finished, @evancohen ?

**Comment by evancohen** [comment]
Yup!
