### ISSUE TITLE
"" missing from calendar section of config.js

### ISSUE THREAD

**Issue by nojkepop** [evancohen/smart-mirror#103]
This section needs "" inside of the [] otherwise the calendar starts to a black screen with a cursor.

    // Calendar (An array of iCals)
    calendar: {
      icals : [],
      maxResults: 9, // Number of calender events to display (Defaults is 9)
      maxDays: 365 // Number of days to display (Default is one year)

**Comment by evancohen** [comment]
This is an issue with the calendar-service, not with the config. It needs to have a check to see if the array is empty.

**Comment by nojkepop** [comment]
The problem is though if you put in your calendar link without the "" the mirror loads to a black screen with a cursor.

**Comment by dardub** [comment]
I can look at this tomorrow, unfortunately that's most likely the soonest I can do it.

**Comment by evancohen** [comment]
Originally I thought that having this empty array was causing the mirror to break, but I looked at this and there is nothing wrong with the way this works. That's just the syntax for an array of strings in JavaScript - there's no other way to do it.

There is also an [explicit example](https://github.com/evancohen/smart-mirror/blob/master/README.md#configuring-the-mirror) of this in the README (which still needs to be updated to reflect the new config format, but that's unrelated).
