### ISSUE TITLE
Idea: News Service

### ISSUE THREAD

**Issue by newtux** [evancohen/smart-mirror#106]
Planning on creating a news service to show top stories on the mirror, at first just pulling stories from: http://developer.nytimes.com/docs/top_stories_api/.

**Comment by kurtdb** [comment]
Wouldn't integrating the RSS-feed be a more flexible solution?

**Comment by evancohen** [comment]
Agreed with @kurtdb on this one.what would this give you that an RSS feed would not?

**Comment by newtux** [comment]
Ah fair point, didn't realize there was already an RSS branch.
