### ISSUE TITLE
Idea: Send X to phone

### ISSUE THREAD

**Issue by newtux** [evancohen/smart-mirror#107]
Thinking about creating a service that allows you to send general things to your phone from your mirror (say the map you were looking at, one of the top news stories, calendar entries, etc.). 

https://pushover.net/ seems like the most straightfoward way to acomplish this.

**Comment by evancohen** [comment]
That or Pushbullet which we are already thinking about integrating.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+33

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
