### ISSUE TITLE
Caching last data

### ISSUE THREAD

**Issue by zenyagami** [evancohen/smart-mirror#108]
Optional to cache data, so if there is no internet connection maybe can display the last available data displayed until internet connection is fixed.

**Comment by kurtdb** [comment]
We could look into storing all the returned JSON in the localstorage and fetch all the data from there. I don't know if this will be a high priority atm, but we can look into it.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+32

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
