### ISSUE TITLE
Enhanced weather ideas

### ISSUE THREAD

**Issue by dano25** [evancohen/smart-mirror#110]
Currently, the mirror just shows the forecast for the week, along with the "Next 7 Days" paragraph. Would it be possible to include the weather for today as well? Something as small as showing the "Next 24 Hours" paragraph on the home screen, or something as complex as a voice command for "What's the weather like today?" which would show the forecast every hour for the next 24 hours.

Also, would it be possible to have a "Show me the radar" voice command, which brings up a map of precipitation in my area?

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+31

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
