### ISSUE TITLE
Deezer implementation

### ISSUE THREAD

**Issue by jaaplallie** [evancohen/smart-mirror#111]
i searched for a good music streaming service to implement (spotify will not work with its current API)
i tried deezer and i think it would work (they have a javascript SDK) but i failed...
Maybe someone with more experience with node/electron could have a crack at it?
The problem that i walked into was that i was unable to get the deezer invisible player loaded
(https://developers.deezer.com/sdk/javascript/example-invisible)
I think that this stuff can work with the pepper flash plugin in electron but i could not get it to run..
Maybe someone can?

Also notice that i am running the smartmirror software on a windows pc and that my mirror is connected to that (i'm not using a pi, maybe that's a/the problem)

**Comment by evancohen** [comment]
I'm already implementing YouTube on the `search` branch. There are some audio problems on the Pi that need solving like #67 before I'm willing to merge it in.

I'd like to avoid using flash if at all possible, it's a resource hog and on the Pi it has a somewhat noticeable effect on performance.

Running everything on your windows PC shouldn't change anything (one of the beauties of Electron being cross platform)

**Comment by jaaplallie** [comment]
There aren't a lot of music services that open up their api, it's a bummer!
The moment i saw that deezer used that ye olde flash i was disappointed too :(
I know that it should not be a problem that i run everything on windows but the use of the pepper flash plugin in electron on windows could be the problem (was just some sideinfo that could be of influence)
Hope the holy YT is going to work out..
