### ISSUE TITLE
Youtube and Soundcloud

### ISSUE THREAD

**Issue by StevenTLBF** [evancohen/smart-mirror#113]
I have code here for the use of Youtube and Soundcloud with commands such as "Play music", "Stop music", "Play Youtube", etc. Can someone please remove all the korean and implement this into Evan's code? It is based off of Evan's code, now we just have to remove the korean. https://github.com/mojosoeun/smart-mirror-ko

**Comment by StevenTLBF** [comment]
https://github.com/mojosoeun/smart-mirror-ko

**Comment by Shubham0209** [comment]
@StevenTLBF i think that those functionalities are still incomplete even in the korean version.

**Comment by evancohen** [comment]
This is code that was copied from the `search` branch, which is still in progress. Also, the SoundCloud looks like it only plays one song - which I'm guessing is not what you want ;)

**Comment by StevenTLBF** [comment]
My apologies. As you can see, I'm not very experienced with Javascript.

**Comment by evancohen** [comment]
No worries, I'm going to close out this issue though as there are a couple others tracking YouTube stuff. Until I can fix audio playback issues it'll stay on the `search` branch.
