### ISSUE TITLE
Annyang: Stop and start listening to commands

### ISSUE THREAD

**Issue by mrtruebeliever** [evancohen/smart-mirror#114]
I added a command Stop Listening, within it I tried to remove all annyang commands and added a new one "Start Listening"
```
// Stop listening
AnnyangService.addCommand('Stop listening', function() {
  console.debug("Not listening anymore");
  annyang.removeCommands();
  annyang.addCommands('Start listening', function() {
    // add code to get all commands back
  });
});
```
But I'm not getting this to work, no commands are removed and "Start listening" is not added. Anybody got an idea? I can add the "Start listening" command with
```
AnnyangService.addCommand('Start listening', function() {
  // add code to get all commands back
});
```
But that adds back al the other commands too.

**Comment by beto2909** [comment]
I'm working in a better structure to add other language support. In order to change the language I had to call annyang.abort(); then I set my language, then I add the new commands and I call annyang.start();

**Comment by evancohen** [comment]
@beto2909 you should be setting the language in annyang-service.js as the first line of `.start()` https://github.com/evancohen/smart-mirror/blob/master/js/annyang-service.js#L26

**Comment by beto2909** [comment]
Yea I know but I want to switch between languages. If I just create the command and call the .setLanguage() it does change it but it takes a while to start listening in the target language.

**Comment by evancohen** [comment]
You watn to switch between lenguages on the fly? Toggled by what, a voice command? 

You might want to check to see how Annyang implement's it's lenguages switching - it might be a simple fix.

**Comment by beto2909** [comment]
Yea I can show later what I did, in the Api documentation just says to call .setLanguage(language) but when I call it in a function in the annyang service it does the language change but it starts listening in the target language after the "end callback" is called. 

And I just noticed you moved that part inside the service. It's not in the controller.js file anymore

**Comment by mrtruebeliever** [comment]
@evancohen Thanks for the reply, I'm in the process of learning more about angular so I can understand the syntax a little bit better. Then I'll try to get this done

**Comment by evancohen** [comment]
Feel free to reopen this issue if you have any more questions about it, but I'm going to consider this closed.
