### ISSUE TITLE
Invisible Mouse

### ISSUE THREAD

**Issue by gothmate** [evancohen/smart-mirror#116]
Is there a way to turn the mouse invisible when the mirror starts?
It is very annoying to see the mouse pointer at the center of the greetings message.

**Comment by Shubham0209** [comment]
https://github.com/evancohen/smart-mirror/pull/79/files#diff-04c6e90faac2675aa89e2176d2eec7d8R84

follow this link, it has got instructions to hide the mouse, as well as to run the mirror on startup.

**Comment by gothmate** [comment]
@Shubham0209 thanks, a lot! There are so much issues I couldn't find that.

**Comment by gothmate** [comment]
Well, I did what the link says and Unclutter is obsolete or missing... :(
Anyway, I'll look up for another source to install it.

**Comment by evancohen** [comment]
@gothmate you should just be able to `sudo apt-get install unclutter`. Keeping this open until I update the documentation with this info.

**Comment by gothmate** [comment]
There it goes, @evancohen ! Thanks!!
