### ISSUE TITLE
Logitech Harmony

### ISSUE THREAD

**Issue by mkerfoot** [evancohen/smart-mirror#117]
Let's get this mirror in connected homes!

**Comment by evancohen** [comment]
I don't have one, but you should have a go at it. I still haven't been able to get access to their API.

**Comment by mkerfoot** [comment]
I just shot them an email requesting access to their API. Hopefully they'll get back to me within a reasonable amount of time.

**Comment by evancohen** [comment]
I requested access about 5 months ago and never heard anything from them :cry:

**Comment by evancohen** [comment]
Closing this because it's impossible to get a Harmony API key today. Someday when it becomes publicly available I think it would be awesome to implement.
