### ISSUE TITLE
Issue with installing npm

### ISSUE THREAD

**Issue by Time4u2run** [evancohen/smart-mirror#132]
Hey,

I always get an error while installing npm: "Failed at the electron-prebuild@0.36.9 postinstall script 'node install". What did I do wrong?

/ Markus

**Comment by evancohen** [comment]
Please elaborate. What command did you actually run? Was it `npm install`?

What OS are you using? What version of Node do you have installed? 

Maybe just a typo, but the package is actually `electron-prebuilt ` if that's not what you are using then that could be the issue.

**Comment by Time4u2run** [comment]
I ran cd /home/Pi/Smart-mirror/
Then npm install

I have the actual wheezy and node 4.3.2 and i read something with electron-prebuild within the errors while installing npm

**Comment by StevenTLBF** [comment]
@Time4u2run I had the same error. I extended the root partition with sudo rapsi-config, rebooted, than ran sudo npm install

**Comment by Time4u2run** [comment]
Alright, I will try this, thanks!

**Comment by distortd6** [comment]
Time4u2run, I have same setup as you.  I just tried this, to no avail... have you by chance tried this yet?  Curious to see if it works for you and I'm just doing something wrong

**Comment by Time4u2run** [comment]
No i'm on Holiday at the Moment. Will be able to try it on sunday. When I did, i will inform you guys :)

**Comment by tomasvr** [comment]
Having issues with running 'npm' from /home/Pi/Smart-mirror/ aswell. It doesn't recognize the command 'npm' even though I have node 4.3.2 installed at my /usr/local directory.  I am not yet using the actual wheezy OS. I used the standard Raspbian version from the NOOBS software, maybe that's part of the issue? I'm pretty new to the raspberry so yeah. Would love to hear back!

**Comment by evancohen** [comment]
@tomasvr are you sure you properly installed Node? `npm` comes packaged with it, so if the command is not found than it likely wasn't installed correctly.

**Comment by kurtdb** [comment]
@Time4u2run any update on this? It's been over a month, so did you have any time to test?

**Comment by evancohen** [comment]
closing this out because this issue has gotten stale

**Comment by ragsmax** [comment]
I have the same error as mentioned in the op

**Comment by evancohen** [comment]
Try running
```
npm install --save-dev electron-prebuilt 
```
and then `npm install` again
