### ISSUE TITLE
Cannot get Apple iCal events to show

### ISSUE THREAD

**Issue by jamesarm97** [evancohen/smart-mirror#142]
I have tried to get the links to my calendar to work but nothing I try works. They begin with an webcal:// and if I try that link in a browser it attempts to import to my calendar. If I do a wget on the line I see a bunch of redirects to another link. Does anyone have apple iCloud calendars working?

**Comment by chuddnutts** [comment]
Hi Jamesarm97, I have an apple iCloud calendar working my address is published as https:// I had to publish the calendar online first to get it working,

**Comment by evancohen** [comment]
Please try that. If it doesn't solve your problem you can re-open this issue.
