### ISSUE TITLE
Issue with npm start

### ISSUE THREAD

**Issue by sabbyt** [evancohen/smart-mirror#145]
Followed the instructions and received the following error: 

npm ERR! Linux 4.1.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.1 start: `electron main.js `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.1 start script 'electron main.js '.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js 
npm ERR! You can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

**Comment by evancohen** [comment]
You can't start the mirror via SSH, you have to run the command from the desktop UI. It looks like that's the problem that you are having right now.

**Comment by sabbyt** [comment]
Thanks! That works! Additional question - have you tried electron-packager to wrap all the files into an .exe?

**Comment by evancohen** [comment]
I have, but when you do that you also wrap the config file - making it impossible to configure the mirror.

**Comment by sabbyt** [comment]
Good point. I'm looking at different ways of doing this and thinking of maybe packaging the  app - did you use electron-packager for Linux ia32?

**Comment by evancohen** [comment]
I did, yeah. I'll eventually move to binaries with auto-update, but until I finish #48 it's not going to happen. If you'd like to contribute you should jump into the gitter chat :)

**Comment by secdude** [comment]
On the original topic of running the mirror via SSH an additional comment: It is possible to run the mirror via SSH if you use `ssh pi@raspberry -X` which will activate x Window Forwarding. Runs natively  on my Kali, you can use xming on windows. For sure apple's OS will have something in store as well.  Have used this myself but performance is horrible. But if you lack options and you are testing/developing it might be an option.

**Comment by evancohen** [comment]
Hey @secdude I'll totally have to try that out, that's awesome. As for testing/developing I've been running the mirror on my desktop and doing the bulk of my development there and then just pulling changes onto the pi to verify that it works. Thanks!
