### ISSUE TITLE
start the mirror over ssh

### ISSUE THREAD

**Issue by lucasfischer** [evancohen/smart-mirror#148]
i figuered out how to start the mirror over ssh.

just create a script with the following content. like `start-mirror.sh`

```
#!/bin/bash
export DISPLAY=:0
export XAUTHORITY=/home/pi/.Xauthority
cd /home/pi/smart-mirror && npm start
```
then start it via `sh start-mirror.sh`
thanks to @capfirepants who provided me with this script #109

**Comment by evancohen** [comment]
I always suspected this would work, but I never tried it. Not all environmental vars are there so you may have trouble with some functionality (this includes speech). I'm sure you could modify the script to export the appropriate vars to have speech working.

**Comment by evancohen** [comment]
This is now mentioned in the documentation http://docs.smart-mirror.io/docs/troubleshooting.html
