### ISSUE TITLE
Are you open to enhancements?

### ISSUE THREAD

**Issue by gnurph69** [evancohen/smart-mirror#15]
I'm *really* new to github, but my impression is that the overarching approach here is code and idea sharing.  I don't have a clue as to how I might suggest some things to you - and even though I had no exposure to angular.js yesterday, I've added some functionality that might have some value.  I suspect it wouldn't have taken you long, but - eh, what do I know?

Also, your instructions appear to be written from the point of view of somebody who has some experience in Raspberry Pi's UNIX distro - I rewrote them for myself, but they are in a state such that I'd guess 95% of all RPi users could replicate the resultant functionality relatively quickly. Might that be of help?  I know the community has an approach of "learn how to do it and we'll support you through Q&A" but sometimes one just want some quick results, without having to wade through esoterica of SSH, CSS, and the like.

Are you game for that?  If not, I understand.

Thanks,

Lee

**Comment by evancohen** [comment]
I'm *totally* game. If you want to contribute you should fork the repository (if you haven't already) and then creating a pull request with your recommended changes.

I'm working on some changes that effect how the mirror is run - one of which is ditching the need for SSH certificates and other complexities. So hopefully that'll help others like yourself getting things running :)
