### ISSUE TITLE
Shared Exchange Calender is not working

### ISSUE THREAD

**Issue by FrankMatheis** [evancohen/smart-mirror#150]
I have shared my exchange2010 calender. I got 2 links. Both working fine. I put https:// infront of the *.ics link and put that into the config.js.
Result is
![calender](https://cloud.githubusercontent.com/assets/17391346/13711177/77f6d41c-e7bd-11e5-89ec-56528858f0ef.png)
Than, I shared my icloud calender, paste the ics link into config.js and the calender is shown. but I need the exchange calender, not the icloud one :-( 
Any hints?

**Comment by yaydogan** [comment]
I am using MS Exchange calendar and I have the exact same problem. Couldn't get a chance to debug further.

**Comment by FrankMatheis** [comment]
Boy, if we could find someone from Microsoft who knows about Outlook - that would be great (just kidding :-)))

**Comment by yaydogan** [comment]
@FrankMatheis I got a chance to debug it today. I have a fix for it. You can check the PR #156 for the changes if you want to try it.
