### ISSUE TITLE
Bad layout on 720P display during map viewing

### ISSUE THREAD

**Issue by willem-hill** [evancohen/smart-mirror#151]
Hey everyone,
First of all this is a great project. Love it. everything works fine, except that some text gets overlayed on other text on my 1280 x 800 display when I view a map. The customized greeting scrolls up, but then its actually on top of the clock. Here is an image of what I'm talking about: http://imgur.com/NWxSYjU

**Comment by evancohen** [comment]
Change the greeting line in `index.html` so it only shows the greeting when in the default view state and fades it out when in another state.

``` html
<h1 ng-show="focus == 'default'" class="fade">{{greeting}}</h1>
```

**Comment by willem-hill** [comment]
@evancohen Beautiful! Thank you.

**Comment by willem-hill** [comment]
@evancohen Sorry to bother you more, but similarly, the map image is somewhat vertically stretched.

**Comment by evancohen** [comment]
I think it's less about the map being vertically stretched than it being horizontally squished. You might want to modify the request in the map controller to use a different width/height to make sure the aspect ratio doesn't get messed up.

**Comment by willem-hill** [comment]
OK thanks. I'll do that at some point. Right now I'm trying to figure out the scientific notation time thing. And other people have that problem too...
Thanks for the help, BTW.
