### ISSUE TITLE
A few minutes after starting smart-mirror, the time changes to scientific notation

### ISSUE THREAD

**Issue by willem-hill** [evancohen/smart-mirror#152]
Here is an image of the problem: http://imgur.com/KrWK2nJ

And please note that this only started happening after I updated to the most recent update (as of March 11).

**Comment by evancohen** [comment]
I've had my mirror running for 45 minutes and haven't been able to reproduce this... In the chat you mentioned that you were seeing an error with Bing maps, maybe you should start by trying to fix that and see if that works.

**Comment by willem-hill** [comment]
@evancohen yes, I fixed the Bing maps error, that was simply because I hadn't filled in where I work and live in the config.js. But the time display issue is still happening.

**Comment by tomecerqueira** [comment]
Same thing here. It's weird, don't happens everytime i start the mirror. But when happen, occurs after 5 minutes and the time changes the hour format.

**Comment by willem-hill** [comment]
I have determined that this only happens in specific time zones. If you would like to reproduce this issue, I suggest (using `sudo raspi-config`) to change your pi's time zone to EST, where it is happening to me. Choose New York time.
