### ISSUE TITLE
display errors

### ISSUE THREAD

**Issue by chuddnutts** [evancohen/smart-mirror#153]
I have just downloaded the latest master and when i run this on my mac i get a white display with all the text on
<img width="1280" alt="screen shot 2016-03-11 at 23 48 31" src="https://cloud.githubusercontent.com/assets/17237803/13718677/090bcba8-e7e4-11e5-8ba7-4b5aa06d179c.png">

is anyone having this issue. I have node installed and Electron (v0.36.7)

Thanks

John

**Comment by shoaibuddin** [comment]
do: npm install and bower install then run it

**Comment by evancohen** [comment]
@chuddnutts you'll have to run `npm install` again (`bower install` should automatically be run as a part of this process). You'll also have to update `config.js` based on the new instructions in the readme.

**Comment by chuddnutts** [comment]
Hi @evancohen @shoaibuddin , I have reran the the npm install but that is failing, I have attached the log. I tried running it with sudo too.

"
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose readDependencies loading dependencies from /Users/John/Downloads/smart-mirror-master-2/package.json
5 verbose install where, deps [ '/Users/John/Downloads/smart-mirror-master-2',
5 verbose install   [ 'angular-i18n',
5 verbose install     'bower',
5 verbose install     'electron-prebuilt',
5 verbose install     'install',
5 verbose install     'npm',
5 verbose install     'wiredep' ] ]
6 verbose install where, peers [ '/Users/John/Downloads/smart-mirror-master-2', [] ]
7 verbose installManyTop reading for lifecycle /Users/John/Downloads/smart-mirror-master-2/package.json
8 info preinstall smart-mirror@0.0.1
9 verbose installManyTop reading scoped package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/angular-i18n/package.json
10 verbose installManyTop reading scoped package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/bower/package.json
11 verbose installManyTop reading scoped package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/electron-prebuilt/package.json
12 verbose installManyTop reading scoped package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/install/package.json
13 verbose installManyTop reading scoped package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/npm/package.json
14 verbose installManyTop reading scoped package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/wiredep/package.json
15 verbose readDependencies loading dependencies from /Users/John/Downloads/smart-mirror-master-2/package.json
16 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/angular-i18n/package.json
17 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/bower/package.json
18 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/electron-prebuilt/package.json
19 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/install/package.json
20 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/npm/package.json
21 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/wiredep/package.json
22 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/.bin/bower/package.json
23 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/.bin/electron/package.json
24 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/.bin/npm/package.json
25 verbose targetResolver reading package data from /Users/John/Downloads/smart-mirror-master-2/node_modules/.bin/wiredep/package.json
26 verbose already installed skipping bower@^1.7.7 /Users/John/Downloads/smart-mirror-master-2
27 verbose already installed skipping electron-prebuilt@^0.36.5 /Users/John/Downloads/smart-mirror-master-2
28 verbose already installed skipping install@^0.5.4 /Users/John/Downloads/smart-mirror-master-2
29 verbose already installed skipping npm@^3.7.5 /Users/John/Downloads/smart-mirror-master-2
30 verbose already installed skipping wiredep@^3.0.0 /Users/John/Downloads/smart-mirror-master-2
31 verbose already installed skipping angular-i18n@^1.5.0 /Users/John/Downloads/smart-mirror-master-2
32 silly install resolved []
33 info build /Users/John/Downloads/smart-mirror-master-2
34 info linkStuff smart-mirror@0.0.1
35 silly linkStuff smart-mirror@0.0.1 has /Users/John/Downloads as its parent node_modules
36 verbose linkBins smart-mirror@0.0.1
37 verbose linkMans smart-mirror@0.0.1
38 verbose rebuildBundles smart-mirror@0.0.1
39 verbose rebuildBundles [ '.bin',
39 verbose rebuildBundles   'angular-i18n',
39 verbose rebuildBundles   'bower',
39 verbose rebuildBundles   'electron-prebuilt',
39 verbose rebuildBundles   'install',
39 verbose rebuildBundles   'npm',
39 verbose rebuildBundles   'wiredep' ]
40 info install smart-mirror@0.0.1
41 verbose unsafe-perm in lifecycle true
42 info smart-mirror@0.0.1 Failed to exec install script
43 verbose stack Error: smart-mirror@0.0.1 install: `bower install`
43 verbose stack Exit status 1
43 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
43 verbose stack     at emitTwo (events.js:87:13)
43 verbose stack     at EventEmitter.emit (events.js:172:7)
43 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
43 verbose stack     at emitTwo (events.js:87:13)
43 verbose stack     at ChildProcess.emit (events.js:172:7)
43 verbose stack     at maybeClose (internal/child_process.js:821:16)
43 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
44 verbose pkgid smart-mirror@0.0.1
45 verbose cwd /Users/John/Downloads/smart-mirror-master-2
46 error Darwin 15.0.0
47 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
48 error node v4.3.0
49 error npm  v2.14.12
50 error code ELIFECYCLE
51 error smart-mirror@0.0.1 install: `bower install`
51 error Exit status 1
52 error Failed at the smart-mirror@0.0.1 install script 'bower install'.
52 error This is most likely a problem with the smart-mirror package,
52 error not with npm itself.
52 error Tell the author that this fails on your system:
52 error     bower install
52 error You can get their info via:
52 error     npm owner ls smart-mirror
52 error There is likely additional logging output above.
53 verbose exit [ 1, true ]
 "

**Comment by roelofjan-elsinga** [comment]
Do you have bower installed globally (npm install bower -g)?

**Comment by chuddnutts** [comment]
@roelofjan-elsinga I ran sudo npm install bower -g and this is what i i got after it installed

/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
bower@1.7.7 /usr/local/lib/node_modules/bower

**Comment by chuddnutts** [comment]
@roelofjan-elsinga and this

bowler@0.0.0 /usr/local/lib/node_modules/bowler
└── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)

**Comment by Shubham0209** [comment]
@chuddnutts first install bower by **npm install -g bower**
then to install bower dependencies run **bower install**

**Comment by Zaratiegui** [comment]
I am having the same problem when installing in raspberry pi 2 with jeesie: 
"npm WARN lifecycle smart-mirror@0.0.1~install: cannot run in wd %s %s (wd=%s) smart-mirror@0.0.1 bower install /home/pi/smart-mirror"
Tried all what I found in the forum (this time I really was reading before posting) and my point is that it works in other pi I used wheezy. I think I did the same steps, but I might have missed something.
node version 4.4.1
bower: 1.7.7
linux 4.1.19-v7+ arm
electron 0.37.3

Tried the config.js that works with wheezy and tried the example one= white screen.
Just int the image (same as chuddnutts) I see "we are using node 5.1.1." so, could that be what we need?

**Comment by chuddnutts** [comment]
Hi @Zaratiegui @evancohen, I believe i have fixed the issue...

When trying to run the 'npm install' it was showing that there was no access to "Error: EACCES: permission denied, open '/Users/John/.config/configstore/bower-github.yml'
You don't have access to this file."

I browsed to the above location and found that my user account was not in the access list. I added my account and gave it read/write access. I had to do it to the 'configstore' folder first and then run 'npm install' which then created the the 'bower.github.yml' file and then give my account read/write privileges to the newly added 'bower.github.yml file. 

Finally ran the npm install -g bower and then bower install after and everything worked correctly after that.

I am running this on my Mac currently which is 10.11 Beta.

Hope this helps

Thanks 

John

**Comment by yomgdf** [comment]
Hi,
I'm havin exactly the same issue. 
Thanks to Shubham0209, hos procedure to install bower solve that problem !
But I still erros on startup with an empty black screen and a bar on the bottom of the screen :
![image](https://cloud.githubusercontent.com/assets/11963962/15290817/34264212-1b7b-11e6-949a-98b90adafe11.png)

I thought about a config.js problem, but i can't find it !
`var config = {

    // Lenguage for the mirror
    language : "fr", //must also manually update locales/X.js bower component in index.html
    layout: "main",
    //greeting : ["Hi, sexy!", "Greetings, commander"], // An array of greetings to randomly choose from

    // Alternativly you can have greetings that appear based on the time of day
    /*
    greeting : {
       night: ["Bed?", "zZzzZz", "Time to sleep"],
       morning: ["Good Morning"],
       midday: ["Hey!", "Hello"],
       evening: ["Good evening"]
    },
    */

    // forcast.io
    forcast : {
        key : "***", // Your forcast.io api key
        units : "auto" // See forcast.io documentation if you are getting the wrong units
    },
    // Philips Hue
    //hue : {
        //ip : "", // The IP address of your hue base
        //uername : "", // The username used to control your hue
        //groups : [{
            //id : 0, // The group id 0 will change all the lights on the network
            //name : "all"
        //}, {
            //id : 1,
            //name : "bedroom"
        //}, {
            //id : 2,
            //name : "kitchen"
        //}]
    //},
    // Calendar (An array of iCals)
    calendar: {
      icals : ["https://calendar.google.com/calendar/ical/****/basic.ics"],
      // Be sure to wrap your URLs in quotes
      maxResults: 9, // Number of calender events to display (Defaults is 9)
      maxDays: 365 // Number of days to display (Default is one year)
    },
    // Giphy
    giphy: {
      key : "***" // Your Gliphy API key
    },
    traffic: {
      key : "***", // Bing Maps API Key
      reload_interval : 5, // Number of minutes the information is refreshed
      // An array of tips that you would like to display travel time for
      trips : [{
        mode : "Driving", // Possibilities: Driving / Transit / Walking
        origin : "1, Rue de la gare, Paris, France", // Start of your trip. Human readable address.
        destination : "2, Rue de la gare, Paris, France", // Destination of your trip. Human readable address.
        name : "work", // Name of your destination ex: "work"
        //startTime: "",
        //endTime: "" // Optional starttime and endtime when the traffic information should be displayed on screen. The format can be either hh:mm or hh:mm am/pm
      }]
    }
};
`

In the console, when I "npm start", I have this error: 
[2026:0516/153612:ERROR:logging.h(813)] Failed to call method: org.freedesktop.NetworkManager.GetDevices: object_path= /org/freedesktop/NetworkManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files

I read it was related to chromium, but I don't know if its related to my balck screen...

Any help please ?

**Comment by evancohen** [comment]
Hey @yomgdf can you run `npm start dev` and tell me what error you see in the dev console?

**Comment by yomgdf** [comment]
Hi @evancohen 
Here are the logs:
> smart-mirror@0.0.1 start /opt/smart-mirror
> electron main.js  "dev"

> [13954:0516/235254:ERROR:logging.h(813)] Failed to call method: org.freedesktop.NetworkManager.GetDevices: object_path= /org/freedesktop/NetworkManager: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files

**Comment by evancohen** [comment]
@yomgdf I'm talking about the chromium dev tools (the side panel that opens up inside the UI of the mirror).

**Comment by yomgdf** [comment]
Sorry...

Red logs are:
angular.js:13236 TypeError: Cannot read property 'midday' of undefined
    at greetingUpdater (controller.js:117)
    at MirrorCtrl._this.init (controller.js:135)
    at new MirrorCtrl (controller.js:379)
    at Object.invoke (angular.js:4604)
    at extend.instance (angular.js:9855)
    at nodeLinkFn (angular.js:8927)
    at compositeLinkFn (angular.js:8226)
    at compositeLinkFn (angular.js:8229)
    at publicLinkFn (angular.js:8106)
    at angular.js:1696

**Comment by evancohen** [comment]
Ah, I see what the issue is. You commented out `greeting` in your config so the mirror assumed that you were specifying time bound greetings, which is also commented out.

If you want to have no greeting you can set the `greeting` array to a single empty string to fix this problem.

**Comment by yomgdf** [comment]
Arf I haven't see the /* */ comments on multi line greetings...
Thanks a lot @evancohen, it works !
