### ISSUE TITLE
Time all screwed up

### ISSUE THREAD

**Issue by jonoscott** [evancohen/smart-mirror#157]
Hi there,
Just updated to the latest version of the smart mirror (had been waiting for the different messages for different time of day) and it appears that the time initially comes up fine, but after the time changes (next minute), the hour (and Calendar hour) becomes completely screwed up eg.  11:00 PM is showing as 2.225071738008484308:00 PM, where as 11:01 PM shows as 2.225071738000848308:01 PM.

Hoping you can help here.

**Comment by willem-hill** [comment]
I have the same problem, as many of you probably know, since I was quite vocal about it initially. If I change the time zone to something wacky, them this issue doesn't happen anymore. Out of curiosity, what time zone are you in, @jonoscott? I'm in eastern standard time.

**Comment by jonoscott** [comment]
Hi there @willem-hill,  currently my timezone is set to: Pacific/Auckland.
This was working fine up until me pulling down the latest update, prior to that it was fine,  however I have noticed that it seems to be fine for any time (so far that I can see at least) in the morning eg 7:57 AM is fine, and all calendar appointments in the morning appear to be fine as well.

Unfortunately I don't have the give of coding that these guys do, otherwise I would try work it out, all I'm good at is finding faults.

**Comment by willem-hill** [comment]
@jonoscott I found that it works almost always except in the evening eg. 6-10PM. This fits with what you were saying.

**Comment by skru1es** [comment]
Hey guys

I think I found the problem. I had the exact same problem with my install on a raspberry pi. It was really frustrating because it only happed in the afternoon. However I traced the issue to the new version of moment.js.

I downgraded my moment.js to 2.10.6 found here: https://github.com/moment/moment/releases/tag/2.10.6

I replaced my moment folder in /home/pi/smart-mirror/bower_components with the 2.10.6 version and it worked.

I hope that helps!

**Comment by jonoscott** [comment]
Hi there @skru1es, 

Nice work, I've confirmed that just replacing the moment.js file with the older one works fine.  No need to replace the entire folder, just the file.  

So far so good, along with the time not going weird, all my calendar appointments are showing the correct time as well.

**Comment by dano25** [comment]
Also confirmed on my end that switching out the moment.js file solved this.
