### ISSUE TITLE
Calendar not displaying

### ISSUE THREAD

**Issue by jaysan21** [evancohen/smart-mirror#158]
I have looked at few examples. After adding the ical link in config it is still not showing on my smart mirror. Am i suppose to edit anything else? do i need php? please help.

 `calendar: {
      icals : ['https://calendar.google.com/calendar/ical/STUFF/basic.ics'],
      maxResults: 9, // Number of calender events to display (Defaults is 9)
      maxDays: 365 // Number of days to display (Default is one year)
    }`
STUFF = my link to calendar stuff

**Comment by luchadorman** [comment]
As a total newbie, I found that I had made the mistake of not using " ", instead of '', and also you must make your google calendar public I believe. I could be wrong, but those are the only two things I have different besides you and mine works.

**Comment by kurtdb** [comment]
You don't have to make your google calendar public. You can perfectly use the private ical-link.

Normally adding only the ical-link should be enough. Are you sure the link is correct? If so, what does it say when running ```npm start dev```?

**Comment by jaysan21** [comment]
I am currently running this on windows 10 in chrome. Would that make a difference?

**Comment by kurtdb** [comment]
That shouldn't make any difference.

**Comment by jaysan21** [comment]
Sorry i am kind of a newbie when it comes to this stuff. how do i see what it says when running npm start dev?

**Comment by jaysan21** [comment]
![2016-03-14](https://cloud.githubusercontent.com/assets/17818014/13744839/01ace0a2-e9c1-11e5-8c70-f433963eaeca.png)
The error can be seen on the right.

**Comment by kurtdb** [comment]
Normally electron should handle the access-control headers for you. Odd that you are receiving such an error in the console.

**Comment by evancohen** [comment]
My thoughts exactly @kurtdb... Are you running the mirror via `npm start`?

**Comment by jaysan21** [comment]
I am not familiar with `npm start` what is that or where can i find it?

**Comment by evancohen** [comment]
That's why you are having access issues. Read the [documentation](docs.smart-mirror.io) :)
