### ISSUE TITLE
Not all content is localized

### ISSUE THREAD

**Issue by ctutu** [evancohen/smart-mirror#159]
Hello,

Could you please add  "var DEFAULT_COMMAND_TEXT = 'Say "What can I say?" to see a list of commands...';"  from controller.js to be able to translated into locales files ?

Regards

**Comment by evancohen** [comment]
Not all the content was localized on the first pass. Using this bug to track the work to localize the rest of the mirror content.

**Comment by ctutu** [comment]
what do you think to use angular-translate module to translate each text you want.
I don't know if the best way to do that and how to implement.

**Comment by evancohen** [comment]
It's just about extending the existing locale files. Should be pretty easy.

**Comment by evancohen** [comment]
Seems like this is now all taken care of. It'll be an ongoing process to keep all the localization files up to date, so please file a new issue or create a PR if anything gets out of sync.
