### ISSUE TITLE
Hardware related: Is original RPi B+ not compatible?

### ISSUE THREAD

**Issue by distortd6** [evancohen/smart-mirror#160]
Finding issue after issue with getting this original RPi B+ up and rolling.  Is it just not compatible?

**Comment by evancohen** [comment]
It's not :/ There are no chromium binaries recent enough that are compiled for ARMv6. I invested some time getting it working a couple of months ago only to discover that the performance was really bad (to the point that I decided that it wasn't worth supporting the device).

It's only $35 for a Pi 3 (which others have verified is compatible). I'm not quite finished with it yet, but this limitation is documented here: http://docs.smart-mirror.io/docs/supported_hardware.html
