### ISSUE TITLE
Switch away from bower

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#163]
Bower seems to be eating our moment dependency (and using a version that is making the time show up in scientific notation in certain time zones #157).

We should switch this out for `npm` or another dependency manager.

**Comment by nicolasmn** [comment]
Hi Evan, the correct way of doing this would be to specify an "overrides" object in `bower.json` for wiredep to pick up the additional dependency. ´

This should work:
```json
{
  "overrides": {
    "moment": {
      "main": [
        "moment.js",
        "min/locales.min.js"
      ]
    }
  }
}
```
See https://github.com/taptapship/wiredep#bower-overrides for more information.

**Comment by evancohen** [comment]
Ahha! Yes you are absolutely right. Reopening this so it can be tracked.
