### ISSUE TITLE
Integration with Home Assistant

### ISSUE THREAD

**Issue by icopp** [evancohen/smart-mirror#164]
[Home Assistant](https://github.com/balloob/home-assistant) is an open-source smart house hub app that's meant to link lots of different platforms (for example, it already has support for Insteon hubs, Nest, Wink, generic Z-Wave devices, etc etc). You can do quite a lot of automation in it (take a look at their [Examples page](https://home-assistant.io/cookbook/) for more of an idea).

Integration with this project could give lots of interesting benefits - for example, being able to trigger from a motion sensor on any of HA's supported platforms in order to wake up the smart mirror automatically.

What would be needed would probably be something like:
- adding a basic REST-type interface to Smart Mirror
- adding a Smart Mirror module to HA that connects to that interface

Commands aren't hardcoded in HA and can have arbitrary payloads, so the module on the HA side could be quite generic as long as it knows how to interpret anything it's getting back for Smart Mirror device status ("screen is on/off", etc).

**Comment by evancohen** [comment]
I love Home Assistant! Not sure if you saw it, but there is a `home-assistant` branch (very out of date). I've considered doing this a number of times but wasn't sure if it would be worth the time (unsure if anyone else would be interested).

I've already prototyped a REST interface for remote configuration, so I could just extend that. Would you be interested in doing the work to create the HA module? What's the best way for us to collaborate on this?

**Comment by i-c** [comment]
I haven't made any HA modules before, but I'd be willing to give it a try.

Having a REST interface to work with would be the first part of things. I think for HA, the important bits would be getting the status of the device (screen on/off, which focus is current, etc), being able to change wake/sleep status, and changing the current focus with whatever suitable arguments.

Something else that potentially comes to mind here, actually, would be using an MQTT client in SM, like [MQTT.js](https://www.npmjs.com/package/mqtt). It's more complicated, but it would allow more sophisticated handling of stuff like live updates, as well as giving SM more of a direct inroad for integration with other MQTT smart devices for people not using HA.

**Comment by geman220** [comment]
I use HA extensively and would love to have support for it on the mirror.

**Comment by justbill2020** [comment]
moved this to in progress rather than suggestion... since its labeled next

**Comment by justbill2020** [comment]
referenced in http://feathub.com/evancohen/smart-mirror/+2

**Comment by justbill2020** [comment]
closing this currently tracked via feathub.com
