### ISSUE TITLE
Connecting to Twitter

### ISSUE THREAD

**Issue by beto2909** [evancohen/smart-mirror#168]
Has anybody tried connecting the mirror to twitter? I know there's some tokens but I can't find a way to give the tokens in order to get the response.

**Comment by evancohen** [comment]
You might be better off using RSS feeds from twitter once that work is done. I don't plan on making twitter a "first party" integration any time soon, but you are welcome to send a pull request should you decide to implement it. Feel free to drop into the gitter if you have any questions.
