### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by CaolanMcK** [evancohen/smart-mirror#169]
Hey guys, i am currently working on building my own smart mirror, but i just get this screen when i try to load it. I checked and the config is correct, and chrome is telling me that angular is not defined for most of the scripts. any advice?

![image](https://cloud.githubusercontent.com/assets/16864978/13898361/825faac8-edc6-11e5-9a6a-e75afc058e63.png)

**Comment by evancohen** [comment]
You may not have installed bower (which should have happened via `npm install`)
Run:
```
npm install -g bower
bower install
```
Then start the mirror.

**Comment by CaolanMcK** [comment]
getting a segmentation fault when i try to install npm

**Comment by samueller1** [comment]
I had a similar issue when installing for the first time on a fresh install. I tried the two commands you suggested, bower installed however the issue persists. Is there a need to install a separate web browser for this to run? 

Additional info, I am running this on a Pi 3, using a copy/paste of the config.js file listed in the install instructions.

**Comment by chuddnutts** [comment]
did you fix this? as i am having the same issue..

**Comment by evancohen** [comment]
Interesting... I just got my Pi 3 in the mail so I'll give this a shot tonight. You are running `bower install` from within the smart-mirror directory, right?

**Comment by evancohen** [comment]
Interesting... I just got my Pi 3 in the mail so I'll give this a shot tonight. You are running `bower install` from within the smart-mirror directory, right?
