### ISSUE TITLE
Ideas 

### ISSUE THREAD

**Issue by javidrazak** [evancohen/smart-mirror#17]
How about syncing your smartphone notifications and displaying it on the mirror? I think that would make the mirror really "smart".
 I am kinda beginner, and don't know how to push these notifications to the httpserver , so it would be nice if you are integrating it(if u like the idea).

**Comment by evancohen** [comment]
I've actually already experimented with that using Pushbullit to "mirror" the notifications from an Android device to the mirror. I never quite finished it though...

Request received! I'll add this to my list :)
