### ISSUE TITLE
npm install Syntax error: ")" unexpected Node v5.9.0 arm64 (Pi 3)

### ISSUE THREAD

**Issue by Badaboomchef** [evancohen/smart-mirror#171]
Hi,
i receive an error on the npm install command:
pi@raspberrypi:~/smart-mirror $ npm install electron-prebuilt
/usr/local/bin/node: 18: /usr/local/bin/node: ELF���s@�d@@%"@@@@@��@@@@��������Y��Yx�p����Y��Y00@@DDQ�tdR�td����Y��YXX/lib/ld-linux-aarch64.so.1GNUGNU>�T$�
j=�y,M�d�H�
                 0���@�`#C
4@  B��@`$@��TB�LhH"P�
      %H�F�0!       �2�T#(@&(@�PHh�
                                        ���0�"E� @"�&@3�!�+�$�HJA`� �ɀ(@@  M�ꪔ��XP1������2F	���L1��$����Pl&��$2�$�$d�a�˂��X
         �!\&
 Ȁ(��A��b�)�� AO@@S,5TT B"(C�.�H@���t	1BH����"��b@
	  L�(��x!��p �"8@ �&�����$0
                                                  �0�2��
                                                        	0
                                                                  �a����&�@$�5
(g�1�(
��
     @��`G��T��� �`�
                            �0��#%�b�$�!�2A�
                                                     ��!	A*@L
                                                                    ��k\$
                                                                            �� �(1M	 �$� A�PU;�`��
                          *A�L�0F� v	� A ( �]@@pf��`��dB
�bG"�@ �B��d2L0a� �#��lA@ �
���(T4P	� �D (� ��S*�k�h(�@�!DT �(|q�@`�E������@�D�*�!�PY*HkPÄ�$�B�hN BB�t8K�d
                                  C,���0�
��Z@pD�PrQ"x��T#A�  b�CP	�
�0 0	bHR����Ԙ�&�j
!�*��e��A�V@C! �!b@	%��#B( bp�X bP@@� �@�Tu ��&�( L�"GHb@ ��	��*�1� W�@�P@[@
                                  4����#(�%*�@��)`d�	       D8�CH ���8(@|��
J�4�l4����T�� &��I�ք�9	 `� �9����Q*uT�H�I`T����+ <���!� �HP8��
�$	��
��`ʂ1@\`��P�wQ	"�z��@ ,@Q&�!@	@���
�$H�,!�p�$@!B� 
                     �b��7͂F/,   H@�E) !�	�� !� Ȉ0DP

	
F��a�  ������8��P�!@�1
                  R�"DP@8D�`���łLD0 � �(0�IJC�� �"�@R���  �e��1�""
>�l-8DJ�@c�,U�LH$��@h�B�: not found
/usr/local/bin/node: 19: /usr/local/bin/node: Syntax error: ")" unexpected

I'm using Raspberry Pi 3 and have installed the following node:
https://nodejs.org/dist/v5.9.0/node-v5.9.0-linux-arm64.tar.gz

Did i choose a wrong node file?
I searched for a solution but couldn't find one.
May you can help me?
Thanks in advance

**Comment by evancohen** [comment]
Pretty sure the Pi 3 uses ARMv7, so that's the incorrect binary. Node v5.x has not been tested yet and is not recommended. Follow the instructions in the documentation and it should work.
