### ISSUE TITLE
Mirror not starting

### ISSUE THREAD

**Issue by MarkAsRead** [evancohen/smart-mirror#174]
Hi All,

I keep getting this error message when I want to start NPM

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.1 start: `electron main.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.1 start script 'electron main.js '.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/node-v4.0.0-linux-armv7l/npm-debug.log

**Comment by Robiv8** [comment]
Hallo,
i have the same Problem!
I am a newbie in raspberry pi, so thanks for help.
