### ISSUE TITLE
No access control allow origin.

### ISSUE THREAD

**Issue by Robiv8** [evancohen/smart-mirror#178]
no-access-control-allow-origin-header-is-present-on-the-requested-resource
Hallo
How to fix this in chromium, Raspberry Pi 2, jessi, localhost

**Comment by kurtdb** [comment]
Currenty there is no support for use cases bypassing the use of the electron library. (which takes care of the origin headers)

**Comment by Robiv8** [comment]
Hello , I do not understand ! Evan Cohen operates this mirror with its software with chromium .
And since it works yet ! Or is it? Then makes the whole but not meaningful. Confused.

**Comment by evancohen** [comment]
If you are using Electron, like the [documentation](docs.smart-mirror.io) outlines you will not have this issue. You should not be running the mirror via localhost.
