### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by wuast94** [evancohen/smart-mirror#184]
i have noobs raspian clean install on raspberry 2 .. follow the dokumenation and all good, when i run `npm install`
 or `npm start` i became error. 

i have tried:
```
npm install -g bower
bower install
```
but don´t change anything
the output from npm-debug:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart smart-mirror@0.0.1
6 info start smart-mirror@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info smart-mirror@0.0.1 Failed to exec start script
9 verbose stack Error: smart-mirror@0.0.1 start: `electron main.js `
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid smart-mirror@0.0.1
11 verbose cwd /home/pi/smart-mirror
12 error Linux 4.1.19-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error smart-mirror@0.0.1 start: `electron main.js `
17 error Exit status 1
18 error Failed at the smart-mirror@0.0.1 start script 'electron main.js '.
18 error This is most likely a problem with the smart-mirror package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron main.js
18 error You can get their info via:
18 error     npm owner ls smart-mirror
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by evancohen** [comment]
Are you using the Raspberry Pi 2/3? Are you running the latest on master?
I pushed an update two days ago that should have fixed this.

**Comment by evancohen** [comment]
Sorted out over gitter. Issue was that you can't start the mirror via ssh. Updated the documentation to reflect this: http://docs.smart-mirror.io/docs/troubleshooting.html
