### ISSUE TITLE
Wiredep not found error

### ISSUE THREAD

**Issue by Bjern** [evancohen/smart-mirror#189]
Since I'm no linux guru and certainly not familiar with node.  This is the error I'm getting...

bower postinstall   npm run wiredep
bower postinstall   > smart-mirror@0.0.1 wiredep /home/pi/smart-mirror
bower postinstall   > wiredep -s index.html
bower postinstall   sh: 1: wiredep: not found
bower postinstall   npm
bower postinstall
bower postinstall   ERR!
bower postinstall    Linux 4.1.19-v7+
bower postinstall   npm ERR!
bower postinstall   argv "/usr/local/bin/node" "/home/pi/smart-mirror/node_modules/.bin/npm" "run" "wiredep"
bower postinstall   npm ERR!
bower postinstall    node v4.0.0
bower postinstall   npm ERR! npm  v3.8.3
bower postinstall   npm ERR! file sh
bower postinstall   npm ERR! code ELIFECYCLE
bower postinstall   npm ERR! errno ENOENT
bower postinstall   npm ERR! syscall spawn
bower postinstall   npm ERR! smart-mirror@0.0.1 wiredep: `wiredep -s index.html`
bower postinstall   npm
bower postinstall    ERR! spawn ENOENT
bower postinstall   npm ERR!
bower postinstall   npm ERR! Failed at the smart-mirror@0.0.1 wiredep script 'wiredep -s index.html'.
bower postinstall   npm ERR! Make sure you have the latest version of node.js and npm installed.
bower postinstall   npm ERR! If you do, this is most likely a problem with the smart-mirror package,
bower postinstall   npm ERR! not with npm itself.
bower postinstall   npm ERR! Tell the author that this fails on your system:
bower postinstall   npm ERR!     wiredep -s index.html
bower postinstall   npm ERR! You can get information on how to open an issue for this project with:
bower postinstall   npm
bower postinstall   ERR!     npm bugs smart-mirror
bower postinstall   npm ERR! Or if that isn't available, you can get their info via:
bower postinstall   npm ERR!     npm owner ls smart-mirror
bower postinstall   npm ERR! There is likely additional logging output above.
bower postinstall   npm
bower postinstall    ERR! Please include the following file with any support request:
bower postinstall   npm ERR!     /home/pi/smart-mirror/npm-debug.log
bower ECMDERR       Failed to execute "npm run wiredep", exit code of #1 sh: 1: wiredep: not found  npm ERR! Linux 4.1.19-v7+ npm ERR! argv "/usr/local/bin/node" "/home/pi/smart-mirror/node_modules/.bin/npm" "run" "wiredep" npm ERR! node v4.0.0 npm ERR! npm  v3.8.3 npm ERR! file sh npm ERR! code ELIFECYCLE npm ERR! errno ENOENT npm ERR! syscall spawn npm ERR! smart-mirror@0.0.1 wiredep: `wiredep -s index.html` npm ERR! spawn ENOENT npm ERR!  npm ERR! Failed at the smart-mirror@0.0.1 wiredep script 'wiredep -s index.html'. npm ERR! Make sure you have the latest version of node.js and npm installed. npm ERR! If you do, this is most likely a problem with the smart-mirror package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR!     wiredep -s index.html npm ERR! You can get information on how to open an issue for this project with: npm ERR!     npm bugs smart-mirror npm ERR! Or if that isn't available, you can get their info via: npm ERR!     npm owner ls smart-mirror npm ERR! There is likely additional logging output above.  npm ERR! Please include the following file with any support request: npm ERR!     /home/pi/smart-mirror/npm-debug.log

Additional error details:
sh: 1: wiredep: not found

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/home/pi/smart-mirror/node_modules/.bin/npm" "run" "wiredep"
npm ERR! node v4.0.0
npm ERR! npm  v3.8.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! smart-mirror@0.0.1 wiredep: `wiredep -s index.html`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.1 wiredep script 'wiredep -s index.html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wiredep -s index.html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.1 install: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.1 install script 'bower install'.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

The debug log is as follows...

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/pi/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/pi
7 error Linux 4.1.19-v7+
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
9 error node v4.0.0
10 error npm  v2.14.2
11 error path /home/pi/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

I can confirm copying package.json to '/home/pi/' (I'm using a pi 2 model B)
I do have a config.json BUT not with all API's - not sure if that's a must.
I am using lastest raspbian jessie 2016-03-18.
I have cleaned and reinstalled "git clean -xdf" then "sudo npm install" then "npm install" -> for some reason the first npm install gives me permissions fail errors on wiredep so I have to run sudo first then again after.  It installs all the way to postinstall then the error above.

After this colossal fail error message it still boots and shows the "mirror text"  -> Calendar is not working right, the screensaver and power save kicks in after a while (followed the tutorials to the letter), not picking up my logitech webcam mic...

Any help on the error?

**Comment by evancohen** [comment]
Please update to the latest in master. This issue has already been fixed. Save your config then:
``` 
git pull
git clean -xdf
npm install
```

**Comment by evancohen** [comment]
My fault, you are totally right, something is messed up in the master branch. Please use the `dev` branch for now (which I have just verified is working. 

Reopening this bug

**Comment by Laubre** [comment]
Hey, just want to report back, the Dev branch seems to work!
You should run the following commands from the smart-mirror folder (atleast i had to before i could get it to run):

rm -rf node_modules/
sudo npm update -g npm
npm install
