### ISSUE TITLE
Multiple "Time To" options

### ISSUE THREAD

**Issue by jonoscott** [evancohen/smart-mirror#192]
Thinking it would be nice to have multiple "Time To" options,  eg Time to Work, Time to Gym, Time to etc.

I'm unfortunately not a coder in NodeJS, I was thinking either an Array, or a series of Subroutines for the Time to section.

If anyone is good enough at coding, or could provide a suggestion on how to do this, it would be great.

**Comment by evancohen** [comment]
Yup, I've been meaning to do this for a while but I haven't had the chance. I've added it to the todo list.

**Comment by kurtdb** [comment]
This is one of the reasons I created my timeboxservice. By using it, you could easily switch between the different routes without having to change the way it is displayed on screen.

**Comment by jonoscott** [comment]
Hi there @evancohen, I see this is closed,  does this mean its live in the latest update?

**Comment by evancohen** [comment]
Yup! It's in PR #205. You can try it in the `dev` branch now if you'd like. 
Just beware that the format of the config has changed to accommodate multiple trips so you'll have to update it.

**Comment by jonoscott** [comment]
Oh sweet, that's fine, I noticed the config was different in the notes, but
reinstalled from the live master version, might be a silly question, but
how do I install the Dev version?

**Comment by evancohen** [comment]
You'll need to checkout the branch with 
```
git checkout dev
git pull
```
Depending on how old your current master branch is you may have to run through the [updating](http://docs.smart-mirror.io/docs/updating.html) instructions in the documentation.
