### ISSUE TITLE
Strava Intergration

### ISSUE THREAD

**Issue by jonoscott** [evancohen/smart-mirror#193]
Would be great if we could integrate Strava into the mirror,  I see that Fitbit has just been integrated.  I would think that being able to see the latest activity, week to date, month to date would be all that is needed.  

While I'm not much of a coder (not coding in NodeJS),  I've managed to find this: https://github.com/UnbounDev/node-strava-v3 which perhaps someone may be able to use to incorporate it.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+28

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
