### ISSUE TITLE
DocumentRoot Apache2 ? Newbie 

### ISSUE THREAD

**Issue by Robiv8** [evancohen/smart-mirror#195]
Hello, can someone tell me how this Smart-mirror can run.? I mean, it is supposed to be installed in /home/pi ! But Apache2 does show the data in /var/www/html
I'm confused . Must i put the /home/pi/smart-mirror as the new document Root in the Apache configure file.

Thanks and happy easter

**Comment by Laubre** [comment]
Hi Robin, this is not meant to run under Apache, this is not the Smart-mirror that is set up in the webfiles. You should see the installation guide for this:
http://docs.smart-mirror.io/
If you follow these steps it should work! :)

**Comment by Robiv8** [comment]
Thanks Laubre,
hmm..
If I understand you correctly now then I proceed to the installation instructions. OK
And then?
When I enter on the Chromium browser my IP then comes only the Apache home page, since the / var / www / html folder is nothing in it. (At least, I assume, have not yet installed it.)
I stand on the hose! :-(

I'm going to make it this step by step so and then look what happened.

**Comment by Laubre** [comment]
You don't need to enter an IP into any browser for this, it runs as a kind of "standalone" programm. You follow the step by step guide from the link, on the last page you have 2 things to do ( Run "npm install" from the "smart-mirror" folder, and after that has completed you can run "npm start" from the "smart-mirror" folder, then after a short loading time a dark screen will pop up with the Information (depending on what you have configured in the config file this will display weather, time, date, calendar and / or some other stuff)

**Comment by Laubre** [comment]
There is a "smart mirror" setup which runs off php, apache (a web server) but it's not this one, it's the one from michael teeuw which is located here (https://github.com/michmich/magicmirror/tree/master) It's a little easier to setup :) ,
But the one you are working on here (from evancohen) has some possibiltys that the other should not have (including speech recognition)

**Comment by Robiv8** [comment]
Great! Thank you. I understand now.
I have it installed and it is RUN :-) For the first a white page ;-) but hey! Slowly

How can i stop this white page? and reload it again after i put the right dat in my config.js

**Comment by Laubre** [comment]
Glad to hear that you are making Progress :+1: 
A white page should be caused by the Config file, have you renamed the config_example.js to config.js (in the main "smart-mirror" folder) ?

You can reload it after you made changes by pressing the "alt" button on your keyboard, youll have a menu bar appear, their is an option (located under view or window afaik) where it says reload..

Or you can simply end the application and restart it by running "npm start" from the smarr-mirror directory again :)

**Comment by Robiv8** [comment]
Thank you very much!
One more question:
Is it possible to have more than 1 Calender, i have 2 google and 1 iCal. How can i do that.

**Comment by Laubre** [comment]
Yes it is, the config file from the Installation guide shows that already

calendar: {
      icals : ["https://calendar.google.com/calendar/ical/SOMESTUFF/basic.ics",
"https://outlook.office365.com/owa/calendar/SOMESTUFF/reachcalendar.ics"],
      maxResults: 9, 
      maxDays: 365 
    },

There you have 2 calendars, or did you mean displaying 2 calendars on the screen, and not combine the information/dates from both calendars into 1 ?

**Comment by Robiv8** [comment]
Great! Its work :-)
Many Thanks for your HELP

Only the display_rotate=1 in the /boot/config.txt have no reaction.
The raspberry pi 2 is conected with HDMI to DVI Kabel on a Dell UltraSharp U2412M 61cm (24'')  VGA,DVI-DP (1920x1200)

**Comment by Laubre** [comment]
Glad to hear that! :)

Ok, Have you restarted your pi after adding the line to the /boot/config.txt arlready ? it needs a restart afaik

**Comment by Robiv8** [comment]
yes! Thanks!
Its late in the Night here in Germany, i give it a try tomorrow ;-)

Good Night
Robert

**Comment by Laubre** [comment]
^^ Sure, good luck tomorrow!

**Comment by evancohen** [comment]
Seems that this has been resolved :) thanks for helping @Laubre!

:rocket:
