### ISSUE TITLE
animatetd weather icons (skycons)

### ISSUE THREAD

**Issue by stephwe** [evancohen/smart-mirror#196]
Has anyone tried to use the animatetd weather icons (skycons)? I know that there is some tokens , but I can not find a way to give the token to obtain the answer .

Thanks and happy easter.

**Comment by nicolasmn** [comment]
In fact skycons are already implemented and utilized by the "icesnow" theme. Simply change the key "layout" inside your `config.js`:
```js
{
  // ...
  layout: "icesnow"
}
```
