### ISSUE TITLE
Microphone problems with the Smart mirror

### ISSUE THREAD

**Issue by Laubre** [evancohen/smart-mirror#197]
Hey, I have my usb headset set up and got it to work correctly, i can record sound from my microphone and play that file..
But whenever i start the Smart mirror, i get this error:

ALSA lib pcm.c:7924:(snd_pcm_set_params) Channels count (2) not available for CAPTURE: Invalid argument
ALSA lib pcm.c:7993:(snd_pcm_set_params) Unable to set hw params for CAPTURE: Invalid argument
ALSA lib pcm.c:7924:(snd_pcm_set_params) Channels count (2) not available for CAPTURE: Invalid argument
ALSA lib pcm.c:7993:(snd_pcm_set_params) Unable to set hw params for CAPTURE: Invalid argument

Doesn't the Smart-Mirror take the system default sound settings ?

Best regards
Laurenzb

**Comment by evancohen** [comment]
It should, it uses the same audio input methods as Chromium. You might have better luck when using PulseAudio. Check out the troubleshooting docs.

**Comment by Laubre** [comment]
Pulseaudio fixed it! :+1:  Thanks for the quick tip :P
