### ISSUE TITLE
Second Fitbit User

### ISSUE THREAD

**Issue by Prahli** [evancohen/smart-mirror#199]
I was wondering if it would be possible to add a second fitbit user. As my girlfriend and I use the same mirror and both have a Fitbit it would be nice to see the stats of both of us. 
As I understand the config, it wouldn´t be necessary to make a hole new config entry but another token with credentials of the second user is needed. And it has to be implemented in the GUI as well. Poorly as I am no developer I have no idea how to start this so I write it down here with hope of more skilled persons than me.

**Comment by evancohen** [comment]
Should be possible :)

@Shogan can you take a look at this?

**Comment by Shogan** [comment]
@evancohen @Prahli I'll take a look at adding support for a second user - should be able to get to it in the next couple days :smile:

**Comment by kurtdb** [comment]
@Shogan any updates on this? :)

**Comment by Shogan** [comment]
Hi Kurt,

Unfortunately I've been tied up with other work the last week. I haven't
had a chance yet, but will look into it soon I hope.

On 11 April 2016 at 14:56, Kurt Du Bois <notifications@github.com> wrote:

> @Shogan <https://github.com/Shogan> any updates on this? :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/evancohen/smart-mirror/issues/199#issuecomment-208355300>
>



-- 
VMware vExpert 2012-2016
Shogan.tech <http://www.shogan.co.uk> - VMware, Cloud, Automation,
scripting blog
Hobbyist Coder <http://hobbyistcoder.com> - Programming and Game
Development blog

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+27

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
