### ISSUE TITLE
Issues with running on a mac with electron/bower

### ISSUE THREAD

**Issue by chuddnutts** [evancohen/smart-mirror#204]
Hi All,

I am having an issue with running the new version of the 'Master' since bower is required on a mac. I have tried reinstalling it all but i now get a lot of fails. When I load it in Electron it appears as a white screen and a lot of text <img width="1280" alt="screen shot 2016-03-11 at 23 48 28" src="https://cloud.githubusercontent.com/assets/17237803/14135910/054d3eac-f658-11e5-82c4-421091237862.png">. I have followed the read me file.

Is anyone else having the same issue? I haven't tried running it on the Pi yet..

Thanks

**Comment by evancohen** [comment]
Follow the instructions under "Still Having Problems": http://docs.smart-mirror.io/docs/updating.html
