### ISSUE TITLE
Multilingual Detection of Spoken Words inside Services

### ISSUE THREAD

**Issue by 7h30n3** [evancohen/smart-mirror#208]
It would be nice if the detection of spoken words inside the services (e.g. hue-services.js) were multilingual, too.

I think we should determine an universal and simple way how to do that. Any suggestions?

**Comment by evancohen** [comment]
There already is a "universal" way of doing this, and it's through the locale files. There is still some content, as mentioned in #159, that is not using the new localization system. 

I'll make this a part of the next update, but I'll need help from some folks to actually localize the content.

**Comment by ctutu** [comment]
About hue-service by exemple, we use two different word to say switch on or switch off. How to translate ?

**Comment by evancohen** [comment]
You'll have to create an array of synonyms in the loc file and then do something like
```
if ($translate.instant('hue.on').includes(spokenWord[i])) {
    update["on"] = true;
    update["bri"] = 250;
}
```

**Comment by ctutu** [comment]
Thx for advices,  I'll try to do.

**Comment by overflOw11** [comment]
Check on the dev branch, the support for multilingual detection in hue-service was merge 2 days ago :p
