### ISSUE TITLE
What browser should you use for this? 

### ISSUE THREAD

**Issue by dithom02** [evancohen/smart-mirror#21]
I havent been able to get it working with epiphany-browser which comes stock with raspbian-jessie.

When I try to use this demo link: https://evancohen.github.io/smart-mirror/ I dont get anything.

I figured thats a good sanity check. I have installed nodejs and npm and followed the github install instructions and after npm start I get this error:

> smart-mirror@0.0.1 start /home/pi/smart-mirror
> electron main.js

npm ERR! smart-mirror@0.0.1 start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.1 start script.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/home/pi/node-v0.10.28-linux-arm-pi/bin/node" "/home/pi/node-v0.10.28-linux-arm-pi/bin/npm" "start"
npm ERR! cwd /home/pi/smart-mirror
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
npm ERR! not ok code 0

**Comment by gdscheele** [comment]
You have to use chrome or chromium for speech recognition

**Comment by evancohen** [comment]
@dithom02 Are you running the latest from master? You also need to be in GUI mode, Electron can't launch if it is not running. Run `startx` to launch it.
