### ISSUE TITLE
Transit time 

### ISSUE THREAD

**Issue by alexkhalaf** [evancohen/smart-mirror#210]
Can we add transit times to the mirror

http://transitapp.com/developers

**Comment by jonoscott** [comment]
Not sure if this is what your meaning @alexkhalaf, but there is already a Time To option built in which shows you your travel time to work, or wherever you put in your config.js file.

**Comment by evancohen** [comment]
Agreed with @jonoscott not really sure what you mean. You can already see transit times. Can you be more specific about what you have in mind?

**Comment by alexkhalaf** [comment]
Hi, 
The mirror shows the travel time (which really never change), where the transit times shows what time will the bus arrive (Live) if you check the transit app you will know exactly what I mean

**Comment by kurtdb** [comment]
The hard part to implement this, is that there is no standardized service that offers this information as far as I know. There might be one for the US, but in Europe this information will not be very useful.

This might result in a service which only 1% of users will use. I'm afraid this will result in a very low priority, so might be best to implement it yourself and contribute it.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+26

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
