### ISSUE TITLE
How to get usb mic working with smartmirror

### ISSUE THREAD

**Issue by jaysan21** [evancohen/smart-mirror#211]
I am using a usb mic and was wondering how to get it to work with smart mirror application. The mic works alone on the raspberry pi but when I run the application it doesn't work or detect any voice input.

**Comment by evancohen** [comment]
Have you looked at the troubleshooting steps in the documentation?

**Comment by jaysan21** [comment]
Yes, we installed pulse audio and it is still not picking up the mic in the smart mirror application.

**Comment by evancohen** [comment]
Did you restart the Pi after? If you run `npm run microphone-debug` (on the latest in master) I created a simple utility to debug microphones. The "blank" entry in the dropdown is your default microphone.

**Comment by jaysan21** [comment]
We were working on a older version of the project about 2 months ago we are using that.

**Comment by evancohen** [comment]
There's not much I can do to help without more information. What have you tried so far? You might want to give the instructions here a shot: http://askubuntu.com/questions/31206/how-can-my-audio-input-always-be-the-webcam-microphone

**Comment by jaysan21** [comment]
The mic worked once but the app doesnt always pick it up. Its either a hit or miss.

**Comment by evancohen** [comment]
Without more info there's nothing I can do. Please give me a little more to go on (what's your default PulseAudio device, what USB mic are you using, what Pi are you using, etc)
