### ISSUE TITLE
Black screen without any information on Raspberry Pi Zero - Help highly appreciated

### ISSUE THREAD

**Issue by darealShadow** [evancohen/smart-mirror#212]
Hi all,

first of all let me tell you, Even, I love your project and want to make that work too. So I got myself a Pi Zero and installed Raspbian. Then I followed pretty much your instruction to make it work. After installing nodejs in the version 4.4.1 (I used the one for the ARM6 as the pi zero is based on a ARM6 chip as far as I know) and installing the dependencies I only get a black screen when opening the index.html. 
I also must admit that I am still waiting for my mic to arrive. Can that have an impact on the display? I think it shouldn't but what do I know... Anyway I hope that someone can help me getting the up an running on my Zero.

Thank you so much for your help in advance.

**Comment by evancohen** [comment]
The microphone has no impact on the display, but I've never tested any of this on the Pi Zero - not a lot I can do to help you without some error logs I'm afraid.

The last time I checked `electron-prebuilt` only worked with ARMv7, but I've heard from a few people that they got it working with the Pi Zero (not sure how though).

**Comment by darealShadow** [comment]
Hi Evan
Thanks for your feedback. I'll try to follow your instructions updating. If that doesn't work I'll uninstall node and electron again and try again running it on the arm7 version. 
If anyone successfully installed it on the pi zero let me know.  As soon as I get that running I will publish a detailed instruction on my blog if that's OK with you, Evan. Appreciate your feedback.

**Comment by evancohen** [comment]
Pretty sure ARMv7 binaries wont work on a ARMv6 device ;) You'll need a Raspberry Pi 2 or 3.

**Comment by darealShadow** [comment]
Well if thats all what it takes I will make this investment ;)

**Comment by evancohen** [comment]
If you are doing it I recommend the Pi 3 (same price, more power). Good luck!
