### ISSUE TITLE
Python code/script by voice command

### ISSUE THREAD

**Issue by Shubham0209** [evancohen/smart-mirror#213]
Actually I was thinking of running the motors,led strip and other Hardware devices connected to the gpio pins of Raspberry Pi through voice command.I was able to download the python code available for running the motor on rasp forum but don't know how to integrate it with the smart mirror.I also went through the Python branch of the smart mirror but was unable to understand how to use it, any help would be deeply appreciated.

**Comment by evancohen** [comment]
The Python branch create a service (craftally named python-service.js) which executes arbitrary bash commands as the active user. So this means you can run a Python script (or anything else) from within the mirror.

Check out that file and let me know if you have any more questions :)

**Comment by Shubham0209** [comment]
[motor_pi.docx](https://github.com/evancohen/smart-mirror/files/209711/motor_pi.docx)
suppose this is the python code which is to be executed on voice command - "run motor", then what changes are required to be made into the python branch in order to execute it. Sorry for the noob question.

**Comment by evancohen** [comment]
the python controller actually lets you run arbitrary bash commands (see the python service). So you could `python motor_pi.py`
