### ISSUE TITLE
RFID/NFC Authentication system

### ISSUE THREAD

**Issue by cxcornel** [evancohen/smart-mirror#214]
Can you add some sort of authentication system for multi-user usage? This way it can store preferences and be used also as an alarm system using Motion detection(webcam) or PIR sensor.

**Comment by rholmboe** [comment]
I'd probably go with some sort of wifi/bluetooth module and check distance and/or closest match. Latest RPI comes with both embedded, and most operative systems support simple dongles from what-ever site you prefer.

When random person X is closest, nothing but the "default" is visible.
When legit person Y is near, default + extras is shown for him/her.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+25

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
