### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#219]
An install script that downloads the mirror and installs all dependencies. 
This needs a little bit more love to get working 100%. The script does the following:
- Installs node (if not installed already)
- Installs unclutter (hides mouse when inactive)
- Sets rotation for mirror (requires reboot)
- Clones the `smart-mirror` (using the master branch)
- Creates an empty config file
- Installs `smart-mirror` dependencies (this takes a while)

Should work by running:
```
wget https://raw.githubusercontent.com/evancohen/smart-mirror/dev/scripts/install.sh
sudo chmod +x install.sh
sudo ./install.sh
```

**Comment by javiersigler** [comment]
What about this way: 
curl -s https://raw.githubusercontent.com/evancohen/smart-mirror/dev/scripts/install.sh | bash
?

**Comment by justbill2020** [comment]
I think there should be an option to select which branch to install. (dev or master)

**Comment by justbill2020** [comment]
Also, it still is set to install pulseaudio... there's an option to say no... but not sure that will help

also in the event that smart-mirror is already installed perhaps force a clone on top of or have a recursive script to delete the folder and start fresh... with an option to decline a fresh install..

**Comment by justbill2020** [comment]
something on the install of a fresh install of raspbian...
```
pi@raspberrypi:~/smart-mirror$ npm start

> smart-mirror@0.0.2 start /home/pi/smart-mirror
> electron main.js 


npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.2 start: `electron main.js `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.2 start script 'electron main.js '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
pi@raspberrypi:~/smart-mirror$ 

```

**Comment by justbill2020** [comment]
turning display 90 degrees did not work in script.

**Comment by evancohen** [comment]
Thanks for testing this out @justbill2020! The work on this is a bit out of date (which is why it still tries to install PulseAudio) and is still "in progress". My approach to this install script is that it should give the user the least options possible, everything is reconfigurable later (ex: choosing a branch, it's a 1-line command to use).

It's also a 1-line command to remove the smart-mirror from your Pi so you can re-run the script for a reinstall, so I'm not sure if it's worth implementing in the Bash script that's for installing. Also, it's a 1-line command to revert any changes you've made to the mirror on your Pi to the latest update - so again, not sure if it's worth it.

I'll have to look at the monitor rotation, thanks for pointing this out.

**Comment by justbill2020** [comment]
No problem just wanted to put together some thoughts as i was going through it.

**Comment by evancohen** [comment]
Got this working. Now it's a one line script:
```
curl -sL https://raw.githubusercontent.com/evancohen/smart-mirror/dev/scripts/pi-install.sh | bash
```
