### ISSUE TITLE
Error while start

### ISSUE THREAD

**Issue by darkeagl** [evancohen/smart-mirror#222]
Hi, I get this error when I start the Raspberry (Pi 1 B+)
It is a clean install from your docs website, followed everything

** Message: app.vala:76: Launching pcmanfm 

** (lxsession:523): WARNING **: app.vala:86: Failed to execute child process "xscreensaver" (No such file or directory)

** (lxsession:523): WARNING **: app.vala:87: Error when launching xscreensaver
** Message: app.vala:76: Launching /home/pi/smart-start.sh 
** Message: options.vala:107: Create build-in Clipboard
** Message: main.vala:429: Check keymap_mode (null)
** Message: app.vala:76: Launching /usr/bin/ssh-agent 
SSH_AUTH_SOCK=/tmp/ssh-zr563GA4f055/agent.671; export SSH_AUTH_SOCK;
SSH_AGENT_PID=684; export SSH_AGENT_PID;
echo Agent pid 684;
Obt-Message: Xinerama extension is not present on the server
** Message: app.vala:130: /usr/bin/ssh-agent exit with this type of exit: 0
Openbox-Message: Unable to find a valid menu file "/usr/share/lxde/openbox/menu.xml"
** Message: x-terminal-emulator has very limited support, consider choose another terminal
** Message: x-terminal-emulator has very limited support, consider choose another terminal

(lxpanel:657): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(lxpanel:657): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed
** Message: Connecting ...
** Message: Status changed to down

(lxpanel:657): Gtk-CRITICAL **: IA__gtk_dialog_response: assertion 'GTK_IS_DIALOG (dialog)' failed
** Message: Status changed to opened
** Message: Connected to dhcpcd-6.7.1
** Message: Status changed to connected
** Message: eth0: CARRIER
** Message: eth0: Configured 192.168.26.26/24

> smart-mirror@0.0.1 start /home/pi/smart-mirror
> electron main.js 

** Message: app.vala:130: /home/pi/smart-start.sh exit with this type of exit: 0

(lxpanel:657): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(lxpanel:657): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

(lxpanel:657): Gtk-CRITICAL **: IA__gtk_misc_set_alignment: assertion 'GTK_IS_MISC (misc)' failed

**Comment by kurtdb** [comment]
The raspberry pi 1 B+ is not supported, as is stated in the documentation. (http://docs.smart-mirror.io/docs/supported_hardware.html)
