### ISSUE TITLE
Speech recognition not working via wifi

### ISSUE THREAD

**Issue by ddelm** [evancohen/smart-mirror#226]
Hi there,
I am a baby with codes and solving my problem is beyond my skills : I connected my pi to ethernet and the smart-mirror works like a charm :o).
When I unplug the network cable and connect with wifi the Google speech recognizer gets down...
Any idea please ?

**Comment by evancohen** [comment]
It could be a few things

1) You are connected to the WiFi but not the internet
2) Your WiFi/internet is running super slow
3) You are actually out of requests (connecting back to Ethernet gives you the same error)

I'm guessing 3 is the culprit here, can you test Ethernet again?

**Comment by ddelm** [comment]
Thank you for your reply evancohen.
1-> no, the internet works fine
2-> my wifi connection is actually pretty good
3-> may be but when I connect the Ethernet it works again.

When I surf on he I Internet via wifi it works very well.

I will try to replace my wifi stick maybe it comes from that.

Thanks again for your help.

**Comment by Prahli** [comment]
Hi ddelm,
I had a similar problem with the raspberry 3. After some hours of Google I have read about a problem that even if the signal goes out via wifi, the raspberry is waiting for response on the ethernet port. So I have outcommented the ethernet port in the config file. Now it works good for me. It´s worth a try

**Comment by evancohen** [comment]
@Prahli thanks for the info! Sounds like that's the issue to me.

**Comment by ddelm** [comment]
Thank you so much ! You solved my problem :0)
