### ISSUE TITLE
idea: Twitter, Facebook and others feed.

### ISSUE THREAD

**Issue by wuast94** [evancohen/smart-mirror#227]
It would be nice to impliment feed from Social Media

**Comment by evancohen** [comment]
This can be done via RSS (although I suppose it would be possible to make these "first party" modules).

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+23

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
