### ISSUE TITLE
Plug in microphone, Google speach recognizer is down :(

### ISSUE THREAD

**Issue by skydazz** [evancohen/smart-mirror#228]
When I don't have a microphone pluged in it says what can I Say but when I plug in my mic it says Google speach recognizer is down :(

RPI 2 raspian
Turtle beach px22 ear force controller for mic

**Comment by evancohen** [comment]
This is active issue with the Google speech recognizer and is already being tracked by #170. The current solution is to get your own speech keys (instructions for this in the documentation) and to the the keyword spotting branch.

**Comment by skydazz** [comment]
For Anyone else with this issue I had to install PulseAudio
