### ISSUE TITLE
Search for function

### ISSUE THREAD

**Issue by blackshroud** [evancohen/smart-mirror#23]
This does not seem to work.

Is this a function that has actually been completed as yet? or something that is still in the works?

// Search images
            AnnyangService.addCommand('Show me *term', function(term) {
                console.debug("Showing", term);
            });

I also can't see anything that relates to the functions of adding reminders.

Brilliant work thus far

**Comment by andrewda** [comment]
No, it hasn't been completed yet.

**Comment by blackshroud** [comment]
So, I have completed the "add reminder" function.

Have setup a todo list in the left section that uses local storage to create a list that can then be marked as complete and cleared of complete items.

Now to get the search function working...

**Comment by andrewda** [comment]
Make a fork or pull request! I would love to see what you've done :)

**Comment by blackshroud** [comment]
https://github.com/blackshroud/smart-mirror

**Comment by evancohen** [comment]
Create a pull request and I'd be happy to review it! I was thinking of integrating some kind of service to sync reminders. Maybe Wonderlist?

**Comment by blackshroud** [comment]
Hadn't heard of wonderlist, might check it out.

On trust me, my coding will be less than average! hahaha.

**Comment by evancohen** [comment]
That's why there are code reviews! I'm sure it's fine. Lots of stuff is hacky in the code today :P

Their documentation seems really straightforward: https://developer.wunderlist.com/documentation

If I've got some time this weekend I'll take a look at doing this.

**Comment by Shubham0209** [comment]
@blackshroud reminder function in your program doesn't work. Reminders do get added, but don't get striked off or deleted on command "Item ______ is done".

Please can you explain me how it works..

Moreover your program doesn't appear to have main.js(https://github.com/evancohen/smart-mirror/blob/master/main.js)

Pardon me if the question appears silly.

**Comment by blackshroud** [comment]
hmmm odd......

The adding and removing with the command you mentioned works for me....

And main.js exists within the js folder.

Do you get anything in javascript console when you speak commands for
striking things of the list?

**Comment by Shubham0209** [comment]
I am running the code in chrome(laptop), I hope that might not be any issue.

**Comment by Shubham0209** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14998135/12880564/2b590e68-ce68-11e5-857d-5191e307e869.jpg)
this is the error which i receive on using the main.js descried by you..

However on using the main.js of that of evan the program works but reminder part doesn't work

**Comment by Shubham0209** [comment]
If I am not wrong the command to strike off the reminder is "Item ______ is done."?.

And on using the main.js of evan on on executing the command "Item ______ is done.", I get the following error.

Uncaught TypeError: Cannot set property 'completed' of undefined - controller.js:58.

**Comment by kurtdb** [comment]
Keep in mind that this functionality is still incomplete, so chances are very realistic it won't work. (as you have proven)

Afaik no-one has picked up on implementing this functionality yet, so feel free to implement it and submit a pull request. Maybe you can add an external service to store the tasks? (wunderlist for example is a known service for sharing tasks between devices)

**Comment by blackshroud** [comment]
sounds to me like you are using a mix of both mine and evans.

There have been changes made to the main.js and the controller.js of mine
that are likely incompatible.

The list and remove function does work, and require the files on my repo.

What do you mean by "using the main.js"?

The entire app should be run in browser, but as mentioned, will require a
PHP enable webserver to run it on.

**Comment by evancohen** [comment]
@Shubham0209 The mirror code used to run using a simple python hosted HTTPS server - there are a number of issues with this, which is why I moved to Electron.

We no longer officially support the method of running the mirror in Chrome.

Furthermore this project doesn't use jQuery, so I'm not really sure what is going on with that error... The main process that it is referring to isn't `main.js` in this project.

As for getting reminders to work it's kinda low on the priority list right now. Feel free to take a stab at it and send a pull request when ready.

**Comment by Shubham0209** [comment]
@blackshroud thanks for looking into the query.Now what I can conclude is i need PHP enabled webserver to run your code. But how do i get one? Can you please guide me.

**Comment by blackshroud** [comment]
I have the whole thing running of a simple XAMPP install. Check it out ;)

https://www.apachefriends.org/index.html

**Comment by Shubham0209** [comment]
@blackshroud could you please suggest me the changes which are are required to be made so that i can integrate your code with that of evan i.e it can be run using electron with npm start command.
