### ISSUE TITLE
Mirror going to sleep

### ISSUE THREAD

**Issue by Binaryash** [evancohen/smart-mirror#233]
As requested by Evan, posting the mirror sleeping issue.

My mirror goes to sleep in just 2 or 3 mins. A press of the connected keyboard wakes it straight up.

I can recreate the issue after a complete rebuild of the mirror, using s fresh Jessie install

Binaryash>

**Comment by evancohen** [comment]
Just for clarification purposes @Binaryash followed the steps in the documentation and his pi keeps going to sleep: http://docs.smart-mirror.io/docs/configure_the_pi.html#disable-screensaver

**Comment by Binaryash** [comment]
Resolved : 
I found that putting the code from this section of the documentation..
[http://docs.smart-mirror.io/docs/configure_the_pi.html#disable-screensaver]

into this file     /home/pi/.config/lxsession/LXDE-pi/autostart

stops the screen from sleeping.

Binaryash>
