### ISSUE TITLE
[Dev Branch] Alot of videos can't be played

### ISSUE THREAD

**Issue by skydazz** [evancohen/smart-mirror#239]
I am on the dev branch. When I play a video alot of them say they must be watched on YouTube.com due to (dcc? I think) Regulations.

**Comment by evancohen** [comment]
Relevant to the completion of #113. According to the [YouTube Documentation](https://developers.google.com/youtube/v3/docs/search/list#parameters) we should be able to use the `videoEmbeddable` parameter to exclude results that can't be embedded in the mirror.

**Comment by evancohen** [comment]
This should be fixed now
