### ISSUE TITLE
Forecast, Time to work and voice do not work unless started in Dev mode.

### ISSUE THREAD

**Issue by wagdatto** [evancohen/smart-mirror#244]
After a fresh rebuild of the whole system to try to fix the voice not working, I have things displaying properly.  However, unless I start npm using the dev tag, the forecast and driving time don't display, and the microphone doesn't push anything to the bottom of the screen as voice commands.  Once started in dev, voice works and the forecast, etc show up.  Once the dev window is closed, the voice stops working again.

**Comment by kurtdb** [comment]
Sorry for the late reply, but which branch are you using? And is the problem still showing?

**Comment by evancohen** [comment]
This is fixed in the latest `dev` branch and will be merged into `master` soon.
