### ISSUE TITLE
map not displaying without throwing errors when changing language to fr in Config.js, working well with en

### ISSUE THREAD

**Issue by nicoparis** [evancohen/smart-mirror#245]
Hi Evan,

As i told you, when i change the language to 'fr' in config.js the map is not displaying when i told the map to display.
Not a sound detection problem i think it's later because the speech detected is the same than the one in the localization file.

Thank you very much for your help

**Comment by kurtdb** [comment]
Do the other commands work correctly?

**Comment by evancohen** [comment]
You should be setting the language to `"fr-FR"` in the config, not just fr (which will change the language, but not speech detection)
