### ISSUE TITLE
Mirror Service

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#248]
In an attempt to make the mirror more user friendly, we should add a service to manage mirror operations:
- Let you control the power of the mirror remotely (Possibly via something like Home Assistant or other home automation tool).
- Run a command on the mirror remotely (for testing purposes)
- Uses the GitHub API to check the [release version](https://api.github.com/repos/evancohen/smart-mirror/releases) for updates.
- Let's you update the mirror via a voice command (this may be problematic because of occasional breaking changes in the config)

Other suggestions are welcome!

**Comment by thomasstr** [comment]
You were talking about having a single node server for administrating the config. How about if you also  would be able to add/remove the different "widgets" that you would like to show in the default view? Maybe a site with all the widgets that is available and you can have a checkbox on each for showing them.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+22

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
