### ISSUE TITLE
windows7 electron install error

### ISSUE THREAD

**Issue by Aosdin** [evancohen/smart-mirror#249]
run git-bach

$ npm start

> smart-mirror@0.0.1 start C:\Users\nb-0698\documents\smart-mirror
> electron main.js

'electron'▒▒(▒▒) ▒▒▒▒ ▒Ǵ▒ ▒ܺ▒ ▒▒▒, ▒▒▒▒▒▒ ▒▒ ▒ִ▒ ▒▒▒α׷▒, ▒Ǵ▒
▒▒ġ ▒▒▒▒▒▒ ▒ƴմϴ▒_.(Internal or external command, program or batch file)_

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.1 start: `electron main.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.1 start script 'electron main.js '.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nb-0698\documents\smart-mirror\npm-debug.log

**Comment by evancohen** [comment]
> npm ERR! Please include the following file with any support request:
> npm ERR! C:\Users\nb-0698\documents\smart-mirror\npm-debug.log

Please include this file to help debug.

**Comment by kurtdb** [comment]
I would say: try installing nodejs in a path that does not contain a space. Most of the time, it's the root of all evil.

**Comment by evancohen** [comment]
Stale issue, also Windows isn't fully supported anymore (although I am working on it)
