### ISSUE TITLE
Having trouble with mirror.conf set up. Any help?

### ISSUE THREAD

**Issue by patm189** [evancohen/smart-mirror#250]
Hi, I'm not a programmer whatosever, but I've been doing okay following instructions on smart mirror until now. I'm working on adding mirror.conf but getting stuck. 

I'm on the following step. I believe I've done everything correct. I added the configuration to "sudo nano /etc/nginx/sites-available/mirror.conf", but when I try to activate the configuration with, "sudo ln -s /etc/nginx/sites-available/mirror.conf /etc/nginx/sites-enabled/mirror.conf sudo service nginx reload", Terminal says, "ln: target 'reload' is not a directoy". I'm completely stuck since the tutorial I am following offers no troubleshooting. Any help would be greatly appreciated.

**## Installing a web server**

In order to host the webpage you’ll need to install a web server and to run Lumen you’ll need php installed:

_sudo apt-get update sudo apt-get install nginx php5-fpm php5-cli php5-mcrypt git_

That might take awhile, but once that completes you need to configure nginx to know where the MirrorMirror site is located:

_sudo nano /etc/nginx/sites-available/mirror.conf_

And paste the configuration in this gist:

[mirror.conf](https://gist.github.com/ctrlaltdylan/18d78a608a3d81c964e7)

Save, and exit.

Now activate this configuration by running:

_sudo ln -s /etc/nginx/sites-available/mirror.conf /etc/nginx/sites-enabled/mirror.conf sudo service nginx reload_

You now have a php enabled web server running on your pi!

**Comment by evancohen** [comment]
I think you may be in the wrong place, friend. No PHP servers in this smart mirror! 

The documentation for this project can be found here:
http://docs.smart-mirror.io

That said I'll still totally help you with what you've got going (but I will close the issue because it isn't relevant to this project). Could you share the tutorial you were following so I can get a better sense of what's going on?

Cheers :rocket:

**Comment by patm189** [comment]
Thanks for the reply, Evan! That is so strange, I thought I was following the correct instructions to the letter: http://blog.dylanjpierce.com/raspberrypi/magicmirror/tutorial/2015/12/27/build-a-magic-mirror.html

Perhaps there's more than one way to skin a cat? I am hoping I didn't irreversible screw anything up on my Pi. I will run through the documentation you provided and follow up if I run into any snags. Again, thanks for lending a hand.

Pat
