### ISSUE TITLE
weather is not work

### ISSUE THREAD

**Issue by gunatenam** [evancohen/smart-mirror#251]
I'm a student in Korea trying to set up smart mirror with Evancohen's guidance.

I'm not used to Javascript, so I'm just following steps of Evancohen's smart mirror guide post. I succeeded to show greetings and time on display, but I'm stuck on weather forecast.

I don't know how to get weather API and input it in weather.js without error. Tried my best, but when I run npm start, only time and greetings show up on my display.

The picture is the time when I inputted API in weather.js.
![result](https://cloud.githubusercontent.com/assets/19358851/15267403/4d8c738c-19fc-11e6-8687-0d971964f3f8.png)

It would be really helpful if you can teach me what are mistakes of my config and weather.js files.

These are config.js

var config = {
    // Lenguage for the mirror
    language : "ko", //must also manually update locales/X.js bower component in index.html
    layout: "main",
    greeting : ["Hi, kihyun!", "Greetings, kihyun"], // An array of greetings to randomly choose from

    // Alternativly you can have greetings that appear based on the time of day
    /*
    greeting : {
       night: ["Bed?", "zZzzZz", "Time to sleep"],
       morning: ["Good Morning"],
       midday: ["Hey!", "Hello"],
       evening: ["Good evening"]
    },
    */

    // forcast.io
    forcast : {
        key : "{ab68b753b3aba5e9b71781cdcba2df99}", // Your forcast.io api key
        units : "auto" // See forcast.io documentation if you are getting the wrong units
    },
    // Philips Hue
    hue : {
        ip : "", // The IP address of your hue base
        uername : "", // The username used to control your hue
        groups : [{
            id : 0, // The group id 0 will change all the lights on the network
            name : "all"
        }, {
            id : 1,
            name : "bedroom"
        }, {
            id : 2,
            name : "kitchen"
        }]
    },
    // Calendar (An array of iCals)
    calendar: {
      icals : [], // Be sure to wrap your URLs in quotes
      maxResults: 9, // Number of calender events to display (Defaults is 9)
      maxDays: 365 // Number of days to display (Default is one year)
    },
    // Giphy
    giphy: {
      key : "" // Your Gliphy API key
    },
    traffic: {
      key : "", // Bing Maps API Key
      reload_interval : 5, // Number of minutes the information is refreshed
      // An array of tips that you would like to display travel time for
      trips : [{
        mode : "Driving", // Possibilities: Driving / Transit / Walking
        origin : "", // Start of your trip. Human readable address.
        destination : "", // Destination of your trip. Human readable address.
        name : "work", // Name of your destination ex: "work"
        /*startTime: "",
        endTime: ""*/ // Optional starttime and endtime when the traffic information should be displayed on screen. The format can be either hh:mm or hh:mm am/pm
      }]
    }
};
and weather.js:

(function() {
    'use strict';

    function WeatherService($http) {
        var FORCAST_API_KEY ="ab68b753b3aba5e9b71781cdcba2df99";
        var service = {};
        service.forcast = null;
        var geoloc = null;

        service.init = function(geoposition) {
            geoloc = geoposition;
            return $http.jsonp('https://api.forecast.io/forecast/'+FORCAST_API_KEY+'/'+37+','+127+'?callback=JSON_CALLBACK&units=auto')
                .then(function(response) {
                    return service.forcast = response;
                });
        };

        //Returns the current forcast along with high and low tempratures for the current day 
        service.currentForcast = function() {
            if(service.forcast === null){
                return null;
            }
            service.forcast.data.currently.day = moment.unix(service.forcast.data.currently.time).format('ddd');
            service.forcast.data.currently.temperature = parseFloat(service.forcast.data.currently.temperature).toFixed(1);
            service.forcast.data.currently.wi = "wi-forecast-io-" + service.forcast.data.currently.icon;
            service.forcast.data.currently.iconAnimation = service.forcast.data.currently.icon;
            return service.forcast.data.currently;
        }

        service.weeklyForcast = function(){
            if(service.forcast === null){
                return null;
            }
            // Add human readable info to info
            for (var i = 0; i < service.forcast.data.daily.data.length; i++) {
                service.forcast.data.daily.data[i].day = moment.unix(service.forcast.data.daily.data[i].time).format('ddd');
                service.forcast.data.daily.data[i].temperatureMin = parseFloat(service.forcast.data.daily.data[i].temperatureMin).toFixed(1);
                service.forcast.data.daily.data[i].temperatureMax = parseFloat(service.forcast.data.daily.data[i].temperatureMax).toFixed(1);
                service.forcast.data.daily.data[i].wi = "wi-forecast-io-" + service.forcast.data.daily.data[i].icon;
                service.forcast.data.daily.data[i].counter = String.fromCharCode(97 + i);
                service.forcast.data.daily.data[i].iconAnimation = service.forcast.data.daily.data[i].icon;
            };
            return service.forcast.data.daily;
        }

        service.hourlyForcast = function() {
            if(service.forcast === null){
                return null;
            }
            service.forcast.data.hourly.day = moment.unix(service.forcast.data.hourly.time).format('ddd')
            return service.forcast.data.hourly;
        }

        service.refreshWeather = function(){
            return service.init(geoloc);
        }

        return service;
    }

    angular.module('SmartMirror')
        .factory('WeatherService', WeatherService);

}());

Thank you.

**Comment by evancohen** [comment]
Lose the brackets inside the forcast key:
```
forcast : {
    key : "ab68b753b3aba5e9b71781cdcba2df99", // Your forcast.io api key
    units : "auto" // See forcast.io documentation if you are getting the wrong units
},
```

that's the only change you should need.

**Comment by gunatenam** [comment]
yes, I do that. But I can't see weather yet.
