### ISSUE TITLE
weather problem.

### ISSUE THREAD

**Issue by gunatenam** [evancohen/smart-mirror#252]
Now I have a problem in weather part.

In config.js

I wrote

forcast : {
    key : "ab68b753b3aba5e9b71781cdcba2df99", // Your forcast.io api key
    units : "auto" // See forcast.io documentation if you are getting the wrong units

and

In weather.js

service.init = function(geoposition) {
        geoloc = geoposition;
        return $http.jsonp('https://api.forecast.io/forecast/'+config.forcast.js+'/'+37+','+127+'?callback=JSON_CALLBACK&units=auto')
            .then(function(response) {
                return service.forcast = response;
            });
    };

But I can't see weather in my display.
How to do solve this problem?

**Comment by evancohen** [comment]
Looks like you made some changes to that file. https://github.com/evancohen/smart-mirror/blob/master/js/services/weather.js#L11

Unless you need them you should revert. If you are still having issues then look at the network tab and see if you are making the correct request. This may be a symptom of Electron not being able to determine your location, so you may want to hard-code it (this config value may not exist in `master` yet, so check the `dev` branch)
