### ISSUE TITLE
Video Stop On "Go Home" Command

### ISSUE THREAD

**Issue by HelloExactly** [evancohen/smart-mirror#258]
Video continues to play upon arriving at home screen.

**Comment by evancohen** [comment]
Thanks for following through and filing this. I'll take a look after I finish the keyword spotter :)

**Comment by HelloExactly** [comment]
Thanks for putting this project together!

**Comment by justbill2020** [comment]
@evancohen has this been fixed? i think this should be added to the mute when using KWS features... http://feathub.com/evancohen/smart-mirror/+14

I'm labeling this as a bug. If its fixed please close... 

If this is a future enhancement please comment on feathub related to feathub+14. Thanks

**Comment by evancohen** [comment]
Yup, it's a bug 🙃

**Comment by justbill2020** [comment]
@evancohen was this fixed in #500?

if not do we have a fix?

**Comment by evancohen** [comment]
It wasn't. There's something really strange with the iFrame that's causing digest cycles to not fire - I had an experimental hack fix, but the real solution for this is to use routing instead of `$scope.focus` (which we should be doing anyway). I'll add this to my to-do list.
