### ISSUE TITLE
Smart mirror startup

### ISSUE THREAD

**Issue by snypervash** [evancohen/smart-mirror#259]
Hey Guys, I followed the guide and when I reboot my pi, it just gets stuck on the desktop screen with no taskbars. Any help is much appreciated.

Also, I can't install NPM without getting the 'illegal instruction' error.

**Comment by hiltonmw** [comment]
How did you resolve this - I'm having the same problem

**Comment by snypervash** [comment]
I was using the Raspberry PI 1, which isn't supported. It worked perfectly on my RPi 2

**Comment by phelixz** [comment]
Hi Snypervash,

I got same problem and found that I had written the unclutter function ("unclutter -idle 0.1 -root")  in the wrong autostart file. 

I wrote it to  /home/pi/.config/lxsession/LXDE-pi/autostart 

but it need to be added here: 

/etc/xdg/lxsession/LXDE-pi/autostart 

as mentioned in cohen´s manual.

I hope this will help.
