### ISSUE TITLE
Weather not working

### ISSUE THREAD

**Issue by swinkq** [evancohen/smart-mirror#26]
Hi, i can't get the weather work... I got the working api, paste in config file , but the weather does not show..
I should paste it only in config.js? 
var FORCAST_API_KEY = "{https://api.forecast.io/forecast/apikey/47,29}"; Like that?﻿

**Comment by evancohen** [comment]
The format of the api key should be as follows:

`var FORCAST_API_KEY = "la1ksd90afujw309sd0934afj";`

I'll update the documentation to reflect that :)
