### ISSUE TITLE
Switch calendar via Voice Command per User 

### ISSUE THREAD

**Issue by sata73** [evancohen/smart-mirror#266]
It would be great to show different calendar or even RSS feeds per user via voice command, eg. "Show Evans calendar" or log in as a user via voice command to show specific content and log out to show default content.
It could probably be done by adding users to modules in the config and define if it is for this or for that user or for all.

**Comment by evancohen** [comment]
I think the best approach here would be to use the webcam and facial recognition here, as suggested in #59

**Comment by sata73** [comment]
Thanks for your fast reply!
I thought about voice control, because not everyone is fine with having a cam spying into the room. And since voice control is already enabled, it might be worth a thought, using the available technology.
The command home shows the default layout. Probably different layouts could be defined which can be called by custom commands like Evans home? Is that possible?

**Comment by jallen1227** [comment]
Agreed on the privacy relative to cameras, what about switching based upon use of Pi's NFC module.  That way, a phone or tablet could be used to switch between users.  Certainly not as convenient as voice but opens up options and validation / security of content shown.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+21

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
