### ISSUE TITLE
Slideshow mode

### ISSUE THREAD

**Issue by trenkert** [evancohen/smart-mirror#268]
for screens that are smaller or have a lower resolution. 

The idea is that different modules like weather, calendar, greetings are shown as rotating slides. Only when a voice command is activated, the screen stays fixed (and shows a map, for instance).

**Comment by evancohen** [comment]
I think the better solution here would be to use viewport based font sizes so that the mirror gracefully degrades down to smaller screen sizes.

How does that sound?

**Comment by trenkert** [comment]
Yes, that would be an alternative. However, I still think that rotating slides also have some benefits.

**Comment by evancohen** [comment]
It'd be interesting to see how it would work. Create a rough prototype and I'd be happy to take a look.

**Comment by R3dRuM** [comment]
I like the idea about the slideshow. I'm currently using a pretty small screen (19"), too. I'd love too see as much information as possible but it gets packed pretty quickly and disctracts you from the original purpose of the mirror :)
are you working on this yet @trenkert ?

**Comment by trenkert** [comment]
@R3dRuM i am not, in fact. It shouldn't be too difficult to do it, though.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+19

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion
