### ISSUE TITLE
css themes

### ISSUE THREAD

**Issue by trenkert** [evancohen/smart-mirror#269]
The default theme is nice but I'd like an option where the font weight is a little bolder. I can, of course, do this manually for each module. But I would prefer having the option of different themes.

**Comment by evancohen** [comment]
A theme system already exists (see icesnow in the config documentation). Can you be a bit more specific about what you want?

**Comment by GobleSt** [comment]
A more simple method of customizing the main interface, such as including more/different features or excluding unwanted features other than playing with css would be real nice for those of us who do not actually want to learn cascading style sheets....?

I would like to simply move the greeting to the bottom of the window and include newsfeeds.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+18

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion
