### ISSUE TITLE
Lights

### ISSUE THREAD

**Issue by Codeusa** [evancohen/smart-mirror#27]
Just out of curiosity, how did you go about hooking up the system to your house lights/changing colors? Would love to do something similar.

**Comment by monaiz** [comment]
Hi, take a look in hue-service.js the code is explained very well.

https://www.meethue.com/api/nupnp

**Comment by evancohen** [comment]
Thanks @monaiz :+1: 
hue-service.js can be found here: https://github.com/evancohen/smart-mirror/blob/master/js/hue-service.js
