### ISSUE TITLE
Error: "Cannot find module" and "Unknown Provider"

### ISSUE THREAD

**Issue by kralle1987** [evancohen/smart-mirror#271]
Hi,

I am somehow not able to get it running.
I used the step by step installation guide.
I only use the greeting, weather, traffic and the calendar. everything else is commended.
when I run it in dev mode I get 2 errors:
"Cannot find module './router'" 
and 
"Unknown Provider: FitbitServiceProvider <-Fitbitservice <- MirrorCtrl"

View the [Screenshot](http://i.imgur.com/HMaF99n.png) here

Any ideas?

Thanks!

Chris

**Comment by evancohen** [comment]
Do not remove config values, this will cause a bunch of issues in master. This has already been fixed in the dev branch with 30fe896bae25450a88400ad17b26fe6ac3fa73b2 but for now just leave the empty config values there.
