### ISSUE TITLE
Load of the config.js file in main.js doesn't work

### ISSUE THREAD

**Issue by overflOw11** [evancohen/smart-mirror#272]
Load of the config.js file doesn't work in the main.js file. We can check if the file exists with the first if clause in the catch block. The line "config = require(__dirname + "/config.js");" doesn't load the file, it just allow us to check if the file exist so later in the main.js file, when we load the config.speech.model (var modelFile = config.speech.model || "smart_mirror.pmdl"), the config file isn't load and the value of the modelFile variable is always smart_mirror.pmdl.

**Comment by evancohen** [comment]
You're probably missing the final line of your config file:
``` javascript
if (typeof module !== 'undefined') {module.exports = config;}
```

See: https://github.com/evancohen/smart-mirror/blob/dev/config.example.js#L88

**Comment by overflOw11** [comment]
My mistake ! Thank you
