### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by vrsho** [evancohen/smart-mirror#278]
Hi, when i start the shell script, nothing happens. I have raspberry pi 1 and i installed the node for armv6. What could be the issue? Thanks. 

> pi@raspberrypi:~  $ ./smart-start.sh

> smart-mirror@0.0.2 start /home/pi/smart-mirror
> electron main.js

> pi@raspberrypi:~

**Comment by evancohen** [comment]
As noted in the documentation (in the hardware section), the Pi 1 is not supported for this project. 

You may be able to install Chromium and use a local HTTPS Python server (go back through this projects history to the very beginning, that's how it used to work). I can't gerentee that everything will work with that method though (for instance the keyword spotter would have to be started manually).
