### ISSUE TITLE
What time is it?

### ISSUE THREAD

**Issue by ikucukkaya** [evancohen/smart-mirror#280]
The "what time is it" command is shown in the available commands however it has no effect. Evan I open a new issue because you told me if i didn't misunderstand you :d

**Comment by glcohen** [comment]
I've been playing with getting this working today and am nearly there. I've been using the SpeechSynthesisUtterance API. Here's the code I've got so far. Haven't gotten sound working quite yet, but this method does work if I run it from a non-mirror js console.

`function getTime() {
              var currentTime = new Date();
              var hours = currentTime.getHours();
              var minutes = currentTime.getMinutes();
              var t = "The time is ";
              if (minutes < 10) {
                minutes = "0" + minutes;
              }
              t += hours + ":" + minutes + " ";
              if (hours > 11) {
                t += "PM";
              }
              if (hours <= 11) {
                t += "AM";
              }
              return t;
            }


            addCommand('time_show', function(task) {
              var msg = new SpeechSynthesisUtterance(getTime());
              window.speechSynthesis.speak(msg);
              console.debug("The time is", moment().format('h:mm:ss a'));
            });`

**Comment by glcohen** [comment]
I had been exploring [Artyom](https://github.com/sdkcarlos/artyom.js), but it looks like, unfortunately, Google has discontinued the use of the Speech API in embedded/dev chromium environments.

[https://discuss.atom.io/t/webkitspeechrecognition-google-webkit-speech-api-throws-network-error-in-electron-app/27958/3](url)

Not sure what to look into next...

**Comment by evancohen** [comment]
@glcohen I think what you are talking about is unrelated to this issue... As for the Speech API, the workaround is in the documentation and is no longer an issue for us.

**Comment by glcohen** [comment]
Could you point me to the documentation with the workaround?

As far as I can tell the problem is that speechSynthesis won't load any voices (speechSynthesis.getVoices() returns a null set), because synthesis isn't supported in Chromium.

**Comment by evancohen** [comment]
Having the mirror talk back to you is not really a missing feature, I have expressly kept it out of the mirror up until now. See my response in #78 for details.

You should open up a new issue for this and we can discuss the merits of the mirror responding to you via voice there (I'll try to help you get speech synthesis working regardless).

**Comment by justbill2020** [comment]
removed suggestion label as this is being worked on and is labeled "next"

**Comment by justbill2020** [comment]
#386 duplicate
