### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by ikucukkaya** [evancohen/smart-mirror#281]
Can the timer wink when time is up? or something like that.

**Comment by evancohen** [comment]
@nicolasmn maybe you could take a look at this? Your call if you think it's something we should do. BTW, did you ever get some sounds that we could use when the timer was up?

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+17

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion
