### ISSUE TITLE
Google Speech Recognizer is down :(

### ISSUE THREAD

**Issue by vrsho** [evancohen/smart-mirror#282]
Hi, i cant fix this error. The Speech Recognizer was working Yesterday and suddenly stopped this Morning. I have tried to install pulseaudio, microphone is working good. I have registered to the speech API and added the API Keys to the env but still no speech recognition. Is there anything else i missed? Thanks.

**Comment by ikucukkaya** [comment]
This is a known issue and everybody have this problem you are not the only one :d You can check here: https://github.com/evancohen/smart-mirror/issues/170 Evan is working on the keyword spotting to solve this problem and in that link there are some steps which Evan told, you can try them.
