### ISSUE TITLE
RSS feed support

### ISSUE THREAD

**Issue by rohansood** [evancohen/smart-mirror#283]
I think it would be great if we could manually add a RSS feed source in the config.js that would display things like news/sports

**Comment by ikucukkaya** [comment]
There is a pull request for RSS feed, i tried to run that but i couldn't. If you want to look: https://github.com/evancohen/smart-mirror/pull/161

**Comment by yaydogan** [comment]
I have a working RSS service in my branch:
https://github.com/yaydogan/smart-mirror/tree/customize

Unfortunately my branch is behind Evan's main branch so I can't merge. I was too busy and couldn't get my branches up to date and raise a new PR. You can look at the code and just pull in RSS service related code. If you need help, IM me privately and I can point you what files (and sections) you need.

**Comment by evancohen** [comment]
If someone could create a new PR with @yaydogan's changes that would be super helpful :)

**Comment by yaydogan** [comment]
I am working on resolving conflicts. I should be able to complete it by tomorrow.

**Comment by evancohen** [comment]
This has now been merged into the `dev` branch.
