### ISSUE TITLE
Soundcloud starts to play but stops.

### ISSUE THREAD

**Issue by GobleSt** [evancohen/smart-mirror#284]
When using voice and having Soundcloud play a song, it comes up starts to play then stops.  In addition, the greeting is moved to the top of the screen and jumbles up with the calendar and weather features.  Soundcloud plays fine with no issues in the browser.

**Comment by ikucukkaya** [comment]
I have the same issue, i thought this error comes up because of my internet speed but now i can see it is not related to speed.

**Comment by evancohen** [comment]
Sounds like a bug! I'll take a look this week.

**Comment by GobleSt** [comment]
This may be fixed in the new update.  I still need to test.

**Comment by GobleSt** [comment]
Not fixed.  In the default web browser Soundcloud is not able to complete playing a track.  It just never completes the buffer.  I installed Chromium and Soundcloud plays with no issue.

**Comment by evancohen** [comment]
Ok. @mojosoeun maybe you could take a look at this since you were the one who sent the original PR?

**Comment by mojosoeun** [comment]
I'll take a look this week.

**Comment by digitaldidge** [comment]
Can you please post the HTML code you used, I used an <iframe> tag to get a youtube playlist to present itself earlier and it would always play the full first track in the youtube playlist, but never anything further..

I'm very curious to know how to you got soundcloud to show :D

**Comment by evancohen** [comment]
@digitaldidge all of the code for SoundCloud is in the `master` branch.
You might want to check out [`js/services/soundcloud.js`](https://github.com/evancohen/smart-mirror/blob/master/js/services/soundcloud.js)

**Comment by geman220** [comment]
Soundcloud doesn't seem to even start playback for me.  Not sure if this is a different issue or related to this bug.  Just wanted to throw in my .02 if that helps.

**Comment by evancohen** [comment]
@mojosoeun :bell: just a gental reminder

**Comment by geman220** [comment]
Wanted to post a breakdown of what I've done so far:

1. If I do ```pulseaudio -k``` and manually issue a command in the dev console ```annyang.simulate("SoundCloud play QUERY”);``` to the mirror I will get flawless playback. 

2. If I then ```pulseaudio --start``` and voice issue a command it will playback audio for about 2 seconds before stopping. I'm almost certain it's pulse audio taking a dump. 

3. If you do ```speaker-test -c2 -t wav``` with pulseaudio running it will bug out constantly, usually doesn't get past the first speaker test. 

4. The same command works perfectly if you kill pulseaudio. 

Hopefully this helps someone.

**Comment by mojosoeun** [comment]
@geman220  It seems like a problem between 'pulseaudio' and 'html5 audio' and I found a similar [issue](http://askubuntu.com/questions/646130/no-sound-with-html5-video-player-under-firefox-or-chromium-with-ubuntu-gnome-15). I'm thus looking for the solution.

**Comment by geman220** [comment]
@mojosoeun Awesome, thanks so much.  Just so you know I'm trying everything on my end to find a solution.  justbill2020 is sending me his SD card image that he confirmed is working on 3 different RPi3s.  I've re-formatted and re-setup everything at least 4 times now and I get the same result every time.  I was thinking it could be a hardware issue, but I'm not the only person in the world having the issue so I have a hard time accepting that my hardware could be bad.

**Comment by geman220** [comment]
I've re-formatted and re-configured everything from scratch (again).  Now I am seeing this error when issuing a voice command http://i.imgur.com/q9oDLAA.png .  The voice command pops up for about half a second and errors out with the error at the bottom.  Not sure if it's relevant to this or not.

**Comment by geman220** [comment]
I have quite a few findings and a general hackish work around to this issue I believe #307.

**Comment by Keopss** [comment]
We have any progress?

**Comment by evancohen** [comment]
@Keopss geman is correct, #307 is the solution to this.

**Comment by Keopss** [comment]
Thank you @evancohen. I have to follow "Update 3" changes?

**Comment by evancohen** [comment]
This issue is resolved, see the bug I linked above or the documentation for details
