### ISSUE TITLE
Plex integration similar to Soundcloud and Youtube.  

### ISSUE THREAD

**Issue by GobleSt** [evancohen/smart-mirror#285]
I serve up photos, music, tv and movies using Plex Media Server and I would love to be able to search for a song or show using voice commands on the mirror.

**Comment by kurtdb** [comment]
This will probably involve intercepting the commands that the Plex web client sends to the server. Afaik these are not documented, so might be a cumbersome job.

**Comment by GobleSt** [comment]
I saw this yesterday... [plexpy](https://github.com/drzoidberg33/plexpy/issues)

**Comment by HelloExactly** [comment]
i too would LOVE Plex on this.  Would the video be choppy like the current YouTube vids?

**Comment by kurtdb** [comment]
Looks like we could use this: https://www.npmjs.com/package/plex-api.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+16

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion
