### ISSUE TITLE
Motion Detection with a "sleep" mode

### ISSUE THREAD

**Issue by GobleSt** [evancohen/smart-mirror#286]
Since a lot of us are using webcam for the mic / voice control how hard would it be to add a motion detection using the webcam?  When a certain period of time goes by to sleep the screen to help prevent burn?

**Comment by bajo** [comment]
Motion detection is fairly simple to implement with OpenCV. But I only know of c++ and python support. Is there some way to connect c++ or python to the smart-mirror project?

**Comment by evancohen** [comment]
@bajo The keyword spotter is actually a python library (although I'm in the process of writing a node module for their C++ library). In short: absolutely.

**Comment by geman220** [comment]
Wouldn't motion detection with a PIR sensor be easy?

**Comment by willem-hill** [comment]
@geman220 Yes, it would be absurdly easy. I've done similar projects
(specifically, a burglar alarm system for my house) using a PIR sensor and
a raspberry pi.

On Fri, Jun 24, 2016 at 2:37 PM, geman220 <notifications@github.com> wrote:

> Wouldn't motion detection with a PIR sensor be easy?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/evancohen/smart-mirror/issues/286#issuecomment-228426099>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQ9AkS5j-adneu07Jl1vhv9kdE0e7PSuks5qPCP7gaJpZM4Izh_J>
> .
>



-- 
HillierTech on Facebook <http://www.facebook.com/hilliertech> (Like!)
HillierTech's New Website <http://willemhillier.wix.com/hilliertechvt>

**Comment by geman220** [comment]
@willem-hill That was sort of my point.  Instead of making a webcam sensor make a PIR sensor, they are cheaper to buy and easier to implement.

**Comment by GobleSt** [comment]
Could this be done using:  https://goo.gl/xt2w5d ?

**Comment by bajo** [comment]
@GobleSt possibly. However, OpenCV is the standard library to do something simple like that. 
One good tutorial can be found here [1], full source code as well. I think it can be easily adopted to not output the motion shown as boundary box in an output window, but only as a bool or string which can be used within the js script for further processing. 
However I am not familiar with the process of calling the python script and using the return values in js. 

[1] http://www.pyimagesearch.com/2015/05/25/basic-motion-detection-and-tracking-with-python-and-opencv/

**Comment by evancohen** [comment]
@bajo we currently do that today with the keyword spotter by spinning up a child process with an IPC. See `main.js` for the exact implementation.

**Comment by bajo** [comment]
@evancohen I will look I to it and come back to you if I need some help. Thanks for pointing me in the right direction.

**Comment by evancohen** [comment]
Awesome!

**Comment by GobleSt** [comment]
I have installed motion and am able to view the feed in the web browser.  motion.conf is what I am working on now to get the "on_event_start value" and "on_event_end value" actually calling to my off and on scripts.  Manually calling the scripts work but for some reason the motion.conf doesn't.... I thought is might have been since motion.conf is called by the motion user but sudo -u motion >script< works too....odd

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+12

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
