### ISSUE TITLE
Latest update breaks weather and voice is accepted but commands are not performed.

### ISSUE THREAD

**Issue by GobleSt** [evancohen/smart-mirror#289]
`npm start dev` pops these errors:

angular.js:13642 TypeError: Cannot read property 'key' of undefined
at Object.WeatherService.service.init (weather.js:11)
at controller.js:70
at processQueue (angular.js:16104)
at angular.js:16120
at Scope.$eval (angular.js:17378)
at Scope.$digest (angular.js:17191)
at Scope.$apply (angular.js:17486)
at bootstrapApply (angular.js:1780)
at Object.invoke (angular.js:4708)
at doBootstrap (angular.js:1778)

angular.js:11821 GET http://dev.virtualearth.net/REST/V1/Routes/Driving?wp.0=&wp.1=&avoid=minimi…Tolls&key=Aq8GFZ6_bp7LIu0uuYZl7Z0kv-1Sa0eUAXgAhPMtlLwkj-jFoDGd9cjcpk8IHe1d 400 (Bad Request)(anonymous function) @ angular.js:11821sendReq @ angular.js:11582serverRequest @ angular.js:11292processQueue @ angular.js:16104(anonymous function) @ angular.js:16120$eval @ angular.js:17378$digest @ angular.js:17191$apply @ angular.js:17486bootstrapApply @ angular.js:1780invoke @ angular.js:4708doBootstrap @ angular.js:1778bootstrap @ angular.js:1798angularInit @ angular.js:1683(anonymous function) @ angular.js:31018trigger @ angular.js:3197defaultHandlerWrapper @ angular.js:3487eventHandler @ angular.js:3475
traffic.js:47 Bad Request(anonymous function) @ traffic.js:47processQueue @ angular.js:16104(anonymous function) @ angular.js:16120$eval @ angular.js:17378$digest @ angular.js:17191$apply @ angular.js:17486done @ angular.js:11637completeRequest @ angular.js:11843requestLoaded @ angular.js:11776
angular.js:13642 ReferenceError: duration is not defined
at traffic.js:50
at processQueue (angular.js:16104)
at angular.js:16120
at Scope.$eval (angular.js:17378)
at Scope.$digest (angular.js:17191)
at Scope.$apply (angular.js:17486)
at done (angular.js:11637)
at completeRequest (angular.js:11843)
at XMLHttpRequest.requestLoaded (angular.js:11776)(anonymous function) @ angular.js:13642(anonymous function) @ angular.js:10287processQueue @ angular.js:16112(anonymous function) @ angular.js:16120$eval @ angular.js:17378$digest @ angular.js:17191$apply @ angular.js:17486done @ angular.js:11637completeRequest @ angular.js:11843requestLoaded @ angular.js:11776
controller.js:158 Dilbert comic initialized
angular.js:11821 GET http://dev.virtualearth.net/REST/V1/Routes/Driving?wp.0=&wp.1=&avoid=minimi…Tolls&key=Aq8GFZ6_bp7LIu0uuYZl7Z0kv-1Sa0eUAXgAhPMtlLwkj-jFoDGd9cjcpk8IHe1d 400 (Bad Request)(anonymous function) @ angular.js:11821sendReq @ angular.js:11582serverRequest @ angular.js:11292processQueue @ angular.js:16104(anonymous function) @ angular.js:16120$eval @ angular.js:17378$digest @ angular.js:17191$apply @ angular.js:17486tick @ angular.js:12446
traffic.js:47 Bad Request(anonymous function) @ traffic.js:47processQueue @ angular.js:16104(anonymous function) @ angular.js:16120$eval @ angular.js:17378$digest @ angular.js:17191$apply @ angular.js:17486done @ angular.js:11637completeRequest @ angular.js:11843requestLoaded @ angular.js:11776
angular.js:13642 ReferenceError: duration is not defined
at traffic.js:50
at processQueue (angular.js:16104)
at angular.js:16120
at Scope.$eval (angular.js:17378)
at Scope.$digest (angular.js:17191)
at Scope.$apply (angular.js:17486)
at done (angular.js:11637)
at completeRequest (angular.js:11843)
at XMLHttpRequest.requestLoaded (angular.js:11776)(anonymous function) @ angular.js:13642(anonymous function) @ angular.js:10287processQueue @ angular.js:16112(anonymous function) @ angular.js:16120$eval @ angular.js:17378$digest @ angular.js:17191$apply @ angular.js:17486done @ angular.js:11637completeRequest @ angular.js:11843requestLoaded @ angular.js:11776

**Comment by GobleSt** [comment]
There are changes in the config.js that cause some of the issues above.  I redid the config.js using the new changes in config.example.js and was able to get weather displaying.  Voice is still accepted and no action is perfomed.

Issuing the #`pulseaudio --start` prior to #`./smart-start.sh` will fix the failure of performing voice commands.  

I DO see these when starting the mirror:
`pi@smartmirror:~ $ ./smart-start.sh`

`> smart-mirror@0.0.2 start /home/pi/smart-mirror`
`> electron main.js`

`ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave`

`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline`
`ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave`

`Cannot connect to server socket err = No such file or directory`
`Cannot connect to server request channel`

`jack server is not running or cannot be started`

and I think a lot of our issues is funky or poor quality pulseaudio...

**Comment by GobleSt** [comment]
Mark this one as me being an idiot.

**Comment by SebDuboisMIAGE** [comment]
Hi GobleSt,

Can you show me your config.js please ?
Because i've got the same error on my smart mirror and i don't find how the fix this problem.

Thx

**Comment by evancohen** [comment]
@SebDuboisMIAGE I would just wipe out the config and re-copy `config.example.js`. that should get you back to a good state.

**Comment by SebDuboisMIAGE** [comment]
@evancohen Ok, so i just wait your correction on the config file ?

**Comment by SebDuboisMIAGE** [comment]
I resolved the first problem (i forgot the Bing Maps Api key), so i have no error when i do npm start dev, but the voice recognition doesn't work...

**Comment by GobleSt** [comment]
Soon as I get home it's yours!

**Comment by GobleSt** [comment]
Not sure if you still wanted this but:  
[config.zip](https://github.com/evancohen/smart-mirror/files/353864/config.zip)

**Comment by SebDuboisMIAGE** [comment]
Hi @GobleSt and thank you for the config file.

I resolved my problem, it's just the quality of the microphone which is very bad.
And it struggle to recognize my voice.

Thx a lot !

**Comment by evancohen** [comment]
Seems like this issue is resolved
