### ISSUE TITLE
Snowboydetect fail on Windows 7

### ISSUE THREAD

**Issue by SebHeuze** [evancohen/smart-mirror#293]
Hi everyone,

I tried to launch the last version of Smart Mirror with Snowboydetect on Windows 7
But it fails with "ImportError: No module named _snowboydetect"

Which is logic because snowboydetect is a linux only project right ? 

Or maybe there is a way to use it on Windows 7 ? (I'm using Raspberry 2, but I prefer to work on windows before putting it on my mirror)

If the project didn't fully work on windows maybe you should update the Supported Hardware section ?

Thanks for this amazing project :)

**Comment by evancohen** [comment]
Windows 7 is still supported, I'm working on building an x64 binary but haven't had a chance yet.

The binary that is packaged is ARM, so it doesn't work on OSX either (you have to swap out the binary file).

You could try using the `evancohen/keyword-spotting` branch, which uses another method of keyword spotting that does work on Windows (just not the Pi). Note that the config it quite different so you'll have to update when you switch.

**Comment by SebHeuze** [comment]
It works now with the keyword-spotting branch, didn't seen that this branch was using a different method than master

Thanks
