### ISSUE TITLE
help to create a snowboy model

### ISSUE THREAD

**Issue by seiferal** [evancohen/smart-mirror#295]
hi, i m stuck at the step of making my own model for the voice recognition on the website https://snowboy.kitt.ai/hotword/47

I got to the step that I have to record my voice 3 times. But after the first record, nothing happenned. I could not move on to the 2nd and 3rd record to finish my model. Any ideas why this did not work for me?

I tried this on both Chrome and Firefox. I m running windows 7 x64.
Thank u guys

**Comment by GobleSt** [comment]
I had/have this same issue.  Poor audio / recording with the webcam on the rpi3 is what I attributed it to.  I went ahead and made the recording on another system and used the file that way.  My thought is that the audio issues we are having are related....[284](https://github.com/evancohen/smart-mirror/issues/284) etc... BUT...I am not one of the smart guys here....

**Comment by evancohen** [comment]
Have you set your webcam to be the default input device for your machine? You should confirm that microphone input is working in your web browser first, but you may want to contact the kitt.ai folks if you are still having trouble. They are awesome people and are really responsive :)

**Comment by sata73** [comment]
Can I use it w/o using the model and keyword?
The old version w/o it works like a charm with voice control, this version doesn't do anything with voice comands.

**Comment by evancohen** [comment]
@sata73 you can, but the number of requests that you are allotted will cause the mirror to fail speech recognition after about 5-10 min and be stuck in that state for the next 24 hours. 

Have you installed the new dependencies?

**Comment by sata73** [comment]
Yes, I did install the new depencies. I'll try to setup the system completely new and start up from scratch.
Just to be sure, I have to say "Smart Mirror" before the actual command is spoken?
About the ding: Do I have to have speakers that output a sound which the Smart Mirror detects and then starts recognizing the voice commands? I don't have speakers yet.

**Comment by GobleSt** [comment]
The bottom of the screen will light up when it is listening for commands.  I don't think the ding was put back on yet....

**Comment by sata73** [comment]
Ok, now I've set up the system completely new and it works now, but
- it does seldom recognize the keyword and the screen will not light up
- I also get stuck at the 1st or 2nd record at https://snowboy.kitt.ai/hotword/47
    - I guess, the recognition would be better with the model?

**Comment by GobleSt** [comment]
I had similar issues.  ...try to close the mirror after boot up and run <# pulseaudio --start> then start up the mirror and see if that helps.

**Comment by evancohen** [comment]
I'm going to add `pulseaudio --start` as a part of the mirror boot (as it seems PulseAudio on the current version of Jessie is not autostarting)

**Comment by sata73** [comment]
Nope, doesn't help :-( 
In the meanwhile I wrote with the guys of snowboy because of the model issue and they replied, that there is a know issue with uploading wavs which is not yet fixed.
They told me, that I have to convert the wavs and there we go - I got a model:
`sox -t wav recorded_wav.wav -t wav -r 16000 -b 16 -e signed-integer -c 1 converted_wav.wav`

Anyway, even with the model and `pulseaudio --start` it doesn't work stable. I got the keyword detected only once.

Just for curiosity: How could I turn the keyword spotter off?

**Comment by seiferal** [comment]
@sata73: how do you convert the wav file in windows? i stuck at uploading the 1st audio file :(

**Comment by evancohen** [comment]
@seiferal if you have sox installed on windows the command should be the same.

**Comment by seiferal** [comment]
@sata73 @evancohen  it works perfectly now :+1:  thank you guys so much :D
