### ISSUE TITLE
Youtube video

### ISSUE THREAD

**Issue by digitaldidge** [evancohen/smart-mirror#296]
Hello folks,
inside the config.js file I can see the youtube example..

youtube: {
    key : "vy2u1t34bo123bu41234yduv1234tb"
}

How do I get that to show in the top_left part of the smart-mirror when it's running, any examples would be awesome :D

Thanks for everyones help :D

**Comment by GobleSt** [comment]
If you check out the [chat](https://gitter.im/evancohen/smart-mirror) I just did similar moving the greeting to the bottom...modifying the index.html file...

**Comment by digitaldidge** [comment]
Thanks :D

I just dont know how after I've edited the .js file expect it to just appear on screen where I want it :D

**Comment by evancohen** [comment]
@digitaldidge you'll need to modify `index.html`. Just move the existing `<div>` container to whatever parent section you want.

More development details: http://docs.smart-mirror.io/docs/development_and_contributing.html

**Comment by digitaldidge** [comment]
Cheers buddy, even with adding in the config.js [ youtube : {add google/youtubeID here ], and the controller.js in the $scope.video = 'https://www.youtube.com/embed/videoeries?list=PLuMkI8cH380LOX2YSxC3m29y_69E-6z-I' it still never presented me with a video to see so I could not move on with editing the index.html file and rearranging the <div> tags :(
Thanks very much for the help.

**Comment by evancohen** [comment]
It is also nessesary to change the focus of the mirror using:
``` JavaScript 
$scope.focus = "video";
```
Or you could remove the `ng-show` binding in `index.html`
