### ISSUE TITLE
White screen on startup.

### ISSUE THREAD

**Issue by Criss95** [evancohen/smart-mirror#297]
fix the "white screen" issue that appear at the mirror startup.

**Comment by kurtdb** [comment]
https://github.com/electron/electron/issues/861 > look at @mrtdeh's answer from 23 days ago. Might be an easy fix.

**Comment by evancohen** [comment]
Thanks @kurtdb! There are actually two issues here I think. The first that you described, and a second with `ng-cloak`.

Pretty sure I can fix both of these, no problem. I'll take a stab this week.

**Comment by evancohen** [comment]
@kurtdb I tested out that option. For some reason using this method ignores kiosk mode - I'll have to do some more investigating.

**Comment by evancohen** [comment]
This isn't actually a "bug" per se, and it should be mostly fixed by the performance improvements in #352 and the rest of the optimizations from #345. 

Going to close this out because it's being tracked elsewhere.
