### ISSUE TITLE
Does this only run in Chrome?

### ISSUE THREAD

**Issue by tvfoodmaps** [evancohen/smart-mirror#3]
I'm currently using MIdori for my smart mirror, seems like this only works with Chrome? Is that correct?  If so which version of chromium were you able to get working?

**Comment by usman118591** [comment]
Yeh currently it's supporting by chrome. and Chromium is on its testing phase. Have you checked that on chromium?

**Comment by tvfoodmaps** [comment]
I can't get to seem to get chromium working on my pi1 + Raspbian.

**Comment by evancohen** [comment]
The mirror uses annyang for speech recognition, which only runs on newer versions of Chromium. It is theoretically possible to compile chromium for the Pi 1, although it would be quite difficult and the end result would not be terribly performant - I highly suggest using the Pi 2 as it drastically simplifies the process and does a much better job with speech recognition.

**Comment by missionrulz** [comment]
@evancohen, Perhaps adding that Chrome/Chromium is a requirement on README.md.

**Comment by evancohen** [comment]
@missionrulz This information is now out of date. The project uses Electron, which is already described in the README.
