### ISSUE TITLE
Remove SCSS

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#300]
Based on recent discussion and in the interest of simplicity we should remove SCSS from the project.

**Comment by joelhawksley** [comment]
@evancohen I can't seem to assign myself to this, but I can take this one.

**Comment by kurtdb** [comment]
It's not that strict that you have to assign yourself here on github. A comment should be enough. (and a PR :))

**Comment by joelhawksley** [comment]
👍
