### ISSUE TITLE
Failed to install electron-prebuilt

### ISSUE THREAD

**Issue by arifcit520** [evancohen/smart-mirror#301]
I am trying to install electron-prebuilt using the instruction
![electron-prebuilt](https://cloud.githubusercontent.com/assets/19537585/16256685/a55f3b48-3875-11e6-8f39-4755f02e8a8e.PNG)
 
[https://www.npmjs.com/package/electron-prebuilt](https://www.npmjs.com/package/electron-prebuilt)

but I failed in all ways.

Could anyone help.

**Comment by evancohen** [comment]
> Please include the following file with any support request

Can you add the log file to this bug, it will help to diagnose the issue, it does not appear to be a problem with the smart-mirror. You may have success with this stackoverflow post: http://stackoverflow.com/questions/23885449/unable-to-resolve-unable-to-get-local-issuer-certificate-using-git-on-windows

**Comment by arifcit520** [comment]
[npm-debug.zip](https://github.com/evancohen/smart-mirror/files/329335/npm-debug.zip)

Find the error log

**Comment by evancohen** [comment]
It seems like you aren't running `npm install` from the smart-mirror directory (and are trying to install electron-prebuilt globally, which is not in the documentation)
