### ISSUE TITLE
annyang.simulate syntax error in console

### ISSUE THREAD

**Issue by geman220** [evancohen/smart-mirror#303]
When issuing a command like:

```annyang.simulate("show me a map of Seattle Washington");``` in the dev console I get the following error:

```Uncaught Syntax error: Invalid or unexpected token```

**Comment by evancohen** [comment]
On the latest master with the default config I am unable to reproduce this.

![image](https://cloud.githubusercontent.com/assets/1198365/16324511/f5805c2a-3969-11e6-9b92-db56ae2bcb84.png)

Have you made any changes to the codebase that may cause this issue?

**Comment by geman220** [comment]
No I haven't in fact I just did the following to be sure
```
git clean -xdf -e config.js
npm install
```

**Comment by evancohen** [comment]
This puzzles me... @kurtdb are you able to get this to work?

**Comment by evancohen** [comment]
Nevermind! Got this sorted out in chat. Turns out the encoding of the closing quotation mark was weird: http://i.imgur.com/8VpszUf.png
