### ISSUE TITLE
Can you guide to me how to solve this?

### ISSUE THREAD

**Issue by bravojun7** [evancohen/smart-mirror#305]
Hi, I use rpi2 and installed smart mirror by your guideline. but it does not pop up .
Can you see this?

=========
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start', 'dev' ]
npm info using npm@2.14.12
npm info using node@v4.3.1
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info prestart smart-mirror@0.0.2
npm info start smart-mirror@0.0.2

    smart-mirror@0.0.2 start /home/pi/smart-mirror
    electron main.js "dev"

npm verb unsafe-perm in lifecycle true
npm info poststart smart-mirror@0.0.2
npm verb exit [ 0, true ]
npm info ok

**Comment by evancohen** [comment]
```
cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' | sed 's/^1000//'
```
Running this will It will give you the revision number for the Pi. which you can use to look up the hardware version here: http://elinux.org/RPi_HardwareHistory

Odds are you actually using the Pi B (first generation)
