### ISSUE TITLE
Audio/Video Mute on KWS

### ISSUE THREAD

**Issue by HelloExactly** [evancohen/smart-mirror#306]
For example, If I say "Smart Mirror, show me Game Of Thrones Season 6 Trailer"  the trailer will play fine, it seems to have a bit of trouble distinguishing your voice from the video audio, but it works.  Problem being, once the keyword is activated, the mic picks up the words from the video, rendering your command useless, and you simply have to wait for the video to end before issuing another command.

Is there a way to mute playback once the KWS is active?  That would be ideal.

**Comment by evancohen** [comment]
I really like this idea 👍. Best way to acheve it would probably be to use `amixer sset PCM 45%-` which decreases the existing volume by 45% (kinda just made this number up, maybe it should be customizable). Then the volume could be increased again with `amixer sset PCM 45%+`.

We could probably be a little smarter about this, you can get the currently set volume with the following and then apply a transformation...
```
amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]%'
```

Late night ramblings... There's probably a better way to do this...

**Comment by HelloExactly** [comment]
To circumvent this in the interim, I've simply routed physical volume control outside the Mirror's frame and drop it to zero to issue the "stop video" command. Not a permanent fix although I do like instant access to volume controls.

**Comment by taran27** [comment]
and @HelloExactly @evancohen  there a same issue if we run the certain video after saying going "go home" still video plays or sound but it doesnt quite continuos in background.

**Comment by evancohen** [comment]
@taran27 can you file a separate issue for the sound continuing to play after you go home? This is a separate suggestion.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+14

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
