### ISSUE TITLE
Spoitify Integration

### ISSUE THREAD

**Issue by HelloExactly** [evancohen/smart-mirror#308]
I see Spotify as API's and documentation available.  Would be great to get that in the mix.

**Comment by evancohen** [comment]
Last I checked the Spotify API does not allow for embedded playback. We discussed this a while back in #57.

Maybe this is something that you'd like to look into and send a PR for?

**Comment by kurtdb** [comment]
I'm thinking of integrating this through last.fm's scrobbling support. That way we should use only 1 api and have support for itunes, spotify, etc.

Only downside is that it will only show you the song you're playing through another client.

**Comment by kurtdb** [comment]
@HelloExactly is the current scrobbling support enough for you?

A few people have also been having problems with getting audio from the mirror, so it might be a better solution to look into streaming spotify through a supported app/device.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+13

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
