### ISSUE TITLE
Better handle multi-day and all-day events

### ISSUE THREAD

**Issue by joelhawksley** [evancohen/smart-mirror#317]
@evancohen currently we don't handle multi-day and all-day events very well, displaying the first day of the event in the former case, and displaying the (meaningless) start time for the latter. 

Any thoughts on how we could better handle these cases?

**Comment by evancohen** [comment]
For all-day events we should be displaying a duration rounded to the nearest day in both cases ("all day", "two days", etc) and for multi day events we should also specify an end date + time (if applicable).

The best place for this is probably the second line of the event details (under the name).

**Comment by joelhawksley** [comment]
I like that. I'll chew on this and see if I can come up with something.

**Comment by evancohen** [comment]
The tricky(ish) part will be what to display when in the middle of a multi-day event. Maybe just having something under TODAY and says "three more days" or something like that?
