### ISSUE TITLE
electron not found/install issues

### ISSUE THREAD

**Issue by markparise** [evancohen/smart-mirror#32]
Hey evan, So I got npm installed on my pi, but when I ran the "npm start" I get a whole slew of errors the first of which reads "sh: 1: electron: not found" 

The rest of the error prompt is as follows: 
npm ERR! smart-mirror@0.0.1 start: 'electron main,js'
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.1 start script.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Error: EACCES, open ' npm-debug.log'
npm ERR! { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES' : 'npm-debug.log; }

npm ERR! System Linux 4.1.7-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /git/smart-mirror
npm ERR! node -v v0.10.29
npm ERR! cod ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm ERR! npm -v 1.4.21
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'

I know it is a bit overkill to put the whole error prompt but i don't see why it would hurt. Anything helps. Thanks in advance

**Comment by kurtdb** [comment]
Did you first run the npm install command? If so, did it return any errors?

**Comment by evancohen** [comment]
@kurtdb is right, you have to run npm install before you can run npm start. If for some reason that doesn't work you can run `npm install electron-prebuilt` which will install the dependency manually.

**Comment by markparise** [comment]
maybe I am just running npm install from the wrong location. I did a rmdir
and created a directory called git in which I cloned evans repository. Then
from smart-mirror I ran sudo npm install. But after that installed I get my
errors of no electron found.

Am I running npm install from the wrong place? Would using sudo npm install
cause these issues?

*Mark A. Parise*
College of Engineering - Computer| The University of Iowa
President | Sigma Nu Fraternity, Inc.
Risk Manager | Theta Tau Professional Engineering Fraternity

(Mobile:(224) 388-1299

***Email (School): Mark-Parise@uiowa.edu

***Email (Personal): Mpari13@gmail.com

**Comment by kurtdb** [comment]
Normally if you have installed nodejs and npm correctly, it shouldn't matter.

Have you tried Evan's second suggestion? If that fails, could you post the message you get when running ```npm install``` and ```npm install electron-prebuilt```?

**Comment by markparise** [comment]
when I run from "pi@watsonpi ~/git/smart-mirror $" the npm install
everything works fine now its when I run npm start that in lies my issue.
After running npm start I get the following:

> electron main.js

sh: 1: electron: not found

npm ERR! smart-mirror@0.0.1 start: `electron main.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.1 start script.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.7-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/git/smart-mirror
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/git/smart-mirror/npm-debug.log
npm ERR! not ok code 0



Now when I run npm install electron-prebuilt I get the following:

pi@watsonpi ~/git/smart-mirror $ npm install electron-prebuilt
npm ERR! Error: EACCES, mkdir '/tmp/npm-5506-Dk82G3TQ'
npm ERR!  { [Error: EACCES, mkdir '/tmp/npm-5506-Dk82G3TQ']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/tmp/npm-5506-Dk82G3TQ',
npm ERR!   parent: 'smart-mirror' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.1.7-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
"electron-prebuilt"
npm ERR! cwd /home/pi/git/smart-mirror
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-5506-Dk82G3TQ
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/tmp/npm-5506-Dk82G3TQ'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/git/smart-mirror/npm-debug.log
npm ERR! not ok code 0



I hope this help diagnosis the issue. For further help getting to a
solution when I run "npm version" the results are as follows:

pi@watsonpi ~/git/smart-mirror $ npm version
{ http_parseer: '1.0',
  node: '0.10.29' ,
  v8: '3.14.5.8' .
  ares: '1.10.0' ,
  uv: '0.10.27' ,
  zlib: '1.2.8' ,
  modules: '11',
  openssl: '1.0.1k' ,
  npm: '1.4.21' ,
    'smart-mirror' : '0.0.1' }

Again I hope this helps figure things out on your end because I have been
hitting my head against a wall on this for a week now.

**Comment by markparise** [comment]
Let me quick follow up. I guess I had accidentally deleted my tmp directory
somehow but I fixed that. Now when I run "npm install electron-prebuilt"
this is what I see:

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! electron-prebuilt@0.36.3 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.3 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.7-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
"electron-prebuilt"
npm ERR! cwd /home/pi/git/smart-mirror
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/git/smart-mirror/npm-debug.log
npm ERR! not ok code 0


Sorry for the confusion..

*Mark A. Parise*
College of Engineering - Computer| The University of Iowa
President | Sigma Nu Fraternity, Inc.
Risk Manager | Theta Tau Professional Engineering Fraternity

(Mobile:(224) 388-1299

***Email (School): Mark-Parise@uiowa.edu

***Email (Personal): Mpari13@gmail.com

**Comment by evancohen** [comment]
Looks like you are running a super old version of Node. First, completely remove the version of Node that you currently have installed on your Pi. Then assuming you are using the Raspberry Pi 2 Model B run:
```
wget https://nodejs.org/dist/v4.0.0/node-v4.0.0-linux-armv7l.tar.gz 
tar -xvf node-v4.0.0-linux-armv7l.tar.gz 
cd node-v4.0.0-linux-armv7l
```
This will download the correct Node binaries for the Pi2. Then all you have to do is copy them to /usr/local

`sudo cp -R * /usr/local/`

Once it has been copied run `node -v` to check the version (You should have v4.0.0)

**Comment by markparise** [comment]
Oh my gosh its working and I am so happy I could reach though the computer
and kiss you! Thank you so much he is going to love it! Now I just have to
get it to display upright but Im sure I can figure that one out. Thank you
so much. Seriously!!!

*Mark A. Parise*
College of Engineering - Computer| The University of Iowa
President | Sigma Nu Fraternity, Inc.
Risk Manager | Theta Tau Professional Engineering Fraternity

(Mobile:(224) 388-1299

***Email (School): Mark-Parise@uiowa.edu

***Email (Personal): Mpari13@gmail.com

**Comment by evancohen** [comment]
You can do this by updating your BIOS setting, which is in the /boot partition on your pi. Inside there you'll find a file called config.txt with a bunch of settings. To rotate your monitor just add this line to the file:

`display_rotate=1`

Restart and you should be good to go :)

**Comment by renhuihhh** [comment]
I got the same problem , $HOME/Programs/node-linux-x64/bin has no electron executable file, and I remembered the previous version didn't.

**Comment by renhuihhh** [comment]
[https://www.npmjs.com/package/electron-prebuilt](url) look here

**Comment by evancohen** [comment]
@renhuihhh I'm a bit confused about your issue. Can you please create a new issue with more detail?

**Comment by fledderman** [comment]
I was getting errors similar to these, and I was able to resolve them by running:

`xcode-select --install`

Hope that works for you too.  Happy coding.

**Comment by kosiara** [comment]
```
cd tmp
wget https://nodejs.org/dist/v8.2.1/node-v8.2.1-linux-armv6l.tar.xz
tar xfv node-v8.2.1-linux-armv6l.tar.xz
sudo npm install -g electron --unsafe-perm=true --allow-root
```

**Comment by wirdfire** [comment]
I need help please i got below errors 


root@kali:/opt/AhMyth-Android-RAT/AhMyth-Server# npm start

> @ start /opt/AhMyth-Android-RAT/AhMyth-Server
> electron ./app

/opt/AhMyth-Android-RAT/AhMyth-Server/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `electron ./app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
root@kali:/opt/AhMyth-Android-RAT/AhMyth-Server#

**Comment by wirdfire** [comment]
> 
> 
> Normally if you have installed nodejs and npm correctly, it shouldn't matter.
> 
> Have you tried Evan's second suggestion? If that fails, could you post the message you get when running `npm install` and `npm install electron-prebuilt`?

Please help 

root@kali:/opt/AhMyth-Android-RAT/AhMyth-Server# npm start

> @ start /opt/AhMyth-Android-RAT/AhMyth-Server
> electron ./app

/opt/AhMyth-Android-RAT/AhMyth-Server/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `electron ./app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
root@kali:/opt/AhMyth-Android-RAT/AhMyth-Server#
