### ISSUE TITLE
#313 causes a horrible crash when interval is not defined

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#321]
When `config.forecast.refreshInterval` is not defined in the config there is a horrible crash due to an infinite loop of mirror data being refreshed.

Note that this property value was changed since that PR in #320.

**Comment by joelhawksley** [comment]
@evancohen I'll take this.

**Comment by evancohen** [comment]
@joelhawksley no worries, I've got a fix for it. The problem exists for other services too.

**Comment by evancohen** [comment]
Fixed in https://github.com/evancohen/smart-mirror/commit/4a0e61d85e725c5fcb7cde88d4c1c70299ae3353
