### ISSUE TITLE
Motion Detection and Auto-Sleep / Auto-Wake functionality merger

### ISSUE THREAD

**Issue by justbill2020** [evancohen/smart-mirror#326]
Merging Motion detection and Auto-Sleep / Auto-Wake Functionality. @evancohen I'll start working on this today. should have something for it later on today or tomorrow.
- [x] adding awesome #311 & #128 
- [x] making awesome better

**Comment by justbill2020** [comment]
Currently looking into implementing johnny-five.io for motion detection...

**Comment by glcohen** [comment]
Have you made any progress? Not sure what camera you are using, but I've come across this to work with my PS Eye: http://www.lavrsen.dk/foswiki/bin/view/Motion/WebHome re:https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=7397

**Comment by justbill2020** [comment]
@glcohen I have not further pursued this at this time as i've spent a lot of time troubleshooting on gitter getting the mirror up and running and focusing on the documentation. However, the motion detection we were looking at implementing was using a PIR rather than the camera... as a camera in a bathroom is kinda creepy in my humble opinion... My suspicion would be a bathroom is the likely place people would be putting it.

**Comment by glcohen** [comment]
Fair point; however I wouldn't rule the option out. It's likely possible to distort the image in such a way that the camera can pick up motion but see nothing valuable. You can also set the config to save no images. 

It's a simpler alternative for those who have a single unit camera/mic like the PS Eye. I'll do some thorough experimenting and report back. 

Of course people could always choose to be creepy, we can't stop that!

**Comment by justbill2020** [comment]
to each their own I guess... adding that functionality isn't a bad thing... if you want to fork the project and work on that to see what you can come up with that would be cool....

**Comment by sdetweil** [comment]
it should be configurable, and device extendable... you want to use PIR, then do this, you want to use camera, then do that (new cam type, extend this). In my case the mirror will be out in a hallway, and I am using webcam for voice, so have cam for motion detection.

**Comment by GobleSt** [comment]
I agree with @sdetweil .  Mine is next to the front door.  I think we should have both options for what different people want to do.  The webcam option can continue in issue #286 I suppose.

**Comment by justbill2020** [comment]
the issue with using the webcam is limited resources on the PI... as stated in #286. since most are using a Rasp Pi adding webcam support for motion detection might have to wait until they release the raspberry pi 8... which should have the performance needed for this whenever they get around to that version of coarse 😝 lol

**Comment by justbill2020** [comment]
removed suggestion status, moved this into feathub and added the in progress and help wanted labels...

**Comment by justbill2020** [comment]
@evancohen i started working on this again using johnny-five... the main issue is that it requires root permissions to use the raspi-io node module and access the GPIO pins on the pi... i don't like that... also it seems like the IPC renderer doesn't actually trigger the commands as it should... all of this is frustrating as hell... however the `sudo npm run motion` script I added to the `package.json` works perfect... if you want to take a look here's the branch link... justbill2020/smartmirror/tree/johnny-five

**Comment by justbill2020** [comment]
holy crap nevermind... i figured it out!!!!!

**Comment by justbill2020** [comment]
completed johnny-five functionality in PR #464 tested this extensively and should be ready to go...

**Comment by GobleSt** [comment]
did a git pull today and see that the auto time out works great!.... the wake up not so much.  How do I disable it until I am ready to do a complete rebuild?

**Comment by justbill2020** [comment]
blank out the wake_cmd and sleep_cmd...

**Comment by GobleSt** [comment]
...in the config.js .  Thanks!
