### ISSUE TITLE
[DEV] Flickering Greetings

### ISSUE THREAD

**Issue by 7h30n3** [evancohen/smart-mirror#327]
I'm on the current dev-branch and I have a (funny) issue using the greetings based on the time of the day. If an array for a certain time has more than one string, these strings continuously change. It looks like flickering.

Can anybody else confirm that?

**Comment by evancohen** [comment]
I think @kurtdb had a similar problem. Just looked at it, this is totally my fault 4a0e61d.
I'll try for a fix tonight.

**Comment by evancohen** [comment]
So I don't think I was able to fix it (I wasn't able to reproduce the issue on my desktop), but I did take another look at that code and fixed a bug that would case the greeting message to never refresh...

@7h30n3 Could you pull this change and see if it helps any? If not, I'll have some time that I can debug on the pi this weekend.

**Comment by kurtdb** [comment]
I'm able to reproduce it on my laptop, so I'll take a swing at it tonight.

**Comment by 7h30n3** [comment]
@evancohen Thank you, the problem is fixed.
