### ISSUE TITLE
Mirror won't start correct

### ISSUE THREAD

**Issue by Haffwa** [evancohen/smart-mirror#337]
Hi!
I just reinstalled the mirror but somehow it doesn't start correctly anymore.
On restart, everything looks like normal but the mirror only shows me the code of the browser with no content.
![img_5752](https://cloud.githubusercontent.com/assets/17971355/16617576/b7594e00-4384-11e6-85ed-164447b8be0d.png)
What did I do wrong?
Help is highly appreciated, Thanks!

**Comment by kurtdb** [comment]
Looks like angularjs is not loaded correctly. Did you first run ```npm install```?

**Comment by Haffwa** [comment]
Yes, ran it in the smart-mirror folder and it finished without an error. Should i reinstall it?

**Comment by kurtdb** [comment]
What does the console say if you start the mirror by using ```npm start dev```?

**Comment by Haffwa** [comment]
Looks like this:
![img_5753](https://cloud.githubusercontent.com/assets/17971355/16618125/f78e8708-4387-11e6-9720-fdc741a1dc48.JPG)

Your guess with angular was right, what can i do to solve this?

**Comment by Haffwa** [comment]
I got a warning, that npm can't be run in my working directory...Don't know why

**Comment by kurtdb** [comment]
In which directory are you running npm?

**Comment by Haffwa** [comment]
/home/pi/smart-mirror

**Comment by Haffwa** [comment]
This is what i get, after using npm install in home/pi/smart-mirror:

pi@raspberrypi:~/smart-mirror $ npm install

> smart-mirror@0.0.2 install /home/pi/smart-mirror
> bower install

bower cached        https://github.com/angular/bower-angular-animate.git#1.5.0
bower validate      1.5.0 against https://github.com/angular/bower-angular-animate.git#1.5.0
bower cached        https://github.com/moment/moment.git#2.10.6
bower validate      2.10.6 against https://github.com/moment/moment.git#2.10.6
bower cached        https://github.com/PascalPrecht/bower-angular-translate.git#2.11.0
bower validate      2.11.0 against https://github.com/PascalPrecht/bower-angular-translate.git#2.11.0
bower cached        https://github.com/angular/bower-angular.git#1.5.7
bower validate      1.5.7 against https://github.com/angular/bower-angular.git#^1.5.0
bower cached        https://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.11.0
bower validate      2.11.0 against https://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.11.0
bower cached        https://github.com/jkbr/rrule.git#2.1.0
bower validate      2.1.0 against https://github.com/jkbr/rrule.git#^2.1.0
bower cached        https://github.com/lgalfaso/angular-dynamic-locale.git#0.1.32
bower validate      0.1.32 against https://github.com/lgalfaso/angular-dynamic-locale.git#0.1.*
bower cached        https://github.com/angular/bower-angular-i18n.git#1.5.0
bower validate      1.5.0 against https://github.com/angular/bower-angular-i18n.git#1.5.0
bower cached        https://github.com/angular/bower-angular.git#1.5.7
bower validate      1.5.7 against https://github.com/angular/bower-angular.git#>=1.2.26 <1.6
bower cached        https://github.com/angular/bower-angular.git#1.5.0
bower validate      1.5.0 against https://github.com/angular/bower-angular.git#1.5.0
bower EACCES        EACCES: permission denied, mkdir '/home/pi/smart-mirror/bower_components'

Stack trace:
Error: EACCES: permission denied, mkdir '/home/pi/smart-mirror/bower_components'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/home/pi/smart-mirror/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/home/pi/smart-mirror/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/home/pi/smart-mirror/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/pi/smart-mirror/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/home/pi/smart-mirror/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /home/pi/smart-mirror/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/home/pi/smart-mirror/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/pi/smart-mirror/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 4.4.3
OS: Linux 4.1.19-v7+ arm

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.2 install: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.2 install script 'bower install'.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path npm-debug.log.3355020527
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.3355020527'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.3355020527']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.3355020527' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
pi@raspberrypi:~/smart-mirror $

**Comment by kurtdb** [comment]
Try running it using sudo, so sudo npm install.

**Comment by Haffwa** [comment]
When i do that, I get the warning, that it can't be done in my working directory.

**Comment by Haffwa** [comment]
"npm WARN cannot run in wd smart-mirror@0.0.2 bower install (wd=/home/pi/smart-mirror)"

**Comment by kurtdb** [comment]
First run sudo npm -g bower. Then try again.

**Comment by Haffwa** [comment]
That only gives me a list of how to use npm (possible commands), but beside that, nothing changes

**Comment by kurtdb** [comment]
Forgot a word: sudo npm install -g bower.

**Comment by Haffwa** [comment]
Obviously i messed something up during the installation...
I just had to change ownership (sudo chown pi:pi /home/pi/smart-mirror) and after that, I could use "npm install" in /home/pi/smart-mirror just as intended...The mirror is working!

Thanks kurtdb for your time and advices!!!

**Comment by gatherKnowledge** [comment]
thanks!

I had a same problem.
