### ISSUE TITLE
Unable to install electron-prebuilt

### ISSUE THREAD

**Issue by ojrivera381** [evancohen/smart-mirror#34]
I have followed the tutorial several times. It fails at the npm installs step with or without sudo.

Running RPI 2 B Jessie. 

it fails at the electron-prebuilt install

**Comment by ojrivera381** [comment]
this can be closed i followed the directions provided for a smilier issue posted. Removing the version of node i was using (old) and followed Evans direction in updating to the latest version all worked after that. 

How can i get this to auto start on reboot?

**Comment by evancohen** [comment]
Instructions for running a node process on boot: https://thomashunter.name/blog/running-a-node-js-process-on-debian-as-an-init-d-service/

If you have any problems with this please create a new issue.

**Comment by ojrivera381** [comment]
Thank you.

__________________
 My LinkedIn Profile
 [image: My LinkedIn Profile]
<https://www.linkedin.com/pub/oscar-rivera/14/b79/3a3>
