### ISSUE TITLE
Extend Fitbit API

### ISSUE THREAD

**Issue by dehlen** [evancohen/smart-mirror#340]
Would love to see an extended Fitbit API. 

For example I use Fitbit extensively for food tracking. Would be super cool to see how many calories you burned vs how many you ate, your calorie goal and all your tracked foods. I know this should be easily possible by extending the already existing Fitbit API controller. I am still waiting for my smart mirror hardware parts :) If they arrive and I'll get some free time to build it I might have a look at implementing this.

Maybe someone is already working on it ? I'd love to hear about it.

Cheers,
David

**Comment by evancohen** [comment]
@Shogan was the original author of Fitbit integration. I don't think anyone is actively working on this, but @R3dRuM recently extended it in #276.

**Comment by dehlen** [comment]
OK great thanks for pointing that out to me. The added extension to the fitbit integration however lacks localization and also is shown when there is no data. I will create a PR to make use of ng-show in order to fix this when there is no data to display, aswell as localize the commands for german language if this is appreciated. Just give me a feedback whether you think this would be a useful addition.

Cheers,
David

**Comment by Shogan** [comment]
Hey guys, sorry for my absence. I have been super busy with house renovations above my usual full time job over the last few months.

I had a request to look at also putting two Fitbit user's info up, but after looking into it, decided it would be too messy - as you would need to auth two difference users and handle tokens etc for both + handle the UI for two users too.

Glad to see others are extending/improving where possible.

@evancohen I still planning on getting rid of the fitbit readme in the root repo and creating a section that covers that info in the official docs - is this something that would be useful, or has it already been removed?

**Comment by dehlen** [comment]
I just had a look at extending the localization. The localization keys can be added into the locales/*.json files and then used in the index.html via `{{'localizationKey' | translate}}`. This way the strings would be available in the current languages. Next someone could add a ng-show attribute to the span elements in order to only show them if the data is available for example : `<span class="fitbit-subtitle" ng-show="fbSleep.sleep[0]">`.

By the way I'd also would love to see units added to the information which is display. For example the output should look like this:

Calories Burned: 2400 kcal.

Next the command for refreshing fitbit currently is added via index.html: 
`<dt ng-show="fitbitEnabled">Show my walking</dt>
 <dd ng-show="fitbitEnabled">Refreshes fitbit data.</dd>`

Imo it would be much cleaner to add this to the localized commands array. Then in the controller.js you could change this command:
`SpeechService.addCommand('show_my_walking', function() {`

`addCommand('show_my_walking', function() {`
to this command in order to make the localized command work.

Not sure if I forgot anything but this should be pretty much it in order to clean up the fitbit implementation and make it localizable.

**Comment by evancohen** [comment]
@Shogan I still haven't integrated into the official docs because of the length (the docs do link to the readme though). Multi-user is something that we'd like to do *eventually*, but I don't think we are quite there yet.

@dehlen making use of localization and correct implementation of `ng-show` sounds excellent.

**Comment by dehlen** [comment]
Just made a PR. Just have a look and tell me if there is something I should improve.

**Comment by dehlen** [comment]
Ok PR is merged now which is why i'll close this for now. If someone wants to make more extensions to the fitbit integration or I'll will take some time in the future to make so modifications a new issue should be opened imo.
