### ISSUE TITLE
Quora Integration

### ISSUE THREAD

**Issue by dehlen** [evancohen/smart-mirror#341]
I'd love to see a Quora integration. I look daily into the top stories which are recommended for me and I think there are some pretty interesting stories on Quora. Would be super cool to see them right on your SmartMirror.

**Comment by evancohen** [comment]
Does Quota have an RSS feed that you could use?

**Comment by dehlen** [comment]
Well actually there is the possibility to integrate a RSS feed. I didn't think about that. Thanks
