### ISSUE TITLE
Make localization consistent

### ISSUE THREAD

**Issue by dehlen** [evancohen/smart-mirror#342]
Hello,

I just had a quick look at the list of commands available to the smart mirror. The descriptions are not consistent. Sometimes the description end with a "." and sometimes not. Also the voice commands should follow a specific pattern in my opinion. Third-party extensions like Soundcloud are not localized (for example Soundcloud commands are not localized for the german language).

I might create a PR if you are interested. However I first wanted to hear your opinion about how the commands should look like and whether the description should end with a full-stop (.) or not.

**Comment by evancohen** [comment]
This sounds excellent. If you are creating the PR, I'd follow whatever guidance you come up with in regards to full-stops (although my preference would be to have them for all descriptions).

Regarding a specific pattern for voice commands: **yes**, we should absolutely be more consistent here. Each integration has been slowly added over time and feature authors come up with the command they think best - this has lead to some inconsistency. I haven't given this any significant thought recently so I don't have any guidance for you. I'll noodle on it for a few days and see what I come up with. In the meantime, I'm open to suggestions.

**Comment by dehlen** [comment]
Ok, so I will create a PR today for making the descriptions consistent and wait for your further input concerning the voice commands.

**Comment by dehlen** [comment]
I made a PR with some first tries to make the localization more consistent. Feel free to leave feedback.

**Comment by dehlen** [comment]
PR was merged. Closing this issue now. Further efforts for making the voice commands more consistent should be discussed in a separate issue imo.
