### ISSUE TITLE
MagicMirror2 Modules

### ISSUE THREAD

**Issue by shgmongo** [evancohen/smart-mirror#349]
Hello,
is it possible to install MM2 Modules or 3rd Party software to the Smart Mirror?

See the Modules at
[https://github.com/MichMich/MagicMirror/wiki/MagicMirror%C2%B2-Modules](url)

I´m a Newbie and need the information.

Kind regards,

Volker

**Comment by evancohen** [comment]
@shgmongo you can't use modules from the MagicMirror, although porting modules over to this codebase is quite easy.

Integrating 3rd party services with the smart-mirror is also super easy, you can refer to the developer documentation for more information.
