### ISSUE TITLE
FitBit data not populating... 

### ISSUE THREAD

**Issue by distortd6** [evancohen/smart-mirror#350]
![image](https://cloud.githubusercontent.com/assets/8869368/16951876/78f636c0-4d8c-11e6-837e-0c524ba88a5f.png)
Attached is the error I get when Fitbit data doesn't populate on initial "npm start dev".  After inputting CLIENTID and CLIENTSECRET, I start the mirror, alt+tab to browser, head to http://localhost:4000/fitbit and click on Allow which brings me to this error.   Any ideas guys?  I've been stumped for the past hour!

**Comment by evancohen** [comment]
@distortd6 it would help to know if you are on `master` or `dev`. I don't have a fitbit, so I've never actually done much testing of this code path. You might be able to get an auth token from [grant](https://grant-oauth.herokuapp.com/#/fitbit) and then create the token JSON file that is typically generated for this.

**Comment by distortd6** [comment]
I am on master, but will try dev as suggested in gitter.  This error is somewhat expected and does indeed create the fb-token.json in smart-mirror dir.  The real issue is that no fitbit data populates.

**Comment by justbill2020** [comment]
Hello all, I don't have a Fitbit so cannot independently test... is this issue resolved? @distortd6 I'm trying to close out any pending issues which have been resolved or at least bump them to get a status...

**Comment by justbill2020** [comment]
@jonathanng92 you reported this issue as well in #387 has this been resolved for you?

**Comment by jonathanng92** [comment]
No, it hasn't worked out. But I've been busy with other things so I haven't been able to dedicate time to solving it.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Nov 8, 2016 at 8:59 AM -0800, "Bill Martin" <notifications@github.com<mailto:notifications@github.com>> wrote:


@jonathanng92<https://github.com/jonathanng92> you reported this issue as well in #387<https://github.com/evancohen/smart-mirror/issues/387> has this been resolved for you?

-

**Comment by justbill2020** [comment]
i just got a fitbit to use for testing... not sure how long before i will have time to look at this though...

**Comment by flyerguy** [comment]
Some additional info here. I'm getting this message when running npm start dev after registering my fitbit app on the website.
`angular.js:14195 TypeError: Fitbit is not a constructor at Object.FitbitService (fitbit.js:53) at Object.invoke (angular.js:4767) at Object.enforcedReturnValue [as $get] (angular.js:4605) at Object.invoke (angular.js:4767) at angular.js:4565 at getService (angular.js:4712) at injectionArgs (angular.js:4737) at Object.invoke (angular.js:4759) at $controllerInit (angular.js:10588) at nodeLinkFn (angular.js:9465)(anonymous function) @ angular.js:14195
`

**Comment by evancohen** [comment]
Yeah... this is a long standing bug that I haven't been able to fix because I don't have a Fitbit (thus the help wanted tag).

**Comment by flyerguy** [comment]
Evan, 
Wish I could help out. I have a fitbit but not the programming knowledge. Love the rest of Smart-Mirror so far.

**Comment by evancohen** [comment]
Maybe after the changes Bill and I are making over the holidays he can take a look at it

**Comment by kurtdb** [comment]
Does @justbill2020 have a fitbit? Otherwise I can change my login info and you can use that data. :)

**Comment by justbill2020** [comment]
i'll take a look at it... i might need creds... my mother-in-law gave me one to use for this purpose... I've done 0 with it thus far...

**Comment by DannyLuu** [comment]
With the help of Evan, I was able to get the Fitbit integration up and running.

I am still working on the new UI. The optimization of the calls has been done.

**Comment by evancohen** [comment]
@DannyLuu how we doing on this?

**Comment by DannyLuu** [comment]
@evancohen I have most of it working. I'm just trying to add some extra information. If you are free this weekend could we sync up sometime and work on accessing the json object that is returned?

Thanks.

**Comment by DannyLuu** [comment]
@evancohen I am closing this issue as it has been resolved.

**Comment by kiltedken** [comment]
So, are there any instructions on how to set up the API and such to use it on the mirror?

**Comment by DannyLuu** [comment]
Hey Kiltedken,

I haven't had a chance to write the documentation on it but it closely follows the ones here:
https://github.com/evancohen/smart-mirror/blob/e38eb5670ababc0a6950ffe8fa4441c203324f36/Fitbit-README.md

**Comment by kiltedken** [comment]
Thanks! I will check it out.

Kenneth
