### ISSUE TITLE
White Background and Black Text, No Dynamic Information

### ISSUE THREAD

**Issue by esazsX** [evancohen/smart-mirror#351]
I ran `npm start` and I see the index.html but it shows up as plain text
for example, where the date should be, it says "{{date.format('dddd')}}" and shows something similar for forecast, greeting, and so on

**Comment by evancohen** [comment]
You likeley haven't run `npm install`, which will install all nessesary dependencies. Please refer to the documentation: http://docs.smart-mirror.io
