### ISSUE TITLE
bower installer problem.... 

### ISSUE THREAD

**Issue by vwilk7** [evancohen/smart-mirror#353]
during installing the code(about npm install ) with raspberry pi 3, i found the error in termminal
so i tried to solve the problem but i didn't
also i checked the node version.  the version is 4.0.0.
so i tried to upgrade the virsion but pi told me "permission denied"
after that, i tried to write "sudo apt-get remove node" 
the code can be activating, but not remove the node 
how can i remove the node???   and if node version isn't the installed problem, what 's the problem??

thank you for reading and can you help me??  

there is the error 

 Request to https://bower.herokuapp.com/packages/jquery failed: getaddrinfo ENOTFOUND bower.herokuapp.com bower.herokuapp.com:443
 
npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.1 install: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.1 install script 'bower install'.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:

and npm debug ,too

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose readDependencies loading dependencies from /home/pi/test-smart-mirror/smart-mirror/package.json
5 verbose install where, deps [ '/home/pi/test-smart-mirror/smart-mirror',
5 verbose install   [ 'express',
5 verbose install     'fitbit-oauth2',
5 verbose install     'fs',
5 verbose install     'electron-json-storage',
5 verbose install     'wiredep-cli',
5 verbose install     'bower',
5 verbose install     'install',
5 verbose install     'angular-i18n',
5 verbose install     'electron-prebuilt',
5 verbose install     'npm' ] ]
6 verbose install where, peers [ '/home/pi/test-smart-mirror/smart-mirror', [] ]
7 verbose installManyTop reading for lifecycle /home/pi/test-smart-mirror/smart-mirror/package.json
8 info preinstall smart-mirror@0.0.2
9 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/angular-i18n/package.json
10 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/bower/package.json
11 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/electron-json-storage/package.json
12 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/electron-prebuilt/package.json
13 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/express/package.json
14 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/fitbit-oauth2/package.json
15 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/fs/package.json
16 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/install/package.json
17 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/npm/package.json
18 verbose installManyTop reading scoped package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/wiredep-cli/package.json
19 info package.json fs@0.0.2 fs is also the name of a node core module.
20 info package.json fs@0.0.2 No description
21 info package.json fs@0.0.2 No repository field.
22 verbose readDependencies loading dependencies from /home/pi/test-smart-mirror/smart-mirror/package.json
23 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/angular-i18n/package.json
24 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/bower/package.json
25 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/electron-json-storage/package.json
26 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/electron-prebuilt/package.json
27 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/express/package.json
28 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/fitbit-oauth2/package.json
29 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/fs/package.json
30 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/install/package.json
31 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/npm/package.json
32 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/wiredep-cli/package.json
33 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/.bin/bower/package.json
34 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/.bin/electron/package.json
35 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/.bin/npm/package.json
36 verbose targetResolver reading package data from /home/pi/test-smart-mirror/smart-mirror/node_modules/.bin/wiredep/package.json
37 verbose already installed skipping electron-prebuilt@^1.0.0 /home/pi/test-smart-mirror/smart-mirror
38 verbose already installed skipping npm@^3.8.8 /home/pi/test-smart-mirror/smart-mirror
39 verbose already installed skipping express@^4.13.4 /home/pi/test-smart-mirror/smart-mirror
40 verbose already installed skipping fitbit-oauth2@0.0.1 /home/pi/test-smart-mirror/smart-mirror
41 verbose already installed skipping fs@0.0.2 /home/pi/test-smart-mirror/smart-mirror
42 verbose already installed skipping electron-json-storage@2.0.0 /home/pi/test-smart-mirror/smart-mirror
43 verbose already installed skipping wiredep-cli@^0.1.0 /home/pi/test-smart-mirror/smart-mirror
44 verbose already installed skipping bower@^1.7.9 /home/pi/test-smart-mirror/smart-mirror
45 verbose already installed skipping install@^0.8.1 /home/pi/test-smart-mirror/smart-mirror
46 verbose already installed skipping angular-i18n@^1.5.5 /home/pi/test-smart-mirror/smart-mirror
47 silly install resolved []
48 info build /home/pi/test-smart-mirror/smart-mirror
49 info linkStuff smart-mirror@0.0.2
50 silly linkStuff smart-mirror@0.0.2 has /home/pi/test-smart-mirror as its parent node_modules
51 verbose linkBins smart-mirror@0.0.2
52 verbose linkMans smart-mirror@0.0.2
53 verbose rebuildBundles smart-mirror@0.0.2
54 verbose rebuildBundles [ '.bin',
54 verbose rebuildBundles   'angular-i18n',
54 verbose rebuildBundles   'bower',
54 verbose rebuildBundles   'electron-json-storage',
54 verbose rebuildBundles   'electron-prebuilt',
54 verbose rebuildBundles   'express',
54 verbose rebuildBundles   'fitbit-oauth2',
54 verbose rebuildBundles   'fs',
54 verbose rebuildBundles   'install',
54 verbose rebuildBundles   'npm',
54 verbose rebuildBundles   'wiredep-cli' ]
55 info install smart-mirror@0.0.2
56 verbose unsafe-perm in lifecycle true
57 info smart-mirror@0.0.2 Failed to exec install script
58 verbose stack Error: smart-mirror@0.0.2 install: `bower install`
58 verbose stack Exit status 1
58 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
58 verbose stack     at emitTwo (events.js:87:13)
58 verbose stack     at EventEmitter.emit (events.js:172:7)
58 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
58 verbose stack     at emitTwo (events.js:87:13)
58 verbose stack     at ChildProcess.emit (events.js:172:7)
58 verbose stack     at maybeClose (internal/child_process.js:817:16)
58 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
59 verbose pkgid smart-mirror@0.0.2
60 verbose cwd /home/pi/test-smart-mirror/smart-mirror
61 error Linux 4.4.13-v7+
62 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
63 error node v4.0.0
64 error npm  v2.14.2
65 error code ELIFECYCLE
66 error smart-mirror@0.0.2 install: `bower install`
66 error Exit status 1
67 error Failed at the smart-mirror@0.0.2 install script 'bower install'.
67 error This is most likely a problem with the smart-mirror package,
67 error not with npm itself.
67 error Tell the author that this fails on your system:
67 error     bower install
67 error You can get their info via:
67 error     npm owner ls smart-mirror
67 error There is likely additional logging output above.
68 verbose exit [ 1, true ]

**Comment by evancohen** [comment]
This should no longer be an issue. Closing this out.
