### ISSUE TITLE
Suggestion: More Keywords

### ISSUE THREAD

**Issue by cybertza** [evancohen/smart-mirror#355]
Hi Guys,

I was wondering if its possible to tier the voice recognition, until it becomes offline alike?

Eg:
Listening for: Smart_mirror;
          Then Listening for Play Music off usb
                                        slideshow
                                         pause video
                                         pause music
                                         hide temp
                                         wake up
                                         sleep
                                         or custom?

Maybe the method should be 2 keywords if possible?
                    Keyword one: online searches (smart mirror) 
                    Keyword two: Local trained Library (hey mirror) or whatever.

I understand the offline cant work with loads of things that require online searches, like "show me "...

but it could decrease the online API calls dramatically, and it could basically be at the users discretion as if they wanted to train local words (or even use the local keyword other than "smart_mirror", 

I'm not sure if its something you guys would be Interested, but i guess it could link back to the identification side of things, so an unidentified user will only use online resource, where identified can use their personal trained words?

**Comment by justbill2020** [comment]
@evancohen this seems to be outdated at this point... i think we've moved past this and it would add increased configuration and training of personal models for snowboy...

additionally since we're using Google Cloud Speech API now we're not limited to 50 api calls... 

should i move this to feathub?

**Comment by evancohen** [comment]
I think we've solved this problem. Multiple hotwords is now supported too, so if someone wanted to they could implement this themselves.
