### ISSUE TITLE
Suggestion: Voice Identification (keyword)

### ISSUE THREAD

**Issue by cybertza** [evancohen/smart-mirror#356]
Hi Guys,

Was looking at a few of the ID ideas that there are around from the bluetooth distance and so forth but was wondering if it may be worth doing a voice recognition, that you can train for the mirror, or a voice unlock, once the mirror does recognize you with other bio metrics, i like the idea of having all my personal stuff displayed on the mirror, but i am not crazy about the idea of anyone with access to my room knowing for how long i would be at a meeting or what ever the associated risk may be, with either my task list like (collect wife present) or your home cleaning service knowing you have a 3 hour meeting on at a certain time, ag well, you guys can understand the risk of these things, worse case someone steals the mirror and has access to your work address, meeting schedules, to do list.

Either way, there is so many possibilities if you think about the windows widgets that you used to get, there is a fountain of ideas there https://support.microsoft.com/en-us/help/13787/gadgets-have-been-discontinued, 

http://win7gadgets.com/
http://win7gadgets.com/pc-system/blue-gadgets-set.html

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+10

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
