### ISSUE TITLE
Make "greeting" disappear after "x" seconds

### ISSUE THREAD

**Issue by genbuttnak3cl** [evancohen/smart-mirror#359]
Hi all,
I love this Project and I am currently trying to make this running on my RPi 3.

I would like the "greeting" to fade out after "x" seconds of showing on wake up. Do I just have to change something in the config.js or another file or is it more complicated?

Thank you very much and sorry for my bad english :)

Best regards
Sergej

**Comment by evancohen** [comment]
@genbuttnak3cl you are going to want to edit `js/controller.js` and add a timeout that hides the element

**Comment by genbuttnak3cl** [comment]
@evancohen thank you sir! :) can you tell me the exact line and command for the `controller.js`? I'm a noob... I'm sorry.

**Comment by TwoClipz** [comment]
Have you been able to get this to work?
I'm not much of a coder, but adding something like this might work... I'll try it tonight when I get home.
{
    var x = document.getElementById("greetingTime");
    setTimeout(function(){ x.value=" " }, 6000);
}

**Comment by TwoClipz** [comment]
This seems to be working... it doesn't hide per say 	,it  just changes to to be blank..
I was trying to do a nice fadeOut but couldn't get it working. I'm going to continue to work on it. I'll also try to add the var to the config and get it outta here.

{
var greetingTimeOutMs = 20000; // <-- time in milliseconds
setTimeout(function(){ $scope.greeting = " " }, config.greetingTimeOutMs);
}
