### ISSUE TITLE
Can't get lights to work

### ISSUE THREAD

**Issue by monaiz** [evancohen/smart-mirror#36]
I have 5 lights, they all work on my smart phone, all hooked up to my box and on the same wifi

I have my key right var HUE_BASE = "http://192.168.1.9/api/2f8160674b5f1df27856ce18360f51f0/";

But when I say "lights off" nothing happens..

**Comment by evancohen** [comment]
Have you created a group for your lights? If you don't feel like doing that just change the group number to 0 in hue-service.js: https://github.com/evancohen/smart-mirror/blob/master/js/hue-service.js#L35
(0 is the default group which is reserved for "all lights")
