### ISSUE TITLE
Forecast/Weather is not visible anymore, but was visible in the first hour of using.

### ISSUE THREAD

**Issue by genbuttnak3cl** [evancohen/smart-mirror#360]
Hello :)

yesterday I installed this Project on my RPi 3 and added the API Key from forecast.io to the config.js file. In the first hour or so, the weather was working as expected, but since then I can not see any weather-info on the mirror. I didn't change anything in the weather.js, a reboot doesn't make any changes.

Tried to run in dev mode and there were no errors.

What could be the issue?

sorry, if it's a "noob"-question, but I am not very experienced with this yet ^^

Thank you very much! :)

Sergej

**Comment by genbuttnak3cl** [comment]
Sorry, somehow the Word "forecast" in the config.js was spelled wrong :) but still wondering why it worked at first...

**Comment by justbill2020** [comment]
try ```npm start dev``` look in the console view and see if you get a geolocation error... if so manually enter your geolocation...

**Comment by genbuttnak3cl** [comment]
just started the mirror and again the forecast is not showing up :/ @justbill2020 thanks! Looked in the log and you are right, the geolocation couldn't be determined, so I made it manually, like you said->hardcoded the location in the config->works! :)
but I don't get, why it sometimes can't determine the location and sometimes it works, without manual enter of the geolocation... :/
