### ISSUE TITLE
Problem SpeechRecognition

### ISSUE THREAD

**Issue by SebDuboisMIAGE** [evancohen/smart-mirror#361]
Hi everybody,

I've got a problem in my smart mirror.
I've got an error when i say the keyword (the mirror recognize the keyword but, i've got an error in the console) : 

SpeechRecognitionError {error: "audio-capture", message="", type:"error", target: SpeechRecognition, currentTarget: SpeechRecognition...}

Is there anybody had got the problem ?

Thx

**Comment by evancohen** [comment]
Please refer to the documentation for troubleshooting: http://docs.smart-mirror.io/docs/troubleshooting.html

**Comment by SebDuboisMIAGE** [comment]
Yes, but when i make npm microphone-debug, i've an error : 

pi@raspberrypi:~/smart-mirror $ npm microphone-debug

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/pi/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.15.1 /usr/local/lib/node_modules/npm

**Comment by evancohen** [comment]
The command is `npm run microphone-debug`

**Comment by evancohen** [comment]
Closing this out because the issue has been solved. See #307 for more info.
