### ISSUE TITLE
rocket symbol

### ISSUE THREAD

**Issue by aroonp** [evancohen/smart-mirror#362]
What does it mean rocket symbol

**Comment by evancohen** [comment]
I guess it's just a weird thing I use when something is successful. For instance someone fixes a troubleshooting error. You're likeley talking about the rocket in the commit message from `0.0.3`... It took longer then expected to get that release out so I was happy to finally push things out.

I've always liked the expression "to the moon", and that emoji sort-of does that for me...
:rocket:
