### ISSUE TITLE
Greeting - Position / Visibility

### ISSUE THREAD

**Issue by 7h30n3** [evancohen/smart-mirror#365]
It's a minor cosmetic issue, but I think the postion and visibility of the greeting could be improved.
1. If I tell the mirror to show me a giphy-image the greeting and image are to high. Especially, if you have a long greeting they overlap with the calendar and weather information. So for (small) images the positon of the greeting should be lowered.
2. If I tell the mirror to show me a map I can totally understand to make the map as big as possible, but again the greeting overlaps with the calender and weahter information. In this case we should fade out the greeting.

**Comment by justbill2020** [comment]
@evancohen how hard would it be for the greeting to only show when you're on the "home" screen and to move it back to just above the command line text? similar to what it is on the icesnow template?

**Comment by evancohen** [comment]
@justbill2020 ~1 line of code to only show it on the home screen. A few more lines of CSS and you can put it wherever you want.

**Comment by justbill2020** [comment]
this isn't really a bug... not really a suggestion... its more an aesthetics recommendation... @evancohen since you have it labeled next i'm going to leave this and remove the suggestion label... i'm also leaving this open...

**Comment by evancohen** [comment]
I think this has been sufficiently addressed now. @7h30n3 feel free to re-open if the new updates and these suggestions don't work for you.
