### ISSUE TITLE
Commads without "Text" and "Description"

### ISSUE THREAD

**Issue by 7h30n3** [evancohen/smart-mirror#366]
In the list that appears if you tell the mirror "What can I say", there are two commands with missing translation:

`commands.screen on.text`
`commands.screen off.text`

They don't appear in the locales js. So I think the commands can't even be used.

**Comment by justbill2020** [comment]
@evancohen I've been thinking about the commands going off the screen which is and isn't part of this... we should add a pagination feature for the commands and have a voice command for advancing through the pages (page forward and page back) more of a suggestion than a bug... possibly v1.0

**Comment by Fijvect** [comment]
For those who are waiting for this bug to be resolved, but want a hack-fix in the meantime, then this worked for me:

Under the controller.js file, under the `var addCommand = function(...` function I added the following just inside that function: `if(commandId != 'screen off' && commandId != 'screen on') {`, followed with a closing bracket `}` at the end of the function.
It's not a eloquent fix at-the-source or anything. But at least it will prevent the two strange commands from getting added to the large list of commands

**Comment by justbill2020** [comment]
This was resolved with PR MERGE #474 to Master
