### ISSUE TITLE
Tesla API support

### ISSUE THREAD

**Issue by drewgould** [evancohen/smart-mirror#367]
I'm adding Tesla API support to allow checking some common things about the status of a vehicle. Thinking about showing the vehicle name, charge level/charge status and adding voice commands to toggle on and set the HVAC temperature and summon the vehicle out of the garage. I'd be happy to submit it for review for broader inclusion once it's ready.

**Comment by evancohen** [comment]
This would be super rad! Please do send a PR once you have something :smile:

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+9

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
