### ISSUE TITLE
Forecast Widget cannot automatically locate

### ISSUE THREAD

**Issue by MattTheGamer** [evancohen/smart-mirror#372]
Seems as thought the forecast widget is having trouble locating my location. Manually entering a Lat and Long works though.

**Comment by evancohen** [comment]
I believe this to be an issue with Google's geolocation API (nothing has changed in that code recently). This is a bug!

We may have to try geolocation lookup another way.

**Comment by evancohen** [comment]
Resolved because you can hard-code your geolocation if it's not working #381
