### ISSUE TITLE
Backlight integration

### ISSUE THREAD

**Issue by StevenTLBF** [evancohen/smart-mirror#374]
Looking for some input from the community. Does anyone have any clue as to how the backlight was integrated into the mirror in this article? 

https://medium.com/@maxbraun/my-bathroom-mirror-is-smarter-than-yours-94b21c6671ba#.jjuhp5nj0

**Comment by justbill2020** [comment]
perhaps ask the person that posted the article?

**Comment by evancohen** [comment]
I don't think this is a suggestion, so I'm closing out this issue.
