### ISSUE TITLE
Cloud Speech API google

### ISSUE THREAD

**Issue by EvilBuu** [evancohen/smart-mirror#375]
Hi there, Ive been following the guide of evan and so far everything is working (even my lights). 

I however do have a problem with configuring my speech keys. The steps described on the gifthub are dated and not for google cloud speech. 

Can someone please tell me which options to choose for the API keys? Thanks in advance

**Comment by justbill2020** [comment]
you should use the chromium speech API... there are directions on how to obtain those... they are still as of now available. Cloud speech API is new. and not yet implemented @evancohen has mentioned working on an update that would allow us to select our speech engine however that seems to be a low priority for now... 

in the docs, http://docs.smart-mirror.io/docs/chromium_speech_keys.html there is a link for acquiring keys... we currently use chromium speech keys not google cloud speech API... hope this answers your question... you'll have to join the chromium-dev group to get access to the speech API
when you're creating the key in the API manager you'll select other as the app type

**Comment by EvilBuu** [comment]
Hi thanks for responding It worked out doing a bit more reading. My keys are working i checked it with print command in terminal.
