### ISSUE TITLE
how to install on mac osx

### ISSUE THREAD

**Issue by NilanjPatel** [evancohen/smart-mirror#377]
how can i install smart-mirror in mac osx

**Comment by evancohen** [comment]
The same steps as for the pi in the documentation with a few small exceptions:

- You have to install node for OSX, not ARMv6
- You have to replace the snowboy precompiled binaries in the `speech` folder with the [ones for OSX](https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/osx-x86_64-1.0.4.tar.bz2).
- Run on boot won't work the same way
- You don't need to configure `~/.asoundrc`
- Environmental variables are set differently
