### ISSUE TITLE
Youtube not working

### ISSUE THREAD

**Issue by SenadM** [evancohen/smart-mirror#378]
Giving the error "If playback doesn't begin shortly, try restarting your device"

**Comment by evancohen** [comment]
I've gotten this feedback from a couple of people - it doesn't happen on my Pi so I'll need to do a fresh install to see if I can get it to reproduce.

**Comment by SenadM** [comment]
I can send you my smart-mirror folder and you can take a look on that.

**Comment by glcohen** [comment]
Having this issue as well, getting the spinning wheel of death from the YouTube frame.

**Comment by phelixz** [comment]
Yes, same for me

**Comment by 7h30n3** [comment]
Me, too.

**Comment by evancohen** [comment]
Sounds like a bug, I shall investigate!

**Comment by benjitastic** [comment]
same for me... sorry, don't have much more useful information. here is my .asoundrc file: https://gist.github.com/benjitastic/7fbf0a886f3a68a21103043347ff754f

here's my /boot/config.txt: https://gist.github.com/benjitastic/79c4ee05d97926633f2bb911f4754739

let me know if there are any other files or info that would be helpful.

USB mic input is working

**Comment by cowboysdude** [comment]
Yes just noticed it is also happening to me as well.  Not sure why...   Don't know if this helps any but...I realize this isn't windows but perhaps it's a starting point..

"I have a brand new PC with windows 10 and after the issue happened to me I searched around like everyone else here. Still not entirely sure what causes it but; "Run Chrome as Administrator" fixed it for me. Hopefully this helps for anyone else that comes across this problem."

**Comment by Fabrizio1** [comment]
Hi all,
I had exactly the same problem. 
I checked the code and just replaced "config.youtube.key" with my API key in the "search.js" file, see below.
Now it is working, at least for me. Maybe this helps.
Best, Fab

"//Sharing this key in the hopes that it wont be abused 
                    'key': config.youtube.key"

**Comment by itsmason** [comment]
from what i can tell this is a soundcard issue, i had the same problem but found switching to an external card freed up the problem and videos would run, may possibly be the internal card resource is being hogged by raspbian OS, i'm going to try to disable it for the OS and see if that fixes it.

**Comment by evancohen** [comment]
@itsmason it's very likeley that is the issue, in which case the simple fix is to use Dsnoop. Instructions for this are in #386.

I can test that out over the weekend. I'll update this thread and the docs if that fixes it.

**Comment by justbill2020** [comment]
:boom:

**Comment by itsmason** [comment]
@justbill2020 I've not tried yet sorry, but I'm looking into it over the next week or so. If I get an answer before you (I'm guessing you're having the same issue) I will update.

**Comment by itsmason** [comment]
I've not had a chance to check updates but I was using the most current build last month on both raspbian and smart-mirror code.

**Comment by evancohen** [comment]
I haven't been able to reproduce this problem on the latest build. It could be that you have some straggler environmental variables from an old version of the mirror that are getting in the way. Try clearing those out if you have them.

**Comment by wuppi83** [comment]
I have the same problem on the latest build :0(

**Comment by wuppi83** [comment]
You can fix the problem with

```
Update 3:

Wanted to update the changes I made to the best of my memory.

sudo nano /etc/pulse/default.pa : I changed load-module module-udev-detect to load-module module-udev-detect tsched=0
sudo nano /etc/pulse/daemon.conf : I un-commented and changed the following:
high-priority = yes
nice-level = -11
realtime-scheduling = yes
realtime-priority = 9
exit-idle-time = -1
resample-method = trivial
rlimit-nice = 31
rlimit-rtprio = 9
default-sample-format = s16le
default-sample-rate = 44100
default-sample-channels = 2
default-fragments = 10
default-fragment-size-msec = 7
sudo nano /etc/security/limits.conf I added the following lines to the end:
pi - nice -11
pi - rtprio 9
```

you have to start jackserver and maybe pulseaudio manually:

```
pulseaudio --start
jack_control start
```

**Comment by evancohen** [comment]
Just as a reminder, the mirror doesn't support PulseAudio - I know that some people have added it to their setup for *reasons*, but you really shouldn't need it.

**Comment by justbill2020** [comment]
Unable to reproduce with the most current master branch as of 11/22/2016

### Environment
Device/OS: Raspberry Pi 3 with Raspbian Jessie with Pixel

### Suggestion if you're still having this issue
If you're having this issue and your environment matches the environment I just described in this comment please submit a new issue... please reference this issue in your new issue so we can properly track it.
