### ISSUE TITLE
how to install smart-mirror on ubuntu 16.04

### ISSUE THREAD

**Issue by aanandpant** [evancohen/smart-mirror#379]
hello evan,i've installed all the necessary packages for ubuntu.But,the problem is as soon as i run "npm start" command i get this error "npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.3 start: `electron main.js `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.3 start script 'electron main.js '.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above."

How can i resolve this issue?. Much appreciated

**Comment by evancohen** [comment]
We cleared this up in Gitter, but a summery of the issue for anyone else who has the issue:

- Strange `npm` incompatibility, either use node 4.3.3 or 6.x
- Need to use the right snowboy binaries (the ones included by default are for the raspberry pi)
