### ISSUE TITLE
SoundCloud Request Failing

### ISSUE THREAD

**Issue by glcohen** [evancohen/smart-mirror#384]
In soundcloud.js:23, the query is formatted with "&limit=1". When a query is run, I consistently get the following error in the console
     
    annyang.simulate("soundcloud play kanye");
    undefined
    TypeError: Cannot read property 'permalink_url' of undefined
        at soundcloud.js:26
        at processQueue (angular.js:15552)
        at angular.js:15568
        at Scope.$eval (angular.js:16820)
        at Scope.$digest (angular.js:16636)
        at Scope.$apply (angular.js:16928)
        at done (angular.js:11266)
        at completeRequest (angular.js:11464)
        at XMLHttpRequest.requestLoaded (angular.js:11405) 

This fails for any query. When the query is changed so that the limit is 2 (&limit=2), everything works fine.

**Comment by evancohen** [comment]
I'm not really sure why this would happen, can you include the API response for `&limit=1` and `&limit=2`?

**Comment by glcohen** [comment]
Having the limit set to 1 does work for most requests; however, there is a case where no the response includes nothing with the limit as 1 (i.e. []), but returns a song when the limit is set to 2.

Here's an example...

**Limit = 1**
**Query**: https://api.soundcloud.com/tracks.json?client_id=myclientid&q=dangerzone&limit=1
**Response**:

    []

**Limit = 2**
**Query**: https://api.soundcloud.com/tracks.json?client_id=myclientid&q=dangerzone&limit=2
**Response**:


    [{"download_url":null,"key_signature":"","user_favorite":false,"likes_count":627,"release":"","attachments_uri":"https://api.soundcloud.com/tracks/69023863/attachments","waveform_url":"https://w1.sndcdn.com/rlKDvIuwI3aP_m.png","purchase_url":null,"video_url":null,"streamable":true,"artwork_url":"https://i1.sndcdn.com/artworks-000035011159-sdu4lv-large.jpg","comment_count":64,"commentable":true,"description":"","download_count":100,"downloadable":false,"embeddable_by":"all","favoritings_count":0,"genre":"","isrc":"","label_id":null,"label_name":"","license":"all-rights-reserved","original_content_size":9522262,"original_format":"mp3","playback_count":63801,"purchase_title":null,"release_day":null,"release_month":null,"release_year":null,"reposts_count":123,"state":"finished","tag_list":"","track_type":"","user":{"avatar_url":"https://i1.sndcdn.com/avatars-000020625434-m2s5lz-large.jpg","id":22259271,"kind":"user","permalink_url":"http://soundcloud.com/freeman-dangerzone","uri":"https://api.soundcloud.com/users/22259271","username":"Freeman Dangerzone","permalink":"freeman-dangerzone","last_modified":"2013/01/15 18:37:48 +0000"},"bpm":null,"user_playback_count":null,"id":69023863,"kind":"track","created_at":"2012/11/27 12:22:02 +0000","last_modified":"2015/10/23 15:35:46 +0000","permalink":"10-freeman-handina-godo","permalink_url":"https://soundcloud.com/freeman-dangerzone/10-freeman-handina-godo","title":"10. FREEMAN ( HANDINA GODO )","duration":238076,"sharing":"public","stream_url":"https://api.soundcloud.com/tracks/69023863/stream","uri":"https://api.soundcloud.com/tracks/69023863","user_id":22259271}]

**Comment by evancohen** [comment]
Yup, that's bizarre. Fixed in the above commit on the `dev` branch. Thanks for following up on this!
