### ISSUE TITLE
FHEM Support

### ISSUE THREAD

**Issue by capfirepants** [evancohen/smart-mirror#385]
From the Website:
FHEM (TM) is a GPL'd perl server for house automation. It is used to automate some common tasks in the household like switching lamps / shutters / heating / etc. and to log events like temperature / humidity / power consumption.
The program runs as a server, you can control it via web or smartphone frontends, telnet or TCP/IP directly.

Support for FHEM devices to be controlled over Voice would be amazing. It would open up the possibility to turn on TVs, open Doors and other supported hardware, which there is lots of. 
It can even run on routers and if OS, 2 other huge plus points!

**Comment by evancohen** [comment]
I really like the idea of integrating an existing home automation platform. I believe Home Assistant, which we are looking at for integration (#164), supports all of the home automation tasks that you mentioned (it has a fantastic community and is arguably the best open source home automation system out there right now).

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+8

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
