### ISSUE TITLE
Fitbit integration issue

### ISSUE THREAD

**Issue by jonathanng92** [evancohen/smart-mirror#387]
I am having an issue integrating the Fitbit data to the smart mirror. I have set up the API (was also not sure what to list for application and organization website). I put in the same code from the Fitbit read-me into my config.js file, but in the console I am getting the following error:

TypeError: Fitbit is not a constructor.

Any guidance would be super helpful. Thanks!

**Comment by evancohen** [comment]
Possibly a duplicate but definitely related to #350 - closing this issue out to consolidate this FitBit problem, feel free to follow up there.
