### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by En-TACT** [evancohen/smart-mirror#389]
Unable to reach electron v1.3.5-linux-arm.zip.  Return error, "Error: Failed to find Electron v1.3.5 for linux-arm at https://github.com/electron/electron/releases/download/v1.3.5/electron-v1.3.5-linux-arm.zip".  Folder /download/ does not exist.

**Comment by justbill2020** [comment]
@evancohen,

I submitted this issue on electron's repo on github... you might want to comment anything you find there as well... 

https://github.com/electron/electron/issues/7075

**Comment by evancohen** [comment]
Great, thanks @justbill2020 :+1:

**Comment by arnbruM** [comment]
Sorry to hijack your thread, I am also having this issue, although mine is looking for an arm64.zip.

**Comment by evancohen** [comment]
There isn't an arm64 binary for electron. See https://github.com/electron/electron/issues/259
