### ISSUE TITLE
Temperature in Celsius

### ISSUE THREAD

**Issue by roelofjan-elsinga** [evancohen/smart-mirror#39]
Could this be implemented? I've tried to get this to work, but I failed.

**Comment by gazf11** [comment]
I've managed to get celsius by following blackshroud's solution in closed issues:
 enter 
$http.jsonp('https://api.forecast.io/forecast/'+FORCAST_API_KEY+'/'+geoposition.coords.latitude+','+geoposition.coords.longitude+'?callback=JSON_CALLBACK&units=auto').
into weather-services.js
hope that helps

**Comment by roelofjan-elsinga** [comment]
Thank you!
