### ISSUE TITLE
How to add more speech commands

### ISSUE THREAD

**Issue by wuppi83** [evancohen/smart-mirror#390]
Hi,

if i want to add more speech commands ... which files i have to change ?!
I add a few lines in the "de.json"

`        "shutter": {
            "text": "Schließe die Rolläden",
            "voice": "Schließe die Rolläden",
            "description": "Schließe die Rolläden."
        },`

and in "controller.js"

`            // Shutter
            addCommand('shutter', function() {
		var clickurl = 'http://192.168.1.23:82/user/WebhookBY.php?RUNScriptID=34524';
            });`

But nothing happens :0(

Greetings

Andreas

**Comment by evancohen** [comment]
Those are the only two things that you should have to modify. My guess is that somehow annyang is not correctly matching what you have said to the command.

Use the `annyang.simulate("Schließe die Rolläden")` command in the dev console to see if it matches correctly. Then speak the command and see if the output of the recognized text is ok.

Another potential reason it might not be working: Google speech may not be correctly recognizing in German for the same reason as #376.

**Comment by evancohen** [comment]
Assuming that this solved your issue. Cheers!
