### ISSUE TITLE
Weather not displaying todays forecast

### ISSUE THREAD

**Issue by harvest3155** [evancohen/smart-mirror#391]
i am able to pull and display Current weather, weather description, and weekly weather forecast. I noticed there is something that should call for the current days forecast with High/Low in the ../js/services/weather.js (line 28- 36). however, i am not displaying that information.

**Comment by evancohen** [comment]
That's what the comment says... After reading https://github.com/evancohen/smart-mirror/blob/master/js/services/weather.js#L28-L37 it doesn't look like there is any data transformation on those two fields - although they are returned with the function call, they just aren't consumed in the view.

You could add those two properties by adding them to the template in `index.html`.
