### ISSUE TITLE
Enhancement: consolidate email output

### ISSUE THREAD

**Issue by mkerfoot** [evancohen/smart-mirror#393]
I think it would be sweet if we could get the calendar events all consolidated under the day they below opposed to how mine is showing right now(shown below).

**Today**
appointment 1(all day)
appointment 2(all day)

**Tomorrow**
Appointment 3(1hr)

**Tomorrow**
Appointment 4(1hr)
Appointment 5(1hr)

**Tomorrow**
Appointment 6(1hr)

With the goal being;

**Today**
appointment 1
appointment 2

**Tomorrow**
appointment 3
Appointment 4
Appointment 5
Appointment 6

**Comment by evancohen** [comment]
That's already how it works today... Are you using the latest from master?

![image](https://cloud.githubusercontent.com/assets/1198365/18295925/63d25932-745a-11e6-9cfe-28c3759775eb.png)

**Comment by mkerfoot** [comment]
Strange, everything looks good today. Must of had something to do with my google calendar <-> outlook calendar sync.

P.S. this is the master branch(very recent clone).

Thanks Evan!
