### ISSUE TITLE
Instructions are too old and need updating.

### ISSUE THREAD

**Issue by cowboysdude** [evancohen/smart-mirror#395]
Unless you are a programmer you don't get the average person to want to attempt this... 
Mic issues that should be easily fixable and when you go to the troubleshooting section you end up going around in a big circle with nothing getting fixed....

**Comment by evancohen** [comment]
@cowboysdude it would be helpful if you could elaborate on this. Could you include some more details so that we can improve the documentation?

**Comment by cowboysdude** [comment]
Let me read through it again and see if we can't figure out an approach for non programmers...
Installation section: 

wget https://nodejs.org/dist/v4.4.3/node-v4.4.3-linux-armv7l.tar.gz 
tar -xvf node-v4.4.3-linux-armv7l.tar.gz 
cd node-v4.4.3-linux-armv7l

The above is all wrong because it's version 4.5.0 now... I would suggest this instead:

sudo apt-get install -y nodejs

That works great!  I know, I did it ;)  No need to copy anything... mine runs just fine!

You could explain how to move modules around... I don't see where they are positioned.. or how to change that to custom positions.. 


Configuring Chromium Speech Keys

The instructions don't even follow how to actually do this..
Once you get to the Google API manager it's so complicated.

You know get directed to the Google Cloud Platform and from there the instructions no longer follow correctly.  It's confusing and I know how to figure it out some just never will.. trust me.

Perhaps add another section:

Google Speech Recognizer: Network Error
Explain what this is and why it could possibly be happening.   
It could be quote met for the day... not really sure myself... 

Perhaps add a section on how to get both sound and mic working... 
There are people out here that are using a self powered speaker and plugging it in the 3.5 plug but are getting no sound within the mirror... 


That's about it for now... there are some big [google api key] things there but honestly I'd like to see this particular mirror get VERY popular... it's giving people what they want most.... a mirror you can turn off and on and talk to it..

**Comment by evancohen** [comment]
hey @justbill2020 I know you were thinking about clarifying some parts of the docs and expanding some sections, you should take a look at this feedback.

**Comment by cowboysdude** [comment]
Great!!! I'm just running node 4.5 but it's working...
Well the fun part is trying to figure things out... but pi-install.sh isn't a bad idea either... it has simplified some things... 

We all appreciate your work!  Thank you for putting your time into this!
