### ISSUE TITLE
Weather not working...Geo not working..

### ISSUE THREAD

**Issue by cowboysdude** [evancohen/smart-mirror#396]
I have created both an API and hard coded the long/lat for Geolocation and neither one are working.  

The weather isn't loading...

Continue to get "Google Recognizer: Network Error "  I know my quota has not been reached because I checked that and it's at 0, it's a new key.    It was working fine then suddenly it just started doing that... 
I created a new key and it's still doing the same thing.

 geoPosition: {
       latitude: 42.089796,
       longitude: -76.807734
},

forecast key is correct.

**Comment by evancohen** [comment]
Yup that's a bug, rename "geo_position" to "geoPosition". See #381. The fix is already in the dev branch (which I'm trying to merge into master this weekend).

**Comment by cowboysdude** [comment]
If you're referring to the config.js file it's already named that and still isn't loading....

**Comment by cowboysdude** [comment]
Uncomment the GEO section in the config.js and create ALL chrom keys... my fault.  Issue solved.  :)

**Comment by seihser** [comment]
Excuse me, I'm having the same problem with my old config file.

Can you be more explicit when you say that you have to creat all chrom keys?

Can we have a look at your config.js wchich is working?
