### ISSUE TITLE
Issues installing on pi-3

### ISSUE THREAD

**Issue by itsmason** [evancohen/smart-mirror#402]
Hi, I followed the instructions at docs.smart-mirror.io to the letter but its failing to load.
npm-debug log is as follows:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle smart-mirror@0.0.4~prestart: smart-mirror@0.0.4
7 silly lifecycle smart-mirror@0.0.4~prestart: no script for prestart, continuing
8 info lifecycle smart-mirror@0.0.4~start: smart-mirror@0.0.4
9 verbose lifecycle smart-mirror@0.0.4~start: unsafe-perm in lifecycle true
10 verbose lifecycle smart-mirror@0.0.4~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
11 verbose lifecycle smart-mirror@0.0.4~start: CWD: /home/pi
12 silly lifecycle smart-mirror@0.0.4~start: Args: [ '-c', 'electron main.js ' ]
13 info lifecycle smart-mirror@0.0.4~start: Failed to exec start script
14 verbose stack Error: smart-mirror@0.0.4 start: `electron main.js `
14 verbose stack spawn ENOENT
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid smart-mirror@0.0.4
16 verbose cwd /home/pi
17 error Linux 4.4.11-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.6.0
20 error npm  v3.10.3
21 error file sh
22 error code ELIFECYCLE
23 error errno ENOENT
24 error syscall spawn
25 error smart-mirror@0.0.4 start: `electron main.js `
25 error spawn ENOENT
26 error Failed at the smart-mirror@0.0.4 start script 'electron main.js '.
26 error Make sure you have the latest version of node.js and npm installed.
26 error If you do, this is most likely a problem with the smart-mirror package,
26 error not with npm itself.
26 error Tell the author that this fails on your system:
26 error     electron main.js
26 error You can get information on how to open an issue for this project with:
26 error     npm bugs smart-mirror
26 error Or if that isn't available, you can get their info via:
26 error     npm owner ls smart-mirror
26 error There is likely additional logging output above.
27 verbose exit [ 1, true ]

Any ideas? I've tried twice and had the same error at this point.

**Comment by evancohen** [comment]
Looks like there is something wrong with your electron installation, can you try:
```
npm uninstall electron-prebuilt --save-dev
npm install electron --save-dev
```

**Comment by itsmason** [comment]
thanks evan, i've fixed the issue, the instructions need the following added (i got this info from another answer you gave someone else...

at install point bower needs to be installed from within the smart-mirror directory. this fixed the issue and it's running with no issues now. 

great work by the way, and thankyou.
