### ISSUE TITLE
Voice reco not working on PI 3. 

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#403]
I recently installed SM for the first time. I have a TV as the monitor, with HDMI output, and a USB webcam as mic in. 

I 'think' I have the setup correct so that arecord and aplay work on the default devices with pulseaudio running. 

but nothing works with smart mirror. (is it supposed to make a sound at npm start?)
pulseaudio -v shows the attached
[sound-trace.txt](https://github.com/evancohen/smart-mirror/files/498186/sound-trace.txt)
aplay -l shows
[play_devices.txt](https://github.com/evancohen/smart-mirror/files/498192/play_devices.txt)
arecord -l shows
[record_devices.txt](https://github.com/evancohen/smart-mirror/files/498193/record_devices.txt)

.asoundrc does not exist. 

and the output of npm start is 
[start_output.txt](https://github.com/evancohen/smart-mirror/files/498204/start_output.txt)

**Comment by sdetweil** [comment]
also, what is the training supposed to do? It opens the web site, but on create new hotword it says use Chrome.. then there is the 'record my voice' button, but nothing happens, and the button goes away.
the help doesn't describe what is supposed to happen. 

the snowboy setup step, rec temp.wav works.. so mic is working, sw is configured, ...

**Comment by evancohen** [comment]
Hey @sdetweil, the smart mirror no longer supports PulseAudio (see #307). I responded to that email and on gitter, but for anyone else wondering: 
When training the keyword you have to log in first. I'm guessing in input problems here are caused by PulseAudio issues.

**Comment by sdetweil** [comment]
i removed pulseaudio, fixed up the .asoundrc file, got rec and play to work.. then went to record the model with my mic..    no logon available from pi invocation...  had to go to windows, and record works, test works.

save doesn't UNLESS the name of the model is unique.. (not already used!)..  weird..

now have reco test working, and mirror code shows some blip, but then doesn't do anything else

**Comment by sdetweil** [comment]
I am using my own voice model now..  

today I noticed that microphone-debug and arecord both failed, something about dsnoop..  turned out my usb webcam had changed card numbers.  fixing that is ~/.asoundrc, now works..

**Comment by sdetweil** [comment]
solved by changing the .asoundrc to specifically id my USB device, instead of depending card order.. 

pcm.usb {
type hw
card U0x46d0x825 <----- change this to match your hardware ID. (found with arecord -l command
}
-#asym fun start here. we define one pcm device called "pluged"
pcm.pluged {
type plug
-#this is your output device
slave.pcm "hw:0,1"
}

-#one called "dsnooped" for capturing
pcm.dsnooped {
ipc_key 1027
type dsnoop
-#this is your input device
slave.pcm "usb"
}

-#and this is the real magic
pcm.asymed {
type asym
playback.pcm "pluged"
capture.pcm "dsnooped"
}

-#a quick plug plugin for above device to do the converting magic
pcm.pasymed {
type plug
slave.pcm "asymed"
}

-#a ctl device to keep xmms happy
ctl.pasymed {
type hw
card 0
}

-#for aoss:
pcm.dsp0 {
type plug
slave.pcm "asymed"
}

ctl.mixer0 {
type hw
card 0
}

pcm.!default {
type asym
playback.pcm
{
type plug
slave.pcm "pluged"
}
capture.pcm
{
type plug
slave.pcm "dsnooped"
}
}

ctl.!default {
type hw
card 0
}
