### ISSUE TITLE
White is boring....what about adding some colors?

### ISSUE THREAD

**Issue by GobleSt** [evancohen/smart-mirror#404]
Let's spice things up a bit and add some color or maybe scroll the stocks....something to add some pizzazz.

**Comment by taran27** [comment]
hmmm @GobleSt  your idea is gr8 but its now possilbe as its in mirror form we can setup this later if you go for the touchscreen mirror that can  be too good for dat purpose

**Comment by GobleSt** [comment]
Seems like it would be simple as it is just a Web page but I don't do Web
page coding.  Since I'm a hardware guy I'm hoping one of you smart software
people will hook me up.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+7

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
