### ISSUE TITLE
Calendar recurring events not correctly picking up the day labels

### ISSUE THREAD

**Issue by pearno** [evancohen/smart-mirror#408]
I'm having trouble with calendar events displaying with the 'Today', 'Tomorrow', etc. labels.

I believe this issue is limited to events which are recurring.  These events show the start and end times, but no day or date label at all.

Individual ad-hoc events correctly display the day/date and, curiously, the event immediately after an ad-hoc event also displays the day/date whether it is recurring or not.

This issue seems to have started either with the introduction of the grouping of events by day (issue 314) or with the introduction of the use of moment.js (issue 316), as it was successfully displaying the days of the week per event before I rebuilt my mirror with a fresh copy of the smart mirror repository last week.

I'm not sure how to troubleshoot this issue, but I have created a test calendar to demonstrate my issue, if this helps, which can be found here:

https://p02-calendars.icloud.com/published/2/UxWkcs4VB0dot0OejMK-vrUA26gO3RcgEWexpVYreqWjPlTx72Gz2WpCD5HO09O1ZqaOyfJACkNj3xFAo45WD62MR7OMIeZg9ZpPosO_56g

Any help or pointers greatly appreciated!

-Matt

**Comment by justbill2020** [comment]
@pearno are you still experiencing this issue?

**Comment by evancohen** [comment]
@kurtdb maybe you have an idea of what's going on here?

**Comment by pearno** [comment]
Yes, still happening for me.  I wondered if it might be related to the moment.js localisation issue (#376), since I'm set to UK dates/times?

**Comment by evancohen** [comment]
Ooh, yup. I keep meaning to fix that! Hopefully I can take a shot at it this week.

**Comment by evancohen** [comment]
I'm swamped with the rest of the smart mirror work going on right now.
Let's see if @joelhawksley can take a look, as he has done some work on the calendar in the past.

**Comment by joelhawksley** [comment]
@evancohen @pearno PR opened for fix. Please test to confirm.

**Comment by justbill2020** [comment]
The PR #501 was merged and this is now closed..

@pearno  is this now resolved?

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by pearno** [comment]
Yes, I can confirm that the latest dev branch fixes the issue for me - I get correct day labels for my recurring calendar events, even with my Language set to en-GB.

Thanks for looking into this for me!
