### ISSUE TITLE
Mirror wont load unless RSS feed is defined in config

### ISSUE THREAD

**Issue by jamesrequa** [evancohen/smart-mirror#409]
I ran smart-mirror in debug and got the following Angular error in the console. BTW nothing showing in the program - the whole screen is black.

angular.js:13236 TypeError: Cannot read property 'then' of undefined
    at Object.RssService.service.refreshRssList (rss.js:34)
    at refreshRss (controller.js:275)
    at MirrorCtrl._this.init (controller.js:283)
    at new MirrorCtrl (controller.js:562)
    at Object.invoke (angular.js:4604)
    at extend.instance (angular.js:9855)
    at nodeLinkFn (angular.js:8927)
    at compositeLinkFn (angular.js:8226)
    at compositeLinkFn (angular.js:8229)
    at publicLinkFn (angular.js:8106)

**Comment by evancohen** [comment]
Looks like something is wrong with your RSS config. Try removing it from `config.js` and see if that fixes it.

**Comment by jamesrequa** [comment]
I actually had it commented out in the config file cause I don't have any RSS feeds. Now I tried removing it altogether from the config and rerun but getting the same error back in the console.

**Comment by evancohen** [comment]
Interesting - sounds like a bug. For now you should just be able to add the empty config object and that should work.

**Comment by jamesrequa** [comment]
That worked, now the mirror loads, awesome! Thanks Evan!

----

btw...the mic is picking up my voice since it follows all my commands but there doesn't appear to be any audio playback. All I see is that the bottom of the screen turns slightly white to show the mirror is listening. I can post that issue in a separate thread though.

**Comment by evancohen** [comment]
Fixed in the dev branch. Should be ok now :)
