### ISSUE TITLE
Ios reminders / Amazon echo shopping list

### ISSUE THREAD

**Issue by TheCellMC** [evancohen/smart-mirror#410]
A welcome feature would be the added support to reminders (ios, Android) or the support for the amazon echo shopping list. Then you could just ask the smartmirror to display your shopping list.

**Comment by evancohen** [comment]
thanks for the suggestions!

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+6 

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
