### ISSUE TITLE
Emotion Detection

### ISSUE THREAD

**Issue by p4ndi4** [evancohen/smart-mirror#411]
I know there is a module for face detection to switch between users, but has anyone considered emotion detection (e.g. changing the string that is shown depending on emotion rather than time of day - or both)?

The Cognitive Services API in Azure has a free tier and an emotion API that could be used: https://www.microsoft.com/cognitive-services/en-us/emotion-api/documentation.

**Comment by evancohen** [comment]
Thanks for your suggestion. I've done some on-device face recognition before, but I think this would be really cool. Feel free to take a stab at it and send a PR. Let me know if you need any help!

**Comment by justbill2020** [comment]
migrated to http://feathub.com/evancohen/smart-mirror/+5 please refer to feathub for all future comments on this suggestion. 

Issue will be closed and tracked on feathub moving forward
