### ISSUE TITLE
Failing to start 

### ISSUE THREAD

**Issue by mohiuddinopu** [evancohen/smart-mirror#412]
I configured as per the instruction and seeing the following error while starting. I updated the SM repo, still seeing the same error. 

pi@raspberrypi:~/smart-mirror $ npm start
> smart-mirror@0.0.4 start /home/pi/smart-mirror
> electron main.js
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1036:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/electron-prebuilt/cli.js:7:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)

npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.4 start: `electron main.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.4 start script 'electron main.js '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

**Comment by evancohen** [comment]
Could be that there's an issue with your dependencies, can you try:
```
git clean -xdf -e config.js
npm install
```
and then start it again?

**Comment by evancohen** [comment]
This should be fixed in the latest master.
