### ISSUE TITLE
Integrate OpenTok APIs for video chat

### ISSUE THREAD

**Issue by madhavc** [evancohen/smart-mirror#419]
Opening Issue so we can add it waffle.io and keep track of it.

**Comment by justbill2020** [comment]
migrated to http://feathub.com/evancohen/smart-mirror/+4 please refer to feathub for all future comments on this suggestion.

**Comment by justbill2020** [comment]
keeping open for waffle.io as noted above... @madhavc please add comments to the feathub suggestion... thank you...

**Comment by justbill2020** [comment]
haven't heard a response in over 14 days. I'm closing this issue...

@madhavc  please comment on this issue and we can reopen if needed...
