### ISSUE TITLE
Make internationalization a possibility

### ISSUE THREAD

**Issue by kurtdb** [evancohen/smart-mirror#42]
I see a lot of questions passing where people ask: hey, how do I display my data like this or like that. (eg the weather format being in centigrade or kelvin)

Wouldn't it be a great possibility if we put the configuration of that stuff in the config.js? That way it will become the only file people who want to use the software will have to look at. (unless they want to hack it, in which case they should be encouraged to also use the same approach)

I did a quick try by trying to standardize the way the dates (and the time) are formatted.for my calendar integration, but didn't get it to work yet. Might be looking further into this in the near future.

**Comment by kxd1000** [comment]
Hi,
this is a good idea. I am trying to get my mirror to german language.
I sent a PR today with modification of the weather language. It is not a big change but it is a beginning.

BR. Kurt
