### ISSUE TITLE
Microphone issue

### ISSUE THREAD

**Issue by filimikr** [evancohen/smart-mirror#421]
Hey, 

I have an issue with my usb (creative) camera for the microphone. 
Raspberry recognizes the device and in the sound config file(asoundrc)  I set it as default recording device. 
Microphone-debug recognizes the device as well, and I can record and play my recording. 
Although when I run the Smart-Mirror the microphone is not working. I think that my config.js file is properly edited.

Any help would be appreciated. Thank you!

(Raspberry 3/raspbian upgraded/smart-mirror updated)

**Comment by kurtdb** [comment]
If you start the mirror using ```npm start dev```, do you see any logging concerning the speech?

**Comment by filimikr** [comment]
No, i have only this folowing error (and one more for the rss), but nothing for speech.

TypeError: Cannot read property '@attr' of undefined
    at scrobbler.js:17
    at processQueue (angular.js:15552)
    at angular.js:15568
    at Scope.$eval (angular.js:16820)
    at Scope.$digest (angular.js:16636)
    at Scope.$apply (angular.js:16928)
    at done (angular.js:11266)
    at completeRequest (angular.js:11464)
    at XMLHttpRequest.requestLoaded (angular.js:11405)(anonymous function)

**Comment by evancohen** [comment]
You might want to give the troubleshooting steps a shot and just run the keyword spotter and speech recognition to see what is up: https://docs.smart-mirror.io/docs/microphone_and_speech_recognition_issues.html

**Comment by filimikr** [comment]
Actually I re-installed everything from the scratch(raspbian-smart-mirror etc), and now things are better. the app recognizes the usbCamera normally, and after I trained my own model, the keyword seems like it's ok(it shows this white line across at the bottom.(sonus shows me that it recognizes the keyword as well)

The problem is that after the white effect , it does nothing. It doesn't listen to any command, like "What can i say or sth, and The white effect stays there until I close the app

ps. I ran it in dev mode and no errors appeared.
:/ thanks

**Comment by evancohen** [comment]
You might want to review the steps that you used to get your key. If it doesn't have valid permissions then hotword detection will work but streaming will fail: https://docs.smart-mirror.io/docs/configuring_voice.html#setting-up-speech-recognition

**Comment by justbill2020** [comment]
also the project name in the `keyfile.json` file must match the project name in `config.js` file

**Comment by evancohen** [comment]
Sounds like you haven't enabled billing. Can you double check that?

**Comment by justbill2020** [comment]
@filimikr is this now resolved? 

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you. 

[Also, we're available on gitter to help assist you in real time.](https://gitter.im/evancohen/smart-mirror)
@filimikr is this now resolved? 

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you. 

[Also, we're available on gitter to help assist you in real time.](https://gitter.im/evancohen/smart-mirror)

**Comment by justbill2020** [comment]
haven't heard a response in 10 days. I'm closing this issue...

@filimikr  if you're still having issues please comment on this issue and we can reopen..
