### ISSUE TITLE
Can you...log out of the app?

### ISSUE THREAD

**Issue by petran1420** [evancohen/smart-mirror#422]
Hi all, 

Probably dumb question here- I have the app up and running just fine after npm start, but I'm wondering if theres any way to close the app and get back to the rasp pi home screen? Do I have to turn it off and on again? I have ssh enabled but I don't think npm commands work with ssh so I'm not sure I can do anything remotely

This is my first project making an app like this after a little bit of codeacademy and khan academy tutelage. I'm having a blast so far!

**Comment by justbill2020** [comment]
Alt + F4 will do it... or control + c from the terminal... also alt + tab will work just like it does in other operating systems.

**Comment by petran1420** [comment]
Thanks!!

**Comment by justbill2020** [comment]
If you haven't already check out our gitter page for quick answers to issues @ https://gitter.im/evancohen/smart-mirror
