### ISSUE TITLE
integration of pimatic 

### ISSUE THREAD

**Issue by hyp3rx** [evancohen/smart-mirror#423]
Hello,
it would be nice if we can integrate Pimatic home-automatation. Maybe partially...  for Temp-sensors, status ...

From website:
pimatic is a home automation framework that runs on node.js. It provides a common extensible platform for home control and automation tasks.
 Uniform interface
It defines several schemata for different home devices and sensors, so that all devices can be controled uniform and are presented in a common interface.
Automation tasks can be defined by rules in the form of "if this then that", where the "this" and the "that" part can be fully customized by plugins. See the rule page for more details.
The mobile frontend plugin provides a nice web frontend with a sensor overview, device control and rule definition. The web interface is build using express and jQuery Mobile.

https://pimatic.org

**Comment by justbill2020** [comment]
@hyp3rx This is a great suggestion... my concern is with so many open source projects out there it hard to integrate all of them. As I'm sure you've seen there's requests to integrate everything from smartthings to Logitech harmony hub to wink to insteon... even integration with the tesla app... and everything in between. being pragmatic the only thing most of these have in common with one another is IFTTT... perhaps this is the way to expand the project's reach. I know there was an OAuth service that Evan was looking at for v1.0... which might help with this issue as well...

Regardless, awesome suggestions and definitely a cool project to look into integrating into the Smart-Mirror...

@evancohen I think integrating IFTTT into the mirror would be a great way to integrate many things already compatible with IFTTT...

**Comment by hyp3rx** [comment]
Maybe we can develop some universal plugin for many homeautomatiation since many of them (pimatic included) can be used via api. 
So we use a command line to get some temperature values for the smart-mirror.

**Comment by justbill2020** [comment]
@hyp3rx if you fork the repo you can take a look and see how to go about integrating it and then when complete submit a PR against the dev branch and after some testing and what not @evancohen can merge the PR... once its tested and vetted it will be included in the next master release then. 

we definitely need and can use more community programming involvement.

**Comment by justbill2020** [comment]
migrated to http://feathub.com/evancohen/smart-mirror/+2 please refer to feathub for all future comments on this suggestion.
