### ISSUE TITLE
Cannot find module '@google-cloud/speech'

### ISSUE THREAD

**Issue by wuppi83** [evancohen/smart-mirror#424]
Hi Evan,

do you have an idea ...  what is the problem?!

```
module.js:327
    throw err;
    ^

Error: Cannot find module '@google-cloud/speech'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:11:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by justbill2020** [comment]
did you use the install script for raspberry pi? or a manual installation?

it looks like you're missing dependencies... can you browse the internet?

**Comment by wuppi83** [comment]
I used the script :0( ... and i didn't find anything about this error by the internet ..

**Comment by justbill2020** [comment]
i can't replicate this currently

**Comment by wuppi83** [comment]
Maybe 

`npm install --save google-cloud`

works ... i will test it !

**Comment by justbill2020** [comment]
I would say to do `git pull` and then `npm update` from the `smart-mirror` folder

also you have downloaded your keyfile.json from the google cloud platform console right?

also you've configured your config.js?

**Comment by wuppi83** [comment]
```
pi@Magic-Mirror:~/smart-mirror $ git pull
Already up-to-date.
```

```
pi@Magic-Mirror:~/smart-mirror $ npm update
npm@3.10.10 node_modules/npm
bower@1.8.0 node_modules/bower
```

> also you have downloaded your keyfile.json from the google cloud platform console right?
Yes

> also you've configured your config.js?
Yes

```
npm install google-speech --save
npm install --save google-cloud
```
Doesn't fix the problem :0(

**Comment by evancohen** [comment]
Running `npm install` should resolve the issue, but if it doesn't then you can try

```
npm install @google-cloud/speech --save
```

For reference: https://www.npmjs.com/package/@google-cloud/speech

**Comment by wuppi83** [comment]
`npm install @google-cloud/speech --save`

Works for me :0) Thank you Evan !
