### ISSUE TITLE
Error in automatic installation - GRPC

### ISSUE THREAD

**Issue by weedorbeat** [evancohen/smart-mirror#427]
Hello,
i have used the following manual to install smart-mirror: 
[https://docs.smart-mirror.io/docs/installation.html](https://docs.smart-mirror.io/docs/installation.html). 

There I got the following command and executed this in the shell:
`Curl -sL https://raw.githubusercontent.com/evancohen/smart-mirror/master/scripts/pi-install.sh | bash`

The following error occurred during the installation:
![pi_sm_err](https://cloud.githubusercontent.com/assets/199562/20198742/97523082-a7a6-11e6-9c85-75cff6c8282f.png)

Then I tried the manual installation, but here the same error occurs.

I use a Raspberry Pi 3 with the latest Raspbian version.

NPM-Debug-Log: [npm-debug.txt](https://github.com/evancohen/smart-mirror/files/584677/npm-debug.txt)

I hope the informations are sufficient to help me otherwise I can gladly add more

**Comment by justbill2020** [comment]
did you write the raspbian jessie with pixel directly to your SDcard or did you use noobs to install?

i'm allso going to tag @evancohen  to see if he knows what would cause this?

**Comment by weedorbeat** [comment]
Right, using a Windows PC and DiskImager to write raspbian jessie with pixel directly to mine SD-Card (32GB Samsung)

**Comment by evancohen** [comment]
There's a similar issue compiling gRPC for ARM here: grpc/grpc#6302

That said, I had no trouble compiling on my Pi a few weeks ago so clearly *something* has changed. I'll take a look this weekend.

**Comment by weedorbeat** [comment]
Thanks for your help, I hope you'll find something :thumbsup:

**Comment by weedorbeat** [comment]
Thanks for your help, I hope you'll find something 👍

Here is the verbose log:
![pri_npm_error_verbose](https://cloud.githubusercontent.com/assets/199562/20233838/65d73d80-a874-11e6-92d9-eaf07521c9eb.PNG)

NPM-Debug-Verbose-Log: [npm-debug.txt](https://github.com/evancohen/smart-mirror/files/586950/npm-debug.txt)

**Comment by evancohen** [comment]
Ok, I did some investigating here and the issue is that you are using grpc with Node 7.
If you roll back to `lts` (v6.9.1 right now) it should work.

**Comment by weedorbeat** [comment]
It works. Thanks a lot :)!
