### ISSUE TITLE
Getting Icloud Calendar to work

### ISSUE THREAD

**Issue by jgummersall** [evancohen/smart-mirror#432]
When I put the webcal:\\ address in the config file and run npm start dev, it gives me an error syaing that my URL address is in an unreadable format.

**Comment by jgummersall** [comment]
If you remove the webcal:// and replace it with https:// so it reads https://p10.......... then it will have access to your calendar.

**Comment by ritwickgupta** [comment]
This is still not working for me @jgummersall

**Comment by jgummersall** [comment]
This fox worked for previous versions of the mirror, I have yet to try it on the install and upgrades that came out over Christmas break since I have been slammed with school, didnyou try it with webcal and https?

**Comment by ritwickgupta** [comment]
Yes. I tried with both and it didn't work

**Comment by jgummersall** [comment]
Ok I'll try and look at it this weekend are you getting any specific error message?

**Comment by justbill2020** [comment]
I'm reopening this issue

**Comment by ritwickgupta** [comment]
No error. I haven't check the logs, but on the mirror screen, no calendar appears, not even the google ones once I have added the url for apple calendar

**Comment by overflOw11** [comment]
I check the functionnality on the last dev branch and it works. You have to remove the webcal:// and replace it by https:// on the configuration file.
Have you checked that your icloud calendar is still public ? What's happen when you request the https://p10 link from your favorite web browser ?

**Comment by ritwickgupta** [comment]
@overflOw11 what do you mean by changing it on the configuration file? Yes my calendar is public. I used https:// on the web interface which is used to set up the mirror. When I did that, none of the calendar showed up on the mirror, but other modules worked (Weather, Transit etc).

**Comment by justbill2020** [comment]
He means in the remote configUI

**Comment by ritwickgupta** [comment]
Yes. I put https:// in remote config UI

**Comment by justbill2020** [comment]
@ritwickgupta 
Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time. That might be a better way to attempt to help on this one...

**Comment by justbill2020** [comment]
haven't heard a response in over 14 days. I'm closing this issue...

@ritwickgupta  if you're still having issues please comment on this issue and we can reopen..

**Comment by ritwickgupta** [comment]
@justbill2020 I still can't get it working. I am on dev branch. This is what it looks like [https://ibb.co/bGkqLa](url)

**Comment by ritwickgupta** [comment]
@justbill2020 This is the error from the console
https://ibb.co/crrKDv
