### ISSUE TITLE
sonus stopps working

### ISSUE THREAD

**Issue by hyp3rx** [evancohen/smart-mirror#435]
Today after playing around, started smart-mirror:

npm start

> smart-mirror@0.0.5 start /home/pi/smart-mirror
> electron main.js 

ERROR me/pi/smart-mirror/sonus.js:4
const config = require(__dirname + "/config.js")
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

Excep voice recocizing everything works.

**Comment by evancohen** [comment]
What version of Node are you using?

**Comment by hyp3rx** [comment]
Now i am in real problems, tried to reinstall smart-mirror, but fails here:

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.15.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.15.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
Unable to install dependencies :(

**Comment by evancohen** [comment]
Check out #427
You problem is with node 7.x

**Comment by hyp3rx** [comment]
Have downgraded to node 6.9.1, but:

Installing smart-mirror dependencies...
This may take a while. Go grab a beer :)
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> snowboy@1.1.0 preinstall /home/pi/smart-mirror/node_modules/.staging/snowboy-ae1258f3
> npm install node-pre-gyp



Unable to install dependencies :(

**Comment by hyp3rx** [comment]
I´ve installed electron by hand, then use npm install. Now it´s back working. Maybe there is something wrong in the "one click install script"

**Comment by evancohen** [comment]
I hear that when you get those errors there's a debug log, can you please share it?
The WARN is just that, only a warning, and should not cause any issues with installation.

**Comment by justbill2020** [comment]
This is 14 days old since the last update... @hyp3rx has this issue been resolved for you? if so please comment how it was resolved (hopefully @evancohen's comment helped) and close the issue. If it's not resolved please let us know how we can further help... Also please check us out on [gitter.im](https://gitter.im/evancohen/smart-mirror) if you haven't already... 

If we don't hear anything over the next week we'll assume this is resolved and close the issue.

**Comment by Fijvect** [comment]
This is also a major issue for me right now, so I guess I'll pick up the mantle from here.
Where can I find the debug log? I'll post the results once I find it

**Comment by justbill2020** [comment]
This should be solved by doing `git pull && npm install` within the `smart-mirror` directory...

I'm closing this as resolved...
