### ISSUE TITLE
Voice Command Problem

### ISSUE THREAD

**Issue by chanjungkim** [evancohen/smart-mirror#436]
I fixed using 'What can I say?' command by voice.
however, I need to say 'What can I say?' every time before every c
ommand.
'What can I say?' -> 'Show map' 'What can I say?' -> 'Go home'
'What can I say?' -> 'What can I say?'
It is because I fixed speech>model>"smart_mirror.pmdl" -> "whatcanisay.pmdl(I trained and downloaded it)"from the config.js
As I see in Evan's video, he doesn't repeat the same command before a specific command. When it's "smart_mirror.pmdl" It doesn't response anything.
How can I make the mirror listen and get ready to receive my command?

**Comment by evancohen** [comment]
You'll probably want to train your own hotword here: https://snowboy.kitt.ai/hotword/47

The video is a year old and things have changed - mostly that you can't get unlimited free speech requests and people don't like constantly streaming audio to Google.

Now the way it works is:

"Smart mirror" -> "What can I say?"
"Smart mirror" -> "Go home"
etc.

**Comment by justbill2020** [comment]
@chanjungkim is this resolved now or do you need more guidance on this one... please let us know so we can further assist. if this is resolved please comment how you resolved it and then please close the issue... thank you.

**Comment by justbill2020** [comment]
haven't heard a response in 10 days. I'm closing this issue...

@chanjungkim if you're still having issues please comment on this issue and we can reopen..
