### ISSUE TITLE
Raspberry Pi Zero?

### ISSUE THREAD

**Issue by CaolanMcK** [evancohen/smart-mirror#439]
This might be a stupid question, but can the code be run on a raspberry pi zero?

**Comment by evancohen** [comment]
Not a stupid question, but no - it's not powerful enough (and Electron doesn't have ARMv6 binaries)

**Comment by CaolanMcK** [comment]
Raspberry Pi 1?

**Comment by evancohen** [comment]
Same deal (they essentially have the same specs)
