### ISSUE TITLE
some problem at npm install

### ISSUE THREAD

**Issue by zol60fire** [evancohen/smart-mirror#44]
I've problem at npm install step. What should i do?

![12647590_981106538615557_804877589_n](https://cloud.githubusercontent.com/assets/15710483/12572251/b37d5d24-c424-11e5-811a-620c8348bd3c.jpg)

**Comment by evancohen** [comment]
How big is your SD card? This error means you are out of space. You probably just need to expand your root partition. Run `sudo raspi-config` and then select "Expand root partition to fill SD card". You'll have to restart and then you'll be good to go.
