### ISSUE TITLE
Hi~

### ISSUE THREAD

**Issue by GeonilJang** [evancohen/smart-mirror#444]
I just bought pi3 to make this smart-mirror with you git. There is one thing i wanna know why we have to use pi2 or more than pi2 model?
Coz i have pi b model.
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by justbill2020** [comment]
Its due to the hardware... electron is a dependency for the project and isn't compatible with raspberry pi prior to the pi 2 nor is it compatible with the pi Zero which uses the same processor as the B, and B+... prior to the pi 2 the processor was an arm v6 single core. the pi 2 is v7 quad core. the pi 3 uses a 64 bit processor. While Smart-Mirror works with a pi 2... a pi 3 is highly recommended, we've seen the most success with a pi 3. Hope this answers your question.

I'll close this issue... if you have a follow up question we can continue it in the closed status.

**Comment by GeonilJang** [comment]
thank for letting me know this issue. i will follow your amazing git as soon as i get pi3. i am a student who want to be a good engineer... you are like my mentor... but i am not kind of smart student like you... if you dont mind, could you let me know how to be a good computer engineer and what i should do first?? i am stuck..
many people say that i have to study c languge first.. but when i studied it i didnt know what i cant with c.  sadly.. i dont have any good teacher near me.. i am living at county side and it is hard to reach city. so i have to study only with book.. but it didnt say what i can do with it neither.... in my case, i dont want to bother you. i wish i could do know like what i should study and how to study.. you can ignore this , it was grumbling... By the way thanks a lot!! :) 
-----Original Message-----

**Comment by justbill2020** [comment]
that's an @evancohen question he's the mastermind behind the smart-mirror...

**Comment by evancohen** [comment]
The best computer scientists are the ones who are doing what they are passionate about, it doesn't matter what language you use (although understanding low level languages like C helps you understand what is going on in other languages but depending on what you want to do it may not be super useful except at a conceptual level).

My recommendation would be to pick a project you want to do, something that you want to build. When you start, you'll have no idea what you are doing - but you'll figure it out. 

This approach helps in two ways: You learn about how to solve big problems and learn (how to learn) along the way. Finding useful resources for programming is definitely a learned skill, but the internet is a gold mine of information about programming. Google and StackOverflow are your friends.

If you have trouble picking a project try to solve a simple problem that you have in your day-to-day life. This might be a bit to elaborate for an example, but right now I'm building a cheese cave (highly regulated space for aging home made cheese). I built a system that regulates both temperature and humidity and monitors them over time. It's basically just a Pi with a few sensors, an old fridge, and a humidifier; Along with a database, REST API, and a simple responsive web app that the Pi hosts so you can control the cave from your phone/computer on the network. 

If anyone is interested I'll do a short write up and maybe post some pictures.
