### ISSUE TITLE
Check e-mail

### ISSUE THREAD

**Issue by SenadM** [evancohen/smart-mirror#45]
Would be nice to add under the calendar. Your latest 4-5 mails showing up.

**Comment by evancohen** [comment]
I'm a little (maybe overly) concerned about privacy if you are just showing everyone your most recent emails. I'd be more interested in integrating a service like [PushBullet](https://www.pushbullet.com) to "mirror" notifications from your phone.

**Comment by SenadM** [comment]
PushBuller sounds like a great idea.

**Comment by danielccm** [comment]
I found a free alternative to PB.... http://www.getpushline.com/ ... they will even have an API...

**Comment by evancohen** [comment]
@danielccm good suggestion, I'll check it out.

**Comment by redbeed** [comment]
@evancohen pushline is not ios compatible at the moment :-1:

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+36

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
