### ISSUE TITLE
Scrobbling Service Documentation

### ISSUE THREAD

**Issue by justbill2020** [evancohen/smart-mirror#452]
There's no current documentation for how the scrobbler service works...

**Comment by evancohen** [comment]
Yeah, this needs to be done. I'll take a crack at it tomorrow if I have time

**Comment by justbill2020** [comment]
@kurtdb would you have a bit of time to churn out some scrobbler docs? we're getting a lot of questions and requests on discord regarding it. i know its kind of a simple one but if you could do it that would be awesome...

**Comment by kurtdb** [comment]
I'll try to take a look at it at lunch or tonight.

**Comment by justbill2020** [comment]
closing... moved to docs.smart-mirror.io repo
