### ISSUE TITLE
Errors on 'npm start'

### ISSUE THREAD

**Issue by cheever13** [evancohen/smart-mirror#454]
I'm using RPi3 with Raspbian (full not noobs) and attempting to get this to work. It's most likely something simple as I am relatively new to these types of projects. However. Followed the installation instructions and when attempting to start the mirror for the first time I get some failures. Seems like I'm running from a wrong directory perhaps?

'npm-debug.log' contents:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/pi/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/pi
7 error Linux 4.4.21-v7+
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
9 error node v6.9.1
10 error npm  v3.10.8
11 error path /home/pi/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

Thank you very much for whoever points out whatever obvious mistake I'm making.

**Comment by justbill2020** [comment]
you must be in the smart-mirror folder... such as `cd ~/smart-mirror`

then you can do `npm install`

then you can do `npm start`

**Comment by cheever13** [comment]
Thank you justbill2020, I apologise for my late reply (weekly schedule is difficult for projects). I was able to get farther with your help but it appears I have some syntax issues I need to take care of. It turns out my keyboard has an odd map and was typing ¬ instead of a  tilde. Thank you for your help, I believe I can take it form here.
