### ISSUE TITLE
autoTimer isn´t working

### ISSUE THREAD

**Issue by warflash** [evancohen/smart-mirror#457]
### Expected Behavior
After a specific time the pi should deactivate its HDMI output.

### Current Behavior
The HDMI output won´t get deactivated - pretty simple. I dont get any error or something... 
If I enter "/opt/vc/bin/tvservice -o" manually everything is working fine.  
I just have the part of the config code for anyone wondering:   

 autoTimer: {
        autoSleep: 240000, // How long the screen will stay awake before going to sleep (40 Mins)
        autoWake: '07:00:00', // When to automatically wake the screen up (7:00AM)
        'wake_cmd': '/opt/vc/bin/tvservice -p', // The binary and arguments used on your system to wake
        'sleep_cmd': '/opt/vc/bin/tvservice -o', // The binary and arguments used on your system to sleep
},

### Possible Solution
The Problem is, that I have no Idea whats causing this Issue, I tried using the example config with no changes, changed the time from 40 min to 1 hour and smaller numbers like 5 min or something. I even did a fresh install of Jessie and the smartmirror on another SD-Card.

### My Environment
I´m using a Raspberry Pi 2B with the latest version of the smart mirror and I´m running npm version 3.10.8 and Node version 6.9.1 and the latest Jessie version. Two other things that might be worth mentioning could be that im using a HDMI to DVI adapter and that my router is kinda unstable and disconnects me every minute or so. The mirror then gives me some network changed error messages. i thought that that might be the reason its not working, but even when changing to a stable router wih no disconnects it still doesnt work. 

Thanks alot for your help, I really love this project.

**Comment by justbill2020** [comment]
Thanks for submitting this i've been meaning to and have otherwise been distracted... this is an issue with the tvservice commands not functioning as expected... we'll have to look into it further to solve...

**Comment by roiboos** [comment]
Found the problem: The variables for AutoWake defined in the config.js and autosleep.js are named differentely. Just rename autoWake in config.js to auto_wake

**Comment by Fijvect** [comment]
I just discovered this as well. Works perfectly after that. I changed every other instance of auto_wake to autoWake however, in controller.js and autosleep.js instead.

**Comment by justbill2020** [comment]
created a patch for this and pull request... #458 to be pulled to dev branch...

@evancohen something like this should i just hotfix in master and dev branch of follow the normal workflow?

**Comment by Fijvect** [comment]
Just to give a warning to people in case they are having problems with the monitor turning back on after having been off for so long, there is one more step you may have to do. I had to at least.
Instead of having the autowake run the tvservice - p command, I had it run a custom script instead that ran the tvservice -p, followed by sudo chvt 9 && sudo chvt 7. Then it worked beautifully. I think what it was doing is switching the HDMI outputs back and forth really quick to trigger the monitor to notice the signal and boot itself on again.

**Comment by justbill2020** [comment]
can you attach the script file here... and the command in config.js that you entered... i'll add it to the hotfix PR for this

**Comment by Fijvect** [comment]
Here's the script I used: (based on https://gist.github.com/simlun/1b27b14d707abbba8fc1)

`
#!/bin/bash -e

# /usr/local/sbin/raspi-monitor
# Script to enable and disable the HDMI signal of the Raspberry PI

CMD="$1"

function on {
    /opt/vc/bin/tvservice --preferred

    # Hack to enable virtual terminal nr 7 again:
    chvt 6
    chvt 7
}

function off {
    /opt/vc/bin/tvservice --off
}

function must_be_root {
    if [ $USER != root ]; then
        echo "ERROR: Script must be executed as the root user"
        exit 1
    fi
}

function main {
    must_be_root
    if [ "$CMD" == "on" ]; then
        on
    elif [ "$CMD" == "off" ]; then
        off
    else
        echo "Usage: $0 <on|off>"
        exit 1
    fi
    exit 0
}

main
`

Then for the `wake_cmd` field I put `sudo /usr/local/sbin/raspi-monitor on > /dev/null 2>&1`
and for the `sleep_cmd` field I put `sudo /usr/local/sbin/raspi-monitor off > /dev/null 2>&1`

**Comment by kurtdb** [comment]
Not sure that running the mirror as root is that of a good idea, but that's just my 2 cents.

**Comment by justbill2020** [comment]
its more running the script as root... for purposes of the monitor going on and off...

**Comment by evancohen** [comment]
I'm assuming that there's no reasonable way to run that script without `sudo`, correct?
If we're just running a small purpose specific script just to turn the monitor on/off with `sudo` and not the whole mirror I think that should be ok...

**Comment by justbill2020** [comment]
there isn't... but its just that script running sudo...
