### ISSUE TITLE
Smart mirror doesn't detect my voice

### ISSUE THREAD

**Issue by kbeaux** [evancohen/smart-mirror#460]
Hi,

i'm trying to install smart mirror on my RP3 and everythings seems to work except that the smart mirror never detect my voice (Or detect my voice but didn't do anything :p).
I tryed to run rec test.wav and it worked pretty well.
I verified that my projectId was good.
I set the language at fr-FR and tryed to say "Que puis-je dire?", "What can i say", ... but the smart-mirror never do anything at all.

When i try to run npm start dev or npm sonus i have this : 
![image](https://cloud.githubusercontent.com/assets/7451998/20861301/c377b220-b98c-11e6-9fdd-0452540456c1.png)

Someone can help me plz ?
(Sorry for my english)

**Comment by evancohen** [comment]
It seems that you haven't run the full install. If it's just a problem with Snowboy then you can `npm install snowboy`. If similar module errors persist then you should try `npm install`, which will install all of the dependencies.

**Comment by kbeaux** [comment]
Hi,

i tried the both commands and i still have the same error message with Cannot find module 'sonus'.
Do you have another idea ? 

Thx.

**Comment by evancohen** [comment]
If you run `npm install sonus --verbose` do you get any kind of error?

**Comment by kbeaux** [comment]
Hi,

yes i have these errors : 

```
16850 verbose stack Error: grpc@0.15.0 install: `node-pre-gyp install --fallback-to-build`
16850 verbose stack Exit status 1
16850 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
16850 verbose stack     at emitTwo (events.js:106:13)
16850 verbose stack     at EventEmitter.emit (events.js:191:7)
16850 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
16850 verbose stack     at emitTwo (events.js:106:13)
16850 verbose stack     at ChildProcess.emit (events.js:191:7)
16850 verbose stack     at maybeClose (internal/child_process.js:885:16)
16850 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
16851 verbose pkgid grpc@0.15.0
16852 verbose cwd /home/pi/smart-mirror
16853 error Linux 4.4.32-v7+
16854 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sonus" "--verbose"
16855 error node v7.2.0
16856 error npm  v4.0.3
16857 error code ELIFECYCLE
16858 error grpc@0.15.0 install: `node-pre-gyp install --fallback-to-build`
16858 error Exit status 1
16859 error Failed at the grpc@0.15.0 install script 'node-pre-gyp install --fallback-to-build'.
16859 error Make sure you have the latest version of node.js and npm installed.
16859 error If you do, this is most likely a problem with the grpc package,
16859 error not with npm itself.
16859 error Tell the author that this fails on your system:
16859 error     node-pre-gyp install --fallback-to-build
16859 error You can get information on how to open an issue for this project with:
16859 error     npm bugs grpc
16859 error Or if that isn't available, you can get their info via:
16859 error     npm owner ls grpc
16859 error There is likely additional logging output above.
16860 verbose exit [ 1, true ]

```

**Comment by justbill2020** [comment]
i looks like you're using node vs 7.2.0 please downgrade to node version 6.9.1 and then try `npm install` again

**Comment by kbeaux** [comment]
I downgrade my node version to 6.9.1 and did npm install and now it says that i can't find module '/home/pi/smart-mirror/node_modules/grpc/src/node/extension_binary/grpc_node.node.

![image](https://cloud.githubusercontent.com/assets/7451998/20916688/440002ec-bb8d-11e6-8040-e3be1ee06ccf.png)

**Comment by kbeaux** [comment]
I did npm install grpc and i think everything is good now

**Comment by justbill2020** [comment]
if everything is good @kbeaux will you please close this issue... thank you...
