### ISSUE TITLE
ERROR e:6571)

### ISSUE THREAD

**Issue by XPMCoding** [evancohen/smart-mirror#462]
ERROR e:6571) UnhandledPromiseRejectionWarning: unhandled promise rejection (rejection id: 1) Error: stdout maxBuffer exceeded

**Comment by justbill2020** [comment]
this appears to be a sonus bug... sonus@#22

**Comment by evancohen** [comment]
Should be fixed in the latest version of Sonus. We'll probably want to patch the min version, but any *new* installation of the mirror should have any issues with this.

**Comment by justbill2020** [comment]
@evancohen I think the `package.json` file is set to use a specific release...

**Comment by evancohen** [comment]
Yuuuup! That's my bad. I'll fix that right now.

**Comment by evancohen** [comment]
Patched in `dev` and in `master` 🚀
