### ISSUE TITLE
White Screen - HTML Error

### ISSUE THREAD

**Issue by anbuford** [evancohen/smart-mirror#463]
I have executed all commands. I even erased Raspbian image and reinstalled everything to be sure. I updated config setting (expect Bing, lastFm, fitBit). I completed Javascript Linter. 

### Expected Behavior
Smart Mirror executed 

### Current Behavior
White screen with broken HTML 

### Possible Solution
errors in HTML?

### Steps to Reproduce (for bugs)
1. update config.js 
2. command npm start
3. white screen with html error 
4. Error:
   ERROR le.js:471 
       throw err; 
       ^

Error: Cannot find module 'sonus'
   at Function.Module._resolveFilename (module.js:469:15) 
.....

### Context

![image](https://cloud.githubusercontent.com/assets/11401555/20903298/cb975d02-bb08-11e6-9c46-021d8a788db7.png)

### Your Environment
Raspberry Pi 3, node.js 6.9.1
Raspbian

**Comment by justbill2020** [comment]
can you attach the `config.js` file and then from the `smart-mirror` folder run `npm ls`

**Comment by anbuford** [comment]
@justbill2020 you bet...

[config.js.txt](https://github.com/evancohen/smart-mirror/files/632353/config.js.txt)

smart-mirror@0.0.6 /home/pi/smart-mirror
├── UNMET DEPENDENCY annyang@^2.6.0
├─┬ electron@1.4.10
│ ├─┬ electron-download@3.0.1
│ │ ├─┬ debug@2.3.3
│ │ │ └── ms@0.7.2
│ │ ├─┬ fs-extra@0.30.0
│ │ │ ├── graceful-fs@4.1.11
│ │ │ ├── jsonfile@2.4.0
│ │ │ ├── klaw@1.3.1
│ │ │ ├── path-is-absolute@1.0.1
│ │ │ └─┬ rimraf@2.5.4
│ │ │   └─┬ glob@7.1.1
│ │ │     ├── fs.realpath@1.0.0
│ │ │     ├─┬ inflight@1.0.6
│ │ │     │ └── wrappy@1.0.2
│ │ │     ├─┬ minimatch@3.0.3
│ │ │     │ └─┬ brace-expansion@1.1.6
│ │ │     │   ├── balanced-match@0.4.2
│ │ │     │   └── concat-map@0.0.1
│ │ │     └── once@1.4.0
│ │ ├── home-path@1.0.3
│ │ ├── minimist@1.2.0
│ │ ├─┬ nugget@2.0.1
│ │ │ ├─┬ pretty-bytes@1.0.4
│ │ │ │ ├── get-stdin@4.0.1
│ │ │ │ └─┬ meow@3.7.0
│ │ │ │   ├─┬ camelcase-keys@2.1.0
│ │ │ │   │ └── camelcase@2.1.1
│ │ │ │   ├── decamelize@1.2.0
│ │ │ │   ├─┬ loud-rejection@1.6.0
│ │ │ │   │ ├─┬ currently-unhandled@0.4.1
│ │ │ │   │ │ └── array-find-index@1.0.2
│ │ │ │   │ └── signal-exit@3.0.2
│ │ │ │   ├── map-obj@1.0.1
│ │ │ │   ├─┬ normalize-package-data@2.3.5
│ │ │ │   │ ├── hosted-git-info@2.1.5
│ │ │ │   │ ├─┬ is-builtin-module@1.0.0
│ │ │ │   │ │ └── builtin-modules@1.1.1
│ │ │ │   │ └─┬ validate-npm-package-license@3.0.1
│ │ │ │   │   ├─┬ spdx-correct@1.0.2
│ │ │ │   │   │ └── spdx-license-ids@1.2.2
│ │ │ │   │   └── spdx-expression-parse@1.0.4
│ │ │ │   ├── object-assign@4.1.0
│ │ │ │   ├─┬ read-pkg-up@1.0.1
│ │ │ │   │ ├── find-up@1.1.2
│ │ │ │   │ └─┬ read-pkg@1.1.0
│ │ │ │   │   ├─┬ load-json-file@1.1.0
│ │ │ │   │   │ ├─┬ parse-json@2.2.0
│ │ │ │   │   │ │ └─┬ error-ex@1.3.0
│ │ │ │   │   │ │   └── is-arrayish@0.2.1
│ │ │ │   │   │ ├── pify@2.3.0
│ │ │ │   │   │ └─┬ strip-bom@2.0.0
│ │ │ │   │   │   └── is-utf8@0.2.1
│ │ │ │   │   └── path-type@1.1.0
│ │ │ │   ├─┬ redent@1.0.0
│ │ │ │   │ ├─┬ indent-string@2.1.0
│ │ │ │   │ │ └─┬ repeating@2.0.1
│ │ │ │   │ │   └── is-finite@1.0.2
│ │ │ │   │ └── strip-indent@1.0.1
│ │ │ │   └── trim-newlines@1.0.0
│ │ │ ├─┬ progress-stream@1.2.0
│ │ │ │ ├── speedometer@0.1.4
│ │ │ │ └─┬ through2@0.2.3
│ │ │ │   ├─┬ readable-stream@1.1.14
│ │ │ │   │ └── isarray@0.0.1
│ │ │ │   └─┬ xtend@2.1.2
│ │ │ │     └── object-keys@0.4.0
│ │ │ ├─┬ request@2.79.0
│ │ │ │ ├── aws-sign2@0.6.0
│ │ │ │ ├── aws4@1.5.0
│ │ │ │ ├── caseless@0.11.0
│ │ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ │ └── delayed-stream@1.0.0
│ │ │ │ ├── extend@3.0.0
│ │ │ │ ├── forever-agent@0.6.1
│ │ │ │ ├─┬ form-data@2.1.2
│ │ │ │ │ └── asynckit@0.4.0
│ │ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ │ ├─┬ chalk@1.1.3
│ │ │ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ │ │ ├── has-ansi@2.0.0
│ │ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ │ ├─┬ commander@2.9.0
│ │ │ │ │ │ └── graceful-readlink@1.0.1
│ │ │ │ │ └─┬ is-my-json-valid@2.15.0
│ │ │ │ │   ├── generate-function@2.0.0
│ │ │ │ │   ├─┬ generate-object-property@1.2.0
│ │ │ │ │   │ └── is-property@1.0.2
│ │ │ │ │   ├── jsonpointer@4.0.0
│ │ │ │ │   └── xtend@4.0.1
│ │ │ │ ├─┬ hawk@3.1.3
│ │ │ │ │ ├── boom@2.10.1
│ │ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ │ ├── hoek@2.16.3
│ │ │ │ │ └── sntp@1.0.9
│ │ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ │ ├─┬ jsprim@1.3.1
│ │ │ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ │ └── verror@1.3.6
│ │ │ │ │ └─┬ sshpk@1.10.1
│ │ │ │ │   ├── asn1@0.2.3
│ │ │ │ │   ├── assert-plus@1.0.0
│ │ │ │ │   ├── bcrypt-pbkdf@1.0.0
│ │ │ │ │   ├─┬ dashdash@1.14.1
│ │ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │ │   ├── ecc-jsbn@0.1.1
│ │ │ │ │   ├─┬ getpass@0.1.6
│ │ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │ │   ├── jodid25519@1.0.2
│ │ │ │ │   ├── jsbn@0.1.0
│ │ │ │ │   └── tweetnacl@0.14.4
│ │ │ │ ├── is-typedarray@1.0.0
│ │ │ │ ├── isstream@0.1.2
│ │ │ │ ├── json-stringify-safe@5.0.1
│ │ │ │ ├─┬ mime-types@2.1.13
│ │ │ │ │ └── mime-db@1.25.0
│ │ │ │ ├── oauth-sign@0.8.2
│ │ │ │ ├── qs@6.3.0
│ │ │ │ ├── stringstream@0.0.5
│ │ │ │ ├─┬ tough-cookie@2.3.2
│ │ │ │ │ └── punycode@1.4.1
│ │ │ │ ├── tunnel-agent@0.4.3
│ │ │ │ └── uuid@3.0.1
│ │ │ ├─┬ single-line-log@1.1.2
│ │ │ │ └─┬ string-width@1.0.2
│ │ │ │   ├── code-point-at@1.1.0
│ │ │ │   ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │   │ └── number-is-nan@1.0.1
│ │ │ │   └─┬ strip-ansi@3.0.1
│ │ │ │     └── ansi-regex@2.0.0
│ │ │ └── throttleit@0.0.2
│ │ ├─┬ path-exists@2.1.0
│ │ │ └─┬ pinkie-promise@2.0.1
│ │ │   └── pinkie@2.0.4
│ │ ├─┬ rc@1.1.6
│ │ │ ├── deep-extend@0.4.1
│ │ │ ├── ini@1.3.4
│ │ │ └── strip-json-comments@1.0.4
│ │ ├── semver@5.3.0
│ │ └─┬ sumchecker@1.2.0
│ │   └── es6-promise@3.3.1
│ └─┬ extract-zip@1.5.0
│   ├─┬ concat-stream@1.5.0
│   │ ├── inherits@2.0.3
│   │ ├─┬ readable-stream@2.0.6
│   │ │ ├── core-util-is@1.0.2
│   │ │ ├── isarray@1.0.0
│   │ │ ├── process-nextick-args@1.0.7
│   │ │ ├── string_decoder@0.10.31
│   │ │ └── util-deprecate@1.0.2
│   │ └── typedarray@0.0.6
│   ├── debug@0.7.4
│   ├─┬ mkdirp@0.5.0
│   │ └── minimist@0.0.8
│   └─┬ yauzl@2.4.1
│     └─┬ fd-slicer@1.0.1
│       └── pend@1.2.0
├── UNMET DEPENDENCY electron-json-storage@2.0.0
├── electron-prebuilt@1.4.10
├── UNMET DEPENDENCY express@^4.13.4
├── UNMET DEPENDENCY fitbit-oauth2@0.0.1
├── UNMET DEPENDENCY hyperion-client@1.0.3
└── UNMET DEPENDENCY sonus@0.1.0

npm ERR! missing: annyang@^2.6.0, required by smart-mirror@0.0.6
npm ERR! missing: electron-json-storage@2.0.0, required by smart-mirror@0.0.6
npm ERR! missing: express@^4.13.4, required by smart-mirror@0.0.6
npm ERR! missing: fitbit-oauth2@0.0.1, required by smart-mirror@0.0.6
npm ERR! missing: hyperion-client@1.0.3, required by smart-mirror@0.0.6
npm ERR! missing: sonus@0.1.0, required by smart-mirror@0.0.6

**Comment by justbill2020** [comment]
config looks good... 

but i think that this is the issue... you're missing dependencies... 

`npm ERR! missing: annyang@^2.6.0, required by smart-mirror@0.0.6
npm ERR! missing: electron-json-storage@2.0.0, required by smart-mirror@0.0.6
npm ERR! missing: express@^4.13.4, required by smart-mirror@0.0.6
npm ERR! missing: fitbit-oauth2@0.0.1, required by smart-mirror@0.0.6
npm ERR! missing: hyperion-client@1.0.3, required by smart-mirror@0.0.6
npm ERR! missing: sonus@0.1.0, required by smart-mirror@0.0.6`

please go to the `smart-mirror` folder and run

`git pull && npm install` and let us know the results...

**Comment by anbuford** [comment]
@justbill2020 If we were at a bar right now, I'd buy you 2 beers. Thank you so much...

![image](https://cloud.githubusercontent.com/assets/11401555/20907585/291158ca-bb1d-11e6-8c48-bd48c2816c32.png)

**Comment by justbill2020** [comment]
sweet deal... happy to help. As you continue make sure to follow the docs.smart-mirror.io it can get tricky.
