### ISSUE TITLE
Questions for implementing new features

### ISSUE THREAD

**Issue by kbeaux** [evancohen/smart-mirror#465]
Hi,
I want to try to add some commands for domoticz because domoticz works pretty well with many things like z-wave and enocean wich is an alternative to philips hue and it works  with REST API and json.
But i'm not pretty sure to understand everythings to implement for sending "orders", can someone correct me or tell me if i'm right.

In controller.js i have to add an "addCommand" like this for example: 
```
addCommand('domoticz_turn_off_lights', function () {
                console.debug("Turn off all the lights in the house");
                $scope.domoticz= DomoticzService.postTurnOffLights();
                $scope.focus = "domoticz";
            });
```
then build an domoticz.js in the services and do everything i want in this js.
With the scope.focus and css i can show what i want on the screen.

Did i miss something or not ?
Thanks.

**Comment by kurtdb** [comment]
Did you translate the domoticz_turn_off_lights in the translation files? This is just a placeholder: the text you have to say will be in the en.json in the locales-directory. (or in your native language if the file is present)

**Comment by kbeaux** [comment]
I don't really begin all the work, for the moment i just look all the api documentation of domoticz but yes i saw all the /locales files to implement but i forget to speak about them ^^.
Except that, all is good ?

**Comment by justbill2020** [comment]
Then is you want to create a PR to merge what you've done you would do it against the dev branch.
