### ISSUE TITLE
Error is thrown after spoken keyword is recognized

### ISSUE THREAD

**Issue by slgoodson** [evancohen/smart-mirror#468]
### Expected Behavior
Smart mirror should respond to the command after the white bar appears following a keyword recognition.

### Current Behavior
Currently, I say 'Smart Mirror' and, while the white bar appears, terminal shows the following error immediately after. If I follow this keyword by 'What Can I Say?' nothing happens. No matter what, the white bar never goes away and commands never work.
```
ERROR  error:Error: invalid_grant

ERROR 2 02:41:05.543075371    3975 plugin_credentials.c:67]    Getting metadata from plugin failed with error: invalid_grant
E1212 02:41:05.543226569    3975 client_auth_filter.c:93]    Client side authentication failure: invalid_grant

```

@justbill2020 tried to help me solve this so he used my config file and keyfile.json and it worked fine for him.

### Your Environment

* Environment name: Raspberry Pi 3  
* Operating System: Raspbian GNU/Linux 8 (jessie)
* Node Version: 6.9.2
* npm Version: 3.10.9

**Comment by slgoodson** [comment]
My Raspberry Pi is having problems setting the date and time correctly, and that was the cause of this issue. The API request fails since the system clock is out of sync.

After I manually set the date and time it worked fine. I will still need to find a way to keep the time from resetting after reboots, though.

Related article that helped me figure this out here: https://groups.google.com/forum/#!topic/google-doubleclick-for-publishers-api/ogoaTEIJeCI

**Comment by evancohen** [comment]
Glad you were able to sort this out yourself. We should probably add this to the documentation, I've created an issue there.
