### ISSUE TITLE
Reminders list fails to populate text

### ISSUE THREAD

**Issue by jgummersall** [evancohen/smart-mirror#469]
![img_5719](https://cloud.githubusercontent.com/assets/19269741/21122061/48a6c146-c08d-11e6-8c42-15e964a8cabf.JPG)
### Expected Behavior
It should populate a list of reminders from voice-to-text for the user to see.

### Current Behavior
The list that i am getting is just bullet points, it represents the number of reminders I make but there are no words following the bullet points. It is just black.

### Possible Solution
I have tried change the CSS and looked at it as far as I understand the directory and cant figure out why it is blank, I don't think it is the color of the text, but I am not ruling that out, since it would be the easiest fix.

### Steps to Reproduce (for bugs)

1.Tell the mirror "remind me to.. (anything)
2.bullet points are populated but no text.
3.
4.

### Context
Just want it to be fully functional with simple reminders so I can say something in the morning and check it when I get home from work.

### Your Environment
* Raspberry Pi 3 model B
* Operating System Raspbian (jessie)

**Comment by jgummersall** [comment]
![img_5719](https://cloud.githubusercontent.com/assets/19269741/21122061/48a6c146-c08d-11e6-8c42-15e964a8cabf.JPG)

**Comment by jgummersall** [comment]
the photo shows the bullet points.

**Comment by justbill2020** [comment]
@jgummersall please check out http://feathub.com/evancohen/smart-mirror if you haven't, to up-vote (or down vote) feature requests... i think there's some in there about todoist and what not...

**Comment by evancohen** [comment]
Fix available with remote work.

**Comment by justbill2020** [comment]
fix is now in master... @jgummersall please confirm this is now working for you.

**Comment by justbill2020** [comment]
@jgummersall is this now resolved?

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
The fix for this is in `master`. Should be working fine now :)
