### ISSUE TITLE
 Failed at the snowboy@1.1.0 preinstall script 'npm install node-pre-gyp

### ISSUE THREAD

**Issue by prashanth57** [evancohen/smart-mirror#470]
when i first try to to setup this smart mirror  it shows 
npm WARN deprecated node-uuid@1.4.7: use uuid module instead and check your nodjs version 
then i reinstalled nodejs and npm and try it again but it shows following erros

###[log.txt](https://github.com/evancohen/smart-mirror/files/648794/log.txt)

#### Failed at the snowboy@1.1.0 preinstall script 'npm install node-pre-gyp

#npm WARN deprecated node-uuid@1.4.7: use uuid module instead

###  Environment
npm ERR! Linux 4.4.0-51-generic ubuntu 64 bit
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

can you explain me how to solve this errors.

**Comment by justbill2020** [comment]
please upgrade node to 6.9.2... this should solve the issue... please report back the result... Based on ubuntu 64 bit you should use the 64 bit download below...

[32 bit Node DL](https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x86.tar.xz)
[64 bit Node DL](https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.xz)

Again please report back on whether this resolved your issue and if so close out this issue and let us know. Thank you.

**Comment by prashanth57** [comment]
how can i configure this source code in my Ubuntu machine their is no configure file for source code .....can you tell me how to compile this source code....
thanks for your reply

**Comment by justbill2020** [comment]
@evancohen keep me honest here...

you should be able to ignore these errors because there's a fall back to a precompiled file for your platform if compiling fails...

**Comment by justbill2020** [comment]
@evancohen  ❗️ ❗️ ❗️

**Comment by prashanth57** [comment]
thanks man it work for me...
i installed latest version of node.js 6.9.3 from source code .i download the source code from the node.js website
now smart mirror runs on my machine......

**Comment by prashanth57** [comment]
![screenshot from 2017-01-04 14-11-46](https://cloud.githubusercontent.com/assets/21117577/21636236/d537da44-d287-11e6-944e-754ab5b0b48b.png)

**Comment by justbill2020** [comment]
Per comment that this is now working, I'm closing this issue...

@prashanth57  if you're still having issues please comment on this issue and we can reopen..
