### ISSUE TITLE
Document: YouTube preview image loads, but video never starts

### ISSUE THREAD

**Issue by slgoodson** [evancohen/smart-mirror#471]
### Expected Behavior
Video should buffer and then play.

### Current Behavior
After saying "smart mirror show me how to tie a bow tie" the image preview for the video loads. After the loading cog spins for a while, it then displays the message "If playback doesn't begin shortly, try restarting your device." and the video never loads.

![video](https://cloud.githubusercontent.com/assets/16243710/21161267/e36cf088-c155-11e6-9f0e-91eb974b08be.png)

### Steps to Reproduce (for bugs)

1. Say "smart mirror ... show me how to tie a bow-tie" on a raspberry pi 3 running raspbian jessie.

### Context
No videos play at all. It's not just the bow-tie.

### Your Environment
- Environment name: Raspberry Pi 3
- Operating System: Raspbian GNU/Linux 8 (jessie)
- Node Version: 6.9.2
- npm Version: 3.10.9

**Comment by justbill2020** [comment]
@slgoodson please git pull and attempt this again...

**Comment by Fijvect** [comment]
Tried out the latest commit by @evancohen but it sadly didn't seem to fix it

**Comment by Fijvect** [comment]
will try git pull first, instead of manually changing the 3 lines

**Comment by Fijvect** [comment]
@evancohen After the latest git pull, I'm getting these errors now (also, youtube is still doing the same thing sadly):

I get these errors in the terminal:
```
pi@raspberrypi:~/smart-mirror $ npm start

> smart-mirror@0.0.7 start /home/pi/smart-mirror
> electron main.js 


> smart-mirror@0.0.7 motion /home/pi/smart-mirror
> sudo node motion.js


ERROR me/pi/smart-mirror/motion.js:6
  throw "Configuration Error! See: https://docs.smart-mirror.io/docs/configure_the_mirror.html#motion";
  ^
Configuration Error! See: https://docs.smart-mirror.io/docs/configure_the_mirror.html#motion

ERROR 
ERROR 
ERROR ! Linux 4.4.34-v7+

ERROR ERR! argv "/usr/bin/nodejs" "/home/pi/smart-mirror/node_modules/.bin/npm" "run" "motion"
npm ERR! node
ERROR 9.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

ERROR ERR! smart-mirror@0.0.7 motion: `sudo node motion.js`
npm ERR! Exit status 1
npm ERR! 
npm
ERROR ! Failed at the smart-mirror@0.0.7 motion script 'sudo node motion.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm
ERROR ! Tell the author that this fails on your system:
npm ERR!     sudo node motion.js
npm ERR! You can get information on how to open an issue for this project with:
npm 
ERROR      npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

ERROR 
ERROR ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
```

And this is the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/pi/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/pi
7 error Linux 4.4.21-v7+
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
9 error node v6.9.1
10 error npm  v3.10.8
11 error path /home/pi/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]
```

**Comment by slgoodson** [comment]
Didn't fix it for me either, sadly!

**Comment by justbill2020** [comment]
@fijvect you have to update config.js... you're missing the motion element

**Comment by justbill2020** [comment]
You also need to do `npm install` after `git pull`

**Comment by slgoodson** [comment]
Mine is throwing errors too, @justbill2020 
Did npm install , added motion element, and set it to false (Disabled).

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/home/pi/smart-mirror/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'motion' ]
2 info using npm@3.10.10
3 info using node@v6.9.2
4 verbose run-script [ 'premotion', 'motion', 'postmotion' ]
5 info lifecycle smart-mirror@0.0.7~premotion: smart-mirror@0.0.7
6 silly lifecycle smart-mirror@0.0.7~premotion: no script for premotion, continuing
7 info lifecycle smart-mirror@0.0.7~motion: smart-mirror@0.0.7
8 verbose lifecycle smart-mirror@0.0.7~motion: unsafe-perm in lifecycle true
9 verbose lifecycle smart-mirror@0.0.7~motion: PATH: /home/pi/smart-mirror/node_modules/npm/bin/node-gyp-bin:/home/pi/smart-mirror/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/smart-mirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle smart-mirror@0.0.7~motion: CWD: /home/pi/smart-mirror
11 silly lifecycle smart-mirror@0.0.7~motion: Args: [ '-c', 'sudo node motion.js' ]
12 silly lifecycle smart-mirror@0.0.7~motion: Returned: code: 1  signal: null
13 info lifecycle smart-mirror@0.0.7~motion: Failed to exec motion script
14 verbose stack Error: smart-mirror@0.0.7 motion: `sudo node motion.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/pi/smart-mirror/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/pi/smart-mirror/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid smart-mirror@0.0.7
16 verbose cwd /home/pi/smart-mirror
17 error Linux 4.4.34-v7+
18 error argv "/usr/bin/nodejs" "/home/pi/smart-mirror/node_modules/.bin/npm" "run" "motion"
19 error node v6.9.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error smart-mirror@0.0.7 motion: `sudo node motion.js`
22 error Exit status 1
23 error Failed at the smart-mirror@0.0.7 motion script 'sudo node motion.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the smart-mirror package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     sudo node motion.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs smart-mirror
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls smart-mirror
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by justbill2020** [comment]
thanks for reminding me... i need to test the final fix for this so evan can patch it on dev and master

**Comment by wuppi83** [comment]
Do you use audio over HDMI ?!

I have had the same problem ... paste

`pcm.!default {
  type asym
   playback.pcm {
     type plug
     # This is your output device (In this case AUX out on the Pi)
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     # This is your input device (it may be different from what is seen here)
     slave.pcm "hw:1,0"
   }
}`

with nano ~/.asoundrc .. but do not change  slave.pcm "hw:0,0" to  slave.pcm "hw:0,1"

after that

amixer cset numid=3 2

and it schould be work over hdmi ;0)

**Comment by slgoodson** [comment]
👍 👍 👍 💯 
@wuppi83 you're the best!! Now YouTube plays fine! Do you know what the heck was causing this to only affect audio/YouTube inside of smart-mirror? I followed the guide on audio setup and the HDMI output worked fine playing YouTube videos directly from Chromium. Weird!

**Comment by justbill2020** [comment]
haven't heard a response in over 7 days. I'm closing this issue...

@slgoodson  if you're still having issues please comment on this issue and we can reopen..

**Comment by akfritz** [comment]
I seem to be having this problem as well, did a git pull &  npm install and everything updated fine, but still having this same issue. Tried the Wuppi83 audio configuration suggestion but no change there either. Noticed chromium YouTube has no sound either, SoundCloud works fine though.

**Comment by justbill2020** [comment]
This is working on mine... however i still can't stop video even with volume on speakers down

**Comment by DannyLuu** [comment]
I'm actually experiencing this in dev. The image loads but doesn't play.

**Comment by justbill2020** [comment]
@DannyLuu do `amixer cset numid=3 2` for hdmi and should fix it

**Comment by DannyLuu** [comment]
Hey Bill,

I have already configured my sound manually prior to this, but I will give
it a go once more tonight.

Thanks!

**Comment by DannyLuu** [comment]
@wuppi83 solution worked

**Comment by evancohen** [comment]
Re-purposing this issue to make sure we include this in the documentation. Thanks @wuppi83!

**Comment by justbill2020** [comment]
@evancohen so are we saying that the .asoundrc file's playback.pcm should always be: 
```
playback.pcm 
{ 
type plug 
slave.pcm "hw:0,0" 
} 
```
even if its going out the HDMI and to force it out using the `amixer` command as the new norm?

**Comment by evancohen** [comment]
Yeah, I guess that's the approach we'll have to take. Pretty bizarre behavior.

**Comment by justbill2020** [comment]
this is handled in the new docs yet to be released...

**Comment by ragsmax** [comment]
Am facing the same issue YouTube only loads preview images..the video does not load

**Comment by evancohen** [comment]
Have you tried the solution described in this thread?
