### ISSUE TITLE
No further command recognition after the KeyWord

### ISSUE THREAD

**Issue by derweba** [evancohen/smart-mirror#472]
Hey there,

my issue is more a question...

If i say my KeyWord, the small white bar in the bottom of the screen appear, but it isn't detecting any commands. I think this is probably a error with the Google Cloud Speech configuration, but i am not sure, so has anybody a tip to solve this problem, or to see if my configuration of the smart mirror is correct, especially the configuration with the Google Cloud Speech?

**Comment by justbill2020** [comment]
the most common issue is not enabling billing in google cloud platform...

**Comment by derweba** [comment]
Ok thanks for the fast answer, i will try it and comment if it solved my issue.

**Comment by derweba** [comment]
Thank you very much, this solved my problem. It was just my fault, I thoght it would work without enabling billing in the google cloud platform.

But maybe you make it in the documentation a bit bigger or something like that so that this fault isn't coming up in the future.

**Comment by justbill2020** [comment]
That's a great suggestion. I'm glad yo ugot it working. I'll close this issue now.
