### ISSUE TITLE
Holiday Improvments

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#475]
### Overview
We'll be putting in some time over the holidays to do:
 - [x] Refactor
 - [x] Remote Config UI
 - [x] Bugfixes
 - [ ] Client side analytics
 - [ ] Auto-update
 - [ ] Bonus: Announcements on the mirror (Updates etc.)

**Comment by Fijvect** [comment]
Awesome!!!
And "Thank You", btw! For putting in all this time to the community you've made.

**Comment by justbill2020** [comment]
@evancohen we're 2 for 6 right now...

**Comment by evancohen** [comment]
Sometimes it's better to be overly ambitious! I think the changes we have made are going to be really impact (and we'll continue to work on the outstanding items in this new year)

**Comment by justbill2020** [comment]
We did well... this is being closed out thanks to PR #500 we'll pick up where we left off next week...
