### ISSUE TITLE
Create mobile configuration agent

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#48]
There needs to be a way to better input configuration info into the mirror. Hosting a local Node server with an HTML page that would let you control temp units, time format, service keys, updates, etc. would be a great way to solve that problem.

**Comment by gothmate** [comment]
That would be amazing to final users, particularly if they are not developers...

**Comment by cybertza** [comment]
So besides the standard accessing via an website to change settings, i was thinking along the idea of an USB drive, that if it contained a file like getconfig, an process that monitors storage would push the required files to the flash drive: like the boot/config.txt a system overview, like ip and what ever and so forth, but also allow you to drop a file on there like updateconfig.txt, and that would push all the settings one could ask for to whereever, like an ssid, or an ip config, or the boot config file, even thou web config is nice, one may not always be in a position to know what the ip is without adding an keyboard/mouse, also you cant set the web, if you don't have connection to wi-fi and so forth, so besides maybe using the bluetooth of the device and an phone app as an alternative, but USB functionality with slideshows/music could also be great. just a few ideas

**Comment by evancohen** [comment]
I have an architecture diagram for how a mirror<=>server handshake would work so that you wouldn't need to know the IP of your PI (you can just scan a QR code on the screen with your phone). Not quite ready to share it though. I think we are still a ways off from landing this because of the substantial amount of work involved, but i do have a plan to get us there...

1) Begin using Grant to obtain OAuth tokens on https://config.smart-mirror.io (this domain does not exist yet). Users will have to create their own service keys. This is so we can support FitBit in a more performant way, but it also gives us the opportunity to integrate with a bunch of services that we couldn't today.
2) Start using smart-mirror service keys to make people's lives easier. Retain the option to use your own keys.
3) Using `wss://` implement a client server handshake to establish a mirror<=>server connection for updating config values. This piece of work is heavier, and there are still some unanswered questions:

- How do we keep user data secure? (Config values only live on the mirror, which only sends the server a list of priorities it already has - not the value of those properties).
- How do we update the config when people upgrade the mirror and the syntax has changed? (No idea, yet)
- Lots more details I haven't thought about

4) Make it super easy for people to update the mirror to the latest stable version via the remote configuration agent or the mirror itself (via voice command).

Like I said, this is a long term plan and everything is subject to change...

:rocket:

**Comment by justbill2020** [comment]
@evancohen for now i labeled this as in progress and next rather than suggestion... this seems to be on our hit list right now...
