### ISSUE TITLE
angular.js TypeError: Cannot read property

### ISSUE THREAD

**Issue by dcvonb** [evancohen/smart-mirror#480]
Hi,

I've been working on adding traffic map support to the smart mirror. To do this I am using the Bing Maps API. I can ask the smart mirror to show traffic and it will return a static map with traffic in my area. I also wanted to be able to ask it to show traffic in different locations or zoom in and out. The problem is I cannot get it to zoom in or out unless the map URL is using the location coordinates. I've tried following [Microsoft's instructions](https://msdn.microsoft.com/en-us/library/ff701724.aspx) for adding zoom (using zoomLevel=15 or lvl=15), but it doesn't work with a static map. For example, I doesn't matter what the zoomLevel is set with this URL, it will always show the same area:
`http://dev.virtualearth.net/REST/V1/Imagery/Map/Road/Seattle%20Washington?mapLayer=TrafficFlow&mapSize=990,1200&zoomLevel=15&key=Bing_Map_API_Key`

But if I use the location coordinates, zoom can be set:
`http://dev.virtualearth.net/REST/V1/Imagery/Map/Road/47.605893,-122.334950/14?mapLayer=TrafficFlow&mapSize=1200,1200&key=Bing_Map_API_Key`

The easiest way to get the coordinates seems to be using this Google Maps API:
`$http.get("https://maps.googleapis.com/maps/api/geocode/json?address=" + local)`

This returns a JSON file similar to the one Evan uses to get the users geolocation, but the lat and lng coords are located at "results.geometry.location.lat" and "results.geometry.location.lng" instead of "location.lat" and "location.lng". I added the below code to the 'geolocation.js' and when I ask the smart mirror to "show traffic in Seattle Washington" I get an angular error.
Code:
```
	service.getTrafficLocation = function(local) {
	    console.log("In getTrafficlocation-geolocation.js");
	    var trafficMapArea = {} ;
	    $http.get("https://maps.googleapis.com/maps/api/geocode/json?address=" + local).then(
                function (result) {
	   	    console.log("Get requested location")
                    var coordLocation = angular.fromJson(result).data.location
                    deferred.resolve({ 'coords': { 'latitude': 'results.geometry.location.lat', 'longitude': 'results.geometry.location.lng' } })
		    var lat, lng;
		    console.log("Geo: done getting coords: " + coordLocation.coords.latitude);

		    //Note: This is how Google suggested to parse the JSON file but there is also a angular error at “result.results.length”
		    /*
		    for (var i = 0; i < result.results.length; i++) {
			console.log("getting lat");
			lat = result.results[i].lat ;
			console.log("lat: " + lat) ;
			trafficMapArea[0] = lat ;
		    }
		    for (var j = 0; j < result.results.length; j++) {
			lng = result.results[j].lng ;
			console.log("lng: " + lng) ;
			trafficMapArea[1] = lng ;
		    }
		    */
		    //console.log("coordLocation: " + trafficMapArea[0] + ", " + trafficMapArea[1]) ;
                },
                function (err) {
                    console.debug("Failed to retrieve geolocation.")
                    deferred.reject("Failed to retrieve geolocation.")
                });

	    trafficLoc = deferred.promise ;
	    return deferred.promise ;
	    //return trafficMapArea ;
	}
```
This is the error:
`angular.js:13236 TypeError: Cannot read property 'coords' of undefined
    at geolocation.js:65
    at processQueue (angular.js:15552)
    at angular.js:15568
    at Scope.$eval (angular.js:16820)
    at Scope.$digest (angular.js:16636)
    at Scope.$apply (angular.js:16928)
    at done (angular.js:11266)
    at completeRequest (angular.js:11464)
    at XMLHttpRequest.requestLoaded (angular.js:11405)`

Any help figuring out what is causing the angular error would be greatly appreciated!

**Comment by kurtdb** [comment]
Looks like the response doesn't contain a location. You should try to debug this and look at the full response you're getting from the google maps api.

Try it like this:

```console.log(angular.fromJson(result).data)```

or start your mirror using ```npm start dev``` and look in the network tab for the google maps api call. There you should be able to see the full response you're getting. (or the http error code)

**Comment by dcvonb** [comment]
Thank you for the help!

I looked in the network tab and can see the google api call does return the area I'm looking for, in this case I said Redmond, WA:
<img width="320" alt="screen shot 2016-12-19 at 8 20 34 am" src="https://cloud.githubusercontent.com/assets/24350171/21320003/5699ffde-c5c4-11e6-8912-32b771058ceb.png">

Full Result:
`{results: [{,…}], status: "OK"}
results
:
[{,…}]
0
:
{,…}
address_components
:
[{long_name: "Redmond", short_name: "Redmond", types: ["locality", "political"]},…]
formatted_address
:
"Redmond, WA, USA"
geometry
:
{bounds: {northeast: {lat: 47.7171189, lng: -122.036733},…},…}
bounds
:
{northeast: {lat: 47.7171189, lng: -122.036733},…}
location
:
{lat: 47.6739881, lng: -122.121512}
lat
:
47.6739881
lng
:
-122.121512
location_type
:
"APPROXIMATE"
viewport
:
{northeast: {lat: 47.71239, lng: -122.078646}, southwest: {lat: 47.627058, lng: -122.1645101}}
place_id
:
"ChIJI-4AIK0MkFQR8gTYxeqQA14"
types
:
["locality", "political"]
status
:
"OK" ` 

If I hover over 'lat' in the Network tab with the mouse it shows the location as:
`.results["0"].geometry.location.lat`

I changed the code in the geolocation.js file to:
`deferred.resolve({ 'coords': { 'latitude': 'result.results["0"].geometry.location.lat', 'longitude': 'results["0"].geometry.location.lng' } })
		    var lat, lng;`
And:
`deferred.resolve({ 'coords': { 'latitude': 'result.results[0].geometry.location.lat', 'longitude': 'results[0].geometry.location.lng' } })
		    var lat, lng;`
But still get the same error. I am not sure I am pulling the lat and lng data from the result correctly. Or is it something else? 

Thanks again for the help

**Comment by evancohen** [comment]
I suppose it's possible that their API has changed since this was first implemented. Can you provide a full stack trace for this error? I should have some time in the next few days to investigate.

**Comment by kurtdb** [comment]
You're actually reading the JSON in an incorrect way: you don't have any location element inside a data element.

I'm guessing this should work:

```var coordLocation = angular.fromJson(result).results[0].geometry.location```

**Comment by dcvonb** [comment]
Thanks again for the help!

@kurtdb 
I tried your suggestion and I get this error:
angular.js:13236 TypeError: Cannot read property '0' of undefined
    at geolocation.js:68
    at processQueue (angular.js:15552)
    at angular.js:15568
    at Scope.$eval (angular.js:16820)
    at Scope.$digest (angular.js:16636)
    at Scope.$apply (angular.js:16928)
    at done (angular.js:11266)
    at completeRequest (angular.js:11464)
    at XMLHttpRequest.requestLoaded 
(angular.js:11405)(anonymous function) @ angular.js:13236
(anonymous function) @ angular.js:9965processQueue @ angular.js:15560
(anonymous function) @ angular.js:15568
$eval @ angular.js:16820
$digest @ angular.js:16636
$apply @ angular.js:16928
done @ angular.js:11266
completeRequest @ angular.js:11464
requestLoaded @ angular.js:11405

Also tried this:
`var coordLocation = angular.fromJson(result).results.0.geometry.location`
And the smart mirror crashed right away with this error:
Uncaught SyntaxError: Unexpected number
angular.js:13236 Error: [$injector:unpr] Unknown provider: GeolocationServiceProvider <- GeolocationService <- MirrorCtrl
http://errors.angularjs.org/1.5.0/$injector/unpr?p0=GeolocationServiceProvider%20%3C-%20GeolocationService%20%3C-%20MirrorCtrl
    at angular.js:68
    at angular.js:4397
    at Object.getService [as get] (angular.js:4550)
    at angular.js:4402
    at getService (angular.js:4550)
    at injectionArgs (angular.js:4574)
    at Object.invoke (angular.js:4596)
    at extend.instance (angular.js:9855)
    at nodeLinkFn (angular.js:8927)
    at compositeLinkFn (angular.js:8226)
(anonymous function) @ angular.js:13236

I've never done anything in java script before, so figuring out these little syntax errors has been a little of a pain, so I appreciate your help.

@evancohen 
This is a great project. I've had fun tinkering with it. Thanks for putting it out in the world!
Is the above error information enough or do you need more? I don't know how to pull a full stack trace, so please let me know.

Thank you

**Comment by evancohen** [comment]
Usually `$http()` can figure out the data type. Do you actually need to use `angular.fromJson()`? 
Or can you just use `result.results[0].geometry.location`?

**Comment by justbill2020** [comment]
@dcvonb is this now resolved?

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by dcvonb** [comment]
Hi,

Sorry it took so long to respond. Yes, I was able to resolve this by accessing the location with:
`var coordLocation = angular.fromJson(result).data.results[0].geometry.location ;`

Before I was missing the ".data."

Thanks for the help and quick responses!
