### ISSUE TITLE
How to update to the last version ?

### ISSUE THREAD

**Issue by kbeaux** [evancohen/smart-mirror#485]
Hi, 

i saw there is a new patch (0.0.7), how can i update my project to the last version plz ?
i tried "npm update" but it didn't worked.

Thanks.

**Comment by justbill2020** [comment]
use `git pull && npm install`

**Comment by justbill2020** [comment]
you'll have to update the config.js file to include anything added to config.example.js

**Comment by kbeaux** [comment]
I try it now.

Thanks :).

**Comment by evancohen** [comment]
Thanks @justbill2020 👍 

For future reference: https://docs.smart-mirror.io/docs/updating.html
