### ISSUE TITLE
the mirror is not responding

### ISSUE THREAD

**Issue by abendplays** [evancohen/smart-mirror#490]
Hi guys, 
just having some problems with the speech regognation... 
I used the microphone debug mode, which worked completely fine! When I say anything, nothing happens! 
Tried different sensitivitys and it is not working.. 
Help me pleeeeaaase.. 
![unbenannt](https://cloud.githubusercontent.com/assets/21024367/21455558/7b28aff2-c921-11e6-8f89-36f56846bbcc.png)
Just censored a few things..

**Comment by justbill2020** [comment]
@evancohen is microphone debug really verifying a proper audio config?

**Comment by abendplays** [comment]
yes! I don´t change anything (leave it at default) and when I play it later, everything works just fine!

**Comment by justbill2020** [comment]
@abendplays There's a lot of white space in your keyfile. Also just `./keyfile.json` Is sufficient.

Also, have you configured your `~/.asoundrc` file?

Have you trained your personal model?
Have you enabled billing on the google cloud platform?

**Comment by justbill2020** [comment]
I don't know what you mean by this:
>yes! I don´t change anything (leave it at default) and when I play it later, everything works just fine!

**Comment by abendplays** [comment]
yes, I blanked out a few things with black, that´s why it looks like this.. yes, configurated the asoundrc file and it works either! 
No, I don´t trained the modell and didn´t enable billing, because I don´t want to pay for this project!

**Comment by abendplays** [comment]
I thought about the debug mode! When you start it, it asks you which microphone you want to use, to check if it works. I left it at default and it worked fine!

**Comment by justbill2020** [comment]
Oh right in microphone debug! Yeah I don't know that is testing everything. Which is why I tagged Evan.

**Comment by kurtdb** [comment]
You have to enable billing for the speech recognition to work.

**Comment by abendplays** [comment]
ok... does it really cost anything, or is it free?

**Comment by justbill2020** [comment]
Ok that's why it's not working...

**Comment by abendplays** [comment]
oh ok :D that´s a mad mistake :D 
but does it really cost something? Have you ever paid for it?

**Comment by kurtdb** [comment]
I haven't seen anyone who has gotten a bill for their usage.

**Comment by abendplays** [comment]
ohhhh, ok... thank you :D

**Comment by justbill2020** [comment]
My console doesn't even display API calls currently and I've seen where it says the first 60minutes is included every month

**Comment by abendplays** [comment]
Just activated the billing and it is still not working D: Still having the same problem D:

**Comment by abendplays** [comment]
Which way do I have to change the sensitivity? When I turn it up, might it recognize my voice, or do I have to turn it down?

**Comment by justbill2020** [comment]
the normal sensitivity is 0.5 (50%) maxing at 1 (100%)... from the snowboy docs:

What is detection sensitivity?
> Detection sensitivity controls how sensitive the detection is. It is a value between 0 and 1. Increasing the sensitivity value lead to better detection rate, but also higher false alarm rate. It is an important parameter that you should play with in your actual application.
