### ISSUE TITLE
Displayed Time

### ISSUE THREAD

**Issue by incubik** [evancohen/smart-mirror#491]
The time shown on the screen is 1 hour late. I hardcoded the position to Madrid for weather but time shown still 1 hour behind. Any ideas why this is happening?

**Comment by dnorthrupva** [comment]
Hey @incubik as I mentioned in Gitter, this is actually an issue involving Moment.JS which creates the time. 
`new moment()` is returning the value that the mirror is using to dictate the time.
For the time being please modify your `controller.js` -
`https://github.com/evancohen/smart-mirror/blob/master/js/controller.js#L85-L86` - to include
`$scope.date = new moment().add(1, 'hour');` and you result should be as expected.

I would also go to `https://github.com/moment/moment` and raise an issue with them.

**Comment by justbill2020** [comment]
@incubik is this now resolved?

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by justbill2020** [comment]
haven't heard a response in over 7 days. I'm closing this issue...

@<owner> if you're still having issues please comment on this issue and we can reopen..
