### ISSUE TITLE
Not responding to voice commands

### ISSUE THREAD

**Issue by jgummersall** [evancohen/smart-mirror#494]
I have been running my smart mirror with out any issues but at some time today, unaware of when I wasnt getting any responses from the mirror when I tried to command it to do something. When I closed I noticed in the terminal that I would get this error.
ERROR error:Error: invalid_grant
ERROR 3 22:14:11.831820590 1322 plugin_credentials.c:67] Getting metadata from plugin failed with error : invalid_grant
E1223 22:14:11.831932205 1322 client_auth_filter.c:93] Client side authentication failure: invalid_grant
The only thing I can think of is that since coming back home (I built it in MST and live in PST) the time will not change to PST correctly, when I go to raspi-config and select los angeles it gives my an incorrect time, but that hasnt stopped it from working in since ive been here, looking for any help or thoughts to fix it thanks!

### Expected Behavior
It should respond to the command given like it has in the past.

### Current Behavior
Freezes the mirror

### Possible Solution
Maybe a timezone issue?

### Steps to Reproduce (for bugs)
1.Run npm start
2.say any command
3.mirror freezes
4.exit and get the same error codes

### Context
Just want the mirror to function properly again

### Your Environment
Raspberry Pi 3
Raspbian

**Comment by dnorthrupva** [comment]
#468 Seems to be the same issue you're having. I'm surprised this is related due to it mentioning an invalid_grant. Can you confirm if manually resolving the time differences resolves your issue, as a temp solution?

**Comment by justbill2020** [comment]
@jgummersall can you update if this is in fact a duplicate and the resolution in #468?

**Comment by biophile** [comment]
I have the correct time, but still experience the same issue (white bar won't go away + invalid grant).

**Comment by evancohen** [comment]
The white bar not going away has been fixed in `dev`, so I think this issue is safe to close.
