### ISSUE TITLE
.asoundrc changes after reboot causing errors in console and audio to not work.

### ISSUE THREAD

**Issue by justbill2020** [evancohen/smart-mirror#495]
### Expected Behavior
 

on restart the .asoundrc file remains unchanged

### Current Behavior

before reboot.
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     # This is your output device (In this case AUX out on the Pi)
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     # This is your input device (it may be different from what is seen here)
     slave.pcm "hw:1,0"
   }
}
```
after reboot...
```
pcm.!default {
  type hw
   playback.pcm {
     type hw
     # This is your output device (In this case AUX out on the Pi)
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     # This is your input device (it may be different from what is seen here)
     slave.pcm "hw:1,0"
   }
}
```

Also, this is found in the console after starting smart-mirror

```
ALSA lib pcm_plug.c:1261:(_snd_pcm_plug_open) Unknown field card
ALSA lib pcm_plug.c:1261:(_snd_pcm_plug_open) Unknown field card
```

### Possible Solution

find the source of the change or find a template that will not change and still work with the mirror.

### Steps to Reproduce (for bugs)

1. configure audio 
2. restart pi
3. look at ~/.asoundrc file and see the changes

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4): Raspbery pi 3, node 6.9.2
* Operating System and version (e.g. Raspbian, Ubuntu, OSX): Raspbian Jessie w/Pixel

**Comment by TylerThompson** [comment]
sudo nano /etc/asound.conf

then copy below into file and reboot. should work
pcm.!default {
 type asym
   playback.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
}

**Comment by evancohen** [comment]
@justbill2020 can you confirm @TylerThompson 's fix? I feel like that should work...

**Comment by TylerThompson** [comment]
one minor issue 
 slave.pcm "hw:0,0" should be 0,0 not 1,0 and the last one should be slave.pcm "hw:1,0". I had those backwards. sorry about that

**Comment by justbill2020** [comment]
this is resolved but need a pr for audio config script... if there's no comments (has signs `#`) in `.asoundrc` this works fine

**Comment by justbill2020** [comment]
updated script
