### ISSUE TITLE
node-pre-gyp ERR! - Pre-built binaries not found

### ISSUE THREAD

**Issue by justkrisp** [evancohen/smart-mirror#504]
After smart mirror and NPM install on
Raspberry Pi 3, node.js 6.9.2):
Raspbian

node-pre-gyp ERR! Tried to download: http://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.15.0/node-v48-linus-arm.tar.gz
node-pre gyp ERR! Pre-built binaries not found for grpc@0.15.0 and node@6.9.2 (node-v48 ABI) (Falling back to source compile with node-gyp)

**Comment by justbill2020** [comment]
there should be a npm-debug.log file can you please post it here?

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
This is expected. They don't provide prebuilt binaries so we are forced to compile them on-device. I could theoretically fork grpc and create ARM builds.

I know this is feasible, but not if it's practical. Another solution would be to ask them to publish their binaries for ARM.

**Comment by justbill2020** [comment]
This should now be resolved as a non-issue?

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.
