### ISSUE TITLE
Greetings are not shown on the screen. 

### ISSUE THREAD

**Issue by ukiras123** [evancohen/smart-mirror#508]
When I do npm start, it starts without any error but on the screen, I do not see the greetings that I had configured. Why ? Is something broken?
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by justbill2020** [comment]
@evancohen i am fixing this on dev.... will need to port it to master after

**Comment by ukiras123** [comment]
@justbill2020 @evancohen  I see that documentation for scrobbler, maker etc are not updated. Is there anyway I can help documenting these things, or can inform you guys if something needs to be updated/added? For example: few functionality are missing (or may be I didn't c): Once user asked for timer, there is no way to clear timer from screen, same thing for Show xkcd and few other commands.

**Comment by justbill2020** [comment]
@ukiras123 that's awesome... We would love help with stuff like this. can you please create separate issues for these those... there's already an issue for some of it so we don't have duplicates.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
Fixed in 2188fcb 🚀
