### ISSUE TITLE
Light settings : Hue type in selector is not saved

### ISSUE THREAD

**Issue by shoten** [evancohen/smart-mirror#519]
On the remoteUI, in the Light Settings the "Hue" type in the selector is not saved after submission

### Expected Behavior
 

Change the select from "hyperion" to "hue" save and use the miroir to light up the room 

### Current Behavior

On the remoteUI, in the Light Settings I set the Hue ip and hue username  
in the setup part I add a name "Room", a target "Item1"  select the type "Hue" (and not "hyperion") and the id to "1"  
I save
I submit the changes the type is set to "hyperion" (and in the config file too)
the light doesn't work

### Possible Solution

Save the "hue" type in the file
(I actually did that manually)

### Steps to Reproduce (for bugs)

1. go to the remoteUI params
2. add a light with "hue" type
3. save
4. reopen the light settings

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
Rapsberry 3, ps EYE, node v6.9.2 , npm v3.10.9
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):
Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux

**Comment by justbill2020** [comment]
@dannyluu is working on this... total rockstar on this challenging task!
