### ISSUE TITLE
Config not saving due error in Motion settings

### ISSUE THREAD

**Issue by ruudmens** [evancohen/smart-mirror#524]
New install, remote config will not save, no error displayed. Checked the console output, noticed a validation error:

`message
:
"Instance is not a required type"
schemaUri
:
"urn:uuid:03c5b456-5e19-4612-a370-123501e967a3#/properties/motion"
`

Display mode is set on "disabled", changing it reveals the motion setting and an inline error message.

Removed the motion setting field with the Chrome element inspector, was able to save the config. The remote config is working fine now, motion settings is not throwing an error anymore.

### Expected Behavior
Validation error should be visible, even if the field is hidden.

### Environment
Raspberry Pi 3 model B, node 6.9.4, Raspbian

**Comment by evancohen** [comment]
Hey @ruudmens, thanks for reporting this! Sounds like a bug, maybe @justbill2020 knows what's going on here?

**Comment by kyl3d3nt0n** [comment]
Deleting the motion config settings in config.json and config.default.json seemed to fix this issue for me. A temporary solution to at least get the mirror running.

But I'm also having trouble with the remote when adding greetings....I have at least 10 for each time of day and they keep getting deleted and only one for each time of day remains. I had to manually put them in the config.json file and if I try to add more and click submit they get overwritten again.

 Also light config is doing something similar, I have all my light types as 'hue', but they keep getting changed to 'hyperion' when making changes in the remote config. 

Just speculating....but I think it has something to do with them both have select boxes and the default for greeting is 'random' and the default for light is 'hyperion'.

**Comment by evancohen** [comment]
Thanks for posting that work-around. It seems that the over arching issue here is that the config is not saving properly. 

Either way, there are some issues here.

**Comment by justbill2020** [comment]
I have the push the fix for this one

**Comment by evancohen** [comment]
So it should be working in `dev` then? Did your fix also address the issues saving light types?

**Comment by justbill2020** [comment]
No...

**Comment by justbill2020** [comment]
fixed in #529 and merged with dev...
