### ISSUE TITLE
'Go home' command does not clear previous content

### ISSUE THREAD

**Issue by cwelinder** [evancohen/smart-mirror#526]
Issuing the voice-command "Go home" is recognised and printed, but content does not clear from screen. When calling new content it stacks from the bottom.
Various commands does not work, not sure if related though.

<img width="1440" alt="screen shot 2017-01-11 at 12 29 34" src="https://cloud.githubusercontent.com/assets/22574410/21847041/1101f588-d7fa-11e6-802b-ef46321e97f4.png">
<img width="1440" alt="screen shot 2017-01-10 at 12 43 18" src="https://cloud.githubusercontent.com/assets/22574410/21847040/11017964-d7fa-11e6-9d55-2d3dbc92793a.png">

Running updated master branch.

**Comment by evancohen** [comment]
This is fixed in the `dev` branch already with: d83ceeec3f21f5274a1b124551b3d69976ec9549

Leaving this open for visibility. I'll try to push an update tonight.
