### ISSUE TITLE
On a 19" screen (and I would assume smaller), whenever it is Wednesday, the "y" is just slightly off screen. This causes a scroll bar to appear on the bottom of the mirror.

### ISSUE THREAD

**Issue by MattTheGamer** [evancohen/smart-mirror#527]
On a 1600x900 resolution. It could just be because my monitor can't go any higher.

### Expected Behavior
 

I think it should auto-format a bit better. But I doubt many people use a screen this small, so it wasn't accounted for.

### Current Behavior

It does not format the String for day, at least on Wednesday. the "y" is off screen causing a scroll bar to appear.

### Steps to Reproduce (for bugs)

1. Be Wednesday
2. Have a <19" (1600x900) monitor

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
We should switch to using [relative viewport lengths](https://drafts.csswg.org/css-values-3/#viewport-relative-lengths) for all of our fonts and sizes (that way the mirror can scale on different resolutions).

**Comment by DannyLuu** [comment]
Please assign this to me.

**Comment by DannyLuu** [comment]
Hi @MattTheGamer could you post a screenshot of the bug?

I tried to replicate the issue but was unable to.
<img width="880" alt="screen shot 2017-01-11 at 8 54 09 pm" src="https://cloud.githubusercontent.com/assets/3261578/21874022/63ee8964-d840-11e6-8c7c-f3f994f5a766.png">

**Comment by MattTheGamer** [comment]
Drat, I forgot to mention I've been using the icesnow? (forgot the name) format because the messages always appearrd the center of the screen. Here you are http://imgur.com/1nSYZ6N

**Comment by evancohen** [comment]
Ooh, yeah. icesnow isn't activly maintained, maybe the original contributor @redbeed could take a look?

**Comment by evancohen** [comment]
@MattTheGamer you should just adjust the font-size value for that text. Feel free to send a PR with your changes to the `dev` branch if you do.
