### ISSUE TITLE
dependencies install fail

### ISSUE THREAD

**Issue by pilkingtonm01** [evancohen/smart-mirror#528]
When using the script install I get a message that the dependencies can not be installed
raspberry pi3

starting from completely fresh raspian jessie install with full pixel.
everything has been updated and upgraded before running install script.

Installing smart-mirror dependencies...
This may take a while. Go grab a beer :)
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> snowboy@1.1.0 preinstall /home/pi/smart-mirror/node_modules/.staging/snowboy-ae1258f3
> npm install node-pre-gyp

Unable to install dependencies :( 
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by justbill2020** [comment]
@pilkingtonm01 please update you're issue according to the template... we need to know what version of raspbian you're using? did you install using NOOBS?

**Comment by pilkingtonm01** [comment]
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

did not install w/noobs.
fresh flash from https://www.raspberrypi.org/downloads/raspbian/  Jessie w/pixel
flashed sd, enabled wifi, updated and upgraded os then ran the above script.

thanks for your help

**Comment by evancohen** [comment]
I've heard this from a few people recently and I'm going to investigate it tonight.

**Comment by pilkingtonm01** [comment]
Update, I used a fresh download of the Raspbian image and got it working. Now I'm battling some mic issues but I'll put more time into the mic issue before I post about it. And if needed I will post about it in its own thread.

**Comment by evancohen** [comment]
Ah, in that case I'll close this issue out and assume that we're ok.
