### ISSUE TITLE
What about GTFS?

### ISSUE THREAD

**Issue by bastian-w** [evancohen/smart-mirror#53]
I think i will implement: 
https://www.npmjs.com/package/gtfs-realtime-bindings

or does anyone  already did it?

**Comment by evancohen** [comment]
I don't think anyone is working on this - what GTFS sources are you thinking of adding?

**Comment by bastian-w** [comment]
First of all my local one (VRS/Cologne, Germany)

**Comment by evancohen** [comment]
I don't see why that couldn't work :) Let me know how it goes. If you have any issues along the way feel free to reopen this and ask.
