### ISSUE TITLE
Documentation - Broken Link

### ISSUE THREAD

**Issue by DannyLuu** [evancohen/smart-mirror#530]
Visit -> https://docs.smart-mirror.io/docs/development_and_contributing.html
Under the section Project Structure, the anchor link to Electron leads to a 404.

The link in question is: https://docs.smart-mirror.io/docs/electron.atom.io

### Expected Behavior
Link to the correct resource

### Current Behavior
Nothing happens when clicked. If opened in a new tab a 404 page is returned.

### Steps to Reproduce (for bugs)
1. Visit https://docs.smart-mirror.io/docs/development_and_contributing.html
2. Look at the section: Project Structure
3. Click on Electron OR Open link in a new tab/window.

**Comment by evancohen** [comment]
You are absolutely correct. Fixed in https://github.com/evancohen/docs.smart-mirror.io/commit/997689751cbece9dfc4ffcd4bfb23b04f2fdb8e2
