### ISSUE TITLE
Adding support for the more languages for remote.

### ISSUE THREAD

**Issue by taran27** [evancohen/smart-mirror#544]
current version supports english only it should have a option for selecting other languages too.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment
 -Raspberry Pi 3, node.js 5.4
-Operating System and version. Raspbian, OSX)

**Comment by justbill2020** [comment]
@taran27 are you asking to translate the page or for speak functionallity to use multiple languages??

**Comment by evancohen** [comment]
@justbill2020 I asked him to create this. Right now we only do English for the STT. It'd be pretty easy to pull the correct language from the config, we just don't do that today.

**Comment by justbill2020** [comment]
@taran27 @evancohen  this is addressed in #546

**Comment by evancohen** [comment]
Fixed in `dev`
