### ISSUE TITLE
No action?

### ISSUE THREAD

**Issue by awolberg** [evancohen/smart-mirror#547]
When I say things the mirror shows at the bottom what words are said, but no actions happen. I am using a raspberry pi 3 and believe I have updated versions of everything. Thanks for the help!

**Comment by justbill2020** [comment]
this appears to be a duplicate... #525 

I'm closing this ticket... please refer to the previously entered issue.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.
