### ISSUE TITLE
Google speech stream error 

### ISSUE THREAD

**Issue by muhammadsamir11** [evancohen/smart-mirror#554]
### Expected Behavior
App should react on Hotword or other audio commands.

### Current Behavior
StreamingError: Error: stream was destroyed

### Steps to Reproduce (for bugs)
No result data. I need to repeat Hotword again to start.

### Your Environment
* Node.js 5.4
* OSX

**Comment by evancohen** [comment]
I created a clean install and was unable to reproduce this error. Can you give any more context? Can you try running the audio detection on its own to see if you get a more descriptive error: `npm run sonus`

Have you:
- Enabled billing for speech recognition
- Downloaded and configured the keyfile

**Comment by muhammadsamir11** [comment]
Yes i enabled billing and i am using configured json keyfile, 
Actually when i say the hotword it works and speech recognition works fine but if i didn't say anything for 10 mins then i say the hotword it works but the speech recognition show this error "stream was destroyed".

**Comment by evancohen** [comment]
Ah, ok. Now those are some repro steps I can work with!

**Comment by muhammadsamir11** [comment]
Thanks

**Comment by evancohen** [comment]
Hey @muhammadsamir11 still haven't had the chance to look at this yet, hoping I can take the chance to look tonight. Can you give more specific steps for reproduction?

**Comment by evancohen** [comment]
I think I may have a fix for you. Can you checkout the dev branch and update sonus to `0.1.5`. Details here: #553

**Comment by muhammadsamir11** [comment]
Thanks alot

**Comment by justbill2020** [comment]
haven't heard a response in over 14 days. I'm closing this issue...

@muhammadsamir11  if you're still having issues please comment on this issue and we can reopen..
