### ISSUE TITLE
Error in saving greetings

### ISSUE THREAD

**Issue by tnrplaya** [evancohen/smart-mirror#561]
### Expected Behavior
Expected behaivor is that custom greetings are saved indefinately when entered via the config UI. 

### Current Behavior
Saving custom greetings (many, ~15-25), some (between 1-all) get deleted after multiple saves of the congif.ui

### Possible Solution
Bill Martin suspects there is an issue with the jsonform. 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context
cannot save multiple custom greetings. would like to save 50+ and have them cycle through the day or with each wake command... however currently they are deleted with some number of saves from the config ui

### Your Environment
Raspberry Pi 3, full Rasbian install. fresh script install as of 1.18.17, all dependancies up to date per my knowledge.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
@justbill2020 Do you know what is up here?

**Comment by justbill2020** [comment]
Not yet...
