### ISSUE TITLE
RSS feeds not working

### ISSUE THREAD

**Issue by tgeci** [evancohen/smart-mirror#569]
I am trying to get RSS Feeds running, but they're not working with my setup. 

### Expected Behavior
Displaying RSS Feeds.

### Current Behavior
No RSS News are displayed. 

### Possible Solution
---

### Steps to Reproduce (for bugs)
1. Configure http://www.spiegel.de/politik/index.rss or https://www.heise.de/security/news/news-atom.xml as Feed in Remote UI.
2. Reload with Remote UI or Restart with kill & npm.

### Context
Error: 
`
TypeError: Cannot read property 'feed' of undefined
    at cycleNews (controller.js:48)
    at callback (angular.js:12053)
    at Scope.$eval (angular.js:16820)
    at Scope.$digest (angular.js:16636)
    at Scope.$apply (angular.js:16928)
    at tick (angular.js:12043)
`

### Your Environment
* Raspberry Pi 3, Node v6.9.4, NPM v3.10.10
* Raspbian with PIXEL Environment
* smart-mirror.git -> Current dev Branch

**Comment by justbill2020** [comment]
I will look into this over the next day or two

**Comment by justbill2020** [comment]
can you pull latest dev... also post here what your current commit is by doing

```javascript
git rev-parse HEAD
```

the error refers to line 48 above but it doesn't seem right when i look at the code.


Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by justbill2020** [comment]
haven't heard a response in over 14 days. I'm closing this issue...

@tgeci  if you're still having issues please comment on this issue and we can reopen..

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.
