### ISSUE TITLE
Integrating a streaming service

### ISSUE THREAD

**Issue by SenadM** [evancohen/smart-mirror#57]
Could be Spotify, Apple music etc,

"Play the top ten list"
"Play this song"

Etc.  It could be great.

**Comment by evancohen** [comment]
I'd rather have the mirror integrate with some kind of speaker _thing_ thank have it play music itself. Something like Sonos or Chromecast maybe?

**Comment by StevenTLBF** [comment]
I thought the same thing. If the board could connect wirelessly through bluetooth to a bluetooth enabled speaker, it could be phenomenal. "Play *insert song name here*" and bam... thoughts? "Now playing *insert song/playlist/album name here" could be displayed somewhere on the mirror.

**Comment by evancohen** [comment]
@StevenTLBF totally agreed (although dealing with Bluetooth would be a bit of a pain). If you want to take a stab at it let me know. With a slight modification I could modify the YouTube functionality to also play music and just use the 3.5mm aux out on the pi, but I think some kind of streaming solution would be better.

**Comment by SenadM** [comment]
@evancohen the youtube idea is also good, but I think you would have a problem playing playlists? I don't want to search a new song every time the last one finish, so playlists are the way to go, I think.

**Comment by evancohen** [comment]
@SenadM not necessarily... The YouTube API does let you [search for playlists](https://developers.google.com/youtube/v3/docs/playlists/list) and the iFrame in which the YouTube video is embedded fires a `onPlayerStateChange` event so you could queue up the next video once one is finished. This is all in theory of course... But if that works you could have "play next track" and/or "skip track" commands.

There is also message posting to the iFrame that you could use to play/pause the video...
``` javascript
iframe.postMessage('{"event":"command","func":"pauseVideo","args":""}', '*');
```

I haven't tried it yet, but it should work :shipit:

**Comment by SenadM** [comment]
Well if it is possible to search for playlists also, then Youtube would be a great start as you already did implement it. And later, maybe other developers could add other alternatives.

**Comment by chr1s1** [comment]
+1 for sonos integration :)

**Comment by jaaplallie** [comment]
spotify isn't optimal to work with atm...
the api isn't 'good' enough to work with (play songs etc.)...
it mostly supports data fetching, not 'controlling' spotify.
Maybe someone has a hacky way to get it to work but it is definitely not normally supported right now

**Comment by evancohen** [comment]
Yeah, there really isn't a good way to do Spotify. SoundCloud works pretty well thoigh. Both YouTube and SoundCloud are on the search branch (which is now horribly out of date). It's probubly worth the time to rewrite. Maybe I can look at doing that tonight.

**Comment by kurtdb** [comment]
@SenadM is the soundcloud and youtube integration enough for you? Or do you see another possible integration point?

**Comment by evancohen** [comment]
@chr1s1 It seems that you can get Sonos (and Chromecast!) integration with PulseAudio, which is already a dependency of the mirror: https://github.com/masmu/pulseaudio-dlna/issues/32

I'm going to add https://github.com/masmu/pulseaudio-dlna to the smart-mirror documentation because that is **totally awesome**.

**Comment by chr1s1** [comment]
Awesome! Thanks a lot! @evancohen

**Comment by justbill2020** [comment]
pandora.... would be awesome!!

**Comment by justbill2020** [comment]
@evancohen should this be labeled as outdated? this would require pulseaudio which we've found causes issues with smart-mirror...

**Comment by evancohen** [comment]
Yeah, this is a bit out of date. It would be nice to support this functionality at some point, but it won't be via PulseAudio. There may be some Node libs that we can look at for DLNA streaming.

**Comment by justbill2020** [comment]
i'm going to leave it... i don't think anyone will install pulseaudio based on this issue...

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+13

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
