### ISSUE TITLE
No YouTube on mirror

### ISSUE THREAD

**Issue by janner6** [evancohen/smart-mirror#572]
I've been slowly working on my smart mirror and it's coming together nicely. One problem I have though is that YouTube just does nothing when called on. I got my API key from the developer website and have input it into the mirror config screen. Can anyone give me some pointers as to where to look next please?
I've also not been able to find the .js file for YouTube? There's no section for YouTube in plugins?
Any help would be appreciated.

**Comment by DannyLuu** [comment]
@janner6 is your youtube video loading but not playing? If so there is another issue opened for this with a solution inside.

You need to execute the video command by saying "Show me <some type of video>".

**Comment by janner6** [comment]
No it's not doing anything at all

**Comment by janner6** [comment]
I got it I had a wrong character in the API key. All sorted now
