### ISSUE TITLE
LIFX support

### ISSUE THREAD

**Issue by JaxonWright** [evancohen/smart-mirror#579]
### Expected Behavior
Should work similarly to the hue integration, but use LIFX bulbs instead

### Current Behavior
See above

### Possible Solution
https://api.developer.lifx.com/

**Comment by justbill2020** [comment]
This isn't an bug or issue this is a feature request... 

please confirm this isn't already listed and if it is please upvote it, if it isn't already listed please add this to feathub... http://feathub.com/evancohen/smart-mirror 

thank you

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
@JaxonWright there's a stale lifx branch that you might take a look at. I created the prototype but I don't have LIFX bulbs so I couldn't test. If you take that code, bring it up to date, and send a PR we'd gladly accept!
