### ISSUE TITLE
mirror on laptop

### ISSUE THREAD

**Issue by Shubham0209** [evancohen/smart-mirror#58]
My question might appear quite awkward but its because i dont anything about web development.

Thus i want to know, how can i use/run this project on my chrome browser(laptop) in windows without using raspberry.

Why dont you guys make a webpage/webapp like this http://vann.io/graveyard/smrt/# , it would get quite easy for newbies like me.

**Comment by roelofjan-elsinga** [comment]
You can actually run this on Chrome, you'll just have to install Node on your laptop. You can get it from:  https://nodejs.org/en/ Afterwards you'll need to run "npm install" and when that is finished, you'll need to run "npm start".

**Comment by evancohen** [comment]
The short answer is that you don't want to run this in Chrome/Chromium, that's how it used to work but I moved to Electron - there are a lot of things that Electron can do that you can't do in Chrome.

@roelofjan-elsinga is right. The code is completely self contained and can run on _pretty much_ any platform, just install Node on your laptop, clone the code, and you'll be off to the races!
