### ISSUE TITLE
npm start "config error: config.js not found

### ISSUE THREAD

**Issue by almeidag** [evancohen/smart-mirror#580]
npm start config error: `config.js` not found

when i run the smart mirror for the first time i got an error: 'config.js' not found. 

i did everything as the tutorial, havent skipped any step.

**Comment by justbill2020** [comment]
@almeidag I can't reproduce this error... config.js has not been a part of the mirror since the beginning of this year... can you share the full stack of the error to help... 

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by DannyLuu** [comment]
@almeidag you need to setup your configurations within the remote in order for the config.js to be created.

Then your error will disappear along with the QR code that is displayed.

**Comment by evancohen** [comment]
You might want to try updating, seems like you may have some out-of-date code

**Comment by sniparsdogg** [comment]
although, if you have created already the config and it still doen't work, try getting it checked with a javascript linter. eslint will do the job.

**Comment by justbill2020** [comment]
if you're using the config ui the config will not be corrupt in anyway and should need to go through eslint... if you're editing the file yourself that kinda is a very very bad idea

**Comment by sniparsdogg** [comment]
it depends, if the person configured incorrectly their config in the config ui (for example, adding quotes on a link in the calendar) that could still create some errors

**Comment by justbill2020** [comment]
hey @sniparsdogg have you jumped on  [discord chat](https://discord.gg/EMb4ynW) yet?

**Comment by sniparsdogg** [comment]
Not yet as I'm at work. I just saw your waffle.io link on the page when I was on the bus and decided to take a look. But will do.

**Comment by justbill2020** [comment]
we barely use waffle for anything at this point... and really don't maintain it...

discord is where we do the majority of the support of the mirror... jump on get verified and i'll add you to the contributors role... you're obviously eager, willing, and able to help support people who have issues so lets make it official and help some smart-mirror users...

**Comment by sniparsdogg** [comment]
Fair enough! :)

2017-02-10 16:30 GMT+00:00 Bill Martin <notifications@github.com>:

**Comment by justbill2020** [comment]
haven't heard a response in over 7 days. I'm closing this issue...

@almeidag if you're still having issues please comment on this issue and we can reopen..
