### ISSUE TITLE
Sonus not running and I'm a newb

### ISSUE THREAD

**Issue by DurzoBlint13** [evancohen/smart-mirror#581]
Hello All,

I saw the smart mirror project a few months ago and decided to give it a try using a Raspberry Pi3 Model B. I should preface all this by stating that I am a programming newb. I literally have no idea what I'm doing and have no experience programming, but luckily you all have created some awesome step-by-step tutorials. 

So, I believe my issue is with Sonus, and by extension, my mic. Whenever I try to test my mic, I get the following errors:

pi@raspberrypi:~/smart-mirror $ sudo npm run sonus

> smart-mirror@0.0.10 sonus /home/pi/smart-mirror
> node sonus.js

module.js:471
    throw err;
    ^

Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:5:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "sonus"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.10 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.10 sonus script 'node sonus.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node sonus.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

Additional Info: 

I installed Smart-Mirror and dependencies using the one-line script. 

I've tried re-installing them separately, but that does not fix the issue (but I could be doing this wrong). I've even tried a complete re-install of everything.

I've been using the instructions at https://docs.smart-mirror.io/

PLEASE HELP!!! I've tried troubleshooting this for hours and I believe it's my last hurdle. Thanks!!!!

**Comment by justbill2020** [comment]
so a lot of issues here... starting with using `SUDO` now i can't tell how and where you used it but a good start is with this which you posted above...
> pi@raspberrypi:~/smart-mirror $ sudo npm run sonus

now having said that i would start off either renaming your smart-mirror folder or deleting it... 

then run the script again without the sudo command... Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time. You should go there and post in the support channel when you finish rerunning the install script... I can help you from there... however i'm only around for about 30 more minutes today...

**Comment by DurzoBlint13** [comment]
Alright. Thanks for all the help. I deleted the smart-mirror folder completely and then re-installed it using the one line script. I then redownloaded my speech.json file and snowboy model from google cloud platform and snowboy. After that everything worked fine. I must have messed something up during the configuration process the first time. I'll admit I got confused as to which terminal I should be using, the raspberry pi main terminal or the smart-mirror root terminal.

**Comment by justbill2020** [comment]
@DurzoBlint13 what do you mean by "raspberry pi main terminal" or "smart-mirror root terminal" i would love to get more details from you to see if there's anyway to improve the docs and help others

i'm in the process of revamping the docs right now

**Comment by sniparsdogg** [comment]
If that error happens again, try running "DISPLAY=:0 npm start" (without quotes) instead. That's a common problem and this command usually fixes it.

**Comment by justbill2020** [comment]
that's a great point if you're trying to start the mirror via ssh however running via ssh is not a great idea considering that electron has issues installing via ssh...

**Comment by justbill2020** [comment]
well i mean... what was up that caused you to have to add that command that I've never had to while running on the pi directly... if there's an issue with the mirror or the docs i would love to update it to fix the issue... or if there was something you did to your pi config that caused it that's helpful as well so we can better identify when they might need to add the display command...
