### ISSUE TITLE
Error in installation on non PIXEL 

### ISSUE THREAD

**Issue by philipp1987** [evancohen/smart-mirror#585]
Hey guys,

I have a project. I want to try combine SmartMirror with Volumio2. I have installed a blank Volumio2 Image and other stuff like GUI. And now the problem... At "npm install" I get a few Errors.  Can someone help me and knows the solution. Would not have a second PI in my project. 

Sorry for my english, I'm from Germany.

Best regards

Philipp

[Neues Textdokument.txt](https://github.com/evancohen/smart-mirror/files/773046/Neues.Textdokument.txt)

**Comment by justbill2020** [comment]
Technically this isn't a supported os... most likely caused by a dependency being incompatible... perhaps @evan can add more to this or help out...

**Comment by evancohen** [comment]
Looks like this is actually an issue with `make`ing the grpc library. Unfortunately the error is pretty non-descript... You should try to `npm install --verbose` to see if you get any more info.

That said, you might be better off filing an issue on the grpc lib.

**Comment by justbill2020** [comment]
Thanks @evancohen I was at whirlyball and couldn't dive to deep on it i glanced at the error log but that was about it...

**Comment by philipp1987** [comment]
Okay.  I have running smart mirror on volumio now. Yeeeeeaaaaah. But now....there is another Problem.  Auto sleep waiting time is on 1 minute. After the Minute smart mirror hide the greeting and calender. What can i do to deactivate the hdmi Signal?

**Comment by evancohen** [comment]
Are you sure it's auto sleep and not the screensaver for volumio?
Also, can you share what you did to get it working?

@justbill2020 can probably tell you how to disable/extend autosleep

**Comment by philipp1987** [comment]
Volumio 2 has a WebUI only. There is no gui over hdmi. I have installed volumio 2 image and follow these instructions. https://github.com/volumio/volumio-plugins/blob/master/plugins/miscellanea/touch_display/install.sh 

Without the /opt/volumiokiosk.sh in the volumio.kiosk.service file. 

Then I have followed your instructions. Install Nodejs, sox unclutter etc. In the smart-mirror folder I have copied a finish smart-mirror content from image. With npm install I get errors anytime.  
And then a big fight with other programs like python, rpi.gpio etc. 
The motion detector also runs. But there is the problem with sleep time. The monitor shows, after the minute, date, time and weather. Calender, rss and greeting disappear.

**Comment by philipp1987** [comment]
Commands for autostart must be in /etc/xdg/openbox/autostart

**Comment by justbill2020** [comment]
i have no way to attempt to reproduce the issue... but sounds like its isolated to this build it doesn't happen on my raspbian or ubuntu build... @philipp1987 what is the last commit on the branch you're using? 

honestly... you're probably having issues with volumio or other installed dependencies that we would have no way to account for... i can only test if it is functioning correctly on the 2 environments i have it set up on over here... if its working as designed there and not working on your build there's a can of worms of potential issues starting with volumio, to the touch display install scripts you ran to any number of other issues... we don't support raspbian lite for these same reasons, its just impossible to ever really get a build like yours to identify where you're having an issue.

**Comment by philipp1987** [comment]
how may I understand that?

**Comment by justbill2020** [comment]
?? what is unclear?

**Comment by justbill2020** [comment]
@philipp1987 why don't you check out the support channel on discord... 
We're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
So it seems like you aren't using Electron, you are using Chromium Kiosk... There are a bunch of things that just won't work with a Chromium Kiosk - you're going to have a **super** tough time getting that to work.

**Comment by philipp1987** [comment]
I have running both programs on same time. But I need a logo from smart-mirror for a bootlogo!

**Comment by justbill2020** [comment]
Look at the readme file... that icon is the only logo

**Comment by philipp1987** [comment]
Which icon?

**Comment by evancohen** [comment]
I think you used to have to recompile the kernel in order to change the boot logo, but now you can just put an image here: `/usr/share/plymouth/themes/pix/splash.png`
