### ISSUE TITLE
White screen on first startup

### ISSUE THREAD

**Issue by KreatixDev** [evancohen/smart-mirror#587]
Did all configuration step by step and when running "npm start", it open electron with a white screen

Running on a brand new Raspberry Pi 3

**Comment by justbill2020** [comment]
Any errors listen in the dev console or terminal? Are you starting using ssh?

Have you joined the discord chat and asked for help there?

**Comment by gnurph69** [comment]
I'm having the same situation, but I figured that's the way it is.  It's not merely a white screen - it has the greeting to be shown and "home.commands" in black in the upper left.  It stays there, I suspect, until npm finishes loading some kind of CSS and can continue formatting the screen/page.

**Comment by evancohen** [comment]
Ah, that means that there's something wrong with your depends. You might want to try running `npm install` again.

**Comment by KreatixDev** [comment]
@justbill2020 nothing in the console. Didn't join the discord chat
@gnurph69 In my case, only white screen, no text anywhere
@evancohen I tried twice, no luck

Another funny thing, in the procedure, there is a line we need to enter : npm run train-model
This line open electron and should go to snowboy website, but in my case, electron was white 

Seems more related with electron than the smart-mirror itself....

Any idea ?

**Comment by KreatixDev** [comment]
I think I just fixed it with an npm update

Will do some test and confirm later

**Comment by KreatixDev** [comment]
Confirmed, now fixed!
