### ISSUE TITLE
Several commands have become unresponsive

### ISSUE THREAD

**Issue by cwelinder** [evancohen/smart-mirror#588]
### Expected Behavior
Voice commands should work as intended

### Current Behavior
Commands starting with "show" have turned unresponsive, with the exception of "show map of..." and "show (video)..."
EDIT: Errors apply to both voice and text commands.

Some of the unresponsive commands produce errors in the console:

_TypeError: Cannot read property 'feed' of null
    at controller.js:11
    at processQueue (angular.js:15552)
    at angular.js:15568
    at Scope.$eval (angular.js:16820)
    at Scope.$digest (angular.js:16636)
    at Scope.$apply (angular.js:16928)
    at done (angular.js:11266)
    at completeRequest (angular.js:11464)
    at angular.js:11374
    at HTMLScriptElement.callback (angular.js:11495)
(anonymous) @ angular.js:13236
(anonymous) @ angular.js:9965
processQueue @ angular.js:15560
(anonymous) @ angular.js:15568
$eval @ angular.js:16820
$digest @ angular.js:16636
$apply @ angular.js:16928
done @ angular.js:11266
completeRequest @ angular.js:11464
(anonymous) @ angular.js:11374
callback @ angular.js:11495_

As a not I should point out that this happened a few weeks ago, and I solved it with a clean install.

### Your Environment
Raspberry Pi 3
Raspbian
Everything updated

**Comment by cwelinder** [comment]
Possibly related, detection of hotword(s) have almost stopped working.
When changing mic sensitivity to 0.6 it reacts to any sound and listens without the use of hotword.
The white bar is up most the time. The box for Continuous is not checked.

After some testing the application crashed and a error was presented.

Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at Socket.<anonymous> (/home/pi/smart-mirror/main.js:93:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)

**Comment by justbill2020** [comment]
This is normal for most when the mic sensitivity is set above .5 as for the rest you skipped the parts of the issue template on steps on how to reproduce the issue... this is not currently happening to my build so I would say it's not a big g in the most current commit of the master branch

**Comment by cwelinder** [comment]
Will update in a day or two.

**Comment by justbill2020** [comment]
haven't heard a response in over 7 days. I'm closing this issue...

@cwelinder  if you're still having issues please comment on this issue and we can reopen..

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by cwelinder** [comment]
Sorry, have been away for a while.
This should partially have been resolved according to #613, will check tonite.
My issues share the same problem description as in #613, but include other commands also.
Will update later, letting you know if this issue should be reopened.
