### ISSUE TITLE
Face Detection!

### ISSUE THREAD

**Issue by Shubham0209** [evancohen/smart-mirror#59]
Wouldn't it be nice that instead of showing a single comment all the time, mirror may show different comments and greet us based on the detected face.

Can you suggest me any method to so.

Moreover i would also like to "HOW TO USE PUSHBULLET API". Basically being a newbie i don't know how and where to add these api code.

please can you tell me about this in detail.

THANKS!!!

**Comment by evancohen** [comment]
I've experimented with face detection in the past, but I haven't pushed it out publicly because there are a number of issues with it. As for PushBullet I haven't completed this integration yet. I'm experimenting with Android devices this week and will probably have PushBullet done in the next couple weeks.

**Comment by andrewda** [comment]
@evancohen You could possibly make a branch with the face detection code implemented. I would love to take a look and see what I can do about contributing!

**Comment by evancohen** [comment]
I'll clean up what I have and do that :)

**Comment by kurtdb** [comment]
What framework did you use? I've been reading up on this and it seems like OpenCV is the framework to use for this?

**Comment by Shubham0209** [comment]
@evancohen how can we integrate webcam to take our picture on command like "click my picture"?

By doing this we can integrate the feature of selfie mirror.

**Comment by missionrulz** [comment]
@Shubham0209, Do you know how ironic that sounds? I can understand the want and need from a technical point of view, but do you really need your picture taken only to be displayed in a screen behind a mirror. It kind of defeats the whole purpose of a mirror.

**Comment by Shubham0209** [comment]
@missionrulz actually it was only step 1.What i was actually thinking was to maybe post those pictures on fb etc or send them to the phone. so the basic idea was to click the picture and share it. I know it sounds weird.lol

**Comment by tomasvr** [comment]
Thats a pretty neat idea! The point is that you would be able to see the full picture you're about to take of yourself through a big mirror. Only placing the camera at the right position seems kind of tricky because it should be at eye height, where the screen is.

**Comment by Shubham0209** [comment]
yeah @tomasvr you feel me right. lol

**Comment by paviro** [comment]
Not all of it is published yet but I started adding facial recognition to another mirror project you could probably use the code as it is right now to get something up and running:
https://github.com/paviro/MagicMirror-Modules

**Comment by kurtdb** [comment]
@paviro how fast is the facial recognition? I don't think the rpi (even v3) is fast enough to do this in a user-friendly way. (e.g. look at the video at https://www.kickstarter.com/projects/1715072587/adept-mirror-smart-mirror?ref=nav_search)

A user won't wait for 5 seconds to see his/her information, they want it now. I've been looking into alternatives, but it seems that the way to go here might be either a cloud hosted service or an expensive camera that can do the facial recognition for you. (although I didn't find any camera's that had an API from which you could stream the information)

**Comment by paviro** [comment]
A few seconds. For me it's fast enough :)

**Comment by cybertza** [comment]
there is a really great idea on the selfie mirror is the 1 picture a day stream, if you captured 1 picture a day of yourself for ever, it would be rather cool, and with an overlay you may be able to calibrate it so that your face is always in the same place, but yea, just interesting.

**Comment by evancohen** [comment]
@cybertza I like the idea! Want to take a shot at it and send a PR?

**Comment by paviro** [comment]
Like the idea! I might add that to my Module someday :)

**Comment by 7h30n3** [comment]
What's the current status of the face recognition feature?

Maybe we could use the face detection (Just "face detected" and "no face detected", no certain faces) as a substitute for the hotword detection.

**Comment by paviro** [comment]
Feel free to port my module to evan's mirror: https://github.com/paviro/MMM-Facial-Recognition

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+35

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
