### ISSUE TITLE
Full List of all Commands possible

### ISSUE THREAD

**Issue by bronco92** [evancohen/smart-mirror#593]
Hi! 

I am really new to this project and just today I got my full setup working. 

Now when I ask my mirror to show me the commands, it can't show the full list. My Screen might just be too small.

Is there any possibility to get a full list of all commands you can use. I would imagine they are in some file on the PI already but can't seem to find it.

Hoping I posted on the right site, I appreciate any help!

Thanks a lot!

**Comment by justbill2020** [comment]
We're looking at ways to better display this... as the project grew it kind of got out of hand for now. 

So currently the best way is to look at the json file for your language in the `app/locales` folder...

**Comment by bronco92** [comment]
Thanks. How about beeing able to scroll the list of commands with commands: scroll up/down?

**Comment by justbill2020** [comment]
Most people don't have a way to do that. And the mirror is technically a dynamic web page but doesn't allow to scroll...
