### ISSUE TITLE
Microphone not picking up. 

### ISSUE THREAD

**Issue by dannymccaslin** [evancohen/smart-mirror#594]
### Expected Behavior
 

I ran through all of the instructions and the smart-mirror starts, but there is no response when I speak into the mic or use the mobile web interface.

### Current Behavior

When I run npm run sonus I get the following error:

```
> smart-mirror@0.0.10 sonus /home/pi/smart-mirror
> node sonus.js

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/pi/smart-mirror/keyfile.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:12:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "sonus"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.10 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.10 sonus script 'node sonus.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node sonus.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
```

### Steps to Reproduce (for bugs)

1.[npm-debug.txt](https://github.com/evancohen/smart-mirror/files/812189/npm-debug.txt)

2.
3.
4.

### Your Environment

Raspberry Pi 3, Raspbian version 8 (Jessie), Node version 6.10

**Comment by justbill2020** [comment]
You're missing the keyfile.json which is downloaded from the google cloud platform ... please refer to https://docs.smart-mirror.io

**Comment by dannymccaslin** [comment]
I went through that step and downloaded the file. Unfortunately I am away
from my house right now but I will output my ~\smart-mirror folder and post
it. Maybe I got the wrong file.

**Comment by justbill2020** [comment]
I'm responding based on the output you sent so two places to check first is the smart mirror folder to see what your keyfile is named and second is to confirm that you entered it correctly in the speech section of the configUI... 

Eitherway the error states the file is not found.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by dannymccaslin** [comment]
My file from Google is called SmartMirror-0263afeedaab.json. I just downloaded it like that from Google. I need to change the name to keyfile.json?

**Comment by dannymccaslin** [comment]
Changed the name of the file and it is now picking up voice and not erroring out, although it's not working quite right either. On to further debugging. Thank you!

**Comment by justbill2020** [comment]
Before you go down the rabbit hole head over to discord and we can help you there in closing this as it's now resolved 

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.
