### ISSUE TITLE
Limiting the number of calendar items to be seen

### ISSUE THREAD

**Issue by danielccm** [evancohen/smart-mirror#60]
It might be good (or necessary!) to limit the number of lines to be used by the calendar to just show the current day... or (as Evan suggested on a chat) a few days max...

**Comment by kurtdb** [comment]
I would make it configurable so that the user can select which option he wants: either see them all or just see them for the coming number of days.

For me for example, there is no use in limiting the number of items.

**Comment by dardub** [comment]
I have this done, but it's based on the new config model. So I'll have to wait until that is merged before the PR.
