### ISSUE TITLE
i can't connect google api 

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#608]
Hello..
i have 2 problems 
first ,
i installed all things.. (raspi3 with smart-mirror)
and i can speck 'waht can i say ' then show command list on the screen of monitor
i cant't see the any event  after i speake 'show map'
 second.. 
i changed language from english to korean on the web(127.0.0.1:8080)
i speaked 'what can i say  by korean' but couldn't see the command list on the monitor

here is my config.json..

  "general": {
    "language": "ko-KR",
    "layout": "main"
  },
  "speech": {
    "keyFilename": "./keyfile.json",
    "hotwords": [
      {
        "keyword": "smart mirror",
        "model": "smart_mirror.pmdl"
      }
    ],
    "sensitivity": "0.5",
    "continuous": false
  },
  "remote": {
    "enabled": true,
    "port": 8080
  },
  "geoPosition": {
    "latitude": "37.2809",
    "longitude": "127.4429"
  },
  "giphy": {
    "key": "dc6zaTOxFJmzC"
  },
  "greeting": {
    "option": "allDay",
    "allDay": [
      "Hi "
    ]
  },
  "forecast": {
    "key": "apikey",
    "units": "auto",
    "refreshInterval": 2
  },
  "autoTimer": {
    "mode": "disabled",
    "autoWake": "07:00:00",
    "autoSleep": 40,
    "wakeCmd": "sudo ./scripts/raspi-monitor.sh on > /dev/null 2>&1",
    "sleepCmd": "sudo ./scripts/raspi-monitor.sh off > /dev/null 2>&1"
  },
  "lastfm": {
    "refreshInterval": 0.6
  },
  "calendar": {
    "icals": [
      "https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics",
      "https://calendar.google.com/calendar/ical/jy2lee%40gmail.com/private-xxxxxx/basic.ics"
    ],
    "maxResults": 9,
    "maxDays": 60,
    "showCalendarNames": true
  },
  "traffic": {
    "refreshInterval": "5"
  },
  "rss": {
    "refreshInterval": 120
  }
}

pls help me .

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by sniparsdogg** [comment]
Hello nevido and welcome to the smart-mirror!
Have you set up the keyfile field on your remote webpage to be the same name as the authentication file that you got from Google?

**Comment by justbill2020** [comment]
Please refer to the docs... you must say the hotword before saying the command...

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by nevido** [comment]
thank you..  i said first hotword ..it was ok
n i saved xxxx.json file from google and renamed keyfile.json   
this file localed root of smart-mirror directory
 this is my issue(1st)
https://www.youtube.com/watch?v=1OPc1jXsn6w

i say show map.. and can see the show map text on the bottom screen
but.. not event on the monitor after said 

(2nd)
i changed language from en-US to ko-KR 
https://www.youtube.com/watch?v=CtlDGGtLNjg
i said waht can i say by Korean //
then i couldn't see the command list on 

if json file is problme.. ( pls tech me.. how can i get it step by step )

**Comment by justbill2020** [comment]
Try "show me a map of ____________" also please note that not all locations are able to use maps.. you also need to get a bing api and enter that in the configUI 

https://github.com/evancohen/smart-mirror/blob/master/app/locales/ko.json
Do these commands look correct?

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by nevido** [comment]
ok justbill2020 .. i will try it after home
T T thank you

**Comment by nevido** [comment]
pls check it!!
i don't know the reason..
my api json file  is bad from google  ?

![aaaaaaa](https://cloud.githubusercontent.com/assets/25813260/23980052/a91d1668-0a40-11e7-804f-e5e23394aa7f.JPG)

**Comment by justbill2020** [comment]
No the google API is working that's not your issue... if the google API did not work you would have nothing but a white bar at the bottom... 

Please visit discord and allow us to help you in real time...

**Comment by nevido** [comment]
i resolved my problem.. first i have poor English so speech api did't reconize my voice well.. it's my opinion
i spoke other command 
for example : show me map -> not working (i think. cause of my poor english  voice)
show me map of _  -> ok
and etc command ->ok
second, i chaged my language of mirror web field  from en-US to ko-KR 
speak hotword - ok    waht can i say by Korean. .then i couldn't show the commnad list on the screen
i gave up this issue .. i speak  other command (show map of _) or etc  by Korean
it's ok.. 
i will study more about these apis
thank you for your help.. ^^
