### ISSUE TITLE
how can i use  responsivevoice ?

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#609]
how can  i use responsivevoice on smart mirror?

i found some information.. about it..

but. i can't understand.. 

pls help me

**Comment by justbill2020** [comment]
Can you say more about this I'm not clear on what you're trying to do or the problem you're trying to solve.

**Comment by nevido** [comment]
want to add ResponsiveVoice

**Comment by justbill2020** [comment]
What does that mean?

**Comment by nevido** [comment]
IF I SAY "SHOW ME A MAP OF SEOUL"  
  AND THEN  
want to listen "this map is Seoul" from computer(raspi with smart mirror)
TTS

**Comment by justbill2020** [comment]
Ok now I understand... please see the discussion in issue #386 and PR #455
