### ISSUE TITLE
can't see the command list when i say "what can i say?" after change language

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#610]
i changed language from en-US to ko-KR on the localhost:8080(mirrro website)
I said "what can i say"  when language mode  en-US   it's ok  can see the command list on the screen

but ko-KR language can't show the list 

other command(ex: show me a map of _  (by Korean)) is good run
only can't see the list when i say  "what can i say"

i told u English mode is ok   (can see list ) 
Koean mode isn't (cann't see list)
it's my problem

thank you

**Comment by justbill2020** [comment]
If it works in english but not in your language please look at the locale file, often times it is incorrect as we rely on that locale's native language speakers within the community to keep the locale files up to date. 

Also, We're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time. Its often easier to solve issues there than it is here with multiple messages and long periods of time between responses here.

**Comment by nevido** [comment]
i changed command text .. and then it's ok thank you ~
