### ISSUE TITLE
[Question] How can i add  new command 

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#612]
i added text  /smart-mirror/app/locales/ko.json and /smart-mirror/app/js/controller.js
// ko.json 
 "test": {
            "text": "테스트",
            "voice": "테스트",
            "description": "태스트."
        },

//controller.js
var functionService = FUNCTIONSERVICE;

  SpeechService.addCommand('test', function() { 
             	functionService.test($scope); 

// functionService  //app/js/function-service.js
var FUNCTIONSERVICE = {

	test : function($scope) {
		console.debug("test...");   // or other scripts 
	    	$scope.focus = "default";
	},
~
~

//index file /smart-mirror/index.html
<script src="app/js/function-service.js"></script>

not working T T  I don't know the reason.. 
do i have to modify another files ?

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
Most likely your controller isn't actually being loaded into the mirror.
Use `ng-controller` to bind your controller to a DOM element.

**Comment by nevido** [comment]
@evancohen  thank you.. i will try it after work.. 
thank you
