### ISSUE TITLE
not working show map voice command

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#613]
### Expected Behavior
 

map.center = "Sinha-ri+Bubal-eup,Icheon-si,Gyeonggi-do";
or 
map.center = "Seattle,WA";

npm start dev 

i command show map  but no action on the screen
console has no error
i changed other word instead of show map
but same result

do i have to text on the web (latitude , longitude) ?

show map of _   is no problem ..
only show map command  has issue(no action)

pls check it

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by hvaddi9** [comment]
in the controller.js of map plugin. 
add the line `Focus.change("map");` in _map_show_ command

**From**
```
// Show map
    SpeechService.addCommand('map_show', function () {
        $scope.map = generateMap();
    });
```
**To**
```
// Show map
    SpeechService.addCommand('map_show', function () {
        $scope.map = generateMap();
        Focus.change("map");
    });
```

That will solve the issue

**Comment by justbill2020** [comment]
awesome!!! creating a patch change for this right now!!! great work, Great catch @hvaddi9

**Comment by justbill2020** [comment]
this has been fixed on dev

**Comment by nevido** [comment]
thank you everyone really thank you @justbill2020  @hvaddi9

**Comment by justbill2020** [comment]
@nevido I'm leaving this open until it's merged into master

**Comment by justbill2020** [comment]
@nevido please stop closing this issue

**Comment by justbill2020** [comment]
this has now been merged to master...

**Comment by cwelinder** [comment]
Great, have had this issue recurring for quite some time. Will update! Thanks.
