### ISSUE TITLE
Weather Forecast is not working

### ISSUE THREAD

**Issue by hvaddi9** [evancohen/smart-mirror#614]
### Expected Behavior
Weather Forecast display
 

### Current Behavior
Weather Forecast suddenly stopped working. It's not displaying anything. I'm getting this error in log
`Error: [$sce:insecurl]  http://errors.angularjs.org/1.6.1/$sce/insecurl?p0=https%3A%2F%2Fapi.forecast.io%2Fforecast%2F_api-key_%2F12.973%2C79.163%3Funits%3Dauto%26lang%3Den%26callback%3DJSON_CALLBACK`
I haven't changed any code
When I open the URL (api.forecast.io/....) in chromium it returns valid json response.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (Raspberry Pi 3, node.js 6.10):
* Operating System and version (Raspbian with Pixel latest):

**Comment by nevido** [comment]
did you change language on the web(hosts:8080)?
if you changed it .. pls check smart-mirror/plugin/weather/controller.js 
and change  &lang = " + " en-US" + "


    weather.get = function () {
        return $http.jsonp('https://api.forecast.io/forecast/' + config.forecast.key + '/' +
            geoposition.coords.latitude + ',' + geoposition.coords.longitude + '?units=' +
            config.forecast.units + "&lang=" + "en-US" + "&callback=JSON_CALLBACK")

**Comment by justbill2020** [comment]
This was resolved in discord...

`in the weather plugin controller.js, I replaced jsonp with get and removed the CALLBACK parameter in the link. It magically worked. I don't know why and how.

I googled JSONP and it said "JSONP (as in "JSON with Padding") is a method commonly used to bypass the cross-domain policies in web browsers". I thought let's try it once and it worked.`

**Comment by hvaddi9** [comment]
Yeah. It's resolved. Thanks (Y)
