### ISSUE TITLE
latest dev branch (3/25/17), calendar service missing definition of RRule (used in parseICal, line 132)

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#615]
unable to process calendar events, 

var RRule = require('rrule').RRule

missing

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by justbill2020** [comment]
this is an issue with the underlying dependency RRule...
I submitted an issue to them.
https://github.com/jakubroztocil/rrule/issues/166

you cannot "require" on client side JS... and rrule is imported on line 92 of index.html as it always has been.

https://github.com/evancohen/smart-mirror/blob/dev/index.html#L92

**Comment by sdetweil** [comment]
cool.. the require works however

**Comment by justbill2020** [comment]
forced rrule 2.1.0 in bower.json on dev and master as of tonight... we'll update it to latest release after they respond to my issue and i confirm it is fixed... running `npm install` will roll back to previous release...
