### ISSUE TITLE
Set weather units to auto for international support

### ISSUE THREAD

**Issue by teemuha** [evancohen/smart-mirror#62]
Shortcut for having full internationalization support for weather units is just to add units=auto GET parameter to forecast.io API call in weather-service.js.  It then selects the relevant units automatically, based on geographic location.

**Comment by evancohen** [comment]
If you send a pull request I'll merge it right away, otherwise it'll be a day or two before it gets checked in with another feature.

**Comment by andrewda** [comment]
#65 will add support for this!

**Comment by teemuha** [comment]
Thanks @andrewda
