### ISSUE TITLE
fitbit info displays even when no API is entered in ConfigUI

### ISSUE THREAD

**Issue by justbill2020** [evancohen/smart-mirror#626]
![mirrorimage](https://cloud.githubusercontent.com/assets/13437861/24467292/929ed366-1479-11e7-85ce-713aba87b32c.png)

### Expected Behavior
 

if fitbit has no api entered the fitbit section should be hidden

### Current Behavior

fitbit isn't hidden

### Possible Solution

have @DannyLuu look at it...

### Steps to Reproduce (for bugs)

1. checkout dev branch
2. don't have fitbit API inserted in config
3. open mirror
4. see shit show up when it ain't supposed to

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):
raspbian/ubuntu
node 6.10

**Comment by evancohen** [comment]
Probably because we use `ng-if` like this: [index.html#L69](https://github.com/evancohen/smart-mirror/blob/master/index.html#L69).

I'm guessing there's a default config value (even if it is empty). We should be looking at another field here (like the token?) to decide when to display Fitbit data.

**Comment by evancohen** [comment]
Made this fix on my phone so someone should test
