### ISSUE TITLE
On Speech Recognition

### ISSUE THREAD

**Issue by jh13626** [evancohen/smart-mirror#627]
Voice recognition is only recognized when the voice recognition is clicked on the remote page when performing Speech Recognition.Next voice recognition must be pressed again when performing the following voice recognition :
Is there a way to allow continuous recognition of voice recognition?

**Comment by justbill2020** [comment]
ok i need to update this to be more clear... voice recognition on the remote has nothing to do with voice recognition on the smart-mirror... please refer to the docs on how to configure voice recognition.

first you'll have to configure your capture device https://docs.smart-mirror.io/docs/configuring-sound.html

then you'll have to configure the voice recognition...
https://docs.smart-mirror.io/docs/configuring_voice.html

there is no continuous voice recognition as that would kill your API requests quota and would cost you a lot of money not to mention send all nearby voice conversations to google...

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by jh13626** [comment]
Thank you. Let me ask you a little more.
Does remote page speech recognition work without sound configuration and voice configuration?
I think I have completed all the configurations for speech recognition. However, if I do not press the Speak button on the remote control page, the Smart Mirror will not respond. Continuous speech recognition, as I say, is speech recognition without touching the Speak button with the mouse.

And let me know if you have the server code for the discord chat.
Thank you.

**Comment by justbill2020** [comment]
What do you mean server code for discord chat?

Yes the remote does not require sound or voice configuration it is done completely different than the smart mirror... 

When you configure the mirror properly you will say the hotword as in "smart-mirror" and then there will be a white bar at the bottom of the screen and then you will say the command... so it goes like this... 

"Smart-mirror" white bar appears "show me how to tie a bow tie" and then YouTube loads with the video...

**Comment by jh13626** [comment]
Thanks to you, speech recognition is well solved. But I have additional questions. Is it possible to run other applications on the Smart Mirror program? For example, can I run a motion recognition program or run a camera application to operate with voice?

**Comment by jh13626** [comment]
@justbill2020 
Thanks to you, speech recognition is well solved. But I have additional questions. Is it possible to run other applications on the Smart Mirror program? For example, can I run a motion recognition program or run a camera application to operate with voice?

**Comment by evancohen** [comment]
@jh13626 Absolutely. Check out the existing motion plugin (or really any plugin for that matter).  
Dev docs: https://docs.smart-mirror.io/docs/development_and_contributing.html

**Comment by jh13626** [comment]
@evancohen  
Hi There is one more thing to ask.
I want to implement the following subway service.(https://github.com/embian-inc/smart-mirror-ko/blob/master/js/subway-service.js)
However, I do not know what path to write the code because the folder structure is different.
First, I created a subway folder in the plugins folder. Help me...

**Comment by aishaamila** [comment]
I cannot use the voice recognition. When i click on voice button on my phone, It says that unsupported on ios/safari but i am using android. Is there anything i need to change ?
