### ISSUE TITLE
2 or more users

### ISSUE THREAD

**Issue by danielccm** [evancohen/smart-mirror#63]
Would be cool to have 2 or more users share the mirror but display different data from different calendars.... Any idea how to implement it?

**Comment by kurtdb** [comment]
There is currently support for adding multiple calendars. It will take all the calendars into consideration and show the next 10 events.

**Comment by evancohen** [comment]
As @kurtdb mentioned you can include multiple calendars. There are a few ongoing efforts around voice and facial recognition that could potentially solve this problem. I'm going to close this issue because it will be addressed by #59
