### ISSUE TITLE
Error: ENOENT: No such file or directory (cannot find my google voice keyfile json file)

### ISSUE THREAD

**Issue by Leonpa** [evancohen/smart-mirror#633]
### Not able to start Sonus
I am experiencing some bugs with the speech recognition. When I had the smart mirror running, everything just worked perfectly fine, except the speech recognition. My microphone was definitely working, so I decided to run sonus with "npm run sonus" but I got an error. Either I am obviously dumb or too unexperienced in programming because I spent the last few hours trying to fix it. Neither a reinstallation nor my own helpless tries to fix it helped. I went through the entire smart-mirror setup process properly, so there shouldn't be anything to worry about. 
### Current Behaviour
Despite setting up everything correctly and having installed the latest node.js and npm, the command npm run sonus gives me this error: 
![img_2511](https://cloud.githubusercontent.com/assets/27236884/24879320/c84246ee-1e36-11e7-880b-42de04372a93.JPG)

![img_2513](https://cloud.githubusercontent.com/assets/27236884/24879579/a624f452-1e37-11e7-8bee-5e544bebc60f.JPG)

Can anybody of you please help me? Thank you very much for your help:)

**Comment by justbill2020** [comment]
First, it is not that you're dumb, and you don't have to be a coder to get this project working... there's like 5 possible issues all of which could be addressed by us adding additional error handling or trying to be more clear in the documentation. Does the mirror start? that's the most important part... the rest is easy to fix... 

The main issue appears to be that it can't open `/smart mirror-a3f4a-c773fe.json`.
it could be one of these issues:
1. the `/` in front of the filename is messing up resolving the path
1. the space between `smart` and `mirror` is messing things up 
1. the case in the settings are different than the filename
1. the filename is spelt wrong
1. a combination of any of the above

our recommendation is to change the filename to `keyfile.json` and change it in the configUI settings as well... and then go from there.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by Leonpa** [comment]
Thank you @justbill2020 for your quick help,  I just changed the `/smart mirror-a3f4a-c773fe.json `to `keyfile.json`. Now everything just works fine and my mirror is fully operable:) 
Also a huge thank you to @evancohen and all the other collaborators on this project for providing this awesome documentation and help, you guys made my dream of an own smart mirror real:)
