### ISSUE TITLE
npm start directory not found

### ISSUE THREAD

**Issue by Mattmildren** [evancohen/smart-mirror#634]
I am trying to run the mirror startup, but after it loads a few files it says start not found.
### Expected Behavior
 
Should start smart mirror 

### Steps to Reproduce (for bugs)

1.Go to terminal 
2. type npm start
3.  (problem occurs here) 
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 2, node.js 5.4): Raspberry Pi 2
* Operating System and version (e.g. Raspbian, Ubuntu, OSX): Raspbian

**Comment by justbill2020** [comment]
this does nothing to help troubleshoot... there's no mention of the error or problem just some file some lines of errors... 

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.
