### ISSUE TITLE
No Microphone...

### ISSUE THREAD

**Issue by cruze09** [evancohen/smart-mirror#637]
Speech recognition is not possible.

Npm start does not recognize speech.

Npm run sonus Run and say nothing.

Just record the micro recordings are possible. However, if you start with npm, the microphone will not work.

I also created keyfile.json in the Google API.

Running npm run microphone-debug
"Uncaught Type Error: MediaStreamTrack.getSources in not microphone.js: 24 a function
At start (microphone.js: 24)
At microphone.js: 56).

**Comment by justbill2020** [comment]
npm run microphone-debug no longer tests the audio and is there for legacy smart-mirrors... we're actually removing that completely soon...

please see the documentation for troubleshooting your voice response... as there's not enough details here to assist you. https://docs.smart-mirror.io/docs/microphone_and_speech_recognition_issues.html

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by justbill2020** [comment]
haven't heard a response in over 7 days. I'm closing this issue...

@cruze09  if you're still having issues please comment on this issue and we can reopen..

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.
