### ISSUE TITLE
npm run sonus and bug config.js

### ISSUE THREAD

**Issue by kbeaux** [evancohen/smart-mirror#638]
Hi everybody,

I already saw some similar issues but even in following the steps it didn't solved my problem.
So after try to solved it, I tried to delete the smart-mirror folder and reinstall everything but it didn't changed anything.
This is my bug :

pi@raspberrypi:~/smart-mirror $ npm run sonus

> smart-mirror@0.0.12 sonus /home/pi/smart-mirror
> node sonus.js

module.js:471
    throw err;
    ^

Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.32-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "sonus"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.12 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.12 sonus script 'node sonus.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node sonus.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

Can someone help me because i don't see what i can do ... 
Thanks.

**Comment by justbill2020** [comment]
duplicated issue multiple times... please search for issues and add comments to that issue rather than submitting a new issue

**Comment by sheelu18** [comment]
I am having the same issue... any way to resolve???

**Comment by justbill2020** [comment]
This is caused by not configuring the smart mirror using the configUI... please follow the docs
