### ISSUE TITLE
Reminder plugin issue

### ISSUE THREAD

**Issue by Daxo32** [evancohen/smart-mirror#647]
The issue is in the reminder plugin

### Expected Behavior
when I say 'remind me to *action' the system should add a reminder 

### Current Behavior
When I say the vocal command to add a new reminder appear an error in the developer console

Error --> https://imgur.com/gallery/MWaT5

### Possible Solution
I tryed to look but I didn't find a solution 

### Steps to Reproduce (for bugs)
Just say the command to add a new reminder

### Your Environment

Raspberry Pi 2 B+
Raspbian Jessie (not noob)

**Comment by justbill2020** [comment]
did you add the same reminder in twice?

**Comment by Daxo32** [comment]
No

**Comment by justbill2020** [comment]
are you on dev or master?

**Comment by Daxo32** [comment]
What you mean I dont understand

**Comment by justbill2020** [comment]
which branch are you on? are you using your forked repo? or the main repo?

**Comment by Daxo32** [comment]
The master

**Comment by Daxo32** [comment]
main*

**Comment by sdetweil** [comment]
did this get pushed finally?
