### ISSUE TITLE
i cant't  npm run sonus 

### ISSUE THREAD

**Issue by xiangsijiwo** [evancohen/smart-mirror#649]
pi@raspberrypi:~/smart-mirror $ npm run sonus

 

> smart-mirror@0.0.13 sonus /home/pi/smart-mirror

> node sonus.js

 

module.js:597

  return process.dlopen(module, path._makeLong(filename));

                 ^

 

Error: Module version mismatch. Expected 48, got 46.

    at Error (native)

    at Object.Module._extensions..node (module.js:597:18)

    at Module.load (module.js:487:32)

    at tryModuleLoad (module.js:446:12)

    at Function.Module._load (module.js:438:3)

    at Module.require (module.js:497:17)

    at require (internal/module.js:20:19)

    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/grpc/src/node/src/grpc_extension.js:38:15)

    at Module._compile (module.js:570:32)

    at Object.Module._extensions..js (module.js:579:10)

 

npm ERR! Linux 4.9.24-v7+

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "sonus"

npm ERR! node v6.10.3

npm ERR! npm  v3.10.10

npm ERR! code ELIFECYCLE

npm ERR! smart-mirror@0.0.13 sonus: `node sonus.js`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the smart-mirror@0.0.13 sonus script 'node sonus.js'.

npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the smart-mirror package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     node sonus.js

npm ERR! You can get information on how to open an issue for this project with:

npm ERR!     npm bugs smart-mirror

npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls smart-mirror

npm ERR! There is likely additional logging output above.

 

npm ERR! Please include the following file with any support request:

npm ERR!     /home/pi/smart-mirror/npm-debug.log

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
It looks like you've changed the version of node (or npm) installed on your machine since installing the mirror. You'll have to reinstall the native grpc dependency with `npm install`. 

If that doesn't work you can:  
```
npm uninstall grpc
npm install grpc
```

**Comment by justbill2020** [comment]
haven't heard a response in over 14 days. I'm closing this issue...

@xiangsijiwo  if you're still having issues please comment on this issue and we can reopen..

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by ragsmax** [comment]
am having the same issue as op

here is the log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'sonus' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'presonus', 'sonus', 'postsonus' ]
5 info lifecycle smart-mirror@0.0.14~presonus: smart-mirror@0.0.14
6 silly lifecycle smart-mirror@0.0.14~presonus: no script for presonus, continuing
7 info lifecycle smart-mirror@0.0.14~sonus: smart-mirror@0.0.14
8 verbose lifecycle smart-mirror@0.0.14~sonus: unsafe-perm in lifecycle true
9 verbose lifecycle smart-mirror@0.0.14~sonus: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/smart-mirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle smart-mirror@0.0.14~sonus: CWD: /home/pi/smart-mirror
11 silly lifecycle smart-mirror@0.0.14~sonus: Args: [ '-c', 'node sonus.js' ]
12 silly lifecycle smart-mirror@0.0.14~sonus: Returned: code: 1  signal: null
13 info lifecycle smart-mirror@0.0.14~sonus: Failed to exec sonus script
14 verbose stack Error: smart-mirror@0.0.14 sonus: `node sonus.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid smart-mirror@0.0.14
16 verbose cwd /home/pi/smart-mirror
17 error Linux 4.9.41-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "sonus"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error smart-mirror@0.0.14 sonus: `node sonus.js`
22 error Exit status 1
23 error Failed at the smart-mirror@0.0.14 sonus script 'node sonus.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the smart-mirror package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node sonus.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs smart-mirror
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls smart-mirror
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ragsmax** [comment]
pi@raspberrypi:~/smart-mirror $ npm run sonus

> smart-mirror@0.0.14 sonus /home/pi/smart-mirror
> node sonus.js


/home/pi/smart-mirror/sonus.js:14
	throw "Configuration Error! See: https://docs.smart-mirror.io/docs/configure_the_mirror.html#speech"
	^
Configuration Error! See: https://docs.smart-mirror.io/docs/configure_the_mirror.html#speech

npm ERR! Linux 4.9.41-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "sonus"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.14 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.14 sonus script 'node sonus.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node sonus.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

**Comment by ragsmax** [comment]
have tried the steps mentioned here

**Comment by evancohen** [comment]
> /home/pi/smart-mirror/sonus.js:14
throw "Configuration Error! See: https://docs.smart-mirror.io/docs/configure_the_mirror.html#speech"
^

It looks like you have an error with your smart-mirror configuration. Guessing you haven't included a keyfile (or other required field) in the remote config UI.
