### ISSUE TITLE
The pagination command text doesn't use Locale language

### ISSUE THREAD

**Issue by krisaggio** [evancohen/smart-mirror#650]
### Expected Behavior
 The "say next", "say previous" and the pages text should change within the selected languages.
Being hardcoded might be a good idea externalize it with the languages files in /locales

### Steps to Reproduce (for bugs)
1.Change to any other language rather than English 
2.Trigger the show command list.
3.The "say next", "say previous" and the pages text with be shown in English and wont work.

### Context
Browsing the command list menu, moving between pages.

### Your Environment
Raspberry Pi 3, node.js v6.10.3
Raspbian 4.9.27

**Comment by evancohen** [comment]
Yup! This is a localization bug. This should totally be fixed.

**Comment by justbill2020** [comment]
just wrote the code to fix this... not sure i like it i'll push a commit with this and other stuff in #642  later on after i do some testing...

**Comment by sdetweil** [comment]
@justbill2020   did u ever test this?  do you have the code still?
