### ISSUE TITLE
Bluetooth audio stopped working

### ISSUE THREAD

**Issue by Jimbeam55** [evancohen/smart-mirror#651]
Before configuring Sound & Voice, I was able to stream music via YT api from the Raspberry Pi (3) to my bluetooth speakers. After setting up the playstation eye as microphone, bluetooth for speakers (when connecting) doesn't work anymore.
I guess it's because in the guide, it says to force audio through aux. 

### Possible Solution
How can I force Audio playback to go through bluetoot rather than aux?

From the guide:
We no longer need to check the playback device as we will always use hw:0,0 as the playback device.
Note: In order to push audio through the headphone jack, setting hw:0,0 is not enough. You must also run:
amixer cset numid=3 1
To force the audio back through HDMI you can run:
amixer cset numid=3 2
###To force the audio back through Bluetooth you can run:
###?_?_?_?_?_?_?

### Steps to Reproduce (for bugs)
Follow the guide, try to connect to bluetooth speakers.

### Context
Streaming music from the mirror, without the cablesalad that goes with aux.

### Your Environment
Raspberry Pi 3, everything works fine, except bluetooth audio for the whole system.

This is the last step for completing my mirror.

**Comment by justbill2020** [comment]
we do not support bluetooth audio at this time.

**Comment by evancohen** [comment]
Just as a thought: You might try configuring your Bluetooth with PulseAudio - audio on Linux is pretty finicky though, so just beware that it's a rabbit hole.

**Comment by Jimbeam55** [comment]
Thanks for the suggestion. Looking more into it this week.
I'll keep this updated.

**Comment by justbill2020** [comment]
Also be aware we've had issues with pulseaudio in the past it was a messy mess. Good luck let us know how you make out

**Comment by Jimbeam55** [comment]
After some very frustrating hours and getting it to work for like 30 seconds before pulseaudio crashes, I gave up on it. Started from the beginning and going for a Line to BT transmitter. Way simpler.
