### ISSUE TITLE
Question: Google Cloud Speech API moving from beta

### ISSUE THREAD

**Issue by pmagnussen** [evancohen/smart-mirror#653]
This is more of a question than an issue (yet!).

I'm assuming everyone got this email from Google saying that the Google Cloud Speech API beta is moving from beta. And as an owner of a Google project that uses this API, Google urges us to take action and move to the new Cloud Speech API GA.

Do we need to make any changes?

**Comment by justbill2020** [comment]
there's an update coming shortly... we have also posted a message and pinned it in the support channel of discord...
Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
As Bill mentioned, there's an update coming: #652
You can wait until we push the new version and update your dependencies then or, if you want to be proactive, you can update to the most recent version of Sonus right now (which supports the v1 endpoints) by running the following in your `smart-mirror` directory: 
```
npm install sonus@0.1.8
```

**Comment by justbill2020** [comment]
haven't heard a response in over 7 days. I'm closing this issue...

@pmagnussen if you're still having issues please comment on this issue and we can reopen..


Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.
