### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by poetic420** [evancohen/smart-mirror#654]
i closed the magic mirror window..
i try to open it again and cant..

pi@raspberrypi:~ $ npm start
npm ERR! Linux 4.9.24-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by poetic420** [comment]
I ran the comman in directiry
still a problem


pi@raspberrypi:~/smart-mirror $ npm start

> smart-mirror@0.0.14 start /home/pi/smart-mirror
> electron main.js 

Remote listening on http://10.0.0.2:8080
ERROR s:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/pi/smart-mirror/keyfile.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:17:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by evancohen** [comment]
Looks like you're missing your Google Cloud Speech keyfile: https://docs.smart-mirror.io/docs/configuring_voice.html#setting-up-speech-recognition

**Comment by poetic420** [comment]
hey thanks for replay!
 this is my first project and im new to all of this so sorry if i have stupid questions.. 

i have an issue with the Train module keyword (snow boy)
i downloaded the public module, but i cant seem to understand where to save it

"" Once trained, download the model and save it to the root of the **smart-mirror directory**."" 

HOW do i save it in root of the smart mirror dirctory????
can you guys explain where do i need to save it?

**Comment by evancohen** [comment]
the root of your smart mirror is `~/smart-mirror`. Here is an overview of some basic naviation and file manupulation in linux: 
https://www.digitalocean.com/community/tutorials/basic-linux-navigation-and-file-management

You can also use the Pi's GUI file system. Just download your model and then use the file system to move it (click and drag, nothing complex).

**Comment by justbill2020** [comment]
@poetic420 is this now resolved?

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by poetic420** [comment]
well, i tried everything you said...
I run my smart mirror and no mic recognition or any reaction to "smart mirror" command..
when run "npm start" i get the following error:


pi@raspberrypi:~/smart-mirror $ npm start

> smart-mirror@0.0.14 start /home/pi/smart-mirror
> electron main.js 

Remote listening on http://10.0.0.2:8080
ERROR le.js:471
    throw err;
    ^

Error: Cannot find module '/home/pi/smart-mirror/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by poetic420** [comment]
-also:

-  should i change this file "voice1-d674e2ea2876.json" to "keyfile.json"

- in "sound config" https://docs.smart-mirror.io/docs/configuring-sound.html 
I run the commands as writen
"You'll want to determine the recording device:

$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Camera [Vimicro USB2.0 UVC Camera], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0"

And get only errors:
pi@raspberrypi:~ $ $ arecord -l
bash: $: command not found
pi@raspberrypi:~ $ **** List of CAPTURE Hardware Devices ****
bash: #HOME SECOND FLOOR WALL 2.py: command not found
pi@raspberrypi:~ $ card 1: Camera [Vimicro USB2.0 UVC Camera], device 0: USB Audio [USB Audio]
bash: card: command not found
pi@raspberrypi:~ $   Subdevices: 1/1
bash: Subdevices:: command not found
pi@raspberrypi:~ $   Subdevice #0: subdevice #0

************************
Current behavior: smart mirror opens but no reaction to commands at all

thanks for your reply!

**Comment by poetic420** [comment]
all works!!!
after new ras jessy installed and a little help from the guys at discord chat (they are the best!)
thank you everyone for the help!
the smart-mirror is amazing!
