### ISSUE TITLE
autotimer service wakeup in energrystar mode has syntax error

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#655]
syntax error on wakeup

the service.js for the autotimer plugin has a case sensitivity error

### Current Behavior

line 49, 
				} else if (config.autoTimer.mode == "energy") {
					focus.change('default')

### Possible Solution

				} else if (config.autoTimer.mode == "energy") {
					Focus.change('default')

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):
Pi V3 running SM v 14

**Comment by justbill2020** [comment]
fixed in PR #656

**Comment by evancohen** [comment]
This was fixed in c55e4d5561857519b2fecbd0ae7a056082a86b5c
