### ISSUE TITLE
autotimer service in Monitor mode missing Focus change

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#657]
code wakes up monitor, but doesn't tell SM code to display again

### Expected Behavior
 

				if (config.autoTimer.mode == "monitor") {
					service.exec(config.autoTimer.wakeCmd, service.puts);
					Focus.change('default');  <------- missing
				} else if (config.autoTimer.mode == "tv") {

### Current Behavior

				if (config.autoTimer.mode == "monitor") {
					service.exec(config.autoTimer.wakeCmd, service.puts);
				} else if (config.autoTimer.mode == "tv") {

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
Yuup! If you create a quick PR for this issue I'll merge - otherwise I can take care of it tomorrow.

**Comment by sdetweil** [comment]
added PR

**Comment by evancohen** [comment]
Fixed in ab701b1a2f672cf47659a494da9543dd79dab0e7
