### ISSUE TITLE
Microphone is working but not with smart mirror

### ISSUE THREAD

**Issue by Paradiced** [evancohen/smart-mirror#658]
I'm using the PS3 eye as a microphone and unfortunately it does not seem to work with the smart mirror for me. I have followed and re-followed the tutorials, set up the project, API is enabled and created billing account etc, double checked all of that, the json file and the pdml file are in the root directory of the smart mirror folder, with the correct filenames and matching the ones in the admin panel.

Everything seems to be correct from my end as the microphone worked to set up the personal model and works for everything else. It isn't chucking out any errors or anything so i'm a bit baffled as to what the problem is. 

Environment: Rasberry Pi 3, node.js 6.11.0, npm 3.10.10
Operating System: Raspbian

**Comment by evancohen** [comment]
Seems like you fixed this issue! It'd be great if you could share what you did in case anyone else runs into the same problem. Thanks!

**Comment by Paradiced** [comment]
I created a new project on Google and that fixed it. Even though everything on the project i created was set correctly, billing was enabled and connected to project, service account was created with owner permissions. speech api was enabled and json file was named correctly and in the correct directory. Must have bugged out for some reason.

**Comment by montanaman2017** [comment]
I'm having the same issue.  I also have a PS3 eye (great value and works awesome with Alexa on pi).  but not working with smart-mirror

arecord -l shows:

pi@raspberrypi:~/smart-mirror $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CameraB409241 [USB Camera-B4.09.24.1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

and my ~/.asoundrc 

pi@raspberrypi:~/smart-mirror $ cat ~/.asoundrc
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     # This is your input device (it may be different from what is seen here)
     slave.pcm "hw:1,0"
   }
}

any help would be great.  I'm running 
raspian pixel (raspberry pi 3)
