### ISSUE TITLE
Commands probelm

### ISSUE THREAD

**Issue by poetic420** [evancohen/smart-mirror#662]
Hey everyone!
Every thing is up and running (youtube api, hue api)

MY PROBLEMS:

-I am in Israel and trying to set the clock by inputting the longitude and latitude.
i changed the setting then rebooted and no change in time, even changed settings to Miami or New York and still no change in time..
-Also commands like "go to sleep" are not working not via voice control or via remote control when click "sleep" nothing happens.
-I trained my module a few times and modified the mic sensitivity.
Its always NOT responding to key-word OR always responds (even to music, movie  or just a conversation) and it ends up listening for 246.75  Minuts this week!!

Running Raspberry pi3
****************
Any help will be very appreciated!!!
Thank you!

**Comment by evancohen** [comment]
- The time is pulled from the Pi (not longitude and latitude)
- Are you running the most recent code from master? (I think the "go to sleep" bug is fixed in master)
- What values are you using for sensitivity?

**Comment by poetic420** [comment]
Hey, thank for replay..
-Yes, I am running tha latest code
-Tried all values of sensitivity..
If its below 0.5 no detecsion
If higher then 0.5 too much sensitivity and listens all the time..

**Comment by poetic420** [comment]
Acctually, i dont know for sure if i have the latest code from master..
I just followe insructions from here:
https://docs.smart-mirror.io/docs/configuration.html

**Comment by evancohen** [comment]
The snowboy folks just released a universal model so it's possible that will fix it. I'll be off the grid camping this week, but when I get back I'll add it to `dev` so you can try it.

**Comment by poetic420** [comment]
Thank you!
Enjoy camping!

בתאריך 4 ביולי 2017 5:00 אחה״צ,‏ "Evan Cohen" <notifications@github.com>
כתב:

**Comment by poetic420** [comment]
I edited the key word and now hot word detection is working good!
still have the command problems!
-when saying "go to sleep" nothing happens 
-when trying to dim lights (Phillips hue) "dim lights to 50%" nothing happens, only "dim lights" works and light dims only to 80%..
also, "turn lights on max" dosnt have any effect..
rest of the commands are working fine..
any idea what the problem may be?? 
super appreciate your help!

**Comment by evancohen** [comment]
This should now be fixed in the latest version of the `dev` branch :) let me know if you run into any more trouble.

**Comment by aishaamila** [comment]
A have problems with voice command. it is not working? But when typing the command  it works
