### ISSUE TITLE
Running sonus results in nothing. Mirror not receiving microphone input

### ISSUE THREAD

**Issue by Wykiki92** [evancohen/smart-mirror#666]
Everything else us set up correctly, the device works and the microphone worked to record the keywords. Tried to run sonus to troubleshoot but I do not get the blinking cursor or any other response. after a few seconds it returns to allowing me to input a command

**Comment by evancohen** [comment]
It's most likely that you have not correctly configured your microphone. Check out the support docs to make sure you've got everything working properly.

**Comment by Wykiki92** [comment]
Hi Evan,

I believe I have everything configured correctly, running through sending screenshots to the guys on the discord chat and I still can't figure out any reason why this isnt working. Heres a screenshot of the config for the microphone:
![2017-07-13-192922_1920x1080_scrot](https://user-images.githubusercontent.com/30056850/28194218-c89a9320-6810-11e7-839d-920304afd453.png)

**Comment by evancohen** [comment]
Can you try recording something with the microphone using `arecord`?
```
arecord -D plughw:1,0 -f cd test.wav
```
and then play it back to ensure that audio works
```
aplay test.wav
```

It may be that there is something wrong with the microphone itself. Do you have another you could test with?

**Comment by Wykiki92** [comment]
I recorded the keyword using the same microphone, I also ran the test and
heard my file to be clear and loud enough to be recognized

On Jul 20, 2017 12:33 AM, "Evan Cohen" <notifications@github.com> wrote:

Can you try recording something with the microphone using arecord?

arecord -D plughw:1,0 -f cd test.wav

and then play it back to ensure that audio works

aplay test.wav

It may be that there is something wrong with the microphone itself. Do you
have another you could test with?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/evancohen/smart-mirror/issues/666#issuecomment-316593918>,
or mute the thread

**Comment by evancohen** [comment]
And you've selected your recording device from the remote? It's possible that you inadvertently configured the mirror to use a different input device.

**Comment by gomezdt** [comment]
hello, i have the same issue, when i npm start the mirror i get this error:

pi@raspberrypi:~/smart-mirror $ npm start

> smart-mirror@0.0.14 start /home/pi/smart-mirror
> electron main.js 

Remote listening on http://10.0.2.15:8080
ERROR le.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/pi/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v48-linux-ia32/snowboy.node: undefined symbol: _ZN7snowboy13SnowboyDetectD1Ev
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/snowboy/lib/node/index.js:8:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by evancohen** [comment]
@gomezdt this looks like a similar issue, but has different symptoms. There's not much to go on based on that error, so it's going to be hard to diagnose. What if you run snowboy standalone?

Just a shot in the dark here, but you *may* have some luck rebuilding snowboy from scratch. Just install dependencies and install/build:

```
sudo apt-get install libmagic-dev libatlas-base-dev
npm install snowboy --fallback-to-build
```

**Comment by evancohen** [comment]
I've left a detailed solution at https://github.com/evancohen/smart-mirror/commit/252ddb157be346c9e053eb1b3dc4321ecbae6835. Hoping this will work for you. Just remember, if you save your config through the remote again, you'll have to go back and edit it manually.
