### ISSUE TITLE
Sonus not working properly

### ISSUE THREAD

**Issue by MounsifTakkal** [evancohen/smart-mirror#669]
Hi, I got some issues with sonus, can any one helps?
That's what I got when I try npm run sonus:

pi@raspberrypi:~/smart-mirror $ npm run sonus

> smart-mirror@0.0.14 sonus /home/pi/smart-mirror
> node sonus.js

undefined:5
  "private_key": "-----BEGIN PRIVATE 
                                     

SyntaxError: Unexpected token 
 in JSON at position 165
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:17:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-mirror@0.0.14 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.14 sonus script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-07-25T10_08_54_807Z-debug.log

**Comment by MounsifTakkal** [comment]
Well, finally I've decide to made a new fresh install and now everything is working fine.
Thanks!

**Comment by evancohen** [comment]
Glad you got it working. From the error you shared, it looks like there may have been something wrong with the formatting of your keyfile.

**Comment by MounsifTakkal** [comment]
Yeah, I thougt the same, so I made a new keyfile and then no error was througt but sonus still not working properly and i've decide to reinstall because maybe wher something that i was missing about dependencies or anything else.
Now works like a charm.
