### ISSUE TITLE
Lose audio from 3.5mm jack when edited for usb mic

### ISSUE THREAD

**Issue by nandor690** [evancohen/smart-mirror#67]
When I edit the files as suggested in issue #20 I lose audio from the 3.5mm jack. I have try all combinations of editing both files but I can't get them to work at the same time. Forcing it through raspi-config does not help either. Iv also tried mixer set numid=3 1 in Terminal. But both won't work at the same time.

**Comment by kurtdb** [comment]
I wouldn't be surprised if this was a raspberry pi hardware issue. If I'm not mistaken the audio and USB tracks on the board are linked. That's also the reason why audio is pretty bad if you use one or more USB devices coupled to the board.

**Comment by dano25** [comment]
I have also tried everything in issue #20. I can get everything working only if I do sudo npm start. Not sure if this is a big deal to have to sudo or not.... i'm a noob :/

**Comment by beto2909** [comment]
Last night I was doing some testing and just that pcm.default.card 1 in the .asoundrc file is making my audio not work when that line is there and when is not my mic goes out but my sound works. 

Im not sure if it's possible but this is a guide for general Linux system troubleshooting . 
https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture/Troubleshooting#Microphone

I still haven't tested anything in here but this shows how to make the microphone work amor solve issues with the audio through hdmi.

**Comment by nandor690** [comment]
Kurtdb, I was for sure thinking it was something to do with the hardware and how it was connected. Kinda bummed. But I guess I don't really need sound on a mirror......Yet. Lol. 
I'll take a look at the other things mentioned in the comments

**Comment by nandor690** [comment]
Thanks guys

**Comment by boss345** [comment]
I'm struggling with this as well

**Comment by 3y3c0ugh** [comment]
I switched to the search branch, and plugged in my speakers to see I got this issue and I did. The only changes I made were in alsa.conf where I made ```defaults.pcm.card 1```.
I'm not sure if there is a conflicting issue with having both ALSA and PulseAudio, but I installed pulse, and after a reboot, sound works find throughout desktop and mirror. All I did was run
```sudo apt-get install PulseAudio``` and after it was finished I did a ```sudo reboot``` and it's worked since without any other changes.

See if this works for any of you guys

**Comment by nandor690** [comment]
Awesome. I'll try this when I get home. It snowed pretty good here and modot sucks, so it'll probably take awhile. I'll post my results then

**Comment by evancohen** [comment]
I've been investigating PulseAudio as a solution to all of the microphone problems people have been having. While I haven't verified that it works with everything it's a pretty good bet that it's what we'll use going forward.

**Comment by StevenTLBF** [comment]
http://plugable.com/products/usb-audio would this help the issue?

**Comment by evancohen** [comment]
It would introduce the same issue. Electron and the ALSA configuration are not playing well together.

**Comment by 3y3c0ugh** [comment]
So i did more testing and i still get issues..
If i force audio to 3.5 and then install pulse, sound works fine outside mirror and with mirror. However, once pulse is installed, and I want to switch to say HDMI sound from my TV, i get nothing inside or outside the mirror. BUT if I ```sudo apt-get autoremove pulseaudio``` then the sound fixes, forces HDMI sounds, and works outside the mirror but not in the mirror. If HDMI is still forced, and I re-install pulseaudio, HDMI works inside and out the mirror. Strangely, once you force an output and install pulse, thats the only output that works. Until you remove pulse, force the other output, and reinstall pulse.

**Comment by evancohen** [comment]
You might want to check out this response on GitHub about getting PulseAudio working on the pi with analog output: http://raspberrypi.stackexchange.com/questions/639/how-to-get-pulseaudio-running#answer-4022

**Comment by evancohen** [comment]
Ok folks, I spent some time on it this evening and got it working. Revert all changes you've made to ALSA conf files (this will be way easier than messing around with those, I promise).
Then run:

```
sudo aptitude install pulseaudio
sudo modprobe snd_bcm2835
sudo amixer cset numid=3 1
```

That's it. No fancy configuration - nothing to reset after you reboot, everything should just work.

**Comment by beto2909** [comment]
This works great. You should add this in the troubleshooting section.
