### ISSUE TITLE
Installation Troubleshoot

### ISSUE THREAD

**Issue by mmarliu** [evancohen/smart-mirror#673]
Sorry this might be a dumb question:

Pretty new to using Raspberry Pi's, but really excited for the instructions you put together! Thanks again. I'm at the installation and installed all of the dependencies successfully. However, I had to leave so I shutdown the r.Pi and powered it off. When I returned, I powered it back on, but it does not boot up to my monitor. I have the red power light and green light blinking so I think it is pinging/reading the OS. Have you seen this before? I do not have a mic either.

Thanks for the help!

**Comment by evancohen** [comment]
This might also be a silly question: does your monitor have a power saving feature and turned it self off?

You can always power-cycle the Pi and see if that fixes it

**Comment by mmarliu** [comment]
It does have a power saving feature that sends the monitor to sleep but not off. I tried plug/unplug the Pi and get the red light persistent and the green light blinking a few times then blinking once every second or so.

Really appreciate it!

**Comment by evancohen** [comment]
Give the R-Pi Troubleshooting for [No HDMI Output at All](http://elinux.org/R-Pi_Troubleshooting#No_HDMI_output_at_all) and see if anything there works for you.

**Comment by evancohen** [comment]
Did you manage to get this working?

**Comment by mmarliu** [comment]
I plugged it into a different monitor and it booted up fine. So it must be something with my other monitor? Still trying to troubleshoot it.

**Comment by evancohen** [comment]
Ah I see, sounds like something is busted with the first monitor. Since this isn't a problem with the mirror I'm going to close out this issue.

**Comment by mmarliu** [comment]
Sounds good, thanks for the help!
