### ISSUE TITLE
Config.json not found and problems with config.js

### ISSUE THREAD

**Issue by d1bg12** [evancohen/smart-mirror#674]
First off - thank you for the amazing software Evan - keep going !
The problem that I have is that when I open the SmartMirror software on my Raspberry pi 3, it shows me a warning - “config.json is not found” . I could not find the config.js file in the smart-mirror repository and I made my own one but it seems that it is not working as it should.I add some modules (greetings/forecast) in config.js but they are not displayed on the mirror. It is displaying only date,time and what can i do options.
Can you help me fixing that problem? Thank you and good luck with developing your Smart Mirror! :)

**Comment by evancohen** [comment]
"config.json is not found" is an expected warning when you run the mirror without saving your config from the remote. 

When you run the mirror, go to the IP address that is shown on the mirror (or on the command line) and click the gear on the top right. Fill in any desired configuration stuff and then go to the bottom and click save. The mirror should reboot and your new settings applied. If *that* doesn't work come back and let me know :)

... I've heard from a few people that the error is confusing, it should probably be rephrased.

**Comment by sdetweil** [comment]
fixed 0.26
