### ISSUE TITLE
Failed to load resource : the server responded with a status of 404

### ISSUE THREAD

**Issue by StoneSuhyun** [evancohen/smart-mirror#676]
My Smart-mirror have a error that Failed to load resource : the server responded with a status of 404.
server is https://maps.googleapis.com/maps/api/broweserlocation/json?browser=chromium
I don't know that.

Maybe, geoposition don't working.
therefore I changed My code.
`return %https.jsonp('https://api.darksky.net/forecast/' + config.forecast.key + '/' + "37" + ',' +"127" 
+ '?units=' + config.forecast.units + "&lang=" + "en-US" + "&callback=JSON_CALLBACK")`

but I can't see weather...
plese help me.
![123](https://user-images.githubusercontent.com/30653001/29579507-0290f9c2-87ae-11e7-8896-95047ac2ea7c.jpg)

![default](https://user-images.githubusercontent.com/30653001/29578975-3f7827ae-87ac-11e7-9771-a5e48bce8efd.jpg)

**Comment by evancohen** [comment]
Seems like the API is being weird. Try hard-coding your lat and long into the settings, that should work for you :)

**Comment by StoneSuhyun** [comment]
Thank you very very X 100000000000000000000000000000000000  much.
Now, I can see weather.

**Comment by kcwoo326** [comment]
I have the same problem, but I am a beginner. I would really appreciate it if you could share your solution.

**Comment by evancohen** [comment]
@kcwoo326 enter your lat long coordinates into the remote app. That should get things working for you if you're having issues with geolocation.
