### ISSUE TITLE
YouTube does not play after first video

### ISSUE THREAD

**Issue by ragsmax** [evancohen/smart-mirror#678]
Youtube does not load after the first video.
Even after saying go home. The next search yeilds no response
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by ragsmax** [comment]
Any help ?

**Comment by evancohen** [comment]
I've reopened #473
