### ISSUE TITLE
Npm start dev issue

### ISSUE THREAD

**Issue by sharmmoh1983** [evancohen/smart-mirror#679]
smart-mirror $ npm start dev

> smart-mirror@0.0.14 start /home/pi/smart-mirror
> electron main.js  "dev"

npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/opt/nodejs/bin/node" "/usr/local/bin/npm" "start" "dev"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.14 start: `electron main.js  "dev"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.14 start script 'electron main.js  "dev"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js  "dev"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

**Comment by sharmmoh1983** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/bin/node', '/usr/local/bin/npm', 'start', 'dev' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle smart-mirror@0.0.14~prestart: smart-mirror@0.0.14
6 silly lifecycle smart-mirror@0.0.14~prestart: no script for prestart, continu$
7 info lifecycle smart-mirror@0.0.14~start: smart-mirror@0.0.14
8 verbose lifecycle smart-mirror@0.0.14~start: unsafe-perm in lifecycle true
9 verbose lifecycle smart-mirror@0.0.14~start: PATH: /opt/nodejs/lib/node_modul$
10 verbose lifecycle smart-mirror@0.0.14~start: CWD: /home/pi/smart-mirror
11 silly lifecycle smart-mirror@0.0.14~start: Args: [ '-c', 'electron main.js  $
12 silly lifecycle smart-mirror@0.0.14~start: Returned: code: 1  signal: null
13 info lifecycle smart-mirror@0.0.14~start: Failed to exec start script
14 verbose stack Error: smart-mirror@0.0.14 start: `electron main.js  "dev"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/opt/nodejs/lib/node_modules/$
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)

**Comment by sharmmoh1983** [comment]
Issue in starting the application

**Comment by evancohen** [comment]
I haven't tested the mirror with Node 7.x you might want to roll back to 6.x and try installing again.

**Comment by sharmmoh1983** [comment]
I have tested on 6.x also and it is failing. I have jesse lite on my raspberry. Is jesse a pre requisite

**Comment by evancohen** [comment]
Can you provide your `npm-debug.log`?

**Comment by sharmmoh1983** [comment]
I have updated in the issue

**Comment by evancohen** [comment]
Did you install the mirror using the 1-line install, or manually? If you ran the script, did you already have 7.x installed?

**Comment by sharmmoh1983** [comment]
Sorry I did not get that.. Can you tell me the steps to follow to install

**Comment by sharmmoh1983** [comment]
I am using Jesse Lite and not jesse on raspberry. Can that be the issue why electron is not working as it looks for chromium browser which is not present in Jesse lite

**Comment by justbill2020** [comment]
You cannot use Jessie lite... there is no GUI environment in Jessie lite you must use raspbian Jessie full... please see the docs.smart-mirror.io for more info

**Comment by sharmmoh1983** [comment]
I have now installed jesse full version with gui..still same error

On 5 Sep 2017 21:37, "Bill Martin" <notifications@github.com> wrote:

You cannot use Jessie lite... there is no GUI environment in Jessie lite
you must use raspbian Jessie full... please see the docs.smart-mirror.io
for more info

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/evancohen/smart-mirror/issues/679#issuecomment-327177499>,
or mute the thread

**Comment by sharmmoh1983** [comment]
@justbill2020  Jessie full version with UI is also giving same issue

**Comment by sharmmoh1983** [comment]
@evan Please re open the issue

**Comment by evancohen** [comment]
Are you trying to run the mirror over ssh?

**Comment by sharmmoh1983** [comment]
No I am not running it over ssh

**Comment by sharmmoh1983** [comment]
It is resolved now
