### ISSUE TITLE
Enhanced UI

### ISSUE THREAD

**Issue by StevenTLBF** [evancohen/smart-mirror#68]
Is it possible to enhance the UI to resemble the one depicted here: https://medium.com/@maxbraun/my-bathroom-mirror-is-smarter-than-yours-94b21c6671ba#.ikiwookp3

Also how hard is it to add those icons for weather? (The cloud, Sun covered by the cloud, etc).. I just love the font and overall UI of the mirror linked above.

**Comment by andrewda** [comment]
It wouldn't be hard to add the icons - a switch statement for the whether should suffice.

**Comment by yaydogan** [comment]
I am adding weather icons in my repository based on evancohen's smart-mirror. I will commit within the next few days. I can let you know and you can check it out.

**Comment by Shubham0209** [comment]
@yaydogan please can you message and share the link of final working repository here, once you are done.

**Comment by evancohen** [comment]
@yaydogan just send a pull request :)

**Comment by StevenTLBF** [comment]
@andrewda I do apologize; I am new to java script. Could you describe step by step how I would implement my own icons?

**Comment by andrewda** [comment]
@StevenTLBF When `weather-service.js` returns the current weather, you can check if it's, say, `Partly Cloudy` or `Sunny`, and assign the respective icon depending on the weather. I've never really done anything with the forecast.io API, but I'm sure they have documentation you can check out.

**Comment by yaydogan** [comment]
@Shubham0209 Sure I will share the link.

@evancohen I am making some other changes like font type, size, time display etc... to customize the display to my liking. Let me create a new branch which has just the weather icons and send a pull request. You shall review the code before merging though. I am very new to JS - learning with this project :)

**Comment by yaydogan** [comment]
I committed weather icon changes to my repository. If you are interested in trying, this is the link:

https://github.com/yaydogan/smart-mirror-1.git

This is based on evancohen's master branch. 

@evancohen  When you get a chance, please take a quick look and let me know your comments. I can send a pull request if you want to incorporate into your master branch.

**Comment by Shubham0209** [comment]
Awesome work @yaydogan .. Now the UI looks really more pleasing and nice.

**Comment by evancohen** [comment]
@yaydogan I'll totally do that :) I'm on vacation this weekend but I'll take a look at it early next week.

**Comment by evancohen** [comment]
@yaydogan I had the chance to take a look at this today. Awesome job. Please create a pull request and I'll merge it in :+1:
