### ISSUE TITLE
manual installation link not working

### ISSUE THREAD

**Issue by abhinavtk97** [evancohen/smart-mirror#683]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
Can you provide the URL of the page that link is on and the text that is used for the broken link?
