### ISSUE TITLE
Unsuccessful Install using the quick install (Raspberry pi beginner)

### ISSUE THREAD

**Issue by Djnightfires** [evancohen/smart-mirror#684]
Hello

Raspberry Pi beginner here so apologies if I missed something obvious but using the quick install command "curl -sL https://raw.githubusercontent.com/evancohen/smart-mirror/master/scripts/pi-install.sh | bash" (without the brackets) I came across these errors when trying to npm start (& saying start mirror in the mic)

This is the Home directory-

npm ERR! Linux 4.9.41-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

and this is the smart-mirror directory-

> smart-mirror@0.0.14 start /home/pi/smart-mirror
> electron main.js

npm ERR! Linux 4.9.41-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.14 start: `electron main.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.14 start script 'electron main.js '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

saying smart mirror does'nt seem to work for me either and used raspberry pi jessie pixel & raspberry stretch images.

Any help would be apprecitated thanks!

**Comment by evancohen** [comment]
Are you starting the mirror via `ssh`? If that's the case then you'll need to `DISPLAY=:0 npm start`

**Comment by Djnightfires** [comment]
Didn't have much time to work on the mirror but followed your step about DISPLAY=:0 and it worked perfectly! Thanks for the fast reply & the work you did on the smart mirror itself!
