### ISSUE TITLE
Not able to start sonus

### ISSUE THREAD

**Issue by Leonpa** [evancohen/smart-mirror#689]
Hey everyone,

My problem is, that running 

`npm run sonus` results in this output:

pi@raspberrypi:~/smart-mirror $ npm run sonus

 smart-mirror@0.0.14 sonus /home/pi/smart-mirror
node sonus.js

/home/pi/smart-mirror/node_modules/sonus/index.js:5
const {Detector, Models} = require('snowboy')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:20:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "sonus"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.14 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.14 sonus script 'node sonus.js'.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node sonus.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

Consequently my speech recognition is not working...
I can see that this output says something about Snowboy, but I have no clue what could be wrong: I have my snowboy model file and everything else installed properly, everything should be named right and be in the correct folder. 

Thanks for your help

Leon

**Comment by evancohen** [comment]
You're likely running a legacy version of Node. You'll need to install v4+

**Comment by sdetweil** [comment]
closing, old
