### ISSUE TITLE
Smart mirror does not respond to microphone

### ISSUE THREAD

**Issue by transmit-ter** [evancohen/smart-mirror#690]
Hi there! 
My Smart mirror does not respond to microphone
There are no errors in all sources when i run
pi@raspberrypi:~/smart-mirror $ npm start
> smart-mirror@0.0.14 start /home/pi/smart-mirror
> electron main.js 
Remote listening on http:// <my ip address>

I did follow step by step process on docs.smart-mirror.io
I tried rec test.wav with PS eye like post #448, the bars moved but It did not work on smart mirrors.

pi@raspberrypi:~/smart-mirror $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/smart-mirror $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CameraB409241 [USB Camera-B4.09.24.1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/smart-mirror $ nano ~/.asoundrc
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     # This is your input device (it may be different from what is seen here)
     slave.pcm "hw:1,0"
   }
}

My Environment
Environment name and version: Raspberry Pi 3, node.js v6.11.4
Operating System and version: Raspbian

**Comment by evancohen** [comment]
I **think** I know how to fix this :) From the smart mirror folder run:
```bash
git pull
git checkout dev
npm install sonus@next
```

Then go into the remote config app and ensure that you have the correct input device selected and save.

Give that a shot and let me know if you run into any issues.

**Comment by transmit-ter** [comment]
well, i tried 
git pull
git checkout dev
npm install sonus@next
and config my input device (USB Camera-B4.09.24.1). I also tried npm run sonus (like docs.smart-mirror.io/docs/microphone_and_speech_recognition_issues) , but it only worked once, after i rebooted my pi, it didn't work again.

**Comment by mohanadalalawi** [comment]
i have the same problem did u find solution?

**Comment by evancohen** [comment]
You may also want to take a look at #693

**Comment by transmit-ter** [comment]
Yeah thanks a lot for your help, it worked
