### ISSUE TITLE
voice recognition response time issue

### ISSUE THREAD

**Issue by hoon82** [evancohen/smart-mirror#693]
Hi. I installed smart-mirror program using command
curl -sL https://raw.githubusercontent.com/evancohen/smart-mirror/master/scripts/pi-install.sh | bash
using Raspberry 3 device with Full desktop image.
also I made my cloud speech key and keyword spot file(.pdml)
and using npm start, program is working and voice recognition works.
but voice recognition is really slow.
if i say "smart mirror"(keyword) and some command(like "what can i say?", then white bar is come up really slowly.
It seems like 5~7 seconds. after then command text is come out and function works.
If i use dev mode. there's no delay. white bar is come up immediately.
also if i decrease raspberry's resolution like 640x480. voice recognition is very fast.
Is there some performance issues? I look around whole issues page, but there is no voice recognition delay issue. 

 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
I haven't had the chance to try this, but it seems like the consensus in Discord is that it's an electronic perf issue. If you run this from the smart mirror folder it may fix that issue.
```
npm uninstall electron
npm install electron@1.6.11
```

**Comment by hoon82** [comment]
After reinstall electron ver1.6.11
My smart-mirror works perfectly!
There is no delay in voicerecognition and youtube.
Thanks for your support!

**Comment by justbill2020** [comment]
@evancohen we really need to implement yarn
