### ISSUE TITLE
can't show the any image or text on the screen about traffic

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#694]
my general language is en-US
Traffic Settings Information
- API Key - Ali~~~
Trip Name: work
Mode : Driving
Starting Location: 128 24th Ave E, Seattle
Destination Location: Microsoft Linclon Square
-----Locations are sample address ---
Time to start display : empty
Time to stop ~: empty

### Expected Behavior
see the text or image on the top right my screen
 

### Current Behavior

can't see the any event about traffic

### Possible Solution
Change some different address or etc
Change general.language in plugin(controller.js) of traffic   from en-US  to en 
but still have same issue 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment
Raspberry Pi 3, node.js 7.9.0
Raspbian

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by nevido** [comment]
i resolve my problem

**Comment by yuen33** [comment]
How did you solve your problem? Mine always show 0 minutes, without image
