### ISSUE TITLE
stock display no longer working

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#695]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

the yahoo api for stock info is returning no data 

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
Someone mentioned this in the Discord the other day, this is deff a bug.

**Comment by sdetweil** [comment]
here is the results of the yahooapis.com request for AAPL

{
 "query": {
  "count": 0,
  "created": "2017-11-15T20:05:40Z",
  "lang": "en-US",
  "results": null
 }
}

**Comment by evancohen** [comment]
Yeah, that's decidedly not good. Testing a [stock quote query](http://developer.yahoo.com/yql/console/?q=select%20*%20from%20yahoo.finance.quote%20where%20symbol%20in%20(%22YHOO%22%2C%22AAPL%22%2C%22GOOG%22%2C%22MSFT%22)&env=store%3A%2F%2Fdatatables.org%2Falltableswithkey) on the YQL console is failing. Looks like there's a 403 error in there 🤕 .

Either Yahoo's API is broken and we can wait for it to be fixed or it has been deprecated and we need to find a replacement.

**Comment by AbdelElMansari** [comment]
Hello Evan, 
Do you import community table ?
It's seems to work when you check "Show Community Table" . 
Check this [link](http://developer.yahoo.com/yql/console/?q=select%20*%20from%20yahoo.finance.quote%20where%20symbol%20in%20(%22YHOO%22%2C%22AAPL%22%2C%22GOOG%22%2C%22MSFT%22)&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys).

**Comment by justbill2020** [comment]
@AbdelElMansari just tried it as suggested... it still returns no results but if diagnostics is checked you get other data... just not results for the query

**Comment by sdetweil** [comment]
yahooapi used for this is no longer in existence
