### ISSUE TITLE
'responsiveservice.js' and 'annyang.js error'

### ISSUE THREAD

**Issue by sunghoon-kim** [evancohen/smart-mirror#697]
Our source from
> https://github.com/KimJeongChul/smartmirror-web-application/tree/master/smart-mirror 
based on you source

we did most of thing but when we speak to usb mic nothing happens. (we hope vocie command input and output for using youtube, map). so, we checked Toggle Developer Tools.
Here is  the error lines

**@config.js - npm start dev (console)**

> ResponsiveVoice r1.5.6
> index.html:57 Object_events: (...)get _events: ()set _events: (value)_eventsCount: (...)get _eventsCount: ()set _eventsCount: (value)_maxListeners: (...)get _maxListeners: ()set _maxListeners: (value)domain: (...)get domain: ()set domain: (value)__proto__: remoteMemberFunction
> annyang-service.js:23 added command "너는 누구니" Object
> annyang-service.js:23 added command "메뉴" Object
> annyang-service.js:23 added command "홈으로" Object
> annyang-service.js:23 added command "잘자 미러" Object
> .
> .
> .
> annyang-service.js:27 annyang start
> controller.js:64 Geoposition Object
> controller.js:73 Geoposition Object
> controller.js:78 Current Object
> controller.js:79 Weekly Object
> controller.js:80 Hourly Object
**> annyang-service.js:45 End undefined
> responsivevoice.js:74 Voice support NOT ready
> controller.js:103 Traffic Duration
> responsivevoice.js:75 RV: speechSynthesis present but no system voices found
> responsivevoice.js:76 RV: Enabling fallback mode**

and here is the detailed error line

**@annyang-service.js**

> (function(annyang) {
>     'use strict';
> 
>     function AnnyangService($rootScope) {
>         var service = {};
> 
>         // COMMANDS
>         service.commands = {};
> 
>         service.addCommand = function(phrase, callback) {
>             var command = {};
>             
>             // Wrap annyang command in scope apply
>             command[phrase] = function(arg1, arg2) {
>                 $rootScope.$apply(callback(arg1, arg2));
>             };
> 
>             // Extend our commands list
>             angular.extend(service.commands, command);
> 
>             // Add the commands to annyang
>             annyang.addCommands(service.commands);
>             console.debug('added command "' + phrase + '"', service.commands);
>         };
> 
>         service.start = function(listening, interimResult, result) {
>             console.log("annyang start");
>             annyang.addCommands(service.commands);
>             annyang.debug();
>             	
>             annyang.start();
>             
>             sender.on('command',function(command){
>           	  annyang.addCallback('android',function(){
>           		  
>           	  });
>             });
>             
>             if (typeof(listening) == "function") {
>                 annyang.addCallback('start', function(){
>                   $rootScope.$apply(listening(true));
>                   
>                 });
>                 annyang.addCallback('end', function(data){

                	console.log("End", data);  -> error : undefined

 
>                 });
>             };
>             if (typeof(interimResult) == "function") {
>                 annyang.addCallback('interimResult', function(data){
>                 $rootScope.$apply(interimResult(data));
>                 });
>             };
>             if (typeof(result) == "function") {
>                 annyang.addCallback('result', function(data){
> 			     $rootScope.$apply(result(data));
>                 });
>             };
>         };
> 
>         return service;
>     }
> 
>     angular.module('SmartMirror')
>         .factory('AnnyangService', AnnyangService);
> 
> }(window.annyang));

**@ Responsivevoice.js**

**Voice supprot Not reday**

> !1;a.log=function(b){a.debug&&console.log(b)};a.init=function(){a.is_android&&(a.useTimer=!0);a.is_opera||"undefined"===typeof speechSynthesis?(console.log("RV: Voice synthesis not supported"),a.enableFallbackMode()):setTimeout(function(){var b=setInterval(function(){var c=window.speechSynthesis.getVoices();0!=c.length||null!=a.systemvoices&&0!=a.systemvoices.length?(console.log("RV: Voice support ready"),a.systemVoicesReady(c),clearInterval(b)):(console.log("Voice support NOT ready"),a.voicesupport_attempts++,

**RV: speechSynthesis present but no system voices found**

> a.voicesupport_attempts>a.VOICESUPPORT_ATTEMPTLIMIT&&(clearInterval(b),null!=window.speechSynthesis?a.iOS?(a.iOS10?a.systemVoicesReady(a.cache_ios10_voices):a.iOS9?a.systemVoicesReady(a.cache_ios9_voices):a.systemVoicesReady(a.cache_ios_voices),console.log("RV: Voice support ready (cached)")):(console.log("RV: speechSynthesis present but no system voices found"),a.enableFallbackMode()):a.enableFallbackMode()))},100)},100);(a.iOS||a.is_android)&&a.enableWindowClickHook();a.Dispatch("OnLoad")};a.systemVoicesReady=

**RV: Enabling fallback mode**

> function(b){a.systemvoices=b;a.mapRVs();null!=a.OnVoiceReady&&a.OnVoiceReady.call();a.Dispatch("OnReady");window.hasOwnProperty("dispatchEvent")&&window.dispatchEvent(new Event("ResponsiveVoice_OnReady"))};a.enableFallbackMode=function(){a.fallbackMode=!0;a.forcedFallbackMode=!0;console.log("RV: Enabling fallback mode");a.mapRVs();null!=a.OnVoiceReady&&a.OnVoiceReady.call();a.Dispatch("OnReady");window.hasOwnProperty("dispatchEvent")&&window.dispatchEvent(new Event("ResponsiveVoice_OnReady"));a.Dispatch("OnServiceSwitched")};

**Comment by justbill2020** [comment]
Unfortunately we are unable to support forked versions of smart mirror. We recommend using our repo. Sorry.

**Comment by evancohen** [comment]
You can remove that line that's giving you issues with annyang, it's only for debugging purposes. Unfortunately I'm not familiar with ResponsiveVoice so I'm not sure how to help you. Just based on the errors here it looks likeResponsiveVoice is not be playing well inside Electron - some of the APIs available in Chrome aren't there in Chromium/Electron (like speech synthesis). My recommendation would be to use [Poly](https://aws.amazon.com/polly/) instead.

Hope this helps!
