### ISSUE TITLE
Unsuccessful Install using the quick install ( beginner) 

### ISSUE THREAD

**Issue by tubaarif** [evancohen/smart-mirror#699]
Hello

Raspberry Pi beginner here so apologies if I missed something obvious but using the quick install command "curl -sL https://raw.githubusercontent.com/evancohen/smart-mirror/master/scripts/pi-install.sh | bash" 

i got following errors

npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.12.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-4297-9e2ea5ad/registry.npmjs.org/node-forge/-/node-forge-0.7.1.tgz
npm ERR! Expected: 9da611ea08982f4b94206b3beb4cc9665f20c300
npm ERR! Actual:   9d2f149863f8032fecc4614cc9e11f83e8d87268
npm ERR! From:     https://registry.npmjs.org/node-forge/-/node-forge-0.7.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
Unable to install dependencies :(

**Comment by evancohen** [comment]
This looks like an npm service issue, can you try running `npm install` from the `~/smart-mirror/` folder again? I'm thinking this might just be a point-in-time thing.

**Comment by tubaarif** [comment]
i install npm  in smart-mirror directory but still getting following error!  

pi@raspberrypi:~ $ cd ~/smart-mirror
pi@raspberrypi:~/smart-mirror $ npm install
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-4342-b33313ae/registry.npmjs.org/node-forge/-/node-forge-0.7.1.tgz
npm ERR! Expected: 9da611ea08982f4b94206b3beb4cc9665f20c300
npm ERR! Actual:   fd955a80c51b968185e790c81dded1a74c0ded48
npm ERR! From:     https://registry.npmjs.org/node-forge/-/node-forge-0.7.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
pi@raspberrypi:~/smart-mirror $

**Comment by evancohen** [comment]
This has since been resolved. Closing this out.
