### ISSUE TITLE
Say "go to sleep" won't works

### ISSUE THREAD

**Issue by dexterbeng** [evancohen/smart-mirror#700]
Even in the remote site, clicked the sleep button, it won't work too!

What is causing it?

**Comment by evancohen** [comment]
Haven't gotten a positive repro of this, but if this is the case then it's definitely a bug. I've got some time over the holidays that I can look into this in a little more depth.

**Comment by dexterbeng** [comment]
@evancohen Hi Evan,

Is it related to the setting?
as shown image below:
![image](https://user-images.githubusercontent.com/29851477/34095203-7ababcbc-e40b-11e7-9261-40e4f6d68fdb.png)

**Comment by dexterbeng** [comment]
Yup, because the default setting is 'disabled', so it won't run the sleep function.
