### ISSUE TITLE
What is "Maker Settings"?

### ISSUE THREAD

**Issue by dexterbeng** [evancohen/smart-mirror#708]
What is the usage of this "Maker Settings" on the remote site?

![maker setting](https://user-images.githubusercontent.com/29851477/34327460-4aa1dd36-e900-11e7-8c33-269785ed0a9a.PNG)

**Comment by justbill2020** [comment]
It allows you to create some custom calls without coding... see this... https://ifttt.com/blog/2015/06/introducing-the-maker-channel

**Comment by dexterbeng** [comment]
@justbill2020 Thank you so much!

**Comment by dexterbeng** [comment]
@justbill2020 Sorry to ask, have you tried any of maker before?

*like PIR sensor trigger notification.
