### ISSUE TITLE
How to control light using another smart bulb ( e.g. Yeelight Smart bulb)

### ISSUE THREAD

**Issue by transmit-ter** [evancohen/smart-mirror#709]
Hi, I need to control light with single Yeelight Smart bulb with ip address instead of using Philips Hue Starter Kits, how should i change the lights plugin?

**Comment by sdetweil** [comment]
none of us know.. you would have to understand the api to control your lights and design and build a new plugin.

**Comment by transmit-ter** [comment]
yeah, I don't really understand how to build it.
I want to run file like blue.js, which controls the light, when i say "turn on the light and make it blue".

**Comment by sdetweil** [comment]
i understand.  this is an opensource project.. which means there are only a tiny number (2) of people that maintain/enhance the current code.   on open source projects, you are encouraged to develop your solution and contribute it to the project.  you have to learn how to do that.   I have spent a little over a year working on my plugins.. i am currently working on solving a general problem that will affect everyone, but affects me right now.  has nothing to do with my plugins tho..
