### ISSUE TITLE
More features..

### ISSUE THREAD

**Issue by Ayush7541** [evancohen/smart-mirror#710]
Can you add more features like whatsapp, facebook , uber, Netflix, making it touchscreen etc...

**Comment by justbill2020** [comment]
Yeah totes... etc... lol dude this is an open source project...

**Comment by mustafasyed123** [comment]
How though?

**Comment by evancohen** [comment]
Check out the developer documentation for more info on adding capabilities:
[Development and Contributing](https://docs.smart-mirror.io/docs/development_and_contributing.html#development).
Feature suggestions should go on: [feathub.com/evancohen/smart-mirror](https://feathub.com/evancohen/smart-mirror)
