### ISSUE TITLE
Picamera and PIR sensor to form surveillance system to mirror

### ISSUE THREAD

**Issue by dexterbeng** [evancohen/smart-mirror#711]
First of all, sorry for I am a beginner, and thanks to those people who read this topic!

I have a small request is that once my PIR sensor detects an object, it will trigger my Picamera to streamed real-time to preview the video feed on the mirror display for around 5 seconds.

How to accomplish it?

**Comment by sdetweil** [comment]
to accomplish this, you will have to write a plugin to extend the mirror functionality. 

i have extended the autosleep function to use the camera of my webcam for motion detection. 
(see my smart-mirror/motion pull request to look at the code. mostly in the motion.js detection side)

but I use an external program for the motion detection..  see https://motion-project.github.io/motion_guide.html   it can also stream the video..  you would have to write the code that opens the window and streams the data to it.. (and close the window etc)..
