### ISSUE TITLE
python code/script by voice command

### ISSUE THREAD

**Issue by transmit-ter** [evancohen/smart-mirror#712]
Actually I was thinking of running the motors,led strip and other Hardware devices connected to the gpio pins of Raspberry Pi through voice command.I was able to download the python code available for running the motor on rasp forum but don't know how to integrate it with the smart mirror. Any help would be deeply appreciated.

**Comment by sdetweil** [comment]
smart mirror is written in javascript, using angular. i don't know how you would integrate python scripts under that.. 

if you look at the motion.js there is the handling of the motion detection using the gpio device pins.  but this is read access to the pins, not write. 

you will have to write a plugin to handle the voice side..  a plugin consists of the html that will be used for the content, which invokes the plugin controller.js, and the service.js which typically is used to respond to the voice commands..  

i would look at map and autosleep plugins as examples. 

you will also have to add the voice phrases to the app/locales files. 

once you have code ready, then you modify the smart-mirror/index.html to add your html to it, 
this invokes the controller, which may call the service.js... all of those need to be added to the index.html in their appropriate places.

**Comment by evancohen** [comment]
You might want to check out http://johnny-five.io - it's a node JavaScript library that can communicate over GPIO and has a bunch of pre-built component compatibility. 

I've used it for a couple of other projects and I would recommend that over trying to interface with Python.

If you really really want to use Python for whatever reason mention me on discord in the support channel and I'll try to give you a hand.

**Comment by transmit-ter** [comment]
Thanks for helps.
And how can i test my *js file with annyang before i integrate it with the smart mirror?

**Comment by transmit-ter** [comment]
thanks for suggestions

**Comment by transmit-ter** [comment]
Hi again, i did visit w3schools.com and learn some basic code to control LEDs in javascript.
I followed @sdetweil l instructions and here are my code
[Service js.txt](https://github.com/evancohen/smart-mirror/files/1632078/Service.js.txt)
[Controller js.txt](https://github.com/evancohen/smart-mirror/files/1632079/Controller.js.txt)
I also added the voice phrases to the app/locales/en.json file and modify the smart-mirror/index.html
[En js.txt](https://github.com/evancohen/smart-mirror/files/1632084/En.js.txt)
But nothing happend

**Comment by sdetweil** [comment]
and you added the service and controller.js files to the includes in smart-mirror/index,html?

i think there is a missing brace in controller.js

**Comment by transmit-ter** [comment]
I see. But there's a new problem, the mirror seem the mirror doesn't realize voice phrases in my en.json
I tried to change the voice phrase into "let go" to turn on led and it still not working. I find no bug in debug window
![image](https://user-images.githubusercontent.com/32934714/34957069-92b0cc8a-fa5e-11e7-9ba0-66f337311ce8.png)

**Comment by sdetweil** [comment]
ok, a little thinking problem.. if you look at both the controller and the service, they are routines.. 
who calls them??

well, you need to do that.. 

I have a tiny index.html in my plugin which invokes the controller

index.html
```
<div ng-controller="ImageScheduler" >
</div>
```

**Comment by transmit-ter** [comment]
After i add 
<div ng-controller="LED" ></div>
this error popuped
![image](https://user-images.githubusercontent.com/32934714/34969796-2a7b5906-faa3-11e7-9771-016043088da4.png)
i did add 
<script src="plugins/LED/service.js"></script>
<script src="plugins/LED/controller.js"></script>

**Comment by sdetweil** [comment]
javascript is case sensitive

function LEDservice() {  // lowercase s

.factory('LEDService', LEDService); // uppercase S

**Comment by transmit-ter** [comment]
Still have unknow provider error
![image](https://user-images.githubusercontent.com/32934714/34971187-9a887582-faab-11e7-847b-c036258931b3.png)
![image](https://user-images.githubusercontent.com/32934714/34971219-bebbadfc-faab-11e7-98bd-ada4917ba3ae.png)

**Comment by sdetweil** [comment]
ok, one more change.. 

in the service. you again have a function, but nothing executes it 
```
(function(){
...
});
```
but that means the registration of the the service module did not occur..
 change the end to 
```
}());
```

**Comment by transmit-ter** [comment]
Thanks a lot, it worked!
Thank you for all your assistance. I am very grateful for everything you've done!
I'll close this topic.
