### ISSUE TITLE
error while starting the mirror

### ISSUE THREAD

**Issue by rithunrosh** [evancohen/smart-mirror#713]
when i am starting the mirror by using the command ''npm start'' on the command window,  the following error is displayed.

pi@raspberrypi:~ $ npm start

npm ERR! Linux 4.9.41-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
pi@raspberrypi:~ $

**Comment by rithunrosh** [comment]
what is the command for it

**Comment by sdetweil** [comment]
CD smart-mirror

**Comment by rithunrosh** [comment]
Thank you .
I have one more problem, that is the time is incorrect.so how can I set it

**Comment by evancohen** [comment]
Set the time on your Pi - the mirror picks up the time from the device.
