### ISSUE TITLE
Can't find display

### ISSUE THREAD

**Issue by jvasile** [evancohen/smart-mirror#716]
I cloned the repo and did `npm start`, but the app and web interface didn't come up.
### Expected Behavior
I expected the app and web interface to come up for the initial run of the smart-mirror.

### Current Behavior
I saw an inscrutable error in my terminal.  The relevant bit:

    npm ERR! electron-quick-start@1.0.0 start: `electron .`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.

### Possible Solution
When I did `DISPLAY=:0 npm start`, things went as expected.  I was accessing the machine from SSH.  (It's an Ubuntu Xenial box I have running in my living room, not a Raspberry Pi).

It might be useful to check for the DISPLAY environment variable and add a default if one doesn't exist.  It might also help to provide a more explicit and specific error message.

### Steps to Reproduce (for bugs)
1. SSH into the machine
2. Clone the repo
3. cd smart-mirror
4. npm install
5. npm start
 
### Context
I'm just taking a look at the smart-mirror while considering using it in earnest.  This is a "kick-the-tires" install.

### Your Environment
Ubuntu Xenial  LTS
Linux 4.8.0-59-lowlatency kernel
node v6.12.3
npm  v3.10.10

The Ubuntu box is running lightdm, although I don't think that matters at this point.

Thanks!

**Comment by jvasile** [comment]
Perhaps, the documentation should provide some guidance on this point, then?

**Comment by justbill2020** [comment]
Perhaps... 
Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by justbill2020** [comment]
Oh and I don’t mean to be short just jumping on a plane

**Comment by evancohen** [comment]
In the most recent version, you should be able to run `mirror start` - which handles launching via ssh a bit more gracefully. Have you given that a shot?
