### ISSUE TITLE
Can't start web server if port in use

### ISSUE THREAD

**Issue by jvasile** [evancohen/smart-mirror#717]
I did my initial `npm start` and got an error.  The app came up on screen but the web server didn't come up.

### Expected Behavior
I expected to be able to go to the IP and port as advised on the screen and then do config.  

### Current Behavior
I went to the IP and port as advised and got a different service because that port is already in use.  I also got an error in the terminal:

    'config.json' not found.                                                   You can configure your mirror at the remote 
    address below...
    Remote listening on http://192.168.1.189:8080
    A JavaScript error occurred in the main process
    Uncaught Exception:
    Error: listen EADDRINUSE :::8080
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at Server.setupListenHandle [as _listen2] (net.js:1263:14)
        at listenInCluster (net.js:1304:12)
        at Server.listen (net.js:1402:7)
        at Writable.remote.start (/home/guest/src/smart-mirror/remote.js:39:9)
        at Object.<anonymous> (/home/guest/src/smart-mirror/main.js:105:9)
        at Object.<anonymous> (/home/guest/src/smart-mirror/main.js:221:3)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)

### Possible Solution
Pick a different port.  Find one that's open and use it. Tell the user the correct IP and port.

Failing that, don't tell the user to go to an IP and port on which you're not listening.  Maybe give a less cryptic error in the terminal.  The current error, "Error: listen EADDRINUSE :::8080" is clear but probably not suitable for some users.

It might also be good to provide some explanation on a stub config.js file or some other way the user can choose a different port on initial run.

### Steps to Reproduce (for bugs)
1. Start a process that listens for HTTP on 8080
2. npm start
3. Go to the IP and port as instructed in the smart-mirror app that pops up on screen
4. Notice that the web page returned is not the smart-mirror

### Context
This isn't a big stumbling block.  I'll bring the other service down for a minute and see if I can resolve the port contention later.

### Your Environment
Ubuntu Xenial LTS
node v6.12.3
npm  v3.10.10

**Comment by justbill2020** [comment]
We’re always looking for ways to improve the app however there are only 3 people actively contributing to the code base... please feel free to fork the repo and submit a PR to fix this.

The issue stems from something already listening on port 8080 on your localhost ipv6 address though...

**Comment by justbill2020** [comment]
Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
Closing this out as shutting down the other service on 8080 should resolve the problem.
