### ISSUE TITLE
Error : #598

### ISSUE THREAD

**Issue by GJay17** [evancohen/smart-mirror#718]
Console Error : 
return process.dlopen(module, path._makeLong(filename));
                 ^

and another error 
 ENOENT: no such file or directory, open '/home/js6/jay/smart-mirror-master/keyfile.json'
 at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (/home/js6/jay/smart-mirror-master/sonus.js:17:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)

Server side: 
         maps.googleapis.com/maps/api/browserlocation/json?browser=chromium Failed to load resource: the server responded with a status of 404 ().

and

i get the output but partially, like i gave a key of youtube and weather 
i get the output of youtube but i can't get weather on display just because of "config.forecast.key".
"config.forecast.key" give output in console.log, but not getting key in implementation. 

and last when i start server i did't get qr code too

**Comment by sdetweil** [comment]
when u downloaded the keyfile from google for the speech setup, did you rename it keyfile.json, and put it into the smart-mirror folder? 

that is what the error message said
no such file or directory, open '/home/js6/jay/smart-mirror-master/keyfile.json'

i can't find my file.. keyfile.json in the application directory

**Comment by GJay17** [comment]
@sdetweil  thank you for the help. i don't have keyfile.json i'm going to find it. :)

**Comment by sdetweil** [comment]
you downloaded a file from google after configuring the voice api.. THAT is the file..
the download gave it a long funky name

**Comment by GJay17** [comment]
yeah @sdetweil i got that error, and i'm going to solve it. 
but i have another issue is that  "when i start server i did't get qr code" and another console error "return process.dlopen(module, path._makeLong(filename));
^"
