### ISSUE TITLE
White screen after installation. 

### ISSUE THREAD

**Issue by ellas14** [evancohen/smart-mirror#723]
When I install with nodejs version 6.x I get an error mentioning something about electron and it not having anything to do with the npm.. and when I install with nodejs version 9.x I don't get an error but I get a white screen.

When I run npm start dev no secondary debug window comes up.

I am able to log into <IP>:<PORT#> and toggle fullscreen, however nothing else works, just a white screen.
 
### Expected Behavior
 No white screen, loaded modules.

### Possible Solution
Possibly a problem with compatibility somewhere?

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4): **Raspberry Pi 3**
* Operating System and version (e.g. Raspbian, Ubuntu, OSX): **Raspbian**

**Comment by ellas14** [comment]
If anyone actually needs the exact error when running "curl -sL https://raw.githubusercontent.com/evancohen/smart-mirror/master/scripts/pi-install.sh | bash" or doing it manually, I can reinstall Raspbian and run the command again.

**Comment by sdetweil** [comment]
do the default install
started with raw raspian jesse 
```
apt-get update
apt-get install curl npm
run the smart-mirror install script
cd smart-mirror
npm remove electron
npm install electron@1.7.10
npm start
```

**Comment by ellas14** [comment]
Can confirm the smart mirror screen with the barcode showing and no white screen! Thanks Sam! If any other errors occur I will create a new issue.
