### ISSUE TITLE
New install ends up at white screen, npm start dev also

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#724]
after new install with the starter script, the mirror starts to a white screen
### Expected Behavior
 
mirror front page

### Current Behavior

solid white screen

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by evancohen** [comment]
Dupe of #723
