### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by mohago** [evancohen/smart-mirror#726]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by sdetweil** [comment]
sorry, what does this issue mean?  is there a problem? can u describe it for us?

**Comment by evancohen** [comment]
Can't do anything with this issue. Please add more info and I'll reopen.
