### ISSUE TITLE
Weather not working properly

### ISSUE THREAD

**Issue by abendplays** [evancohen/smart-mirror#728]
Hey Guys, 
I just got my smart mirror to working, which looks awesome! 
But unfortunatly neither the weaterforecast, nore the current weather is working.. 
I tripple checked the API-Key but it still won´t work.. Are there any ideas?
Thanks for your help

**Comment by abendplays** [comment]
Now I´m getting requests on the dark sky website, but on the screen nothing shows up..

**Comment by sdetweil** [comment]
the weather requires a key from darksky that is 33 characters long.  many of the returned keys are only 32 chars, these do not work. i do not know why.. one can only keep trying get key

**Comment by onkararj** [comment]
all i am getting is 32 char long. tried too many times. can u plz tell me how to get 33 char log key

**Comment by sdetweil** [comment]
the key can be 32 characters, but you must also set the language and your location for weather to work. 
see the doc here..

the api format used by smart-mirror is
```
 https://api.darksky.net/forecast/[key]/[latitude],[longitude]?units=auto,lang=[language]
```
see the list of supported languages..

make sure you can execute this request in a browser with all the info supplied

**Comment by sdetweil** [comment]
closing no response
