### ISSUE TITLE
JSONFORM error

### ISSUE THREAD

**Issue by joyabbhi** [evancohen/smart-mirror#736]
Hi,
Noticed jsonform error today. It was working fine a day before. Steps to reproduce are below

1. open remote url 
2. click on settings gear icon to configure emirror

the page shows the JSONFORM error below 

Entered content is not yet a valid JSON Form object.
The JSON Form library returned:
TypeError: $(...).jsonForm is not a function
    at n. (http://192.12.1.164:8080/remote-client.js:192:22)
Thanks

**Comment by sdetweil** [comment]
the jsonform repo is on blacklist
https://gitcdn.xyz/repo/joshfire/jsonform/master/lib/jsonform.js

Forbidden - This repo/gist is on the blacklist. If you wish to appeal, please open an issue here: https://github.com/schme16/gitcdn.xyz/issues, with why you feel this repo should not be on the blacklist.

you can see this error on the client browser by opening the developer tools window, select console, see error 403 on requests to the jsonform library

![2018-05-11](https://user-images.githubusercontent.com/1498142/39928273-86de15ba-54fa-11e8-9c3a-fe970450da2d.png)

**Comment by evancohen** [comment]
@sdetweil did you appeal this yet, or shall I open an issue on that repo?

**Comment by sdetweil** [comment]
i did open an issue there and they removed the entry from the blacklist.  see my comments in the contributors section

**Comment by evancohen** [comment]
Going to close this issue then, since this should be sorted
