### ISSUE TITLE
Having trouble with adding new command

### ISSUE THREAD

**Issue by youngchaena** [evancohen/smart-mirror#740]
Hello! I'm student and want to use voice recognition with GPIO(Just LED control is enough)

I have trouble with 'adding new voice command'

I followed [https://github.com/evancohen/smart-mirror/issues/712](https://github.com/evancohen/smart-mirror/issues/712)  
but nothing happens to me.

I tried Voice, and Remote console to try command.

But nothing happens when I try it

I'm not sure my command is added successfully...

I really need help....  please help me ;(

------
I made directory 'led' in plugins as well as other modules.

And made 'service.js' and 'controller.js'

controller.js
```
function LED(SpeechService, LEDService){
    
    SpeechService.addCommand('led_on', function(){
        console.debug("LED On");
        LEDService.setAON();
    });

    SpeechService.addCommand('led_off', function(){
        console.debug("LED off");
        LEDService.setAOFF();
    });


}

angular.module('SmartMirror').controller('LED',LED);
```

and

service.js
```
(function(){
    'use strict';

    console.debug("Started LED service!");

    function LEDService(){
        var service = {};

        var five = require("johnny-five");
        var Raspi = require("raspi-io");
        var board = new five.Board({
            io: new Raspi()
        });

        service.setAON = function(){
            board.on("ready", function(){
                var led = new five.Led("P1-7");
                //led.on();
                //led.off();
                led.on();
            
            });
        }

        service.setAOFF = function(){
            board.on("ready", function(){
                var led = new five.Led("P1-7");
                led.off();
                //led.on();

            });
        }

        return service;
    }

    angular.module('SmartMirror').factory('LEDService',LEDService);

}());
```

and also index.html ( inside /plugins/led/)
``` <div ng-controller="LED"></div> ```

and at main 'index.html', 

I added these two lines too.
```
  <script src="plugins/led/controller.js"></script>
  <script src="plugins/led/service.js"></script>
```

and also worked with 'en.json' 

![2018-06-03 12 18 07](https://user-images.githubusercontent.com/2259291/40877922-ab235cf2-66c3-11e8-8824-999093957951.png)

----

And here's another trouble with me

if i add 
![2018-06-03 12 26 31](https://user-images.githubusercontent.com/2259291/40877973-c8abe1ee-66c4-11e8-94c0-f973a3d423e3.png)
this `<div ng-include="'plugins/led/index.html'"></div>`

console returns some error 

![2018-06-03 00 28 15](https://user-images.githubusercontent.com/2259291/40877985-059853c6-66c5-11e8-9123-57bba79579f5.jpg)

----

### Your Environment
environment is Raspberry pi 3 B+ with raspbian

**Comment by sdetweil** [comment]
did u install the required modules.

```
        var five = require("johnny-five");
        var Raspi = require("raspi-io");
```

also. have you set your geolocation in the config file?

**Comment by sdetweil** [comment]
the error listed above in the screen shot is due to a naming conflict with the Map plugin controller..

i have submitted a PR to fix this

**Comment by sdetweil** [comment]
the latest version 0.21 fixes the problem with Map that you experienced

**Comment by youngchaena** [comment]
Thank you very very much for your all help and assistant!
I apology for my late check. I'm very grateful of your advice and PR!
If you don't mind, may I close this Issue now? 

Thank you for all this help again!

**Comment by sdetweil** [comment]
sure, you can close this
