### ISSUE TITLE
unable to install dependencies

### ISSUE THREAD

**Issue by VH-Tech** [evancohen/smart-mirror#742]
I did a fresh install of smart-mirror repository but got following error ->

> electron@1.7.15 postinstall /home/pi/smart-mirror/node_modules/electron
> node install.js

/home/pi/smart-mirror/node_modules/electron/install.js:48
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:580:26)
npm ERR! Linux 4.9.80-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.7.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
pi@raspberrypi:~/smart-mirror $ npm start

> smart-mirror@0.0.17 start /home/pi/smart-mirror
> electron main.js 

sh: 1: electron: not found

npm ERR! Linux 4.9.80-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! smart-mirror@0.0.17 start: `electron main.js `
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.17 start script 'electron main.js '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
-------------------------------------------------------------------------------------------------------------------
I even did a "npm install" , but recieved the same error
-------------------------------------------------------------------------------------------------------------------
log file ->
[npm-debug.log](https://github.com/evancohen/smart-mirror/files/2084957/npm-debug.log)

I am running raspbian stretch

**Comment by evancohen** [comment]
Please see #755
