### ISSUE TITLE
how can i add my outlook calender

### ISSUE THREAD

**Issue by onkararj** [evancohen/smart-mirror#743]
im new in this. plz tell me how can i add outlook calender to smart mirror.

**Comment by sdetweil** [comment]
i do not think you can get a web link to an outlook calendar.  

i use outlook to display my google calendar, and use the google calendar link in my smart-mirror

**Comment by nathan-brunetti** [comment]
@sdetweil based on this last response I'm understanding that you were able to get your google calendar populating to the smart mirror, right? How did you make this work? I have tried doing it within config (no luck) and I have tried hard coding it into the file, just to see if there was a connection issue with config. Can you show me an example string for Google and iCloud?

**Comment by evancohen** [comment]
@nathan-brunetti try this:
1) Go to https://calendar.google.com and navigate to Settings
2) Select the calendar you want to embed under "Settings for my calendars"
3) Copy and paste the URL from the "Secret address in iCal format" field (near the bottom of the settings page) into your smart mirror config

**Comment by evancohen** [comment]
I actually haven't done this with an Outlook calendar, but I'd imagine the process is very similar.

**Comment by sdetweil** [comment]
secret address won't work. as smart mirror  is not running as YOU on (google, yahoo, apple)..  got to be the public  url

**Comment by evancohen** [comment]
@sdetweil that's the point of the secret address, it allows access to a non-public calendar from an obfuscated URL 🎉. You can verify this by pasting the URL into an incognito window where you aren't logged in (the ical will still download).

**Comment by sdetweil** [comment]
ok, somehow I got my head screwed on crooked today.. I AM using the secret address... weird..

never mind!

**Comment by nathan-brunetti** [comment]
Thanks @evancohen, this ended up working for me.

**Comment by evancohen** [comment]
Great to hear!
