### ISSUE TITLE
Mycroft instead of google speech

### ISSUE THREAD

**Issue by MrSleeps** [evancohen/smart-mirror#744]
Been toying around with Mycroft lately, was wondering how easy it would be to use mycroft for the speech instead of google?

**Comment by evancohen** [comment]
Last time I checked Mycroft supported Google Cloud Speech and Mozilla's DeepSpeech (as of the end of March).  
I'd be really into adding DeepSpeech, it looks like they adding [Node bindings](https://github.com/mozilla/DeepSpeech#using-the-nodejs-package) as of [today](https://github.com/mozilla/DeepSpeech/commit/42eded652ba4e69e87b58a5627fdf5ecf6cd09fd) 🎊!

**Comment by evancohen** [comment]
I've been meaning to do a refactoring of Sonus to support a bunch more cloud services, so I'll include support for DeepSpeech too.

I'm in Serbia right now and will be traveling for a while, so I don't think I'll get to this for a couple of weeks (maybe longer). If you (or anyone else interested) feel up for it you should send a PR to Sonus.

**Comment by sdetweil** [comment]
i am closing this.. unlikely to get done
