### ISSUE TITLE
Issue with first time running smart mirror

### ISSUE THREAD

**Issue by matthewsadd** [evancohen/smart-mirror#745]
Hi all,

Complete newbie here -  first time pi user with limited programming experience so please go easy on me!

I have a clean install of latest version of raspian on a raspberry pi 3 model b+ and have used the one line code to install smart mirror... it said it failed to install dependencies but I have done this separately as per documentation on website which appears to have worked fine.

However, when I try and run smart mirror using the “npm start” command it says “bash: npm: command not found” ?!?!

I’m guessing I’m missing something really obvious? Any help would be all appreciated!

Thanks

Matt

**Comment by angeligareta** [comment]
There was an error during installation. I recommend you to reinstall with the script, it will automatically install npm.

**Comment by matthewsadd** [comment]
I've tried to reinstall with the script a few times and it never installs the dependencies.... it says

"bash: line 126: npm: command not found"
unable to install dependencies :(

Any ideas?

Cheers

**Comment by angeligareta** [comment]
Install npm manually, from the [nodejs webpage](https://nodejs.org/en/)

**Comment by kurtdb** [comment]
Personally, I would install node version manager. (nvm: https://github.com/creationix/nvm)

**Comment by matthewsadd** [comment]
Thanks folks... all sorted now,

Cheers

Matt
