### ISSUE TITLE
Source map error

### ISSUE THREAD

**Issue by Daveladd** [evancohen/smart-mirror#747]
### Expected Behavior
The remote config page should edit JSON file on "submit" click.

### Current Behavior
The Submit button is nonfunctional and the console log for the remote config screen shows the error
```
Source map error: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data
Resource URL: https://gitcdn.xyz/repo/joshfire/jsonform/master/deps/opt/bootstrap.css
Source Map URL: bootstrap.css.map
```
If I click on the "Commands Per Page" box the error pops up in the console log:
```
Empty string passed to getElementById().
FormAutofillHeuristics.jsm:357:12

```
### Possible Solution
??? 
Is this an error of the Resource URL or the JSON parse?

### Your Environment

same problem on OSX and Ubuntu, same problem on old and new installations

**Comment by evancohen** [comment]
@justbill2020 you know anything about this?

**Comment by justbill2020** [comment]
Nope news to me but I don’t have my mirror running currently...

**Comment by Daveladd** [comment]
If I swap the css bootstrap for a different source the Source Map error resolves however the remote config page is still having problems, it can read from the config.json but `Empty string passed to getElementById().` error arises if you click on any entry box and the Submit button does not function.

**Comment by justbill2020** [comment]
What’s the output when you look at the chrome debugger
