### ISSUE TITLE
Dependencies Error while installing 

### ISSUE THREAD

**Issue by siiruna** [evancohen/smart-mirror#749]
### Current Behavior

(node:6001) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.50-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/smart-mirror
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm WARN package.json form-data@0.0.3 No license field.
npm WARN package.json mime@1.2.7 No license field.
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
npm ERR! not ok code 0
Unable to install dependencies :( 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by siiruna** [comment]
> protobufjs@6.8.8 postinstall /home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/protobufjs
> node scripts/postinstall

npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
-
> snowboy@1.3.1 install /home/pi/smart-mirror/node_modules/sonus/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/pi/smart-mirror/node_modules/sonus/node_modules/snowboy/lib/node/binding/Release/node-v46-linux-arm/snowboy.node" is installed via remote
/
> grpc@1.14.1 install /home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:434:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:452:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! stack     at Module.require (module.js:365:17)
node-pre-gyp ERR! stack     at require (module.js:384:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:434:26)
node-pre-gyp ERR! System Linux 4.14.62-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! Linux 4.14.62-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.14.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the grpc@1.14.1 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

**Comment by evancohen** [comment]
Can confirm this issue. Going to look into a fix.

**Comment by evancohen** [comment]
Consolidating this issue into #755, please try the fix I outlined there. Thanks!
