### ISSUE TITLE
Unable to install smart mirror on raspberry Pi 3+

### ISSUE THREAD

**Issue by mykirii** [evancohen/smart-mirror#755]
Unable to install smart mirror on raspberry Pi 3+

### Steps to Reproduce (for bugs)

1.Installing smart mirror using command below
 curl -sL https://raw.githubusercontent.com/evancohen/smart-mirror/master/scripts/pi-install.sh | bash

2.fails with this error
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:434:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:452:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! stack     at Module.require (module.js:365:17)
node-pre-gyp ERR! stack     at require (module.js:384:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:434:26)
node-pre-gyp ERR! System Linux 4.14.70-v7+
node-pre-gyp ERR! command "/home/pi/.nvm/versions/node/v4.0.0/bin/node" "/home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/pi/smart-mirror/node_modules/sonus/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
-
> snowboy@1.3.1 install /home/pi/smart-mirror/node_modules/sonus/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/pi/smart-mirror/node_modules/sonus/node_modules/snowboy/lib/node/binding/Release/node-v46-linux-arm/snowboy.node" is installed via remote
npm ERR! Linux 4.14.70-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v4.0.0/bin/node" "/home/pi/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.15.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the grpc@1.15.1 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
Unable to install dependencies :(

### Your Environment
Raspberry Pi 3 + . 
I have attempted to install using the manual approach, still fails same way . Electron install seem to fail

**Comment by BlurayXL** [comment]
Hello, 
I have the same problem with rpi 3 and stretch.

**Comment by evancohen** [comment]
I can confirm that this is an issue! I'm traveling but will try to find some time to debug in the next few days. 

Thanks for your patience!

**Comment by Lexiconverse** [comment]
Hello

this is the error I'm getting

Installing smart-mirror dependencies...
This may take a while. Go grab a beer :)
bash: line 126: npm: command not found
Unable to install dependencies :( 

please help

**Comment by mykirii** [comment]
Still fails. What are the clear steps to retry?
"pi@raspberrypi:~/smart-mirror $ git checkout dev && git pull
Branch dev set up to track remote branch dev from origin.
Switched to a new branch 'dev'
Already up-to-date.
pi@raspberrypi:~/smart-mirror $
pi@raspberrypi:~/smart-mirror $ npm install sonus@0.2.0-rc1 snowboy@1.2.0
(node:3092) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpd                                                                                                                                                             ir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.j                                                                                                                                                             s:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.71-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sonus@0.2.0-rc1" "sno                                                                                                                                                             wboy@1.2.0"
npm ERR! cwd /home/pi/smart-mirror
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405

> snowboy@1.2.0 preinstall /home/pi/smart-mirror/node_modules/snowboy
> npm install node-pre-gyp

(node:3103) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
node-pre-gyp@0.6.39 node_modules/node-pre-gyp
├── detect-libc@1.0.3
├── semver@5.6.0
├── nopt@4.0.1 (abbrev@1.1.1, osenv@0.1.5)
├── rc@1.2.8 (ini@1.3.5, strip-json-comments@2.0.1, deep-extend@0.6.0, minimist@1.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── rimraf@2.6.2 (glob@7.1.3)
├── tar-pack@3.4.1 (uid-number@0.0.6, once@1.4.0, debug@2.6.9, readable-stream@2.3.6, fstream@1.0.11, fstream-ignore@1.0.5)
├── tar@2.2.1 (block-stream@0.0.9, inherits@2.0.3, fstream@1.0.11)
├── npmlog@4.1.2 (set-blocking@2.0.0, console-control-strings@1.1.0, gauge@2.7.4, are-we-there-yet@1.1.5)
└── request@2.81.0 (aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, tunnel-agent@0.6.0, is-typedarray@1.0.0, caseless@0.12.0, safe-buffer@5.1.2, stringstream@0.0.6, aws4@1.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.2, performance-now@0.2.0, qs@6.4.0, uuid@3.3.2, combined-stream@1.0.7, mime-types@2.1.21, tough-cookie@2.3.4, form-data@2.1.4, http-signature@1.1.1, har-validator@4.2.1)

> snowboy@1.2.0 install /home/pi/smart-mirror/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@8.11.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
module.js:549
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:463:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.71-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/home/pi/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm"
gyp ERR! cwd /home/pi/smart-mirror/node_modules/snowboy
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --fallback-to-build --module=/home/pi/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/smart-mirror/node_modules/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.14.71-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/smart-mirror/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/smart-mirror/node_modules/snowboy
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp configure --fallback-to-build --module=/home/pi/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm' (1)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
npm ERR! not ok code 0

"

**Comment by bhasat007** [comment]
Same issue with me as well............

**Comment by igroo2010** [comment]
$sudo apt-get install sox libatlas-base-dev

After installing this

$cd smart-mirror
$sudo npm install

At runtime

> electron@2.0.14 postinstall /home/pi/smart-mirror/node_modules/electron
> node install.js

/home/pi/smart-mirror/node_modules/electron/install.js:54
  throw err
  ^

Error: EACCES: permission denied, mkdir '/home/pi/smart-mirror/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@2.0.14 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@2.0.14 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-25T09_02_56_840Z-debug.log

node install.js

Why am I getting this error?
Please help ..

**Comment by evancohen** [comment]
This is now fixed in `v0.0.19`, see: #763
