### ISSUE TITLE
no answering with google AIY voice kit

### ISSUE THREAD

**Issue by juanmam5** [evancohen/smart-mirror#757]
I have my mirror working and it recognize my voice, but when I say something like "smart mirror, what time is it?" the mirror writes down the sentence but does nothing. I don't know if it does nothing or just it doesn't sound.
I have checked the audio with the google AIY test and it records and plays correctly. How can I know where is the problem?

**Comment by juanmam5** [comment]
Still can get this solved. I have this configuration:
<img width="726" alt="captura de pantalla 2018-11-22 a las 11 01 48" src="https://user-images.githubusercontent.com/44181544/48895709-08596d80-ee46-11e8-88d8-7b89627eec4f.png">

And this .asoundrc configuration:
<img width="595" alt="captura de pantalla 2018-11-22 a las 11 03 16" src="https://user-images.githubusercontent.com/44181544/48895793-3ccd2980-ee46-11e8-8768-1f8e86d0f677.png">

And this is what we get from command line:
<img width="725" alt="captura de pantalla 2018-11-22 a las 11 05 08" src="https://user-images.githubusercontent.com/44181544/48895908-8ae22d00-ee46-11e8-93e1-6a8e3d2b4421.png">

**Comment by evancohen** [comment]
"smart mirror, what time is it?" isn't a recognized command. Try "what can I say"

**Comment by sdetweil** [comment]
closing, lack of reponse
