### ISSUE TITLE
[Question] mismatch json Version

### ISSUE THREAD

**Issue by igroo2010** [evancohen/smart-mirror#759]
RaspberryPi3 B+
node v - 8.14.0
npm v - 6.4.1

When you say show debug information.
No response.
exit.
error - 
ERROR e:4092) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead

- How can it be solved?
- I'm curious, sir.

**Comment by igroo2010** [comment]
thank you..so much

**Comment by igroo2010** [comment]
> Check out #755. Try switching to the dev branch, which has the last gRPC dependencies

thank you..so much

**Comment by evancohen** [comment]
This is now fixed in `v0.0.19`, see: #763
