### ISSUE TITLE
Calendar events in the past are still displayed

### ISSUE THREAD

**Issue by yaydogan** [evancohen/smart-mirror#76]
I have a calendar event between 1:00pm-2:00pm today. It is 4:00pm and it is still showing. I couldn't figure out why it thinks this event is in the future and still displays it? Anyone knows the fix for this?

**Comment by yaydogan** [comment]
I think I found the issue. I am testing a fix and will see if it addresses the problem.

**Comment by evancohen** [comment]
This is because we display all of the events for the day. There is no logic in place to hide events past their end time. Seems like an easy fix though. Send a PR when you are ready :)

**Comment by yaydogan** [comment]
I typically have lots of meetings in the first half of the day. That is why I was thinking about hiding older events in the day. But now thinking about it, I will use this with family calendar to remind kids' games schedules, appointments, etc... It is better to see all events for the day. I will close this.
