### ISSUE TITLE
Unable to install smart mirror on Rpi 3 B+

### ISSUE THREAD

**Issue by yiyito04** [evancohen/smart-mirror#761]
Can you help me with this issue? i am having this message after trying to install smart mirror

Installing smart-mirror dependencies...
This may take a while. Go grab a beer :)
(node:7135) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.62-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/smart-mirror
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm WARN package.json form-data@0.0.3 No license field.
npm WARN package.json mime@1.2.7 No license field.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/smart-mirror/npm-debug.log
npm ERR! not ok code 0
Unable to install dependencies :(

**Comment by evancohen** [comment]
Should be fixed in v0.0.19 #763

**Comment by yiyito04** [comment]
> 
> 
> Should be fixed in v0.0.19 #763

Thanks champ

**Comment by isaac2004** [comment]
I am having same issue running bash script today. I have Node 8.11.1
