### ISSUE TITLE
Guides out-of-date / RPi 3 and Node-issue - missing npm

### ISSUE THREAD

**Issue by TheStigh** [evancohen/smart-mirror#762]
RPi 3 with latest Stretch: 
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

Did the install the manual way, and after the
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```
...it shows:
node -v : v 8.11.1
npm -v : bash: /usr/bin/npm: No such file or directory

As npm is missing, I can't continue according to your current instructions.

I tried to upgrade to latest node.js and npm was then part of the install.
But then I got issues with installation of electron.

I also tried the trick in issue #755 but still I got errors and it still failed to install electron.

I hope you could be so nice to update instructions/guide to make the install be successful. 
I'm still a bit noob on Linux and are now quite stuck.

Kind regards and Happy New Year,
Stigh - Norway

**Comment by evancohen** [comment]
Hey Stigh! Since you're from Norway (I studied at NTNU in Trondheim) I'll take a look at fixing up the guide this week 😉

**Comment by TheStigh** [comment]
> 
> 
> Hey Stigh! Since you're from Norway (I studied at NTNU in Trondheim) I'll take a look at fixing up the guide this week 😉

Hi Evan, so you've been in Trondheim? Cool! I live in Tromsø :)

Issue is actually solved as the latest build of Stretch found at raspberry.org is with Node 8.0.x and are without npm. Changing using curl pointing to either 8.x `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -` or 10.x for nodejs will also automatically upgrade and also install npm v 6.x.

I've tested with both curl -> 8.x and 10.x, but with success :)

**Comment by evancohen** [comment]
Unfortunately Snowboy doesn't support Node 9 & 10: https://github.com/Kitt-AI/snowboy/pull/537  
That said, 8.x should work totally fine! The change is here b52715c1aac92652916c6079b7c2ede407ca2dec. I've also updated Electron for security and included the newest version of Sonus: #763

**Comment by TheStigh** [comment]
Off-topic though, but what module did you use in the video when you say "show map of...", it need to be presented in a module I assume?

**Comment by evancohen** [comment]
That'd be the [`map`](https://github.com/evancohen/smart-mirror/tree/master/plugins/map) plugin which uses the static Google Maps API - which shouldn't need any configuration. Closing out this issue, but feel free to open another with more questions.
