### ISSUE TITLE
Snowboy, x86 and invalid pointer

### ISSUE THREAD

**Issue by TheStigh** [evancohen/smart-mirror#765]
Hi,

I’ve installed Debian Stretch on my laptop, and tried to get Snowboy to run.
Installations do rune fine with no error messages, but I get an error during startup:
`../../third_party/tcmalloc/chromium/src/tcmalloc.cc:289] Attempt to free invalid pointer 0x7ffeaef7b090`

According to git it states:

Currently Snowboy supports (look into the lib folder):

all versions of Raspberry Pi (with Raspbian based on Debian Jessie 8.0)
64bit Mac OS X
64bit Ubuntu 14.04
iOS
Android
ARM64 (aarch64, Ubuntu 16.04)

Abobody succeeded to run Snowboy under Debian Stretch or Ubuntu 16/18 on a PC?

Thanks for any inputs :)

**Comment by sdetweil** [comment]
closed, no response. Snowbody doesn't work on windows
