### ISSUE TITLE
youtube autoplay doesn't work 

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#781]
smart-mirror show me how to tie a tie

### Expected Behavior
 
expected to play video

### Current Behavior

video loads, but no longer plays, cannot be forced to play

### Possible Solution

browsers have implemented new security
requires commandline switch 

app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required'); 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by shariramani** [comment]
yeah same problem with me.

**Comment by sdetweil** [comment]
Try this work around

edit the smart-mirror/main.js

Find the line 

let mainWindow

and then add this line after it

app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required'); 

Save and restart smart-mirror

**Comment by shariramani** [comment]
Thank you! @sdetweil that worked.

**Comment by pccopper** [comment]
Thank You it was driving me mad

**Comment by sdetweil** [comment]
V 24 fixes this issue
