### ISSUE TITLE
Remote config page returns and error

### ISSUE THREAD

**Issue by gingermcninja** [evancohen/smart-mirror#794]
Accessing the config.html of the remote page returns an error

### Expected Behavior
Pressing the settings button in the remote should take me to a config page that allows me to update my configuration

### Current Behavior
The config page displays the following error:
Entered content is not yet a valid JSON Form object.

The JSON Form library returned:
http://192.168.0.33:8080/remote-client.js:192:30
emit@http://192.168.0.33:8080/socket.io/socket.io.js:2:28730
onevent@http://192.168.0.33:8080/socket.io/socket.io.js:3:5725
onpacket@http://192.168.0.33:8080/socket.io/socket.io.js:3:5349
http://192.168.0.33:8080/socket.io/socket.io.js:3:7491
emit@http://192.168.0.33:8080/socket.io/socket.io.js:2:28730
ondecoded@http://192.168.0.33:8080/socket.io/socket.io.js:1:29254
http://192.168.0.33:8080/socket.io/socket.io.js:3:7491
emit@http://192.168.0.33:8080/socket.io/socket.io.js:1:23667
add@http://192.168.0.33:8080/socket.io/socket.io.js:1:10411
ondata@http://192.168.0.33:8080/socket.io/socket.io.js:1:29206
http://192.168.0.33:8080/socket.io/socket.io.js:3:7491
emit@http://192.168.0.33:8080/socket.io/socket.io.js:2:28730
onPacket@http://192.168.0.33:8080/socket.io/socket.io.js:2:5910
http://192.168.0.33:8080/socket.io/socket.io.js:2:3535
emit@http://192.168.0.33:8080/socket.io/socket.io.js:2:28730
onPacket@http://192.168.0.33:8080/socket.io/socket.io.js:2:18002
onData@http://192.168.0.33:8080/socket.io/socket.io.js:2:17955
onmessage@http://192.168.0.33:8080/socket.io/socket.io.js:3:1453

### Steps to Reproduce (for bugs)

1. Open the remote page
2. Click on the settings icon on the upper right-hand corner

**Comment by sdetweil** [comment]
there is a bug where the site holding the libraries the config uses becomes not available, and we don't handle it.   I submitted a proposed change last week,  PR #792

a workaround  is to edit smart-mirror/remote/config.html
and change all joshfire to evancohen
save the file and reload the config page

**Comment by gingermcninja** [comment]
@sdetweil Thanks for the fast response! Changing the config.html as you suggested didn't work so I'll just wait until your PR gets merged and try again then. Cheers!

**Comment by sdetweil** [comment]
hm,, there are 4 places to change in that file.   my update is to do that very change,
AND add an error message to replace the stackstrace

there currently is no schedule to merge my proposed change

**Comment by iot-werkstatt** [comment]
Guys,

I am facing the same error and did replace all "joshfire" entries and it is still not working. What do you mean by "AND add an error message to replace the stackstrace"?

**Comment by sdetweil** [comment]
In my pull request I added some code to give a better error.   

Recently the gitcdn has been returning an error 500 for all requests.   

Only fix I've found is to clone the joshfire repo into the smart-mirror/remote folder, and fix the HTML to point to those files

**Comment by iot-werkstatt** [comment]
Thanks sdetweil.

I am a newbie and wondering where to find the repo of joshfire. Sorry.

**Comment by sdetweil** [comment]
Google GitHub joshfire

**Comment by Banhammer1919** [comment]
I have exactly the same error after a fresh installation of Raspbian buster and smart mirror. After the first open the config.html

Are there any new insights or solutions?

**Comment by sdetweil** [comment]
do this
```
cd ~/smart-mirror/node_modules
git clone https://github.com/jsonform/jsonform.git
cd ../remote
# notice the trailing dot on the next command
cp -R ../node_modules/jsonform .
```
use this file (config.html) in the ~/smart-mirror/remote folder, instead of the one already there
https://www.dropbox.com/s/ryjqdzu1iof4jkk/config.html?dl=1

after doing this, you can bring up the remote config.html again, and it should work

**Comment by sdetweil** [comment]
V 24 fixes this issue
