### ISSUE TITLE
Hi! I'm trying to make a smart mirror using raspberry pi I'm up to installing dependencies and keep getting 'command not found' when trying to do npm install I'm not sure why it isn't working?

### ISSUE THREAD

**Issue by freyadavis** [evancohen/smart-mirror#795]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by sdetweil** [comment]
the packaging changed.. they split node and npm 

so, to fix do 
```
sudo apt-get install npm
sudo npm i -g npm 
```
then 
redo the npm install

**Comment by freyadavis** [comment]
thank you thank you!! lifesaver <3

**Comment by sdetweil** [comment]
i am going to close this issue, as it appears resolved
