### ISSUE TITLE
"go to sleep" is not working please help and how to view stocks and calendar?

### ISSUE THREAD

**Issue by ItxMuneeb** [evancohen/smart-mirror#797]
In my mirror "go to sleep" is not working please help and how to view stocks and calendar?

**Comment by sdetweil** [comment]
To make go to sleep work, you have to enable the auto timer function

Stocks requires a key
And calendar, u need to.provide the url to the calendars u want to display

**Comment by ItxMuneeb** [comment]
yeah i have insert the key for stocks and url for calendar but still its not displaying

**Comment by sdetweil** [comment]
Open the developers window, ctrl-shift-i,
Select the tab labeled console,  and scroll up. 

On calendar,  take your url, and out it in a browser on the pi.  It should download the ics  file

**Comment by ItxMuneeb** [comment]
http://www.calendarlabs.com/templates/ical/US-Holidays.ics

I am using this link but still its not working for me

**Comment by sdetweil** [comment]
that calendar link is for 2017 thru 2018..  
for 2019 use
https://www.calendarlabs.com/ical-calendar/holidays/us-holidays-76/

**Comment by ItxMuneeb** [comment]
still not working

**Comment by sdetweil** [comment]
sorry, incorrect link 
https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics

**Comment by ItxMuneeb** [comment]
issue of calendar is resolved...
but still stocks is not working

**Comment by sdetweil** [comment]
u have to get an API key for stocks, right?
see the configuring doc 
https://docs.smart-mirror.io/docs/configure_the_mirror.html#stock

**Comment by ItxMuneeb** [comment]
Yeah i have insert the api key but its not working

**Comment by sdetweil** [comment]
ok, show me the stock section of config.json,
mine  looks like this
```
  "stock": {
    "key": "MIWIPUSRG9DWENGX",
    "names": [
      "MSFT",
      "IBM",
      "AAPL"
    ]
  }
```

the api is very sensitive to how often it is used..

and then open the developers window, ctrl-shift-i on the keyboard, select the tab labeled console,
and scroll up to see any errors (usually red text)

**Comment by sdetweil** [comment]
I;m going to close this.. reopen if you still have the problem
