### ISSUE TITLE
I have issue with the weather?

### ISSUE THREAD

**Issue by Robako** [evancohen/smart-mirror#8]
Can you tell me why my weather stays with a circle? I have API Key but still... I am using my site for tests demo: http://visionplayz.com/test2/

**Comment by evancohen** [comment]
Check out the [caveats](https://github.com/evancohen/smart-mirror#caveats) section of the README. There are two ways to make this work: one is to install an extension that allow you to white-list the domain for CORS and the other would be to build a proxy. Unfortunately their API doesn't support JSONP :(

You could also swap out the API entirely and use something else
