### ISSUE TITLE
page truncated on 4k screen sizes (3840x2160)

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#806]
running on Pi4 or jetson nano in 4k mode with large screen 
ui is tiny, does not fill page

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):
node v10.16.3
npm 6.9.0
Ubuntu 18.04.3 LTS
jetson nano sbc
SM v 0.0.25

**Comment by evancohen** [comment]
Should look at using `vh` instead of `px`

**Comment by sdetweil** [comment]
cool.. what was the original px count calculated on 1920/1080?  800/600?

**Comment by sdetweil** [comment]
fixed 0.26
