### ISSUE TITLE
sceen diplay

### ISSUE THREAD

**Issue by abdul93** [evancohen/smart-mirror#807]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by sdetweil** [comment]
i don't understand the issue here

**Comment by sdetweil** [comment]
close no repsonse
