### ISSUE TITLE
screen rotate

### ISSUE THREAD

**Issue by abdul93** [evancohen/smart-mirror#808]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by sdetweil** [comment]
i don't understand the issue here...

screen rotate is not a feature of smart-mirror...
you need to change the system settings.

once you do that, you will need to adjust the css stylesheets.. app/css/main.css

**Comment by abdul93** [comment]
I mean greetings are not visible, its position exceeds the size of the screen, why can it be affected

**Comment by sdetweil** [comment]
what sized screen?  i have not seen this problem

**Comment by abdul93** [comment]
screen size 32 inch

**Comment by sdetweil** [comment]
Hm.. my 32 inch works fine

**Comment by sdetweil** [comment]
@abdul93 any update?
