### ISSUE TITLE
Available spelled wrong in "Available Commands"

### ISSUE THREAD

**Issue by nojkepop** [evancohen/smart-mirror#81]
Index.html line 79.  
  
    
        <div class="commands animate-grow" ng-show="focus == 'commands'">
          <h2>Availalble Commands</h2>
          <dl>
            <dt>What can I say?</dt>
            <dd>Shows a list of voice commands available to you.</dd>

**Comment by evancohen** [comment]
Lol. I'm so dyslexic. Feel free to send a PR, otherwise I'll fix this in the next update.

**Comment by nojkepop** [comment]
All good man, I made one of these mirror for valentines day and it was the first thing my girlfriend noticed...I probably never would have otherwise.

**Comment by evancohen** [comment]
Fixed in master at  93066d4
