### ISSUE TITLE
Map is unresponsive

### ISSUE THREAD

**Issue by JOJOYJ** [evancohen/smart-mirror#812]
we ran it with only a specific key value. YouTube, Bing map 
YouTube was a success. But map is unresponsive

If you need any log you need to see, please let me know.
### Your Environment

* Environment name and version (): Pi 3 B+, node : 8.16.2 npm :6.41
* Operating System and version (e.g. Raspbian, Ubuntu, OSX): 2018 ?? ?? Stretch

**Comment by sdetweil** [comment]
Did I set your location key in config?

**Comment by JOJOYJ** [comment]
Thank you. This problem has been solved. It was a simple key error. 
 I have a question.If I ask the weather, can smart mirror answer with smart mirror own voice?
Just the voice, not the result window.

**Comment by sdetweil** [comment]
currently there is no speech output for smart-mirror

**Comment by JOJOYJ** [comment]
Thank you for your reply.  May you be blessed with all things good.

**Comment by sdetweil** [comment]
closing, resolved
