### ISSUE TITLE
Calendar is not displaying

### ISSUE THREAD

**Issue by ItxMuneeb** [evancohen/smart-mirror#813]
https://www.calendarlabs.com/templates/ical/US-Holidays.ics

I am using this link but still its not working for me...

Max Number of Events for all iCals = 9
Max Number of Days to display = 9

Suggest me the solution

**Comment by sdetweil** [comment]
that calendar link is for 2017-2018..

the 2019 calendar link is 
https://www.calendarlabs.com/ical-calendar/holidays/us-holidays-76/

**Comment by ItxMuneeb** [comment]
still its not working

**Comment by sdetweil** [comment]
sorry, should have copied the url

https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics

**Comment by ItxMuneeb** [comment]
it starts working but only showing 1 event

**Comment by sdetweil** [comment]
the config for calendar is forward n days. 

    "maxDays": 9,

show only events up to 9 days from now

**Comment by ItxMuneeb** [comment]
thank you

**Comment by sdetweil** [comment]
can we close this now?

**Comment by ItxMuneeb** [comment]
yes
