### ISSUE TITLE
upgrade to using node version 10

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#820]
get current

**Comment by sdetweil** [comment]
we have a big problem.. snowboy 1.3.1 doesn't have a solution for node 10.17, doesn't build either

**Comment by justbill2020** [comment]
i saw this and wasn't sure if you saw @evancohen was working on a fix for this already... https://github.com/Kitt-AI/snowboy/pull/537

**Comment by sdetweil** [comment]
closed 0.26
