### ISSUE TITLE
calendar not show on screen

### ISSUE THREAD

**Issue by loricheung** [evancohen/smart-mirror#845]
### Expected Behavior
showing calendar

### Current Behavior
not showing

### Steps to Reproduce (for bugs)
1. git clone
2. npm install 
3. npm start
4. config 

### Context
I start a web server on my own macos, config calendar source as http://192.168.1.140:8000/chinaholiday.ics, the web server showing my raspberry request calendar, but it not showing on screen

### Your Environment
* Environment name and version  Raspberry Pi 3B+, node.js 10.20.1
* Operating System: Raspbian

**Comment by sdetweil** [comment]
can u show the section of the ~/smart-mirror/config.json for calendar, like mine 
```
  "calendar": {
    "icals": [
      "https://calendar.google.com/calendar/ical/yyy@gmail.com/private-xxx/basic.ics"
    ],
    "maxResults": 9,
    "maxDays": 9,
    "showCalendarNames": true
  },
```
if u open a browser on your pi,  can u access your local ics file and cause it to download? (I think you said yes above)
also check the module position config for calendar, and make sure Active is checked

**Comment by loricheung** [comment]
@sdetweil below is my config
```json
  "calendar": {
    "icals": [
      "http://192.168.1.140:8000/chinaholiday.ics"
    ],
    "maxResults": 9,
    "maxDays": 9,
    "showCalendarNames": true
  },
```
and yes, I can directly download ics on raspberrypi from my own mac. also, I hava actived it on position config

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1geq7ba4za3j30p60kswfq.jpg)

**Comment by sdetweil** [comment]
and pushed submit after making sure the checkbox is set to active
and the calendar code config is set to look forward only 9 days from today
    "maxDays": 9,

are there any calendar entries in the next 9 days?

**Comment by loricheung** [comment]
It works!  cause there's no event in the next 9 days. thanks so musch.

may ask I didn't have a dark sky account since it no longer accepting new signup, how should I config it with climacell api? I already have an account and got a key. I read docs, it only show how config with dark sky api.

**Comment by sdetweil** [comment]
you dropdown the type to pick climacell and put in the api key from them

**Comment by sdetweil** [comment]
same for openweather key
