### ISSUE TITLE
Smartmirror(sample)

### ISSUE THREAD

**Issue by ygreen0516** [evancohen/smart-mirror#884]

**Comment by sdetweil** [comment]
how can I help you?

**Comment by ygreen0516** [comment]
I'm just Noob about Github...
How do i use this open source?
Thank you for your attention

**Comment by DannyLuu** [comment]
Please use the discord channel for help on this or google :)

**Comment by ygreen0516** [comment]
Oh sorry... i didn't know that 
:()

**Comment by DannyLuu** [comment]
This is to open bugs or issues with the application itself.

No worries! Welcome to the community!
