### ISSUE TITLE
issue while installing electron in raspberry pi 4b

### ISSUE THREAD

**Issue by reloader20** [evancohen/smart-mirror#894]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):
i was trying in install magic mirror but can not install electron
pi@raspberrypi:~ $ sudo npm install -g electron@1.7.6
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@1.7.6 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-20T07_33_49_148Z-debug.log

**Comment by sdetweil** [comment]
never use sudo

**Comment by sdetweil** [comment]
to fix

chown -r pi ~/.npm

**Comment by dev51200** [comment]
thanks for your response

**Comment by dev51200** [comment]
but that didn't work
``pi@raspberrypi:~ $ chown -r pi ~/.npm
chown: invalid option -- 'r'
Try 'chown --help' for more information.

**Comment by dev51200** [comment]
and after i capitalized R
and trying to install with npm
i got this massage
``pi@raspberrypi:~ $ chown -R pi ~/.npm
pi@raspberrypi:~ $ npm install electron -g
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     `/home/pi/.npm/_logs/2021-01-21T07_46_04_272Z-debug.log`

**Comment by sdetweil** [comment]
sorry, in hospital w covid. csnt help more now

**Comment by reloader20** [comment]
thanks for you help
i install npm using terminal
and i success fully install electron

**Comment by reloader20** [comment]
i wish you get well soon
