### ISSUE TITLE
home screen too cluttered when there are many calendar entries...

### ISSUE THREAD

**Issue by danielccm** [evancohen/smart-mirror#94]
![mirror](https://cloud.githubusercontent.com/assets/9162711/13123980/3cead324-d5bf-11e5-9ab8-70f9ac5f97bb.png)

**Comment by SenadM** [comment]
Move the compliment down, and make it dissappear when the list of commands comes up?

**Comment by evancohen** [comment]
Looks like there needs to be more space between 'Wednesday' and the text too.
