### ISSUE TITLE
when i try       'npm start'    then i will get error              'sh: 1: electron: not found' 

### ISSUE THREAD

**Issue by parveensingh95** [evancohen/smart-mirror#943]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by parveensingh95** [comment]
help to solve this

**Comment by sdetweil** [comment]
please attach ~/install.log

**Comment by sdetweil** [comment]
is this from MagicMirror?

**Comment by sdetweil** [comment]
wrong repo
