### ISSUE TITLE
IDEA: Integrate home automation systems, for example Smartthings

### ISSUE THREAD

**Issue by danielccm** [evancohen/smart-mirror#96]
It would be useful for, for example, those lights that aren't Hue, or to switch the coffee maker on from the bathroom...

Or open the door from the basement, or whatever needs might show up...

**Comment by espilioto** [comment]
You can do all of those things with shell and/or python scripts.
Just add the voice command and the script you want to execute.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+2

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
